/*
 * Päivitysloki: mitä kussakin versiossa muuttui.
 *
 * Omistajan toive: "Tee erittäin tiivis päivitysloki joka tulee
 * näkyviin klikkaamalla versionumeroa kartalla."
 *
 * ERITTÄIN TIIVIS on tässä muotovaatimus, ei tyyliohje. Yksi rivi per
 * versio, korkeintaan noin 60 merkkiä, ilman versiohistorian tavallista
 * jargonia. Lokia luetaan puhelimen ruudulla kartan päältä, ja jos
 * riviä joutuu vierittämään, se on liian pitkä. Testi vahtii pituuden.
 *
 * Uusin ensin. Uusi rivi lisätään aina versionoston yhteydessä.
 * Vanhat rivit eivät muutu — loki on historia, ei kuvaus nykytilasta.
 */
export const MUUTOKSET = [
  { v: 1290, teksti: 'Raamattuun illan linjaukset ja testattavat' },
  { v: 1289, teksti: 'Aarteen loydyttya laatta vain vaihtaa varia' },
  { v: 1288, teksti: 'Takynostot nakyviin heti ilman tuiketta' },
  { v: 1287, teksti: 'Raamattuun promptien toimitusmuoto' },
  { v: 1286, teksti: 'Lehden juttusivun kysymysehdotukset ja odotusrivi' },
  { v: 1285, teksti: 'Takynostokortin rikastus: Sofian areena' },
  { v: 1284, teksti: 'Raamattuun paivan linjaukset ja promptinippu talteen' },
  { v: 1283, teksti: 'Tilannetaulu ajan tasalle ja ihmesavukkeen odotukset' },
  { v: 1282, teksti: 'Ihmekuvat uusiksi 31 kohteeseen' },
  { v: 1281, teksti: 'Tampereen herot ja korjatut herokuvat' },
  { v: 1280, teksti: 'Karttamerkit piiloon eleen ajaksi' },
  { v: 1279, teksti: 'Aarrepaljastus: vinjetointi, fakta ja Aarnin diplomi' },
  { v: 1278, teksti: 'Kaikki 58 paikallisaarrekuvaa peliin' },
  { v: 1277, teksti: 'Nipistyszoomin skriptiaika alas 58 prosenttia' },
  { v: 1276, teksti: 'Aarreleiskat ja paatokset talteen tyoaineistoon' },
  { v: 1275, teksti: 'Kohdekartan merkit palaavat matalalta lavalta' },
  { v: 1274, teksti: 'Drive-nouto laskeutuu alikansioihin' },
  { v: 1273, teksti: 'Kehyssilmukka ilman roskaa: GC-nykays harvemmaksi' },
  { v: 1272, teksti: 'Euroopan 29 maan paikallisaarreparit' },
  { v: 1271, teksti: 'Livian lyhentymat reunoille teksteissa' },
  { v: 1270, teksti: 'Raamattu: puhekielen painopiste reunoille' },
  { v: 1269, teksti: 'Julistekuittaus mainitsee matkalaukun' },
  { v: 1268, teksti: 'Chatin kehysmalli: kaksi aanta ja jatkosignaali' },
  { v: 1267, teksti: 'Nippuraja nakyvasta laatasta ja lahin voittaa' },
  { v: 1266, teksti: 'Livian tekstit vahvaan puhekieleen' },
  { v: 1265, teksti: 'Raamattu: Livian puhekieli ja kehysmalli' },
  { v: 1264, teksti: 'Sofian valittajaote ja synkan aiheen saanto' },
  { v: 1263, teksti: 'Lehtisauma pois ja merkit vasta saapumisen jalkeen' },
  { v: 1262, teksti: 'Raamattu: pariperiaate ja ihmeiden mittakaava' },
  { v: 1261, teksti: 'Ihmeselitteisiin loistoaikojen kaytto' },
  { v: 1260, teksti: 'Nippumerkit lehden mittoihin kapealla ruudulla' },
  { v: 1259, teksti: 'Takypiste symbolin paalle ja pooli kolmeen' },
  { v: 1258, teksti: 'Reaktiot: viisi symbolia ja jaetut laskurit' },
  { v: 1257, teksti: 'Sofian maadoituksen pehmennys' },
  { v: 1256, teksti: 'Paivakirjan kaiutin otsikkoriville' },
  { v: 1255, teksti: 'Ihmenauhan teksti Unohdettu aarre' },
  { v: 1254, teksti: 'Nappula puunvarinen ja laatta nakyviin' },
  { v: 1253, teksti: 'Lippuikkunan tarkennettu laatta pysyy kortissa' },
  { v: 1252, teksti: 'Reaktiojarjestelma koko peliin' },
  { v: 1251, teksti: 'Pullavinkki aarretehtavaan' },
  { v: 1250, teksti: 'Livia pysyvaksi pullapersoonalla ja saapumisrepliikit' },
  { v: 1249, teksti: 'Itameren meripihka ja pikkuaarteiden nimijarjestys' },
  { v: 1248, teksti: 'Esilataussavuke vihreaksi ja heropuskuri kuntoon' },
  { v: 1247, teksti: 'Sahke-tyylit takaisin standaloneen' },
  { v: 1246, teksti: 'README kaikin puolin ajan tasalle' },
  { v: 1245, teksti: 'Raamattuun motivaatioteoria ja pysyva Livia' },
  { v: 1244, teksti: 'Nippusarake tiivistyy kapealla ruudulla' },
  { v: 1243, teksti: 'Ihmenauha skaalautuu kuvan mukana' },
  { v: 1242, teksti: 'Raamattuun paivan linjaukset' },
  { v: 1241, teksti: 'Saksan fokuskartta ja karttakohteet' },
  { v: 1240, teksti: 'Kroatian fokuskartta ja karttakohteet' },
  { v: 1239, teksti: 'Unkarin fokuskartta ja karttakohteet' },
  { v: 1238, teksti: 'Nimiauditti kaikille fokusmaille ja vartio' },
  { v: 1237, teksti: 'Pelinappula yksinkertaiseksi valkoiseksi' },
  { v: 1236, teksti: 'Pollopaneelin nappien ja linkkien hovervarit' },
  { v: 1235, teksti: 'Ihmenauha tasaiseksi kaistaksi kuvan reunaan' },
  { v: 1234, teksti: 'Takynostot tuikkivaksi keltaiseksi pisteeksi' },
  { v: 1233, teksti: 'Livian kevyt mauste faktavastauksiin' },
  { v: 1232, teksti: 'Isoisan maadoituskuplat kevyeen kulkuun' },
  { v: 1231, teksti: 'Livian paneeli korkeammaksi' },
  { v: 1230, teksti: 'Ihmenauha kahden kaistan malliksi' },
  { v: 1229, teksti: 'Livian lisays faktavastausten peraan' },
  { v: 1228, teksti: 'Aarrekysymysten vastaukset lehtiin' },
  { v: 1227, teksti: 'Saattokamera korjattu - mittavalimuisti mitatoityy' },
  { v: 1226, teksti: 'Ihmeet nakyviin nahtavyysikkunaan' },
  { v: 1225, teksti: 'Livia tuuraajaksi: sijaisuus, maadoitus, yliviivaus' },
  { v: 1224, teksti: 'Jatka matkaa -nappi pelin tyyliin' },
  { v: 1223, teksti: 'Saapumisen karttalataus sujuvaksi esilatauksella' },
  { v: 1222, teksti: 'Ihmenauha sinettivahan punaiseksi ja reunan yli' },
  { v: 1221, teksti: 'Livia-kokeilu: pulun tekstit pollon tilalle' },
  { v: 1220, teksti: 'Aliakmonas Strymonas ja Evros kohteiksi' },
  { v: 1219, teksti: 'Nimiokato korjattu ja osumatestit kuntoon' },
  { v: 1218, teksti: 'Kosketusnipistys seuraa sormia Safarin gesture-polulla' },
  { v: 1217, teksti: 'Kahdeksan uutta ihmetta - Libya ja Tunisia mukaan' },
  { v: 1216, teksti: 'Herot era 3: kuusi kaupunkia generoituihin avauskuviin' },
  { v: 1215, teksti: 'Karttamerkit minimalistisiksi vanhan kartan tyyliin' },
  { v: 1214, teksti: 'Smolikas Kreetanmeri ja Traakianmeri kohteiksi' },
  { v: 1213, teksti: 'Maataulun lisatiedot nimen paalle ja pehmea blur' },
  { v: 1212, teksti: 'Ihmenauhan teksti mahtuu ja taite viilattu' },
  { v: 1211, teksti: 'Nimioiden vaisto ahtaissa ryppaissa' },
  { v: 1210, teksti: 'Kreikan lehden poltetut vuori- ja merinimet pois' },
  { v: 1209, teksti: '14 uutta ihmetta seitsemaan uuteen maahan' },
  { v: 1208, teksti: 'Scrollauksen sujuvuus: kompositorikerrokset 38 to 11' },
  { v: 1207, teksti: 'Karttasymbolit mustetyyliin nimioin ja rasteroituina' },
  { v: 1206, teksti: 'Herot era 2: 13 kaupungin avauskuvat generoituina' },
  { v: 1205, teksti: 'Maailmannakyma piirtaa kaikki 134 maalehtea pikkukuvina' },
  { v: 1204, teksti: 'Ihmenauha istuu kuvaan: leikkaus, varjo, leveampi' },
  { v: 1203, teksti: 'Lahdeluettelon epaselvat lisenssit selvitetty' },
  { v: 1202, teksti: 'Nappulan alusta siistiksi: laatta ja sykkeet pois alta' },
  { v: 1201, teksti: 'Euroopan kadonneet: Tuileries, Vanha St Paul, Forum' },
  { v: 1200, teksti: 'Oikeudet ja tekijyys VVI:lle julkisissa teksteissa' },
  { v: 1199, teksti: 'Kuvatekstiremontti valmis: paatoserä Chennaista Rioon' },
  { v: 1198, teksti: 'Uudet luonto-, tekniikka- ja kaupunkisymbolit; Psiloritis' },
  { v: 1197, teksti: 'Kuvatekstiremontti era 8: Hanoista Kabuliin' },
  { v: 1196, teksti: 'Puhekuplan napautus ei enaa vuoda kartalle' },
  { v: 1195, teksti: 'Ihmepopup: nykytilan valokuva, nappi kuvan alle, kulmanauha' },
  { v: 1194, teksti: 'Jalkamatka: hidas hyppy, saattokamera, korjaukset' },
  { v: 1193, teksti: 'Kuvatekstiremontti era 7: Adenista Varanasiin' },
  { v: 1192, teksti: 'Kuvatekstiremontti era 6: Tabrizista Sanaan' },
  { v: 1191, teksti: 'Kuvatekstiremontti era 5: Dohasta Riadiin' },
  { v: 1190, teksti: 'Liput era 12: loput 19 maata, kaikki laudat katettu' },
  { v: 1189, teksti: 'Noppa kartan pintaan ja tinaherra hyppyanimaatiolla' },
  { v: 1188, teksti: 'Kuvatekstiremontti era 4: Dubrovnikista Mekkaan' },
  { v: 1187, teksti: 'Kuvatekstiremontti era 3: Tallinnasta Tromssaan' },
  { v: 1186, teksti: 'Liput era 11: Afrikan itainen puolisko' },
  { v: 1185, teksti: 'Kuvatekstiremontti era 2: 123 selitetta Ateenasta Varsovaan' },
  { v: 1184, teksti: 'Matkakirjan ihmeet: nykyaikakuvat, tahtisymboli, Koe ihme' },
  { v: 1183, teksti: 'Liput era 10: Afrikan pohjoinen ja lantinen puolisko' },
  { v: 1182, teksti: 'Kuvatekstiremontti era 1: 116 selitetta 12 kaupungista' },
  { v: 1181, teksti: 'Sankarien aukion faktakorjaus ja taydennys' },
  { v: 1180, teksti: 'Kappadokian avauskuvat: kolme generoitua herokuvaa' },
  { v: 1179, teksti: 'Lentoaani heti napautuksesta, nippuviivat, saumakorjaus' },
  { v: 1178, teksti: 'Matkakirjateksti ei enaa vaihdu vanhaan laatan ratkettua' },
  { v: 1177, teksti: 'Lippusivut era 9: koko Etela-Amerikan lauta' },
  { v: 1176, teksti: 'Lippusivut era 8: koko Pohjois-Amerikan lauta' },
  { v: 1175, teksti: 'Trackpad: kaksi sormea panoroi, portaaton nipistys' },
  { v: 1174, teksti: 'Kehittajan maailmanappi ja Matkakirjan ihmeet -linjaus' },
  { v: 1173, teksti: 'Kohdesymbolit ja nykyisen kaupungin laatta pienemmiksi' },
  { v: 1172, teksti: 'Ihmeiden rekonstruktiokuvat kortteihin' },
  { v: 1171, teksti: 'Miniatyyrit Vilnaan, Tallinnaan, Ankaraan ja Izmiriin' },
  { v: 1170, teksti: 'Miniatyyrit itaiseen Eurooppaan + kaupunkisymbolin kuva' },
  { v: 1169, teksti: 'Antiikin kadonneet ihmeet fokuskohteiksi' },
  { v: 1168, teksti: 'Izmirin herokuvat avauskaruselliin' },
  { v: 1167, teksti: 'Loydetyn laatan siistinta ja Akropolis laatan viereen' },
  { v: 1166, teksti: 'Miniatyyrit Osloon, Dubliniin, Barcelonaan ja Edinburghiin' },
  { v: 1165, teksti: 'Kaupunkisymboli ja symboli jokaiselle kortinavaajalle' },
  { v: 1164, teksti: 'Panoroinnin jaannoskirjoitukset nollaan + Macin introkartta' },
  { v: 1163, teksti: 'Miniatyyrit Madridiin, Lissaboniin, Budapestiin ja Varsovaan' },
  { v: 1162, teksti: 'Generoidut kaiverrussymbolit karttamerkkeihin' },
  { v: 1161, teksti: 'Pelin nimi Matkakirja etusivujulisteen karkeen' },
  { v: 1160, teksti: 'Mitorajin Ikaros Sisilian herokuvan selitteeseen' },
  { v: 1159, teksti: 'Miniatyyrit Ateenaan, Sofiaan, Bukarestiin ja Sarajevoon' },
  { v: 1158, teksti: 'Viivainten panorointikirjoitukset 9,3 -> 0,9/kehys' },
  { v: 1157, teksti: 'Sisilian herokaruselli + leveampi kohdekortti' },
  { v: 1156, teksti: 'Miniatyyriprompit 20 Euroopan kaupungille' },
  { v: 1155, teksti: 'Akropolis-museon kierrokset pois (upotus ei toimi)' },
  { v: 1154, teksti: 'Elainkohteille useampi kuva (Srebarna, Van)' },
  { v: 1153, teksti: 'Yksi kuplataky per maa, kupla avaa suoraan' },
  { v: 1152, teksti: 'Raamattuun kohdekartan kohdemaara 6-15' },
  { v: 1151, teksti: 'Raamattuun: elainkohteille lisakuvat + livekamerat' },
  { v: 1150, teksti: 'Elainkohteen kuva nayttaa elaimen (Srebarna)' },
  { v: 1149, teksti: 'Kohdekortin kuva isommaksi, kuvateksti irti' },
  { v: 1148, teksti: 'Maataulun lahderivi kokonaan pois' },
  { v: 1147, teksti: 'Kohdekortin raahaus ei enaa rapsahda lopussa' },
  { v: 1146, teksti: 'Maataulun Samat luvut -selite pois' },
  { v: 1145, teksti: 'Kreetan lehdelle herokuvakaruselli' },
  { v: 1144, teksti: 'API-generointilupa Raamattuun + symbolieraajo' },
  { v: 1143, teksti: 'Kohdemerkit hieman pienemmiksi (16 -> 14 px)' },
  { v: 1142, teksti: 'Matkustusreittien askelet laudan noppapisteista' },
  { v: 1141, teksti: 'Panorointi div-kuoreen: asettelu 0,35/kehys' },
  { v: 1140, teksti: 'Kategorialuokat nominatiiviin (Ruoka ja juoma)' },
  { v: 1139, teksti: 'MATKUSTA kullatuksi paanapiksi' },
  { v: 1138, teksti: 'Aktiivisen tayn symboli pysyy kuplan alla' },
  { v: 1137, teksti: 'Kaannetty laatta kaiverruskielelle (arkkukuvake)' },
  { v: 1136, teksti: 'Siivous: testitiedosto pois reposta' },
  { v: 1135, teksti: 'Raamattuun arkkikirjasto-linjaus (pop-upien kieli)' },
  { v: 1134, teksti: 'Paljastus: ruksi pois, reunat kuultavat' },
  { v: 1133, teksti: 'Kohtaamisen Kylla/Ei oikeiksi napeiksi' },
  { v: 1132, teksti: 'Kortin ylarivi: symboli+luokka; etusivun blur koko ruutuun' },
  { v: 1131, teksti: 'Bukarestin lehdelle herokuvakaruselli' },
  { v: 1130, teksti: 'Uudet fokuskohteet Kreikkaan, Bulgariaan ja Turkkiin' },
  { v: 1129, teksti: 'Sarajevon lehdelle herokuvakaruselli' },
  { v: 1128, teksti: 'Kartan panorointi sujuvaksi: mitatut juurisyyt pois' },
  { v: 1127, teksti: 'Paallekkaiset karttamerkit nippuun kaupungin viereen' },
  { v: 1126, teksti: 'Karttasymbolit 12 kategorialle kirjastosta' },
  { v: 1125, teksti: 'Maalehden luenta alkaa leipatekstista' },
  { v: 1124, teksti: 'Ylapalkki tyhjaksi ennen ekaa saapumista' },
  { v: 1123, teksti: 'Etusivun alaotsikko mahtuu kapealle ruudulle' },
  { v: 1122, teksti: 'Pollosavuke julkaisuportiksi Actions-ajona' },
  { v: 1121, teksti: 'Elaintakyt, museokierrokset ja etusivun karttapinta' },
  { v: 1120, teksti: 'Pelitestikierros: 21 korjausta ja saatoa' },
  { v: 1119, teksti: 'Etusivu uusiksi, kartan pohja ehjaksi, erikoispiirit' },
  { v: 1118, teksti: 'Saapumissekvenssi, upeampi lento ja koko laudan atlas' },
  { v: 1117, teksti: 'Lehtien mustat reunat pois puhelimella (JPEG-alfa)' },
  { v: 1116, teksti: 'Koko maailman fokuslehdet atlakseen (93 uutta maata)' },
  { v: 1115, teksti: 'Vanha kartta pois pelista, kartan liike sujuvammaksi' },
  { v: 1114, teksti: 'Lehtien muistikuorma kuriin kuoressa' },
  { v: 1113, teksti: 'Turvatila kattaa koko fokuslehden' },
  { v: 1112, teksti: 'Muistisuojat: puhelinkatot ja turvatila' },
  { v: 1111, teksti: 'Uusi alkuteksti ja luenta' },
  { v: 1110, teksti: 'Nopea avaus, merkit kartan mittakaavaan' },
  { v: 1109, teksti: 'Aarremerkit laattoihin, kiinteat merkkikoot, takykupla' },
  { v: 1108, teksti: 'Suoja paivityksen reload-silmukkaa vastaan' },
  { v: 1107, teksti: 'Neljä uutta maata, aarteet uusiksi, sujuva kartta' },
  { v: 1106, teksti: 'Jatkuva atlas ja kehittajan uudet napit' },
  { v: 1105, teksti: 'Etusivu, sahkeet, Sofia, kohdepopup ja pollo' },
  { v: 1104, teksti: 'Fokus: karaktaari, nostot, luenta, Sofia, lento' },
  { v: 1103, teksti: 'Fokus: lento, napit, kysymykset, viivaimet, hionta' },
  { v: 1102, teksti: 'Fokus: kamera rajattu, laudan piilotus, maataulu' },
  { v: 1101, teksti: 'Kevyt kulku, aanet, Eurooppa, hionta' },
  { v: 1100, teksti: 'Fokusnakyma: mitat, kohteet, napit' },
  { v: 1099, teksti: 'Kortin vieritys ei panoroi karttaa' },
  { v: 1098, teksti: 'Pallot piiloon, suurennos ja kortit' },
  { v: 1097, teksti: 'Aloituslento kartalla, kuvazoom' },
  { v: 1096, teksti: 'Fokuskartta prototyypin lehdeksi' },
  { v: 1095, teksti: 'Fokuskartan polku korjattu' },
  { v: 1094, teksti: 'Pollon kuplat, kuvat kartalle' },
  { v: 1093, teksti: 'Fokusvirran tuplakortti ja fokuskartta korjattu' },
  { v: 1092, teksti: 'Fokusvirta: Ateenan annostelu' },
  { v: 1091, teksti: 'Kreikan fokuskartta ja kamera-ajot' },
  { v: 1090, teksti: 'Fokusmoodi: kytkimet, kelluva pollo' },
  { v: 1089, teksti: 'Herokuvat 15 uuteen kaupunkiin' },
  { v: 1088, teksti: 'Oranssi laatta kartalla viitekuvallisille heroille' },
  { v: 1087, teksti: 'OpenAIn ja Googlen kulut kiintiopalkkeihin' },
  { v: 1086, teksti: 'Herokierros 21 viitekuvilla ja Valparaiso' },
  { v: 1085, teksti: 'Adelaide, Hobart, Darwin ja Port Moresby' },
  { v: 1084, teksti: 'Havanna, Mexico City, New Orleans ja Bogota' },
  { v: 1083, teksti: 'Montevideon kaupunkilehti' },
  { v: 1082, teksti: 'Lisaa kuvia -galleria seitsemasta lahteesta' },
  { v: 1081, teksti: 'Neljä korjattua herokuvaa viitekuvilla' },
  { v: 1080, teksti: 'Tampereen herot viitekuvilla ja Oodi uusiksi' },
  { v: 1079, teksti: 'Viitekuvat herokuvien generointiin' },
  { v: 1078, teksti: 'Matkakirjan tekstille koko leveys takaisin' },
  { v: 1077, teksti: 'Kuvien kokoruutu takaisin, Quito ja Los Angeles' },
  { v: 1076, teksti: 'Tilastotaulun otsikkorivi pysyy, kuvapino piiloon' },
  { v: 1075, teksti: 'Liman kaupunkilehti' },
  { v: 1074, teksti: 'Toronton kaupunkilehti' },
  { v: 1073, teksti: 'Viisi kohdekarttaa ja nelja uutta kaupunkilehtea' },
  { v: 1072, teksti: 'Herot Wellingtonista Tallinnaan — kuusi kaupunkia' },
  { v: 1071, teksti: 'Vancouverin kaupunkilehti' },
  { v: 1070, teksti: 'Melbournen kaupunkilehti' },
  { v: 1069, teksti: 'New Yorkin kohteille yhdeksän akvarellipiirrosta' },
  { v: 1068, teksti: 'Sevillan, Bergenin ja Montrealin kaupunkilehdet' },
  { v: 1067, teksti: 'Wellingtonin kaupunkilehti' },
  { v: 1066, teksti: 'Herot Varsovasta Jekaterinburgiin — kuusi kaupunkia' },
  { v: 1065, teksti: 'New Yorkin kohdekartta ja kymmenen nähtävyysjuttua' },
  { v: 1064, teksti: 'Herot Kööpenhaminasta Lhasaan — kuusi kaupunkia' },
  { v: 1063, teksti: 'Maiden rajat E-Amerikan, Oseanian ja Aasian laudoille' },
  { v: 1062, teksti: 'Herot Dublinista Ulan Batoriin — kuusi kaupunkia' },
  { v: 1061, teksti: 'P-Amerikan laudalle maiden rajat' },
  { v: 1060, teksti: 'Astanan keskipäivän hero uusiksi' },
  { v: 1059, teksti: 'Herot Lissabonista Astanaan — kuusi kaupunkia' },
  { v: 1058, teksti: 'Herot Firenzestä Vladivostokiin — kuusi kaupunkia' },
  { v: 1057, teksti: 'Herot Tukholmasta Kolkataan — kuusi kaupunkia' },
  { v: 1056, teksti: 'Ensimmäinen pöllöpoiminta pakettiin (Gaertner)' },
  { v: 1055, teksti: 'Herot Venetsiasta Kantoniin — kuusi kaupunkia' },
  { v: 1054, teksti: 'Leveät vaakakuvat täysleveinä nostosivuilla' },
  { v: 1053, teksti: 'Poistonappi avattuun pöllöpoimintaan' },
  { v: 1052, teksti: 'Poiminnat-oikotie valikkoon; tallennus kuratointijonoon' },
  { v: 1051, teksti: 'Herot Madridista Kiotoon — kuusi uutta kaupunkia' },
  { v: 1050, teksti: 'Herokarusellit Rioon, BA:iin, Sydneyyn ja Aucklandiin' },
  { v: 1049, teksti: 'E-Amerikan ja Oseanian pilotit: 4 kaupunkia, 4 maata' },
  { v: 1048, teksti: 'New Yorkin ja San Franciscon herokarusellit' },
  { v: 1047, teksti: 'New York, San Francisco ja USA — P-Amerikan pilotti' },
  { v: 1046, teksti: 'Pöllöpillerit; aihesivujen teksti kiertää kuvaa' },
  { v: 1045, teksti: 'Kohdekartalle nimet numeroiden tilalle' },
  { v: 1044, teksti: 'Vaakunan ruskea napautuskorostus pois iPadilla' },
  { v: 1043, teksti: 'Tilastoihin Herot- ja Juliste-sarakkeet' },
  { v: 1042, teksti: 'Herokuvat kuuteen kaupunkiin Ateenasta Luxoriin' },
  { v: 1041, teksti: 'Aihesivujen toisteiset sitaattinostot poistettu' },
  { v: 1040, teksti: 'Kuvien lähderivi kuvatekstin jatkoksi pienemmällä' },
  { v: 1039, teksti: 'Akvarellit valmiit: 24 kaupunkia, Dubai ja Istanbul uusina' },
  { v: 1038, teksti: 'Valmiusvärit kehittäjäkartalle, kohdekyltti alemmas' },
  { v: 1037, teksti: 'Pöllön valmiskysymykset kaikkiin 112 kaupunkiin' },
  { v: 1036, teksti: 'Menovinkkien taitto ei enää vuoda muille aihesivuille' },
  { v: 1035, teksti: 'Maalehden nostot palstaan, linkkisisennys pienemmäksi' },
  { v: 1034, teksti: 'Kuvasuurennoksen selite kapeammalle palstalle' },
  { v: 1033, teksti: 'Peliä voi nyt pelata myös vaakasuunnassa' },
  { v: 1032, teksti: 'Helsingin karusellista pois toisteinen herokuva' },
  { v: 1031, teksti: 'Julisteet 112 kaupunkiin ja etusivun kuvat herokokoon' },
  { v: 1030, teksti: 'Kuvatekstiremontti valmis: selitteet kertovat kohteesta' },
  { v: 1029, teksti: 'Kokoruudulla piirros suurenee kartan päällä, ei korttia' },
  { v: 1028, teksti: 'Aasian kuvatekstit uusittu: 19 kaupunkia kertoo kohteesta' },
  { v: 1027, teksti: 'Kokoruudulla piirros aukeaa ensin korttina' },
  { v: 1026, teksti: 'Akvarelliminiatyyrit leikattu läpinäkyviksi' },
  { v: 1025, teksti: 'Akvarellipilotti: Helsingin miniatyyrit värillisinä' },
  { v: 1024, teksti: 'Lähi-idän kaupunkien kuvatekstiremontti valmis' },
  { v: 1023, teksti: 'Julistekokoelma laajeni 64 kaupunkiin (välijulkaisu)' },
  { v: 1022, teksti: 'Herokuvat: Bangkok — kierros 6 valmis' },
  { v: 1021, teksti: 'Kuvageneroinnin päiväraja 300:aan massatuotantoon' },
  { v: 1020, teksti: 'Herokuvat: Wien ja Petra' },
  { v: 1019, teksti: 'Euroopan kaupunkien kuvatekstiremontti valmis' },
  { v: 1018, teksti: 'Maalehtien kuvatekstiremontti valmis (52 maata)' },
  { v: 1017, teksti: 'Herokuvat: Moskova, Mekka ja Hongkong' },
  { v: 1016, teksti: 'Maalehtien kuvatekstit: 30 maata kohde-linjaan' },
  { v: 1015, teksti: 'Kuvatekstiremontin erä 2: 12 Euroopan kaupunkia' },
  { v: 1014, teksti: 'Herokuvat: Rooma, Jerusalem ja Singapore' },
  { v: 1013, teksti: 'Lunasta juliste -nappi oikean vastauksen alle' },
  { v: 1012, teksti: 'Herot: Lontoo, Dubai, Shanghai; tekstiremontti alkoi' },
  { v: 1011, teksti: 'Julisterivi laukkuun ja maanosagalleria; 15 julistetta' },
  { v: 1010, teksti: 'Herokuvat: Pariisi, Istanbul ja Delhi' },
  { v: 1009, teksti: 'Äänet mediakanavaan; mykistys kattaa striimiluennan' },
  { v: 1008, teksti: 'Karachin kaupunkilehti — Aasian lauta valmis' },
  { v: 1007, teksti: 'Laitteen äänenvoimakkuusnapit säätävät nyt peliä' },
  { v: 1006, teksti: 'Colombon kaupunkilehti alusta asti' },
  { v: 1005, teksti: 'Kuvatekstilinjaus Raamattuun; herotekstit uusiksi' },
  { v: 1004, teksti: 'Kehittäjäkartta: herokuvakaupungit violetilla' },
  { v: 1003, teksti: 'Kokoruutukartta: kohteet aukeavat, zoomi levenee' },
  { v: 1002, teksti: 'Herokuvat: Kairo, Tokio ja Xi\'an; havainnekuva-tekstit' },
  { v: 1001, teksti: 'Kuvageneroinnin päiväraja nostettu 150:een' },
  { v: 1000, teksti: 'v1000: herokuvakoe — Helsinki ja Peking' },
  { v: 999, teksti: 'v999: Grafiikka-lehden tyylikoe ja seliteoikaisut' },
  { v: 998, teksti: 'v998: Grafiikka-lehti — julistekatselmus työhuoneeseen' },
  { v: 997, teksti: 'v997: 18 puuttuvaa sääriviä täydennetty' },
  { v: 996, teksti: 'v996: Mumbai — uusi kaupunkilehti' },
  { v: 995, teksti: 'v995: Chennai — uusi kaupunkilehti' },
  { v: 994, teksti: 'v994: Kabul — uusi kaupunkilehti' },
  { v: 993, teksti: 'v993: Kolkata — uusi kaupunkilehti' },
  { v: 992, teksti: 'v992: Kašgar ja Lhasa — uudet kaupunkilehdet' },
  { v: 991, teksti: 'v991: Jakartan ja Manilan ennen/nyt-parit' },
  { v: 990, teksti: 'v990: Borneo ja Sumatra — uudet aluelehdet' },
  { v: 989, teksti: 'v989: Manila — uusi kaupunkilehti' },
  { v: 988, teksti: 'v988: Jakarta, ennen ja nyt -parit ja julistepalkinnot' },
  { v: 987, teksti: 'v987: äänirivin ennen ja nyt — vanha tallenne radiolle' },
  { v: 986, teksti: 'v986: ennen ja nyt -kuvapari etusivulle (pilotti)' },
  { v: 985, teksti: 'v985: maan kartta kokoruudulle, iPad-mitoitus kuntoon' },
  { v: 984, teksti: 'v984: Taipei ja Hongkong — uudet kaupunkilehdet' },
  { v: 983, teksti: 'v983: Pollo lukee sen jutun jota pelaaja katsoo' },
  { v: 982, teksti: 'v982: kokoruutukartta zoomaa, sulku vain rastista' },
  { v: 981, teksti: 'v981: lukijaoletukset — nopeus 1,2x ja voima 2,0' },
  { v: 980, teksti: 'v980: etusivun anfangi myos kaupunkilehteen' },
  { v: 979, teksti: 'v979: kohdekartta aukeaa napautuksesta kokoruudulle' },
  { v: 978, teksti: 'v978: Yangon ja Mandalay — uudet kaupunkilehdet' },
  { v: 977, teksti: 'v977: maan etusivun kartta isommaksi' },
  { v: 976, teksti: 'v976: kansikuvaremontti valmis — 37 kaupunkia laajoiksi' },
  { v: 975, teksti: 'v975: perustiedot almanakan faktalaatikoksi' },
  { v: 974, teksti: 'v974: kansikuvaremontti era 1 — 13 kaupunkia laajoiksi' },
  { v: 973, teksti: 'v973: Astana ja Kanton — uudet kaupunkilehdet' },
  { v: 972, teksti: 'v972: tehtavalaatikko lehden tyyliin' },
  { v: 971, teksti: 'v971: sivunimet nappeihin ja kansikuvalinjaus Raamattuun' },
  { v: 970, teksti: 'v970: Kathmandu — uusi kaupunkilehti' },
  { v: 969, teksti: 'v969: Ulan Bator — uusi kaupunkilehti' },
  { v: 968, teksti: 'v968: Hanoi — uusi kaupunkilehti' },
  { v: 967, teksti: 'v967: teemasivujen kuvat kainaloon, teksti vierelle' },
  { v: 966, teksti: 'v966: Xi\'an, Varanasi ja kakkossivujen otsikkouudistus' },
  { v: 965, teksti: 'v965: Samarkand — uusi lehti' },
  { v: 964, teksti: 'v964: teemasivuille omat osasto-otsikot' },
  { v: 963, teksti: 'v963: tekstiremontti valmis — E6-E8' },
  { v: 962, teksti: 'v962: opaskuvat pystyyn, Mosulin etusivu nykyaikaan' },
  { v: 961, teksti: 'v961: Singapore + tekstiremontti E4-E5' },
  { v: 960, teksti: 'v960: tekstiremontti E1-E3 — 15 Euroopan lehteä' },
  { v: 959, teksti: 'v959: karttaerottelu + remontti R6, R7, R9b' },
  { v: 958, teksti: 'v958: karttakorjaus + tekstiremontti R4+R5' },
  { v: 957, teksti: 'v957: tekstiremontti R2+R3 — 8 lehteä' },
  { v: 956, teksti: 'v956: palstataitto ja tekstiremontti R1' },
  { v: 955, teksti: 'v955: Kioto — uusi lehti uudella tekstilinjalla' },
  { v: 954, teksti: 'v954: Delhi, V1+V3, karttavärit, Isfahan-pilotti' },
  { v: 953, teksti: 'v953: tilannelehti käytettävään muotoon' },
  { v: 952, teksti: 'v952: Jakutsk ja Magadan — kartat, kuvat ja opas' },
  { v: 951, teksti: 'v951: Peking — kohdekartta kainaloineen ja lehti' },
  { v: 950, teksti: 'v950: Bangkok — ensimmäinen uusi Aasian lehti' },
  { v: 949, teksti: 'v949: Mosul, Halab ja Damaskos nykytietolinjaan' },
  { v: 948, teksti: 'v948: Tilastot-korjaus, tilanne ajan tasalle, nykytieto 1' },
  { v: 947, teksti: 'Salalah ja Mosul: kohdekartat, jutut, avauskuvat ja opas' },
  { v: 946, teksti: 'Riad, Doha ja Kuwait: avauskuvat ja matkaopas' },
  { v: 945, teksti: 'Sana ja Aden: kohdekartat, jutut, avauskuvat ja opas' },
  { v: 944, teksti: 'Masqat, Tabriz ja Isfahan: avauskuvat ja matkaopas' },
  { v: 943, teksti: 'Halab, Damaskos ja Luxor: avauskuvat ja matkaopas' },
  { v: 942, teksti: 'Tilastoihin tuoreusvärit, suodatin ja chipit' },
  { v: 941, teksti: 'Ankara, Nikosia ja Izmir: avauskuvat ja matkaopas' },
  { v: 940, teksti: 'Persepoliksen kohdekartta ja jutut; Luxorin kartta korjattu' },
  { v: 939, teksti: 'Rub al-Khali: uusi aluelehti ja säärivi' },
  { v: 938, teksti: 'Mekka: uusi lehti, kohdekartta, opas ja säärivi' },
  { v: 937, teksti: 'Medina: uusi lehti, kohdekartta, opas ja säärivi' },
  { v: 936, teksti: 'Siirtopromptit aina kopioitavana koodilohkona' },
  { v: 935, teksti: 'Wabarin paino punnittuun lukuun; kuvalinjaus kirjattu' },
  { v: 934, teksti: 'Siinain aluelehti: 8 nostoa ja matkaopas' },
  { v: 933, teksti: 'Jerusalemin lehti, kohdekartta ja kuusi juttua' },
  { v: 932, teksti: 'Persepoliksen lehti: 8 nostoa ja matkaopas' },
  { v: 931, teksti: 'Kappadokian aluelehti: 8 nostoa ja matkaopas' },
  { v: 930, teksti: 'Petran lehti alusta: kartta, 9 juttua, opas' },
  { v: 929, teksti: 'Izmirin avauskuvat — Lähi-idän lehtityö alkaa' },
  { v: 928, teksti: 'Moskova, Pietari, Tromssa ja Lappi — Eurooppa valmis' },
  { v: 927, teksti: 'Alpit, Kreeta ja Sisilia: Matkailijalle-osiot' },
  { v: 926, teksti: 'Odessa, Kiova ja Islanti: Matkailijalle-osiot' },
  { v: 925, teksti: 'Bukarest, Dubrovnik ja Sarajevo: Matkailijalle' },
  { v: 924, teksti: 'Marseille, Granada ja Sofia: Matkailijalle-osiot' },
  { v: 923, teksti: 'Riika, Vilna ja Oslo: Matkailijalle-osiot' },
  { v: 922, teksti: 'Varsova, Krakova ja Tallinna: Matkailijalle-osiot' },
  { v: 921, teksti: 'Dublin, Edinburgh ja Budapest: Matkailijalle-osiot' },
  { v: 920, teksti: 'Madrid, Barcelona ja Ateena: Matkailijalle-osiot' },
  { v: 919, teksti: 'Matkailijan Tukholma -opas' },
  { v: 918, teksti: 'Matkailijan Amsterdam -opas' },
  { v: 917, teksti: 'Matkailijan Lissabon -opas, ensimmainen Flickr-kuva' },
  { v: 916, teksti: 'Matkailijan Venetsia -opas' },
  { v: 915, teksti: 'Avauskuvat viidelle Euroopan aluelehdelle' },
  { v: 914, teksti: 'Avauskuvat Pietariin, Moskovaan ja Tromssaan' },
  { v: 913, teksti: 'Pöllön kuva vasta ladattuna; visan aihe lehteen' },
  { v: 912, teksti: 'Avauskuvat kuudelle Euroopan lehdelle' },
  { v: 911, teksti: 'Matkailijan Praha: uusi opas viidellä jaksolla' },
  { v: 910, teksti: 'Avauskuvat kuudelle Euroopan lehdelle' },
  { v: 909, teksti: 'Avauskuvat Varsovaan, Krakovaan ja Tallinnaan' },
  { v: 908, teksti: 'Avauskuvat Prahaan, Tukholmaan ja Venetsiaan' },
  { v: 907, teksti: 'Avauskuvat Lissaboniin, Dubliniin ja Edinburghiin' },
  { v: 906, teksti: 'Avauskuvat Ateenaan, Madridiin ja Barcelonaan' },
  { v: 905, teksti: 'Avauskuvat Roomaan, Wieniin ja Amsterdamiin' },
  { v: 904, teksti: 'Sankarien aukion mitat lahteineen hu-Wikipediasta' },
  { v: 903, teksti: 'Sankarien aukiolle oma juttu; Helsingin opas nykymalliin' },
  { v: 902, teksti: 'Dubain lehti: 4 uutta kohdetta, opas, avauskuvat' },
  { v: 901, teksti: 'Nähtävyyskuva isoksi puhelimessa; pöllökortti selkeäksi' },
  { v: 900, teksti: 'Istanbulin lehti: 4 uutta kohdetta, opas, avauskuvat' },
  { v: 899, teksti: 'Kartan tilabugi 3: paluun vakiintumisvahti + näppäimistö' },
  { v: 898, teksti: 'Tietäjän tiellä nykyinen pöllö isona selityksen vieressä' },
  { v: 897, teksti: 'Oppaalle tarttuva otsikkorivi; kelluva kaiutin pois' },
  { v: 896, teksti: 'Valittavat siirtokohteet erottuvat: punarengas ja halo' },
  { v: 895, teksti: 'Pöllön juttu aukeaa chatin päälle, sulku palaa chattiin' },
  { v: 894, teksti: 'Paljastuskortti vaalealle sumealle pohjalle' },
  { v: 893, teksti: 'Pöllön kuvan suurennos ei enää katkaise puhetta' },
  { v: 892, teksti: 'Schönbrunnille oma juttu; nähtävyysikkuna leveämpi iPadilla' },
  { v: 891, teksti: 'Kartta ei jää pieneksi: nipistysjumi ja lehden sulku' },
  { v: 890, teksti: 'Pöllön kysymykset yhteen vierityspintaan; vanhat pois' },
  { v: 889, teksti: 'Tietäjätasot vaativat nyt paljon enemmän pelaamista' },
  { v: 888, teksti: 'Pöllö korvaa 1. aarteen; aarretekstit lyhyiksi; kertoja pois' },
  { v: 887, teksti: 'Luvuista turha sarake pois; liitenappi vain lehtiin' },
  { v: 886, teksti: 'Onnittelukupla laukun kohdalle; kupla pois kosketuksesta' },
  { v: 885, teksti: 'Ääninapit kuntoon; luenta lakkaa kortin mukana' },
  { v: 884, teksti: 'Pöllön väkänen alas; pro-kirjautuminen pohjalle' },
  { v: 883, teksti: 'Palautelappu keskelle; pro-rasti ennen lähetystä' },
  { v: 882, teksti: 'Tietäjärivillä nimike, i ja oikealla vain pisteet' },
  { v: 881, teksti: 'Pöllölle valmiskysymykset ja ehdota-nappi' },
  { v: 880, teksti: '30 miniatyyriä: Kairo kokonaan + uudet kohteet' },
  { v: 879, teksti: 'Ehdotuslomakkeeseen saate ja pro-rasti selitteineen' },
  { v: 878, teksti: '15 uutta nähtävyyskohdetta kuuteen kaupunkiin' },
  { v: 877, teksti: 'Miniatyyrit sävytetty kartan pohjaväriin' },
  { v: 876, teksti: 'Oppaan vuosisää avaa saman sääkortin kuin lehti' },
  { v: 875, teksti: 'E00-lehdet: aihesivut ja avauskuvat' },
  { v: 874, teksti: 'Laukku kapeampi iPadilla, varusteet 4 riviin' },
  { v: 873, teksti: 'Kairon lehti täydennetty: kohteet ja opas' },
  { v: 872, teksti: 'Lukija lukee kappaleen kerralla; korostus kevyempi' },
  { v: 871, teksti: 'Lehden alareuna ankkureihin; taustapaluusovitus' },
  { v: 870, teksti: 'Laukun varusteet yhdeksi kuvaruudukoksi' },
  { v: 869, teksti: 'Uudet selkeämmät varustekuvat laukkuun' },
  { v: 868, teksti: 'Lukija lukee vain leipätekstit; pysyvä kaiutin' },
  { v: 867, teksti: 'Pöllön ehdotuskupla osoittaa hampurilaiseen' },
  { v: 866, teksti: 'Varustekuvien uusinta: selkeät promptit ja ajuri' },
  { v: 865, teksti: 'Tampereelle 8 ja Firenzeen 9 nähtävyyskohdetta' },
  { v: 864, teksti: 'Tilastolehden sarakeotsikot näkyviin iPadilla' },
  { v: 863, teksti: 'Tietäjäavatarit, värssyt ja tasogalleria' },
  { v: 862, teksti: 'Kohdekartan ohje kartan päälle opasteeksi' },
  { v: 861, teksti: 'Palautedialogi suoraan ehdotuslomakkeeksi' },
  { v: 860, teksti: 'Työhuoneen tilastot peliin, erillissivusto pois' },
  { v: 859, teksti: 'Kaikki aarteet uuteen paljastusnäkymään' },
  { v: 858, teksti: 'Vuosisäähän ylin ja alin lämpötila (vaihteluvyöhyke)' },
  { v: 857, teksti: 'Pro-tuottajat: koodit, profiilit ja tekijasivut' },
  { v: 856, teksti: 'Viisas Pöllö on löydettävä aarre' },
  { v: 855, teksti: 'Tietäjätasot ja matkalaukku-uudistus' },
  { v: 854, teksti: 'Ehdotuskanava auki: uusi- ja ehdota-napit valikkoon' },
  { v: 853, teksti: 'Lukijoiden ehdotukset: lomake, työhuonelehti ja pöllö' },
  { v: 852, teksti: 'Flickr-kuvat Tokion, Soulin ja Shanghain lehtiin' },
  { v: 851, teksti: 'Lippukortin leikkaus kuntoon iPadilla (kehysremontti)' },
  { v: 850, teksti: 'Raamattuun: ehdotuspalkkio pelirahana (lunastuskoodi)' },
  { v: 849, teksti: 'Raamattuun: lukijoiden ehdotukset -kanavan linjaus' },
  { v: 848, teksti: 'Karusellinuolen vaalea harso pois napautuksen jälkeen' },
  { v: 847, teksti: 'Neljä uusittua miniatyyriä kartalle (erä 3)' },
  { v: 846, teksti: 'Flickr-valokuvat Firenzen ja Tampereen lehtiin' },
  { v: 845, teksti: 'Raamattuun: kaikki sisältö ämpäristä (R2-peili)' },
  { v: 844, teksti: 'Miniatyyripiirrokset kahdeksaan uuteen kaupunkiin' },
  { v: 843, teksti: 'Lippuikkunan lippu terävänä ja laatta kortin sisään' },
  { v: 842, teksti: 'Karusellinuolten tummennus pois kuvien laidoista' },
  { v: 841, teksti: 'Syvä lähikuva tarkentuu odottamatta puskurirengasta' },
  { v: 840, teksti: 'Oppaan karussellikuvan yläpuolinen tumma palkki pois' },
  { v: 839, teksti: 'Kartta tarkentuu heti nopean zoomailun jälkeen' },
  { v: 838, teksti: 'Turhat suorat reitit pois uusien kaupunkien tieltä' },
  { v: 837, teksti: 'Kartta ei jää jumiin taustapaluussa' },
  { v: 836, teksti: 'Tokio, Soul ja Shanghai valmiiksi: kohdekartat' },
  { v: 835, teksti: 'Bagdad, Teheran ja Tripoli valmiiksi: kohdekartat' },
  { v: 834, teksti: 'Lehti täyttää puhelimen ruudun; alakaista pois' },
  { v: 833, teksti: '13 uutta kaupunkia laudoille ja maailmankartalle' },
  { v: 832, teksti: 'Firenze Euroopan laudalle' },
  { v: 831, teksti: 'Tampere ja Rovaniemi Euroopan laudalle' },
  { v: 830, teksti: 'M7b: panorointi ja eleet Kartta-luokkaan' },
  { v: 829, teksti: 'M7a: kamera omaksi Kartta-luokaksi' },
  { v: 828, teksti: 'Pergamentti täyttää ruudun kaikilla ikkunamuodoilla' },
  { v: 827, teksti: 'Raamattuun M7+, aikajana-ajo ja lavalinssi' },
  { v: 826, teksti: 'Raamattuun kaksi linjausta, kaksi dokumenttia arkistoon' },
  { v: 825, teksti: 'Raamattuun Poistetut ideat -osio, päälinjat tiiviimmiksi' },
  { v: 824, teksti: 'Lehtitila-olio, savukevartija ja pöllön nähtävyyslinkki' },
  { v: 823, teksti: 'Islanti paikalleen, säänluonnehdinta joka kaupunkiin' },
  { v: 822, teksti: 'Tuotantosuunnitelma jäljellä oleville kohteille' },
  { v: 821, teksti: 'Luenta ja visa omiksi moduuleikseen (M6)' },
  { v: 820, teksti: 'Maalehti ja sisällys omaksi moduulikseen (M5c)' },
  { v: 819, teksti: 'Kuvataitto, sää ja uutiset lehti.js:ään (M5b)' },
  { v: 818, teksti: 'Lehden sivukoneisto omaksi moduulikseen (M5a)' },
  { v: 817, teksti: 'Opas ja nähtävyydet omiksi moduuleiksi (M4)' },
  { v: 816, teksti: 'Opas ja kaupunkiosiot: Tokio, Soul, Shanghai, Tripoli' },
  { v: 815, teksti: 'Liput, karttazoom ja vertailu omiksi moduuleiksi (M3)' },
  { v: 814, teksti: 'UI:n apurit ja kehysmatikka omaan moduuliin (M2)' },
  { v: 813, teksti: 'Sisältötaulut omaksi moduulikseen (remontti M1)' },
  { v: 812, teksti: 'Miniatyyrigenerointiin hybridimalli (halpa/pro per kohde)' },
  { v: 811, teksti: 'Raamattuun: uusiin kohteisiin vain lehdet, ei kaarta' },
  { v: 810, teksti: 'Matkakassa pois, hintatasorivit, säänluonnehdinnat alkuun' },
  { v: 809, teksti: 'Raamattuun oppaan avauskuvan linjaus' },
  { v: 808, teksti: 'Moduuli- ja dokumenttiremontin suunnitelmat hyväksytty' },
  { v: 807, teksti: 'Raamattuun Matkakassa-linjaus; työlistaan paketti O5' },
  { v: 806, teksti: 'Raamattuun maalehden nimiö ja Matkailijalle-kuvan kaava' },
  { v: 805, teksti: 'Matkailijan Teheran' },
  { v: 804, teksti: 'Matkailijan Bagdad: opas kuudesta uudesta' },
  { v: 803, teksti: 'Kaiuttimen kuvake otsikon kokoiseksi' },
  { v: 802, teksti: 'Arkin alanapit kotipalkin ylapuolelle iPadilla' },
  { v: 801, teksti: 'Kaiutin otsikon perään, kohdelaskuri pois' },
  { v: 800, teksti: 'Etusivun avausteksti pergamentille' },
  { v: 799, teksti: 'Arkin alalaita takaisin ruudulle' },
  { v: 798, teksti: 'Pöllön kuvapopup isommaksi' },
  { v: 797, teksti: 'Oppaan otsikko esiin loveuksen alta' },
  { v: 796, teksti: 'Viiden oppaan avauskuva kolmen kuvan karuselliksi' },
  { v: 795, teksti: 'Helsingin etusivulle Uspenskin katedraali' },
  { v: 794, teksti: 'Wien, Rooma ja Kööpenhamina: pystykuva etusivulle' },
  { v: 793, teksti: 'Orsayn museolle piirros kartalle' },
  { v: 792, teksti: 'Pariisin uusille kohteille piirrokset kartalle' },
  { v: 791, teksti: 'Berliini: Fernsehturm etusivulle pystykuvana' },
  { v: 790, teksti: 'Lontoo: pystykuva etusivulle, karuselli oppaan alkuun' },
  { v: 789, teksti: 'iPad: korkeuden muutos laskee kartan uusiksi' },
  { v: 788, teksti: 'Pariisiin 3 kohdetta, sää kaikkiin 70 kaupunkiin' },
  { v: 787, teksti: 'Lippu maasivun otsikkoon, Eiffel etusivulle, kuvakaava' },
  { v: 786, teksti: 'Opas 5 kaupunkiin: Lontoo, Wien, Berliini, Rooma, Kbh' },
  { v: 785, teksti: 'Sää 32 lehteen, oppaan graafi lehden omaksi, maan nimiö' },
  { v: 784, teksti: 'iPad: kortin alanapit eivät katoa taustapaluun jälkeen' },
  { v: 783, teksti: 'Opas: säägraafi lehtityyliin, Seine-karuselli, paperi' },
  { v: 782, teksti: 'Opas 2.2: kevyt kainalotaulu, säägraafi, kuvahionta' },
  { v: 781, teksti: 'Etusivun nauha koko osion yli, pehmeämmät värit' },
  { v: 780, teksti: 'Opas 2.1: kainalot, paletti, iso otsikko, lämmin kuva' },
  { v: 779, teksti: 'Etusivun opaskyltti: yksi diagonaalinauha' },
  { v: 778, teksti: 'Matkailijalle-kuvatekstit yhteen lauseeseen (7 kaupunkia)' },
  { v: 777, teksti: 'Matkailijalle: kyltti kuvan kulmaan, vaaleampi tausta' },
  { v: 776, teksti: 'Matkailijan opas 2.0: jaksot, laatikot, värit (Pariisi)' },
  { v: 775, teksti: 'Poistoerä: 455 ääntä pois repostä, jakelu R2:sta' },
  { v: 774, teksti: 'Äänet R2-jakeluun; esilataus 242 Mt → 62 Mt' },
  { v: 773, teksti: 'Maxin työlista: moduulirakenne + dokumenttiremontti' },
  { v: 772, teksti: 'Raamattuun: äänet R2:sta, oppaan ilme, speksioppi' },
  { v: 771, teksti: 'Pariisin etusivu: Eiffel, Orsay, Notre-Dame, Vivienne' },
  { v: 770, teksti: 'Etusivukuvien kaava Raamattuun + 4 kuvakäsikirjoitusta' },
  { v: 769, teksti: 'Piirroskarttojen ohjeteksti ajan tasalle (10 kaupunkia)' },
  { v: 768, teksti: 'Matkailijalle: Berliini, Pariisi, Lontoo, Rooma, Wien' },
  { v: 767, teksti: 'Vaakunan ajoittainen tumma laatikko: oma paperi napeille' },
  { v: 766, teksti: 'Opas: otsikko esiin, kuvat taitettu tekstin lomaan' },
  { v: 765, teksti: 'Köpiksen kohteet 7–9: piirrokset karttaan' },
  { v: 764, teksti: 'Kööpenhaminan kartalle 3 uutta kohdetta juttuineen (Opus 18)' },
  { v: 763, teksti: 'lippuikkuna: iso pelkkä vaakuna; liput kasvavat paikallaan' },
  { v: 762, teksti: 'jutun yläreunan vahti: otsikko ei karkaa avauksessa' },
  { v: 761, teksti: 'työhuoneen kulu- ja lähderivit pois (palkit riittävät)' },
  { v: 760, teksti: 'tarkennetulle vaakunalle pergamenttitausta (Safari)' },
  { v: 759, teksti: 'jutun otsikko ei enää liu\'u piiloon kuvan latautuessa' },
  { v: 758, teksti: 'työhuoneen lähteet oikeisiin muuttujiin (peili↔pöllö)' },
  { v: 757, teksti: 'jutun napit seuraavat korttia; leveys kestää sovellusvaihdon' },
  { v: 756, teksti: 'opas leveämmäksi isolla ruudulla; valikkonappi pois oppaasta' },
  { v: 755, teksti: 'vajaa työhuonetulos ei jää istuntoon; uusi haku avauksesta' },
  { v: 754, teksti: 'työhuoneen kulurivi kertoo lähdevirheen; välimuisti v2' },
  { v: 753, teksti: 'Helsingin Matkailijalle: kappale, kuva ja opas kuvineen' },
  { v: 752, teksti: 'työhuoneen tilannetaulu ajan tasalle (v705–v751)' },
  { v: 751, teksti: 'lippusivut: Kaakkois- ja Etelä-Aasia (10 maata)' },
  { v: 750, teksti: 'paluunuoli henkilöjuttuun; työhuoneen kulurivin oikea syy' },
  { v: 749, teksti: 'Kööpenhamina: palstat, Matkailijalle-kuva, oppaan kuvat' },
  { v: 748, teksti: 'Suurennetun piirroksen osuma-alue 50 % kuvasta' },
  { v: 747, teksti: 'Lippusivut: Lähi-itä (8 maata)' },
  { v: 746, teksti: 'Avauskuvat: Berliini, Helsinki, Pariisi, Lontoo; R2 summana' },
  { v: 745, teksti: 'Etusivun avauskaruselli koko palstan levyiseksi' },
  { v: 744, teksti: 'Työhuoneen R2-palkki megatavuina alle gigan' },
  { v: 743, teksti: 'Pöllön kuva: oikea artikkeli varmistetaan, kaimat hylätään' },
  { v: 742, teksti: 'Lukija vaikenee jokaisesta pop-upista (myös pöllö)' },
  { v: 741, teksti: 'Striimiluennan ääni kuuluu Macin Safarissa (piirin herätys)' },
  { v: 740, teksti: 'Työhuone valikkoon: tilannepalkit, tyylinapit, Lukijaääni' },
  { v: 739, teksti: 'Piirros juttuun tekstin kiertona; klikkausalue 80 %:iin' },
  { v: 738, teksti: 'Kööpenhamina-lehti: yleisnäkymäkaruselli ja Matkailijalle' },
  { v: 737, teksti: 'Kartat 6 uuteen kaupunkiin; piirrokset terävinä (1024 px)' },
  { v: 736, teksti: 'Vain varikartta; numero kylttiin' },
  { v: 735, teksti: 'Suurennos keskitetty; 75 %; kyltti kiinni' },
  { v: 734, teksti: 'Kartta 70 %; tarkennettu lippu ilman laatikkoa' },
  { v: 733, teksti: 'Lippusivut: Aasia' },
  { v: 732, teksti: 'Suurennos 65 %; kyltti kiinni rakennukseen' },
  { v: 731, teksti: 'Lippusivut: Slovenia-Azerbaidzan' },
  { v: 730, teksti: 'Lippuikkunan tarkennus; kartta 40 %' },
  { v: 729, teksti: 'Lippusivut: Ita-Eurooppa ja Balkan' },
  { v: 728, teksti: 'Suurennos 1/4 kartasta; kyltista juttuun; vipunappi' },
  { v: 727, teksti: 'Lippusivut: Lansi-Eurooppa' },
  { v: 726, teksti: 'Lippusivut: Pohjoismaat ja Baltia' },
  { v: 725, teksti: 'Lippuikkunan iso kuva isommaksi' },
  { v: 724, teksti: 'Piirrokset kartan mittakaavassa; peruskoko 40 px' },
  { v: 723, teksti: 'Kultaneliön syy: hover-korostus pois piirroksilta' },
  { v: 722, teksti: 'Miniatyyrit PNG:iksi - varma lapinakyvyys' },
  { v: 721, teksti: 'iOS-korostusneliö pois; suurennos 3,5x' },
  { v: 720, teksti: 'Piirroksen suurennos 3x' },
  { v: 719, teksti: 'Piirroksen klikkaus vain suurentaa' },
  { v: 718, teksti: 'Piirrokset pienemmiksi, nuolet pois' },
  { v: 717, teksti: 'Kartan piirrokset yksivärisinä luonnoksina' },
  { v: 716, teksti: 'Lippuikkuna: symboliikka, vaakunat, 2/3-korkeus' },
  { v: 715, teksti: 'Piirrokset hajalleen nuolin; klikkaus suurentaa' },
  { v: 714, teksti: 'Kartan piirrokset leikattuina, numerot pois' },
  { v: 713, teksti: 'Pöllön kuvalle sykkivä paikanpitäjä haun ajaksi' },
  { v: 712, teksti: 'Pöllön vastauskuva löytyy myös haun kautta' },
  { v: 711, teksti: 'Lipusta aukeaa lipun tarina — pilotti Suomi ja Saksa' },
  { v: 710, teksti: 'Miniatyyrit kolmeen kaupunkiin ja piirrokset pisteiksi' },
  { v: 709, teksti: 'Värikartat Helsinkiin, Pariisiin ja Lontooseen' },
  { v: 708, teksti: 'Berliinin kohteille miniatyyripiirrokset ja karttakortti' },
  { v: 707, teksti: 'Berliinin kohdekartta värein — vipu satelliitin tilalle' },
  { v: 706, teksti: 'Raamatun taitto: kappaleet, yksi palsta, sisällys ehjäksi' },
  { v: 705, teksti: 'Tilannetaulut ajan tasalle v704 asti' },
  { v: 704, teksti: 'Radio väistää puhetta kuten muukin tausta' },
  { v: 703, teksti: 'Pöllö hakee vastaukseen kuvan — pikkukuva aukeaa isoksi' },
  { v: 702, teksti: 'Oletusprompti näkyviin ja aikamerkit pois luennasta' },
  { v: 701, teksti: 'Raamattu uusiksi tiiviinä + valmis/kesken-tagit lehteen' },
  { v: 700, teksti: 'Raamattu ja tilannetaulut tiiviiksi (selkeys ensin)' },
  { v: 699, teksti: 'Omat jutut Panthéonille, Lucolle, Kalliolle, Lintsille' },
  { v: 698, teksti: 'Raamattu ilman 2.0:aa ja tyohuoneen suursiivous' },
  { v: 697, teksti: 'Raamattu ja Tilannelehti luettavina pelissä (kehittäjä)' },
  { v: 696, teksti: 'Kohdekartat jatkuvat reunojen yli neljalla kaupungilla' },
  { v: 695, teksti: 'Lehdet ja lukijan alku latautuvat etukäteen' },
  { v: 694, teksti: 'ElevenLabs-äänitteet palasivat ajantasaisiin merkintöihin' },
  { v: 693, teksti: 'Panthéon, Luxembourg, Kallio ja Linnanmäki kartoille' },
  { v: 692, teksti: 'Taustaäänet tasattiin: hajonta 35 dB -> 4 dB (125 raitaa)' },
  { v: 691, teksti: 'Venäjän radio palasi kuuluviin (omistajan linjaus)' },
  { v: 690, teksti: 'Maalehtien kuvatekstit lyhennettiin (erä 4b) — urakka valmis' },
  { v: 689, teksti: 'Maalehtien kuvatekstit lyhennettiin (Eurooppa, Lähi-itä)' },
  { v: 688, teksti: 'Lontoo, Pariisi ja Helsinki: laajemmat kartat + satelliitit' },
  { v: 687, teksti: 'Tauko ennen otsikkoa, yläotsikko sivunvaihdon perään' },
  { v: 686, teksti: 'Valokuvapakettien postikorttitekstit lyhennettiin (5/5)' },
  { v: 685, teksti: 'Tausta väistyy pehmeästi kaiken luennan ajaksi' },
  { v: 684, teksti: 'Nähtävyysjuttujen kuvatekstit lyhennettiin (erä 3/5)' },
  { v: 683, teksti: 'Jatkuva luenta, aloitusrauha ja pehmeät siirtymät' },
  { v: 682, teksti: 'Kaupunkilehtien nostokuvien kuvatekstit lyhennettiin' },
  { v: 681, teksti: 'Kamtšatka, Sahalin ja Vladivostok saivat lehtensä' },
  { v: 680, teksti: 'kohdekartta zoomattavaksi, Berliini laajempi ja terävämpi' },
  { v: 679, teksti: 'Kaupunkilehtien kansikuvien kuvatekstit lyhennettiin' },
  { v: 678, teksti: 'kohtaamiset ja kaariaarteet lukijaäänelle, äänite varalle' },
  { v: 677, teksti: 'puskurisoitin: hiljaisuudet pois, tasaiset saumat' },
  { v: 676, teksti: 'seurantavieritys vain tarpeeseen ja äänen alun ohi' },
  { v: 675, teksti: 'luentasoitin piiloutuu itsestään, kaiutin vipuaa sen' },
  { v: 674, teksti: 'saumaton palanvaihto: kaksi elementtiä, esilataus, limitys' },
  { v: 673, teksti: 'Siperian kaupunkilehdet: Jakutsk ja Magadan' },
  { v: 672, teksti: 'palanvaihdon nykäisy pois: vähemmän rajoja, pehmeä alku' },
  { v: 671, teksti: 'nopeus generoidaan OpenAI:lla, anfangi maalautuu luennassa' },
  { v: 670, teksti: 'nopeutus ilman hännänleikkausta, säädin suorakaiteeksi' },
  { v: 669, teksti: 'lukunopeus tarttuu myös iPadilla (playbackRate palan alussa)' },
  { v: 668, teksti: 'lukija seuraa: maalaus, aloitus näkyvästä, otsikot niputettu' },
  { v: 667, teksti: 'kaiutin hampurilaisen ilmeeseen, sisällyksen paluu esiin' },
  { v: 666, teksti: 'lehtiasettelu: lippu ja kaiutin otsikkoriviin, reunanapautus' },
  { v: 665, teksti: 'Sisällyksen Etusivu-rivi sai kannen kuvan ja ingressin' },
  { v: 664, teksti: 'Lehden hampurilaiseen Palaa kartalle -rivi' },
  { v: 663, teksti: 'Siperian lehtien kuvatekstikorjaukset' },
  { v: 662, teksti: 'Lukijaäänen säädin peliin kehittäjätilan taakse' },
  { v: 661, teksti: 'Lukunopeussäädin ja sivuotsikon ohitus lehdillä kuntoon' },
  { v: 660, teksti: 'Baikal-fakta, Venäjän radio pois linjauksen mukaisesti' },
  { v: 659, teksti: 'Siperian kaupunkilehdet: Jekaterinburg, Novosibirsk, Irkutsk' },
  { v: 658, teksti: 'Berliinin kaupunkikartalle vipu: piirros tai satelliittikuva' },
  { v: 657, teksti: 'Lukija: napsahdus ja turhat otsikot pois; asetukset säilyvät' },
  { v: 656, teksti: 'Työhuoneeseen Lukijaääni-välilehti äänten säätöön' },
  { v: 655, teksti: 'Lukijalle säätöpaneeli: tauko ja kappalehypyt' },
  { v: 654, teksti: 'Merkinnät lukijaäänellä, äänitteet varalle, ääni ylös' },
  { v: 653, teksti: 'Lukijaääni: puhesynteesi kaiuttimiin ja pöllöön' },
  { v: 652, teksti: 'wikin kuvasuurennos täyteen kokoon iPadilla' },
  { v: 651, teksti: 'myös lehtisivun galleriat esilataavat kuvansa' },
  { v: 650, teksti: 'kuvakarusellit esilataavat kuvansa taustalla' },
  { v: 649, teksti: 'sisällysvalikkoon pääsy lehden etusivulle' },
  { v: 648, teksti: 'hampurilainen tekstin reunaan; maalehden nappi takaisin' },
  { v: 647, teksti: 'lehtiotsikko pitää radiorivin yli; hampurilainen otsikossa' },
  { v: 646, teksti: 'kartan väriläikät pois: rae kattaa koko pohjatason' },
  { v: 645, teksti: 'matkakirja pysyy vasemmassa yläkulmassa zoomatessa' },
  { v: 644, teksti: 'Hampurilainen otsikkoriville pelkkinä viivoina' },
  { v: 643, teksti: 'Lehden nimi tarttuu ylös; hampurilainen molempiin lehtiin' },
  { v: 642, teksti: 'Kartta piirtyy heti eikä ruutuja jäsennellä — zoomi valmis' },
  { v: 641, teksti: 'Zoomi ei enää putoa Safarin syliin; ruudut pakkautuvat heti' },
  { v: 640, teksti: 'Maaselain: kirjanappi vasemmalle, maakyltti oikealle' },
  { v: 639, teksti: 'Zoomi ei hypi eikä töki; kartta liukuu sormen perässä' },
  { v: 638, teksti: 'Maailmankartalle 49 uutta maata maasivuineen' },
  { v: 637, teksti: 'Kirjoituskone kuuluu taas; suurennos oikean levyiseksi' },
  { v: 636, teksti: 'Suurennos täysikokoiseksi; kirjakuvake keskelle' },
  { v: 635, teksti: 'Tokion kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 634, teksti: 'Kuvasarja selaa napautuksella; pöllö ja päivitys valikoista' },
  { v: 633, teksti: 'Kuva ei sulkeudu matkakirjasta; pilleri- ja välähdyskorjaus' },
  { v: 632, teksti: 'Pöllö väljemmäksi; vuosisäägraafi elää; vuosiennuste-linkki' },
  { v: 631, teksti: 'Raja jää vahvempana; mikki rehellinen; iPad-lehti leveäksi' },
  { v: 630, teksti: 'Sanan, Adenin, Salalahin ja Mosulin kaupunkilehdet' },
  { v: 629, teksti: 'Ääriviiva paisuu piirtyessään; iPadin tausta kuuluviin' },
  { v: 628, teksti: 'Rajan välähdys hitaammin, nopan tärähdys pysähtyessä' },
  { v: 627, teksti: 'Pöllön mikki heti käyttöön; lähderivi kertoo oman tekstin' },
  { v: 626, teksti: 'Avauslennon luenta aiemmin ja kuulutus kuuluviin' },
  { v: 625, teksti: 'Isfahanin kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 624, teksti: 'Sanelun uusinta esiavaa mikrofonin; virherivi diagnosoi' },
  { v: 623, teksti: 'Sanelun ajaksi äänet taukoon: mikrofoni vapautuu iOS:lla' },
  { v: 622, teksti: 'Teheranin kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 621, teksti: 'iOS-kuoreen haptiikka, iCloud-synkka, widget ja Game Center' },
  { v: 620, teksti: 'Sanelun mikrofoni vapautuu aina; työhuoneen taulut' },
  { v: 619, teksti: 'Lehden mitta varmistetaan avattaessa; kaiutin jälkikäteen' },
  { v: 618, teksti: 'Lukija: kartan esittely luetaan, päiväys ja uutisnimiö ei' },
  { v: 617, teksti: 'Ei ohjetekstiä kartalle, pöllön vihje, maan raja piirtyy' },
  { v: 616, teksti: 'Etusivun taustaääni elpyy iPadilla; pöllölinkit siistiksi' },
  { v: 615, teksti: 'Tabrizin kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 614, teksti: 'Pöllön äänet, striimiluenta ja linkit; lukijaan ohitukset' },
  { v: 613, teksti: 'Pöllö isompana ja vakaana, sanelunappi, valikkorivit' },
  { v: 612, teksti: 'Riadin kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 611, teksti: 'Päivityksen jälkeen popup kahden version muutoksista' },
  { v: 610, teksti: 'Kartan tökkiminen korjattu: tarkkuusvahti odottaa lepoa' },
  { v: 609, teksti: 'Pöllöön suoratoisto, pöllölinkit, kuvapopup ja sanelutila' },
  { v: 608, teksti: 'Luxorin kaupunkilehti, kohdekartta ja saatiedot' },
  { v: 607, teksti: 'Kartan tarkkuus, kapeat alanapit, latausruutu ensipiirtoon' },
  { v: 606, teksti: 'Saatiedot viidelle Lahi-idan kaupungille' },
  { v: 605, teksti: 'Linkit vain tekstissä, valikko viimeistelty, edistymämittari' },
  { v: 604, teksti: 'Damaskoksen kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 603, teksti: 'Aleppon kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 602, teksti: 'Valikon kuvakerivi, pieni versionumero, kehittäjämerkintä' },
  { v: 601, teksti: 'Pöllön ehdotuksia kaksi kerrallaan, ei hokemia' },
  { v: 600, teksti: 'Ankaran kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 599, teksti: 'Izmirin kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 598, teksti: 'Bagdadin kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 597, teksti: 'Masqatin kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 596, teksti: 'Pöllö tietää maan oikein, oikaisee virheet; chat siistiksi' },
  { v: 595, teksti: 'Pöllöön kaiutin, osuvat linkit, jatkot; lehti elpyy' },
  { v: 594, teksti: 'Kuwaitin kaupunkilehti ja kuusi nahtavyysjuttua' },
  { v: 593, teksti: 'Kaiutinluenta sivuille, valikkosiirrot ja iPhonen alareuna' },
  { v: 592, teksti: 'Nikosian kaupunkilehti ja mittakaavajanan tarkistin' },
  { v: 591, teksti: 'Viisas Pöllö hereille: workerin osoite peliin' },
  { v: 590, teksti: 'Kolme matkanappia siististi, pöllön paneeli vaaleaksi' },
  { v: 589, teksti: 'Matkatapa kolmena nappina, pöllön chattiin matala alarivi' },
  { v: 588, teksti: 'Viisas Pöllö: apuri, sanelu, tietohaku, uusi alanappirivi' },
  { v: 587, teksti: 'Dohan kaupunkilehti, kohdekartta ja kuusi nähtävyysjuttua' },
  { v: 586, teksti: 'Auditin korjaukset: minitehtävät, toistot, Dubain jutut' },
  { v: 585, teksti: 'Majakkavälähdys, hitaammat reitit, lennon uusi ajoitus' },
  { v: 584, teksti: 'Sykkivät pisteet, pysyvä jälki, neljä laivaa, lennon teksti' },
  { v: 583, teksti: 'Reittianimaatio Safari-varmaksi, etusivun ääni kuuluviin' },
  { v: 582, teksti: 'Reittianimaatio näkyväksi ja työpöydän ääni käyntiin' },
  { v: 581, teksti: 'Etusivun reittianimaatio ja laatikoton lentonäkymä' },
  { v: 580, teksti: 'Aasian toinen lehtierä: viisi maata lisää, 100 nostoa' },
  { v: 579, teksti: 'Lähi-idän seitsikko uuteen malliin ja Korean K-pop-sivu' },
  { v: 578, teksti: 'Aasian ensimmäiset maalehdet: viisi maata, 100 nostoa' },
  { v: 577, teksti: 'Vanhat saapumismerkinnät luentoineen tilapäisesti takaisin' },
  { v: 576, teksti: 'Seitsemän aarretta — yksi per manner — ja mannerlento' },
  { v: 575, teksti: 'Uusitut tekstit merkitään ja nousevat sivun kärkeen' },
  { v: 574, teksti: 'Kyproksen lehteen viisi aihesivua ja 20 nostoa' },
  { v: 573, teksti: 'Kulkija-johdonmukaisuuspassi: viisi korjausta' },
  { v: 572, teksti: 'Riadin kohtaaminen viittaa oikeaan kysymykseen' },
  { v: 571, teksti: 'Sonnetin 15 löydöstä korjattu — Eurooppa puhdas' },
  { v: 570, teksti: 'Jemenin lehteen historia-, rakennus-, luonto- ja ruokasivut' },
  { v: 569, teksti: 'Euro-hionnan erä 3: EU-lauta kokonaan budjettiin' },
  { v: 568, teksti: 'Euro-hionnan erä 2: 19 kohdetta budjettiin + tagit' },
  { v: 567, teksti: 'Euroopan tekstit -sivu tageineen työhuoneeseen' },
  { v: 566, teksti: 'Euro-hionnan erä 1: 15 pisintä kohdetta pituusbudjettiin' },
  { v: 565, teksti: 'Ateenan kaari tiiviiksi ja lupaus konkreettiseksi' },
  { v: 564, teksti: 'Syyrian lehteen historia-, käsityö- ja ruokasivut' },
  { v: 563, teksti: 'Aarnin luettelon i-seloste ja suurennuslasin syke' },
  { v: 562, teksti: 'Irakin lehteen rakennus- ja suosivut' },
  { v: 561, teksti: 'Irakin lehteen muinaisuus- ja ruokasivut' },
  { v: 560, teksti: 'Iranin lehteen ruoka- ja käsityösivut' },
  { v: 559, teksti: 'Kolme kysymystäsmennystä Sonnetin varmistuskierroksesta' },
  { v: 558, teksti: 'Visaspoilerit pois Euroopasta: 25 kysymystä uusiksi' },
  { v: 557, teksti: 'Yhdeksän saapumista uusiksi: Euroopan rimakierros valmis' },
  { v: 556, teksti: 'Kahdeksan saapumista uusiksi: mittaajan kommellukset (erä 3)' },
  { v: 555, teksti: 'Vuorikohteiden kuvagalleriat valmiit: 52/52, 324 kuvaa' },
  { v: 554, teksti: 'ME: Isfahan-säännön korjauserä työhuoneeseen' },
  { v: 553, teksti: 'Maastokohteille omat artikkelit, vinkkisivun viilaus' },
  { v: 552, teksti: 'Euroopan saapumiset uusiksi: kommellukset ja persoonat' },
  { v: 551, teksti: 'Vuorikohteille kuratoidut kuvagalleriat, erä 1 (21/52)' },
  { v: 550, teksti: 'Numeroina-sivulle yleisluonnehdinta ja käyrien rytmi' },
  { v: 549, teksti: 'Äänipolun kaskadikorjaus, suurennoksen nuolet, esikuuntelut' },
  { v: 548, teksti: 'Etusivun ääni takaisin: reitityskokeilu peruttu' },
  { v: 547, teksti: 'Nähtävyyksien selaus popupissa: nuolet, pyyhkäisy, laskuri' },
  { v: 546, teksti: 'ME:n neljä saapumista uusiksi, visaspoileri pois' },
  { v: 545, teksti: '23 luentaa uusille teksteille, ME-viimeistely, äänipolku' },
  { v: 544, teksti: 'Pääjoet pohjakartalle järvien tyylillä' },
  { v: 543, teksti: 'Maxin vaihtoehtokorjaukset, ME-kaanonkorjaukset ja sapluuna' },
  { v: 542, teksti: 'Maalehti: tyhjä etusivu pois, oikean maan tiedot, kirjanappi' },
  { v: 541, teksti: 'Varusteille omat kuvat paljastukseen ja laukkuun' },
  { v: 540, teksti: 'Kuusi matkakirjamerkintää uusiksi: huumoria ja jännitystä' },
  { v: 539, teksti: '13 viimeisen kuvaduplikaatin vaihto nähtävyysjutuissa' },
  { v: 538, teksti: 'Huudahdus ääneen, kuvat paperiin, kabiini kuuluviin' },
  { v: 537, teksti: 'Aarrelöydölle nuoren herran hihkaisu' },
  { v: 536, teksti: 'Kaariauditin tekstit peliin, uudet luennat odottavat' },
  { v: 535, teksti: 'Tarinan avainkohteet matkakirjan kuviin 11 kaupungissa' },
  { v: 534, teksti: 'Maapilleri lippuineen oikealle, lennon ääni varareitille' },
  { v: 533, teksti: 'Kohtaamiskuvat kortille: Ateena, Sofia ja kätkölöytö' },
  { v: 532, teksti: 'Matkustamoääni avauslentoon, maatiedot löydettäväksi' },
  { v: 531, teksti: 'Aarrekortti pysyy luennan ajan ja ruksi sulkee sen' },
  { v: 530, teksti: 'Maan nimi pilleriksi kartan kehykselle ja luennan feidaus' },
  { v: 529, teksti: 'Peli on yksi lauta: laudanvaihtoportit ja koelaudat pois' },
  { v: 528, teksti: 'Laatta joka kaupunkiin, maailmankartalle mantereiden aarteet' },
  { v: 527, teksti: 'Bahrainille helmien ja muinaisuuden aihesivut' },
  { v: 526, teksti: 'Bahrain Lähi-idän laudalle omana maanaan' },
  { v: 525, teksti: 'Äänivalikko palautettu: v524 pyyhkäisi v523:n muutoksen' },
  { v: 524, teksti: 'Unohdetuille aarteille omat kuvat seitsemälle laudalle' },
  { v: 523, teksti: 'Alun hionta: aulafeidi, äänivalikko 3 tilaan, ohjerivi' },
  { v: 522, teksti: 'Neljä kiellettyä lisenssiä vaihdettu sallittuihin kuviin' },
  { v: 521, teksti: 'Intro v3, lähtöaulan ambienssi, pehmeämpi moottori ja zoomit' },
  { v: 520, teksti: 'Saudi-Arabian sivujen faktat ja kuvatekstit korjattu' },
  { v: 519, teksti: 'Alun viilaus: suora zoom, äänet ja kiikari pois, intro v2' },
  { v: 518, teksti: 'Aarteiden pikkuikonit uusiksi kuviksi, jalokivet pois' },
  { v: 517, teksti: 'Esc ja nuolet yhtenäisiksi kaikissa suurennospopupeissa' },
  { v: 516, teksti: 'Avausteksti ja lennon repliikki uusiksi, luennat v3-tagein' },
  { v: 515, teksti: 'Saudi-Arabialle kallioiden, vuorten ja meren sivut' },
  { v: 514, teksti: 'Puuttuvat kuvien tekijämerkinnät täydennetty' },
  { v: 513, teksti: 'Kuvakatselimen näppäimet, lennon pehmeä lähtö ja äänifadet' },
  { v: 512, teksti: 'Kohderyhmä täsmennetty: 13+ seikkailupeli, ei lastenpeli' },
  { v: 511, teksti: 'Kuwait sai lintujen ja aavikon aihesivut' },
  { v: 510, teksti: 'Tallennetun pelin palautus korjattu: Tutki toimii taas' },
  { v: 509, teksti: 'Kohtaamiselle aarre, uusintayritys ja Aloita peli -nappi' },
  { v: 508, teksti: 'Nähtävyysjutut Vilnaan, Osloon, Kööpenhaminaan' },
  { v: 507, teksti: 'Egyptille eläinten ja käsitöiden aihesivut' },
  { v: 506, teksti: 'Kohtaaminen ensin joka kaupungissa, lehti aina luettavissa' },
  { v: 505, teksti: 'Popupille rako alas, täysikoon kuviin lehden selaus' },
  { v: 504, teksti: 'Nähtävyysjutut Tromssaan, Dubrovnikiin, Riikaan' },
  { v: 503, teksti: 'Valokuvapulma: pylväspulman vaihtoehdot oikeina kuvina' },
  { v: 502, teksti: 'Nähtävyysjutut Kiovaan, Pietariin, Moskovaan, Odessaan' },
  { v: 501, teksti: 'Oman ja Qatar saivat aihesivunsa' },
  { v: 500, teksti: 'Kohtaaminen ensitehtäväksi, nähtävyyksiin valikko' },
  { v: 499, teksti: 'Emiraateille kolmas sivu ja Jordanialle kaksi' },
  { v: 498, teksti: 'Emiraatit sai kaksi aihesivua: Aavikko ja Keidas' },
  { v: 497, teksti: 'Loput kuvaduplikaatit purettu, kaksi hyväksyttiin' },
  { v: 496, teksti: 'Kahdeksan kuvaduplikaattia purettu Afrikasta ja Siinailta' },
  { v: 495, teksti: 'Nähtävyysjutut Sofiaan, Bukarestiin, Sarajevoon' },
  { v: 494, teksti: 'Kaksitoista valokuvakysymystä sai tunnistettavan kuvan' },
  { v: 493, teksti: 'Tallinnan ja Riian muurit kartalle, kujabugi kiinni' },
  { v: 492, teksti: 'Bulgarian ja Kroatian menovinkkeihin kuvat' },
  { v: 491, teksti: 'Venäjän, Ukrainan ja Romanian menovinkkeihin kuvat' },
  { v: 490, teksti: 'Saksan, Ranskan ja Turkin menovinkkeihin kuvat' },
  { v: 489, teksti: 'Menovinkkikuvat viidelle maalle, kolme duplikaattia pois' },
  { v: 488, teksti: 'Nähtävyysjutut Roomaan, Krakovaan, Varsovaan, Tallinnaan' },
  { v: 487, teksti: 'Emiraattien menovinkkeihin kuvat' },
  { v: 486, teksti: 'Suomen menovinkkeihin kuvat, kahdeksan riviä' },
  { v: 485, teksti: 'Oslo ja Kööpenhamina saivat kohdekartat' },
  { v: 484, teksti: 'Dubrovnik, Riika ja Vilna saivat kohdekartat' },
  { v: 483, teksti: 'Viisi kulttuurivisaa osoitti kadonneeseen juttuun' },
  { v: 482, teksti: 'Tromssa sai kohdekartan: salmi, silta ja kaksi rantaa' },
  { v: 481, teksti: 'Viisi viimeistä Euroopan kaupunkia sai lehtensä' },
  { v: 480, teksti: 'Kaupunkikarttojen vedet: saaret ja suihkulähteet' },
  { v: 479, teksti: 'Engel sai oman jutun — nimi Helsingin teksteissä on linkki' },
  { v: 478, teksti: 'Pysähdyksessä yksi tehtävä: pulma korvaa kohtaamisvisan' },
  { v: 477, teksti: 'Nähtävyysjutut Lissaboniin, Barcelonaan, Granadaan' },
  { v: 476, teksti: 'Kohdekarttoihin mittakaavajana' },
  { v: 475, teksti: 'Kuvakaruselli, lehteen vieritysvara, wikihännät pois' },
  { v: 474, teksti: 'Maakyltti nousi kaupunkien päälle, ankkurit mitattiin' },
  { v: 473, teksti: 'Kreeta, Sisilia ja Alpit saivat omat lehtensä' },
  { v: 472, teksti: 'Pylväspulman nimet vuororiveille, ei enää päällekkäin' },
  { v: 471, teksti: 'Ateenan nähtävyysjuttuihin lisää kuvia' },
  { v: 470, teksti: 'Lähi-idän laudalle maatiedot ja menovinkit' },
  { v: 469, teksti: 'Kolmen lehden vanhat jutut pois kahdentumasta' },
  { v: 468, teksti: 'Islanti ja Lappi saivat omat lehtensä' },
  { v: 468, teksti: 'Nähtävyysjutut Istanbuliin, Marseilleen, Edinburghiin' },
  { v: 467, teksti: 'Viisi maalehden juttua vaihtoon päällekkäisyyden takia' },
  { v: 467, teksti: 'Dubain lehteen vanhan kaupungin kohdekartta' },
  { v: 466, teksti: 'Tromssa sai oman lehtensä' },
  { v: 465, teksti: 'Dubai sai oman lehtensä' },
  { v: 464, teksti: 'Joka maalehdessä on nyt omia aihesivuja' },
  { v: 463, teksti: 'Sarajevon merkintä korjattu: kaivon tarina, ei kaivo' },
  { v: 462, teksti: 'Maastotekstien mallitiedoston kommentti oikeaksi' },
  { v: 461, teksti: 'Tanskalle ja Islannille omat aihesivut' },
  { v: 460, teksti: 'Tarinakaari pelissä: kohtaamiset ja vihjeet Euroopassa' },
  { v: 459, teksti: 'Aarre nousee mustasta — kortti ja kuvat uusiksi' },
  { v: 458, teksti: 'Irakin lehden lue lisää -linkki Eufratiin' },
  { v: 457, teksti: 'Maakartat Irakille ja Iranille' },
  { v: 456, teksti: 'Sveitsille ja Norjalle omat aihesivut' },
  { v: 455, teksti: 'Aarrekuvat piirretty yhtenäiseen satukirjatyyliin' },
  { v: 454, teksti: 'Minitehtävä joka maalehden aihesivulle' },
  { v: 453, teksti: 'Maakartat Saudi-Arabialle, Jemenille, Kyprokselle, Syyrialle' },
  { v: 452, teksti: 'Nuori herra huudahtaa kun aarre paljastuu' },
  { v: 451, teksti: 'Aarteen paljastus näyttää nyt oikean valokuvan' },
  { v: 450, teksti: 'Maakartat Kuwaitille, Qatarille, Emiraateille, Omanille' },
  { v: 449, teksti: 'Tšadjärvi ja Madeira saivat omat kuvansa' },
  { v: 448, teksti: 'Britannian musiikki kahdelle sivulle, kuvatoistot pois' },
  { v: 447, teksti: 'Joka mantereella nyt omat aarteet jalokivien tilalla' },
  { v: 446, teksti: 'Helsingin visa kysyy nyt Linnanmäen jarrumestarista' },
  { v: 445, teksti: 'Vaihe B valmis: viimeiset neljä kaupunkia' },
  { v: 444, teksti: 'Lähi-idän maiden rajat valmiina lautaa varten' },
  { v: 443, teksti: 'Suomen lehti kuntoon: Sävel-sivu ja omat menovinkit' },
  { v: 442, teksti: 'Lontoon nähtävyyskuvia paremmiksi: leijona, silmä, silta' },
  { v: 441, teksti: 'Lehdet ja popupit aukeavat aina alusta' },
  { v: 440, teksti: 'Kaksikymmentäkolme sivua siirtyi maalehtiin' },
  { v: 439, teksti: 'Suomenlinna-kainalo kiinni oikeaan alanurkkaan' },
  { v: 438, teksti: 'Isot joet piirtyvät vetenä: Neva, Dnepr, Tonava' },
  { v: 437, teksti: 'Helsingin nähtävyysjuttuihin paremmat kuvat' },
  { v: 436, teksti: 'Nähtävyysjutut Ateenaan, Amsterdamiin, Dubliniin' },
  { v: 435, teksti: 'Helsingin arkisivu siirtyi Suomen maalehteen' },
  { v: 435, teksti: 'Turkki, Irlanti, Portugali ja Unkari saivat maalehden' },
  { v: 434, teksti: 'Lehden mediarivillä nyt vain paikallisradio' },
  { v: 433, teksti: 'Kohdekartat Kiovaan, Pietariin, Moskovaan, Odessaan' },
  { v: 433, teksti: 'Kaikilla 31 kaupunkilehdellä on nyt kohdekartta' },
  { v: 432, teksti: 'Kohdekartat Sofiaan, Bukarestiin ja Sarajevoon' },
  { v: 431, teksti: 'Helsingille nähtävyysjutut, Suomenlinna mukana' },
  { v: 430, teksti: 'Kohdekartat Roomaan, Krakovaan, Varsovaan, Tallinnaan' },
  { v: 428, teksti: 'Kohdekartat Lissaboniin, Barcelonaan ja Granadaan' },
  { v: 427, teksti: 'Kohdekartat Istanbuliin, Marseilleen, Edinburghiin' },
  { v: 427, teksti: 'Istanbulin kartalla näkyy kaksi maanosaa' },
  { v: 426, teksti: 'Nähtävyysjutut Prahaan, Wieniin, Budapestiin, Pariisiin' },
  { v: 425, teksti: 'Kolme uutta isoisän pulmaa: geysir, vuorovesi, tuulikukko' },
  { v: 424, teksti: 'Helsingille kohdekartta ja Suomenlinna kainaloon' },
  { v: 424, teksti: 'Kaukokohteet takaisin kartoille pikkukarttana' },
  { v: 424, teksti: 'Meri piirtyy vetenä eikä pelkkänä rantaviivana' },
  { v: 423, teksti: 'Poistu-nappi himmeämmäksi, suuntanapit keskitetty' },
  { v: 422, teksti: 'Radio kartan ylle, liitelinkki pois päiväyksen päältä' },
  { v: 421, teksti: 'Kohdekartta Ateenaan, Amsterdamiin ja Dubliniin' },
  { v: 420, teksti: 'Valokuvakysymyksen kuvat käyty läpi yksi kerrallaan' },
  { v: 419, teksti: 'Neljä kaupunkia yhden kertojan malliin äänineen' },
  { v: 419, teksti: 'Etsi kätkö joka kaupunkisivun alareunassa' },
  { v: 419, teksti: 'Liitelinkki päiväysriville, tuore versionumero isompana' },
  { v: 418, teksti: 'Kohdekartta Prahaan, Wieniin, Budapestiin ja Pariisiin' },
  { v: 417, teksti: 'Valokuvakysymys näyttää taas paikkoja, ei henkilöitä' },
  { v: 416, teksti: 'Lue maa-liite -nappi kaupunkilehden loppuun' },
  { v: 415, teksti: 'Kätkön ja kohtaamisen pääsee heti lehden etusivulta' },
  { v: 414, teksti: 'Tapaa-nappi täysleveänä myös lehden viimeisellä sivulla' },
  { v: 413, teksti: 'Napautuskaista pois: väkänen vierittää sivun loppuun' },
  { v: 413, teksti: 'Etsi kätkö omalle riville koko leveänä ja matalana' },
  { v: 412, teksti: 'Maan nimikilpi aina kaupunkinimien kokoinen' },
  { v: 411, teksti: 'Tšekille, Itävallalle ja kolmelle muulle maalle aihesivut' },
  { v: 411, teksti: 'Toisen maan lehti ei enää luule tehtävää ratkaistuksi' },
  { v: 410, teksti: 'Kaksitoista uutta kaupunkilehteä Roomasta Odessaan' },
  { v: 409, teksti: 'Kymmenen lehden faktat ja kuvatekstit tarkistettu' },
  { v: 408, teksti: 'Isoisä puhuu omalla äänellään: pilotti kahdessa kaupungissa' },
  { v: 408, teksti: 'Edinburgh ja Pietari uuteen malliin äänineen' },
  { v: 407, teksti: 'Kymmenen uutta kaupunkilehteä Ateenasta Budapestiin' },
  { v: 406, teksti: 'Maan nimikilpi kutistuu kaukaa katsottuna maan mukana' },
  { v: 405, teksti: 'Lehden vieritys ei enää pompahda takaisin pohjaan' },
  { v: 404, teksti: 'Minitehtävä joka kaupunkilehden aihesivulle' },
  { v: 403, teksti: 'Maan nimi ja i yhtenä selkeänä nappina kartalla' },
  { v: 403, teksti: 'Lehden maaosiolinkki pois kameraloven alta' },
  { v: 402, teksti: 'Työhuone hakee aina tuoreimman sisällön verkosta' },
  { v: 401, teksti: 'Guernica-jutun vuosiluku ja Britannian-kierros oikein' },
  { v: 401, teksti: 'Minitehtävä kertoo nyt sivun, ei koko lehden, ratkaistuksi' },
  { v: 400, teksti: 'Visat palkitsevat taas puntina — yksi valuutta' },
  { v: 399, teksti: 'Lehtien visoista tietopisteitä rahan sijaan' },
  { v: 398, teksti: 'Pariisille oma lehti: kukko, kellotorni ja patonki' },
  { v: 397, teksti: 'Nähtävyyskortti ulottuu puhelimella alareunaan asti' },
  { v: 396, teksti: 'Tukholmalle Kadut ja sulut sekä Eläimet kaupungissa' },
  { v: 395, teksti: 'Euroopan viimeiset kuusi maakarttaa, Venäjä mukaan' },
  { v: 395, teksti: 'Balkanin ja idän introt lukevat nyt korkokarttaa' },
  { v: 394, teksti: 'Berliinille Tornit ja torit sekä Arki ja kadut' },
  { v: 394, teksti: 'Venetsialle Kaupunki veden varassa ja Käsityö' },
  { v: 394, teksti: 'Maalehdestä pois kaupunkilehden saapumislause' },
  { v: 393, teksti: 'Nähtävyyskortti mahtuu ruutuun, pitkä juttu rullaa sisällä' },
  { v: 392, teksti: 'Lehden vieritys tasaiseksi tarttuvien rivien kohdalla' },
  { v: 391, teksti: 'Maakartat Islannille, Irlannille ja neljälle muulle' },
  { v: 391, teksti: 'Kuuden maan intro lukee nyt korkokarttaa' },
  { v: 390, teksti: 'Maan nimen perässä i: lehti auki suoraan kartalta' },
  { v: 390, teksti: 'Maalehden sisällys alareunan pop-upiksi, oma sivu pois' },
  { v: 389, teksti: 'Madridille urheilusivu ja Kadut ja talot' },
  { v: 388, teksti: 'Versiokulmassa pelkkä numero, ei kehittäjä-tekstiä' },
  { v: 387, teksti: 'Kartta aukeaa pelaajan kohdalle, kehittäjänumero isommalla' },
  { v: 386, teksti: 'Kaupunkilehdestä pois turha sisällysvalikko' },
  { v: 385, teksti: 'Ranskan menovinkit viidestä neljääntoista' },
  { v: 384, teksti: 'Wienille oma lehti: jättiratas, hevoset ja kahvila' },
  { v: 383, teksti: 'Menovinkit Bulgarialle, Kroatialle ja Bosnialle' },
  { v: 383, teksti: 'Saksan menovinkit takaisin kahteenkymmeneen' },
  { v: 382, teksti: 'Maan lehteen pääsee nyt kartalta ja sisällysvalikosta' },
  { v: 381, teksti: 'Lontoon nähtävyysjutut samaan tiiviiseen malliin' },
  { v: 380, teksti: 'Pohjolan ja Baltian maakartat: kuusi maata lisää' },
  { v: 379, teksti: 'Menovinkit Turkille, Venäjälle, Ukrainalle ja Romanialle' },
  { v: 378, teksti: 'Prahalle oma lehti: Orloj, Golem ja Smetanan joki' },
  { v: 377, teksti: 'Madridille ja Tukholmalle nähtävyysjutut kuvineen' },
  { v: 376, teksti: 'Kairolle ja Venetsialle nähtävyysjutut kuvineen' },
  { v: 375, teksti: 'Menovinkit Virolle, Latvialle, Liettualle ja Unkarille' },
  { v: 374, teksti: 'Kuusi uutta maakarttaa: Ranskasta Puolaan' },
  { v: 373, teksti: 'Saksan menovinkit malliksi: 21 kohdetta kuudessa ryhmässä' },
  { v: 372, teksti: 'Suurennos ikkunan eteen ja pop-up kiinni taustaa napauttaen' },
  { v: 371, teksti: 'Nähtävyysjutun avauskuva: vaaka isona, pysty pienempänä' },
  { v: 370, teksti: 'Lehden nimiö aina keskellä, osiolinkki omalle rivilleen' },
  { v: 369, teksti: 'Nähtävyyskortti keskelle ruutua kaikilla laitteilla' },
  { v: 368, teksti: 'Kaikkien maiden menovinkit samaan listamalliin' },
  { v: 367, teksti: 'Nähtävyysjutut lyhyemmiksi, pienemmät kuvat, pop-up korjattu' },
  { v: 366, teksti: 'Lehden nimi on nyt Unohdettu aarre' },
  { v: 366, teksti: 'Maalehden etusivulle sisällysluettelo kartan tilalle' },
  { v: 366, teksti: 'Sisällys myös alapalkin valikosta, aiheet nappien alle' },
  { v: 366, teksti: 'Saksalle Ruokaa ja tapakulttuuria, kuvat kauniimmiksi' },
  { v: 365, teksti: 'Siivous: orvot äänet pois, vanhat suunnitelmat arkistoon' },
  { v: 364, teksti: 'Selitepallot kartan sävyyn, linkit kevyemmin viivattu' },
  { v: 363, teksti: 'Menovinkit listaksi: enemmän linkkejä, pienemmät kuvat' },
  { v: 363, teksti: 'Poistu vasemmalle, Seuraava oikealle joka sivulla' },
  { v: 363, teksti: 'Tietovisa omaksi kortikseen: väljempi ja vaaleampi' },
  { v: 362, teksti: 'Kaupunkikartat vaaleiksi: kohteet nousevat esiin' },
  { v: 362, teksti: 'Kohteen nimi näkyy hiiren alla työpöydällä' },
  { v: 361, teksti: 'Menovinkit kahdeksalle uudelle maalle' },
  { v: 359, teksti: 'Venetsian laguuni näkyviin: kartta ei ole enää kuiva' },
  { v: 358, teksti: 'Berliinin nähtävyyksille omat jutut kuvineen' },
  { v: 357, teksti: 'Radio ja tv näkyvät nyt kummassakin lehdessä' },
  { v: 356, teksti: 'Työhuone uudeksi: 5 välilehteä, Testaa ja tilanne yhteen' },
  { v: 355, teksti: 'Ruotsille korkokartta: Kiirunasta Malmöhön' },
  { v: 355, teksti: 'Tukholman kohdekartta, ja vesi näkyy vihdoin' },
  { v: 354, teksti: 'Espanjalle korkokartta: Meseta ja kuusi kaupunkia' },
  { v: 354, teksti: 'Madridin kohdekartta: linnalta Retiron portille' },
  { v: 353, teksti: 'Menovinkit viidelle maalle: kokoelmat verkossa' },
  { v: 352, teksti: 'Työhuoneeseen Kehitys-välilehti: kaari, näytteet, Eurooppa' },
  { v: 351, teksti: 'Italialle oma korkokartta ja kuusi kaupunkia' },
  { v: 351, teksti: 'Venetsian kohdekartta: Canal Grande ja kuusi kohdetta' },
  { v: 350, teksti: 'Kaupunki- ja maalehti erikseen, kohtaaminen viimeisenä' },
  { v: 350, teksti: 'Maiden tiedot -varuste: maan lehti suoraan kartalta' },
  { v: 350, teksti: 'Menovinkit: parhaat kokoelmat nettimatkaajalle' },
  { v: 350, teksti: 'Lontoon nähtävyyksille omat jutut kuvineen' },
  { v: 349, teksti: 'Lontoon aiheet Britannialle, kansi jää kaupungille' },
  { v: 349, teksti: 'Musiikkilinkki vie nyt suoraan kappaleeseen' },
  { v: 349, teksti: 'Kaupunkikartta miedommaksi: tausta, ei juliste' },
  { v: 348, teksti: 'Egyptille Musiikki-sivu: Umm Kulthum ja ud' },
  { v: 348, teksti: 'Egyptille Rakennukset: miten pyramidi tehtiin' },
  { v: 348, teksti: 'Egypti-osio ja Kairon katukartta lehteen' },
  { v: 347, teksti: 'Britannialle kuusi aihesivua: historiasta urheiluun' },
  { v: 347, teksti: 'Iso-Britannia-osio: korkokartta ja neljä maata' },
  { v: 347, teksti: 'Lontoon katukartta kuudella kohteella' },
  { v: 346, teksti: 'Aarrevihjeet matkalle: kuiskaus kaupunkien välissä' },
  { v: 345, teksti: 'Koko Eurooppa dekkarina: 41 kaupunkia äänineen' },
  { v: 344, teksti: 'Kuollut taustasoitin siivotaan muistista' },
  { v: 343, teksti: 'Dekkari laajeni: Kairo ja viisi muuta kaupunkia' },
  { v: 342, teksti: 'Taustaääni ei enää katoa kartalla hyppiessä' },
  { v: 341, teksti: 'Saksalle Valokuvaus-sivu: Anschützin haikarat' },
  { v: 341, teksti: 'Lontoo lyhyemmäksi, luennat tasaisemmiksi' },
  { v: 340, teksti: 'Tehosteäänet takaisin: kaikki 28 soivat taas' },
  { v: 339, teksti: 'Kartta terävöityy zoomauksen jälkeen tuplasti nopeammin' },
  { v: 339, teksti: 'Puskurikuvat joutohetkiin: vieritys ei tökkää' },
  { v: 338, teksti: 'Päivän kuva omasta listasta: valokuvan klassikot' },
  { v: 338, teksti: 'Avauslennon repliikki lyhyeksi, uusi luenta' },
  { v: 337, teksti: 'Dekkarimerkinnät napakoiksi: suoraan tarinaan' },
  { v: 336, teksti: 'Mantereelle siirrytään heti, ilman zoomausta' },
  { v: 336, teksti: 'Sumea kartta terävöityy, kun peli palaa esiin' },
  { v: 335, teksti: 'Lontoon kohtaaminen puhuu: Ned ja pelaaja' },
  { v: 335, teksti: 'Kaupunkikartta etusivulle pääkartan sävyissä' },
  { v: 334, teksti: 'Dekkariluennat: viisi kaupunkia uusin äänin' },
  { v: 333, teksti: 'Kohtaamisten tekstit tiiviimmiksi, ääni säilyy' },
  { v: 332, teksti: 'Matkakirja dekkariksi: viisi kaupunkia uusittu' },
  { v: 332, teksti: 'Isoisä sai nimen ja takaa-ajajan — dekkari alkaa' },
  { v: 331, teksti: 'Lehteen sarjakuva: Max ja Morits (Saksa)' },
  { v: 331, teksti: 'Maasivulle Päivän kuva maailmalta — vaihtuu itse' },
  { v: 330, teksti: 'Ääneen lukija pois: ääni ei ollut tarpeeksi hyvä' },
  { v: 329, teksti: 'Kohdekartta isoksi: numeroympyrät ja selitteet' },
  { v: 328, teksti: 'Berliinin kartta uusiksi: oma katukartta OSM:sta' },
  { v: 328, teksti: 'Tv: livet pois, tilalle tagesschaun tallenteet' },
  { v: 328, teksti: 'Saksalle uusi sivu: Sadut ja tarinat' },
  { v: 327, teksti: 'Berliinin sivulle kohdekartta: napauta kohdetta' },
  { v: 327, teksti: 'Saksa-sivulle Loreley-kuva, teksti kappaleiksi' },
  { v: 327, teksti: 'Maan sivuille lippu otsikkoon nimen sijaan' },
  { v: 327, teksti: 'Historian nostoihin vuosileima otsikkoriville' },
  { v: 326, teksti: 'Ääneen lukija: kaiutin lukee Tutki-sivun' },
  { v: 326, teksti: 'Lukunappi myös Lue lisää -artikkeleihin' },
  { v: 326, teksti: 'Lukija valitsee laitteen parhaan suomiäänen' },
  { v: 325, teksti: 'Musiikkisivut soivat: Bach, Beethoven, Vivaldi…' },
  { v: 325, teksti: 'Avainviulu ja Va, pensiero vapaina näytteinä' },
  { v: 325, teksti: 'ABBA ja kumppanit Applen 30 s esikuunteluna' },
  { v: 324, teksti: 'Tukholmaan uusi taustaääni: Saltsjön ranta' },
  { v: 323, teksti: 'Saksa-osiolle aloitussivu: iso korkokartta' },
  { v: 323, teksti: 'Kartalla kaupungit, tunnusluvut ja esittely' },
  { v: 323, teksti: 'Etusivun yläkulmaan Saksa-osio-linkki' },
  { v: 323, teksti: 'Lehden nimeksi Matkasanomat' },
  { v: 322, teksti: 'Työhuoneeseen Todo Samille -välilehti' },
  { v: 321, teksti: 'Vertailulinssi siirtyi suoraan kartalle' },
  { v: 321, teksti: 'Valitse kartalta 3 maata Suomen rinnalle' },
  { v: 321, teksti: 'Vertaa-nappi avaa maat rinnakkain' },
  { v: 320, teksti: 'Ruotsille Musiikki-sivu: ABBA, Lind, avainviulu' },
  { v: 320, teksti: 'Tukholman kanteen Vasa-laivan tarina' },
  { v: 319, teksti: 'Matkakirjan lopusta turha nuoli pois' },
  { v: 318, teksti: 'Uutinen aukeaa pikkulehtenä: nimiö ja päiväys' },
  { v: 318, teksti: 'Teksti kiertää uutiskuvaa, kortti leveämpi' },
  { v: 318, teksti: 'Käännä suomentaa myös otsikon, Palauta palauttaa' },
  { v: 317, teksti: 'Matkakirja aukeaa kartalla kokonaan, ei osittain' },
  { v: 317, teksti: 'Kartan napautus kutistaa sen yhdelle riville' },
  { v: 316, teksti: 'Berliini sai oman lehden: kansi ja Saksa-osasto' },
  { v: 316, teksti: 'Gaertnerin Berliini-teokset galleriana' },
  { v: 316, teksti: 'Saksan uutiset, tagesschau24 ja posetiivari Otto' },
  { v: 315, teksti: 'Tukholma sai oman lehden: kansi ja Ruotsi' },
  { v: 315, teksti: 'Elias Martinin Tukholma-näkymät galleriana' },
  { v: 315, teksti: 'Ruotsin uutiset SVT:ltä, ABBA kannen nostona' },
  { v: 314, teksti: 'Maan sivun otsikossa maan nimi: Egyptin historia' },
  { v: 314, teksti: 'Tilastosivun otsikkona "Egypti numeroina"' },
  { v: 313, teksti: 'Uusi varuste: Vertailulinssi, kaksi maata rinnan' },
  { v: 312, teksti: 'Maa numeroina joka maalle — 228 maan käyrät' },
  { v: 311, teksti: 'Lehteen uusi sivu: Maa numeroina käyrineen' },
  { v: 311, teksti: 'Suomi kulkee joka käyrässä vertailuviivana' },
  { v: 310, teksti: 'Maiden aikasarjat haettu: viisi pilottimaata' },
  { v: 309, teksti: 'Kolme Espanjan kuvaa puuttui peilistä — korjattu' },
  { v: 309, teksti: 'Rikkinäinen kuva yrittää uudelleen myös peilittä' },
  { v: 309, teksti: 'Kerran nähty kuva ei enää lähde verkkoon' },
  { v: 308, teksti: 'Artikkelien kuvat isoina: 330 px -> 1920 px' },
  { v: 308, teksti: 'Suurennos ei enää putoa takaisin pikkukuvaan' },
  { v: 307, teksti: 'Madrid sai oman lehden: kansi ja Espanja-osasto' },
  { v: 307, teksti: 'Goyan Madrid-teokset galleriana' },
  { v: 307, teksti: 'Espanjan uutiset, RTVE:n tv ja kirpputorikauppias' },
  { v: 307, teksti: 'Kuuntele-nappi ei enää valu puhelimen reunan yli' },
  { v: 306, teksti: 'Kuva yrittää uudelleen, jos lataus epäonnistui' },
  { v: 305, teksti: 'Lontoo sai oman lehden: kansi ja Britannia' },
  { v: 305, teksti: 'Canaletton Lontoo-teokset galleriana' },
  { v: 305, teksti: 'BBC:n uutiset, Sky News ja jokietsijä Ned' },
  { v: 305, teksti: 'iPhonen yläreuna sumeaksi, pystykuvat leveiksi' },
  { v: 304, teksti: 'Lue lisää -artikkeli sanomalehtipaperille' },
  { v: 304, teksti: 'Paksut katkoviivat pois: ohut viiva tilalle' },
  { v: 303, teksti: 'Kuvat palstan täyteen leveyteen lehdessä' },
  { v: 303, teksti: 'Lue lisää heti tekstin perään, tulos vihreällä' },
  { v: 302, teksti: 'Nuolet ja sivunumero yhdessä pillerissä' },
  { v: 302, teksti: 'Kuvateksti pysyy kuvan reunojen sisällä' },
  { v: 302, teksti: 'Visa näkyy heti, vaihtoehdot kevyemmin' },
  { v: 301, teksti: 'Kuvatekstit heti kuvan alle lehtijutuissa' },
  { v: 301, teksti: 'Pystykuva saa tekstin viereensä' },
  { v: 301, teksti: 'Sivunuolet pois laidoilta, navigointi alas' },
  { v: 301, teksti: 'Kairoon vuoden 1809 kartta ja tahtib-perinne' },
  { v: 300, teksti: 'Jutut kahdelle palstalle leveällä ruudulla' },
  { v: 300, teksti: 'Pääkirjoitus palstoihin, kuva aina jutun yllä' },
  { v: 299, teksti: 'Tutki-pohja sanomalehdeksi: vaalea paperi' },
  { v: 299, teksti: 'Suora reuna, arkki koko ruudun korkuinen' },
  { v: 298, teksti: 'Pystykuvat eivät enää veny leveiksi lehdessä' },
  { v: 298, teksti: 'Tutki kapeammaksi työpöydällä, sama kuin iPadilla' },
  { v: 297, teksti: 'Kairo sai oman lehden: kansi, Egypti-osasto' },
  { v: 297, teksti: 'Robertsin Kairo-litografiat galleriana' },
  { v: 297, teksti: 'Kätkölle vie kirjakauppias Faruk basaarista' },
  { v: 297, teksti: 'Egyptin uutiset, radio ja tv lehden sivulle' },
  { v: 296, teksti: 'Radion nauha reunaan asti, merkkivalo keskelle' },
  { v: 296, teksti: 'Vesistölinssi maastokartan päälle, joet sinisinä' },
  { v: 296, teksti: 'Topografian pohjoisreunaan omat värit' },
  { v: 295, teksti: 'Tv näyttää vain suoraa lähetystä, ei tallennetta' },
  { v: 295, teksti: 'Lehden sivut korjattu isolle iPadille' },
  { v: 294, teksti: 'Tv-lähetys aukeaa nyt myös iPadilla, rasti pois' },
  { v: 293, teksti: 'Napsahtelut pois: jäljelle noppa, lento ja laiva' },
  { v: 292, teksti: 'Valikkoon ilmaa, lähdelinkki pois' },
  { v: 291, teksti: 'Matkalaukun kahva pois: siistimpi ilman' },
  { v: 290, teksti: 'Valikosta suoraan varusteet, äänet ja komennot' },
  { v: 290, teksti: 'Matkakirja pysyy aina kartan yläreunassa' },
  { v: 289, teksti: 'Visa pois etusivulta kaupungin omalle sivulle' },
  { v: 289, teksti: 'Tapaa-nappi kultaiseksi, tv:ksi euronews italiano' },
  { v: 288, teksti: 'Popupit: kevyt sumennus tummennuksen sijaan' },
  { v: 288, teksti: 'Radio ja tv aina vierekkäin, tv ilman kehyksiä' },
  { v: 287, teksti: 'Laukun kahva roikkuu kartan päällä laukun alla' },
  { v: 286, teksti: 'Suomennos korvaa uutisen tekstin, nappi vaihtaa' },
  { v: 286, teksti: 'Sähkeisiin pikkukuvat, mediarivi uutisten alle' },
  { v: 286, teksti: 'Sky TG24: maan tv-kanavan suora lähetys popupiin' },
  { v: 285, teksti: 'Laukku aukeaa suoraan yläpalkista, Sulje pois' },
  { v: 285, teksti: 'Varusteiden kuvakkeet selvästi isommiksi' },
  { v: 284, teksti: 'Laukun katkoviiva vaihtui nahkaan, tausta ei tummene' },
  { v: 284, teksti: 'Aarnin luetteloon vain löytyneet, muut lukuna' },
  { v: 283, teksti: 'Uutiseen kuva, suomennokset otsikoiden alle' },
  { v: 283, teksti: 'Uutisen leipäteksti kirjan antiikvalla' },
  { v: 282, teksti: 'Matkalaukku: vihreä passi vaihtui Aarnin luetteloon' },
  { v: 282, teksti: 'Tavaroilla omat kuvakkeet, ei enää suurennuslaseja' },
  { v: 282, teksti: 'Laukku aukeaa pillerin alle, nahkareunat ja kahva' },
  { v: 281, teksti: 'Uutinen aukeaa kokonaisena, suomennos otsikon alla' },
  { v: 281, teksti: 'Uutiset kartan viereen, esittely pääkirjoitukseksi' },
  { v: 280, teksti: 'Radion pystysyy takaisin, vaakanaarmut pois' },
  { v: 279, teksti: 'Uutiset päällä: ANSA:n otsikot Italian lehdessä' },
  { v: 278, teksti: 'Lehden etusivu tiiviiksi: isot kuvat, maa ylemmäs' },
  { v: 278, teksti: 'Venetsian nostot omalle sivulleen etusivun jälkeen' },
  { v: 278, teksti: 'Suurennos selattavaksi: koko galleria isolla' },
  { v: 278, teksti: 'Työpöydän kapea tekstipalsta nostoissa korjattu' },
  { v: 277, teksti: 'Radiosta tyhjä puu pois oikeasta laidasta' },
  { v: 277, teksti: 'Kotelon pystyviirut pois: lakattu pinta on sileä' },
  { v: 276, teksti: 'Maaosastossa paikallisia uutisotsikoita (Italia)' },
  { v: 276, teksti: 'Uutinen aukeaa kortille, käännösnappi suomeksi' },
  { v: 275, teksti: 'Venetsiassa kätkölle vie gondolieeri Matteo' },
  { v: 275, teksti: 'Kohtaaminen: hahmo tervehtii, kysyy ja hyvästelee' },
  { v: 274, teksti: 'Tekijätietojen logo tummalle laatalle, pienempänä' },
  { v: 273, teksti: 'Lehden mastossa päivän sää, napautus avaa vuoden' },
  { v: 273, teksti: 'Vuosigraafi: keskilämpö ja sateet kuukausittain' },
  { v: 272, teksti: 'Logo avaa tekijätiedot: nimikilpi pois laukusta' },
  { v: 271, teksti: 'Venetsian Tutki-etusivu taittuu paikallislehdeksi' },
  { v: 271, teksti: 'Canaletton teoksia voi selata galleriana' },
  { v: 271, teksti: 'Lehdessä minitehtävä: vastaus löytyy sivulta' },
  { v: 270, teksti: 'Varusteiden kuvakkeet omiksi neliöikseen' },
  { v: 269, teksti: 'Merkkivalo keskeyttää lähetyksen ja jatkaa sitä' },
  { v: 269, teksti: 'Merkkivalo taas pyöreä, radio matalampi' },
  { v: 269, teksti: 'Taikalasit ovat nyt Varusteet, valikko puoleen' },
  { v: 268, teksti: 'Radio riisuttu: näyttö, asteikko ja merkkivalo' },
  { v: 268, teksti: 'Punainen valo mykistää ja palauttaa äänen' },
  { v: 267, teksti: 'VU-neula osuu kuultavaan: viive mitataan pois' },
  { v: 266, teksti: 'VU-neula seuraa nyt lähetystä myös iPadilla' },
  { v: 265, teksti: 'Tutki: Italian aiheet kaikkiin maan kaupunkeihin' },
  { v: 265, teksti: 'Venetsia sai kansisivun, maa sisäsivut' },
  { v: 265, teksti: 'VU-mittarin pitkä painallus näyttää diagnoosin' },
  { v: 264, teksti: 'Radion näyttö hehkuu meripihkaa, ei laskinvihreää' },
  { v: 264, teksti: 'VU palaa jäljitelmästä aitoon mittaukseen' },
  { v: 264, teksti: 'Neljä asemaa vaihdettu: mittari näkee lähetyksen' },
  { v: 263, teksti: 'Historia sai oman sivunsa kuten muutkin aiheet' },
  { v: 262, teksti: 'Ylärivin nimilogo on nyt piirretty kuva' },
  { v: 261, teksti: 'Radio pysyy yhdellä rivillä isolla ruudulla' },
  { v: 260, teksti: 'Osastonotsikon paksu yläviiva takaisin' },
  { v: 259, teksti: 'Uusi vesistölinssi: pelkät joet ja järvet' },
  { v: 259, teksti: 'Jokien nimet takaisin vesistölinssin kanssa' },
  { v: 259, teksti: 'Tutki-otsikon tausta ei enää näy tummana palkkina' },
  { v: 258, teksti: 'Tutki: osaston otsikko pysyy näkyvissä vierittäessä' },
  { v: 257, teksti: 'Isot järvet takaisin kartalle, vain joet pois' },
  { v: 257, teksti: 'Radio kiinni alareunaan ja hieman kapeammaksi' },
  { v: 257, teksti: 'VU-neula ei jää kuolleeksi soivan aseman päälle' },
  { v: 257, teksti: 'Tutki-tekstin koko tuli oikeasti voimaan' },
  { v: 256, teksti: 'Tutki: leipäteksti luettavalla kirjasimella' },
  { v: 256, teksti: 'Osastojen otsikot lehden tapaan viivojen väliin' },
  { v: 256, teksti: 'Kappalejako, lihavoitu aloitus ja anfangi' },
  { v: 256, teksti: 'Sivulle sitaattinosto kuin aikakauslehdessä' },
  { v: 255, teksti: 'Joet ja järvet pois kartalta: tulossa oma linssi' },
  { v: 255, teksti: 'Taikalasien kuvake: silmälasit, ei suurennuslasi' },
  { v: 254, teksti: 'Joen nimi vain kerran ja aina samassa kohdassa' },
  { v: 254, teksti: 'Merisyvyys pois: ei sinistä, kevyempi vieritys' },
  { v: 254, teksti: 'Joet vaimeammiksi, ei enää viileää välkettä' },
  { v: 254, teksti: 'Topografialinssin vedet samaan musteeseen' },
  { v: 253, teksti: 'Kartan vieritys taas sujuvaa: rae 11x halvempi' },
  { v: 253, teksti: 'Maastonimet kaupunkien nimien kokoisia' },
  { v: 253, teksti: 'Maastonimet vasta kun kaupunkien nimet näkyvät' },
  { v: 253, teksti: 'Logon rivit tasavälein, ei enää kuoppaa keskellä' },
  { v: 252, teksti: 'Vesi on nyt mustetta ja paperia, ei sinistä' },
  { v: 252, teksti: 'Matkakirjan palkki vain sanojensa levyinen' },
  { v: 252, teksti: 'Logon rivit täsmälleen yhtä leveät' },
  { v: 251, teksti: 'VU-mittari pitää aseman herkkyyden koko ajan' },
  { v: 251, teksti: 'Merisyvyys hillitymmäksi: ei enää vuoda rannan yli' },
  { v: 251, teksti: 'Matkakirjan palkki vain otsikkonsa levyinen' },
  { v: 251, teksti: 'Äänet ja taikalasit hampurilaisen alle' },
  { v: 250, teksti: 'Maa erottuu merestä selvästi omalla värillään' },
  { v: 250, teksti: 'Hampurilainen takaisin: säännöt ja uusi peli sen alle' },
  { v: 249, teksti: 'Kutistettuun matkakirjaan jää otsikko ja tausta' },
  { v: 249, teksti: 'VU-mittari palaa asemalle myös kaupunkia vaihtaessa' },
  { v: 249, teksti: 'Merenpohja rajataan piirrettyyn rantaviivaan' },
  { v: 248, teksti: 'Pelin nimi: Matkakirja ja unohdettu aarre' },
  { v: 248, teksti: 'Yläpalkissa nimilogo: viiva ja alanimi' },
  { v: 247, teksti: 'VU-mittari sai lähetykselle oman asteikkonsa' },
  { v: 247, teksti: 'Neula näyttää ohjelman tason, ei nupin asentoa' },
  { v: 246, teksti: 'Meren sinisyys ei enää vuoda maiden päälle' },
  { v: 246, teksti: 'VU-mittari liikkuu myös CORSittomilla asemilla' },
  { v: 246, teksti: 'Kanavanvaihdon häivytys 0,9 sekuntiin' },
  { v: 245, teksti: 'Paperin pinta näkyy nyt myös lähikuvassa' },
  { v: 245, teksti: 'Kanavanvaihdon häivytys selvästi pidempi' },
  { v: 244, teksti: 'VU-mittari sai lähetyksen myös hitaalla alulla' },
  { v: 244, teksti: 'Panaman kuvakortti ei enää kahdennu' },
  { v: 243, teksti: 'Matkakirja kutistuu riviksi karttaa vierittäessä' },
  { v: 243, teksti: 'Linssin selite kutistuu ja avautuu napauttamalla' },
  { v: 242, teksti: 'Ikkunan avaus ei enää korosta ensimmäistä nappia' },
  { v: 241, teksti: 'Jokien nimet pysyvät paikallaan vierittäessä' },
  { v: 241, teksti: 'Nimen koko seuraa zoomia' },
  { v: 241, teksti: 'Maastoon enemmän syvyyttä lähikuvassa' },
  { v: 241, teksti: 'Tutki: ylä- ja alareunasta pääsee päähän' },
  { v: 241, teksti: 'Pelin nimi mahtuu vihdoin iPhonen ruudulle' },
  { v: 240, teksti: 'Tutki on nyt taitettu lehti: pyyhkäise sivuja' },
  { v: 240, teksti: 'Kuvat isommiksi ja tekstin lomaan' },
  { v: 240, teksti: 'Korjattu: kuvat katosivat iPadilla kokonaan' },
  { v: 240, teksti: 'Suurennus aina suorassa ja täydessä koossa' },
  { v: 240, teksti: 'Tutki täyttää puhelimen ruudun reunasta reunaan' },
  { v: 240, teksti: 'Joet kapeammiksi, maastonimet isommiksi' },
  { v: 240, teksti: 'Matkalaukusta lähteet ja tekijätiedot' },
  { v: 239, teksti: 'Kartta lämpimämmäksi, korkeus punaruskeaan' },
  { v: 239, teksti: 'Viritysääni kuuluu taas myös äänet pois päältä' },
  { v: 239, teksti: 'VU-mittari seuraa lähetystä 98 asemalla' },
  { v: 239, teksti: 'Radiokanava kaikkiin 110 maahan' },
  { v: 239, teksti: 'Hiiren rulla zoomaa karttaa työpöydällä' },
  { v: 239, teksti: 'Zoomaus hitaammaksi, ei enää tökkimistä' },
  { v: 239, teksti: 'Topografialinssin yläreuna sai värinsä' },
  { v: 239, teksti: 'Ylärivin napit isommiksi puhelimessa' },
  { v: 238, teksti: 'New York ja Rio vievät nyt maailmankartalle' },
  { v: 238, teksti: 'Saapumisessa ei enää välähdä koko maailma' },
  { v: 238, teksti: 'Zoomaus alkaa kauempaa ja laskeutuu pehmeästi' },
  { v: 238, teksti: 'Pelin nimi pienemmäksi puhelimen ylärivillä' },
  { v: 237, teksti: 'Hampurilainen pois: säännöt ja uusi peli riville' },
  { v: 237, teksti: 'Päivitys ja kehittäjätila versionumeron takaa' },
  { v: 237, teksti: 'Radiotilassa vain kartta ja soitin' },
  { v: 237, teksti: 'Kanavalista hehkuu epätasaisesti, lasi syvenee' },
  { v: 237, teksti: 'Viritys häipyy sisään ja ulos ristikkäin' },
  { v: 237, teksti: 'Viritysnauha nykii kuin oikea rulla' },
  { v: 237, teksti: 'VU-mittari seuraa myös lähetystä' },
  { v: 237, teksti: 'Pelin nimi kahdelle riville puhelimessa' },
  { v: 236, teksti: 'Radion kytkimet kuluneiksi, valoläiskät pois' },
  { v: 235, teksti: 'Maastonimet vaakaan ja isommalla' },
  { v: 235, teksti: 'Versionumero ei enää tummu laatikoksi' },
  { v: 234, teksti: 'Saapumisessa zoomaus, kohdemanner näkyviin' },
  { v: 234, teksti: 'Lento kestää repliikin lukemisen ajan' },
  { v: 234, teksti: 'Pieni nuoli ohittaa lennon halutessa' },
  { v: 234, teksti: 'Loitonnus ei enää näytä samaa paikkaa kahdesti' },
  { v: 234, teksti: 'Tangeriin tarkka markkinakuva Grand Socolta' },
  { v: 233, teksti: 'Beringinsalmi ehjäksi: Tšukotkan kärki takaisin' },
  { v: 233, teksti: 'Radiossa soiva kaupunki näkyy punaisena' },
  { v: 232, teksti: 'Kartta jatkuu ehjänä laudan reunan yli' },
  { v: 232, teksti: 'Kartta tarkentuu zoomatessa eikä sumene' },
  { v: 232, teksti: 'Uusi kuvake: kultainen aarre kahden pallon välissä' },
  { v: 231, teksti: 'Pelin nimi on nyt Unohdettu aarre' },
  { v: 231, teksti: 'Avausteksti tiiviimmäksi, luenta 34 s → 23 s' },
  { v: 230, teksti: 'Siperia ja Alaska yhtyvät ehjänä rantana' },
  { v: 230, teksti: 'Radio näkyy matkalaukussa' },
  { v: 230, teksti: 'Versionumero pois matkakirjan päältä' },
  { v: 229, teksti: 'Aarteet ovat nyt unohdettuja aarteita' },
  { v: 229, teksti: 'Tarinaan Aarnin luettelo, pelin ajojahti' },
  { v: 228, teksti: 'Radion äänisäädin pois, kytkimille tilaa' },
  { v: 228, teksti: 'Viisi aitoa lyhytaaltoäänitystä viritykseen' },
  { v: 227, teksti: 'Radion asteikossa naapurikaupungit, klikattavina' },
  { v: 227, teksti: 'Kromatut vipukytkimet ja hehkuva merkkivalo' },
  { v: 227, teksti: 'Viritysääni kun radio hakee kanavaa' },
  { v: 227, teksti: 'Kyrilliset ja kiinalaiset merkit näytölle' },
  { v: 227, teksti: 'Vanhat vedokset seitsemään kaupunkiin lisää' },
  { v: 226, teksti: 'Aarteella on oma nimi jokaisella laudalla' },
  { v: 226, teksti: 'Maailmankartan aarrekuulutus ei väitä Meripihkahuonetta' },
  { v: 225, teksti: 'Avauslento esittelee pelin idean ääneen' },
  { v: 225, teksti: 'Lennot muistuttavat unohdetusta aarteesta' },
  { v: 224, teksti: 'Maailmanradio: kaupungit soivat kartalta' },
  { v: 224, teksti: 'Vanhan ajan radiosoitin ruudun alalaitaan' },
  { v: 224, teksti: 'Kehittäjätilaan kaikki toimivat aarteet' },
  { v: 223, teksti: 'Järvet, joet ja vuoristot nimetty kaunolla' },
  { v: 223, teksti: 'Vesi saa syvyyden ja värin lähelle zoomatessa' },
  { v: 223, teksti: 'Joet levenevät uomiksi kun karttaa katsoo läheltä' },
  { v: 223, teksti: 'Nimen perässä i avaa paikan tarinan' },
  { v: 222, teksti: 'Kuvat kaikkiin 248 kaupunkiin' },
  { v: 222, teksti: 'Uusi alue piirtyy viisi kertaa nopeammin' },
  { v: 222, teksti: 'Korjattu: joet eivät näkyneet kartalla lainkaan' },
  { v: 222, teksti: 'Järvet ja joet meren sävyyn, sininen pois' },
  { v: 221, teksti: 'Matkakirja valmis: 248 paikkaa, 248 luentaa' },
  { v: 221, teksti: 'Amerikat ja Oseania kirjoitettu ja luettu' },
  { v: 221, teksti: 'Kertoja eläytyy: huikeat paikat kuuluvat äänessä' },
  { v: 220, teksti: 'Tutki-aiheet valmiit monistettaviksi muualle' },
  { v: 220, teksti: 'Lontoon metro, Proms ja piirakka aiheisiin' },
  { v: 220, teksti: 'Aiheisiin Lue lisää -napit ja musiikkilinkit' },
  { v: 219, teksti: 'Loput 13 luentaa: koko Aasia on nyt luettu' },
  { v: 218, teksti: 'Korjattu: Tutki-ikkuna ei auennut monessa kaupungissa' },
  { v: 217, teksti: 'Vuoret, joet ja järvet kartalle' },
  { v: 217, teksti: 'Korjattu: kuvat jäivät välillä lataamatta' },
  { v: 217, teksti: 'Himalajan lumi ei enää näytä reiältä' },
  { v: 216, teksti: 'Aasian ja Lähi-idän merkinnät uusiksi' },
  { v: 216, teksti: 'Kertojan luenta 50 uuteen kaupunkiin' },
  { v: 215, teksti: 'Luennat eivät enää lopu napsahdukseen' },
  { v: 214, teksti: 'Uudet kaupungit: Asunción, Montevideo, Houston, Havanna' },
  { v: 213, teksti: 'Nipistys zoomaa karttaa — nyt oikeasti' },
  { v: 213, teksti: 'Zoomipainikkeet pois kosketuslaitteilta' },
  { v: 212, teksti: 'Koko Eurooppa kirjoitettu uusiksi ja luettu' },
  { v: 212, teksti: 'Kertojan luenta kaikkiin 41 Euroopan kaupunkiin' },
  { v: 211, teksti: 'Nipistys zoomaa karttaa kahdella sormella' },
  { v: 211, teksti: 'Korjattu: kartta katkesi kesken kierroksen' },
  { v: 210, teksti: 'Pohjolan merkinnät uusiksi yhden idean malliin' },
  { v: 209, teksti: 'Maailmankartta korvasi vanhan maailman laudan' },
  { v: 209, teksti: 'Maat, rajat ja matkakirja maailmankartalle' },
  { v: 209, teksti: 'Kesken jäänyt peli siirtyy uudelle kartalle' },
  { v: 209, teksti: 'Työhuone laski puutteita liian ankarasti' },
  { v: 208, teksti: 'Helsingin merkintä uusiksi: kaupunki pala palalta' },
  { v: 207, teksti: 'Baltian merkinnät lyhyemmiksi ja selkeämmiksi' },
  { v: 206, teksti: 'Koko maailma yhtenä karttana: 248 kaupunkia' },
  { v: 206, teksti: 'Kartta kiertää ympäri eikä pääty reunaan' },
  { v: 206, teksti: 'Valtameriylitykset yhdistävät mantereet' },
  { v: 206, teksti: 'Kartta latautuu kolmekymmentä kertaa nopeammin' },
  { v: 205, teksti: 'Korjattu: nostojen kuvat puuttuivat iPhonelta' },
  { v: 204, teksti: 'Aiherivi pysyy näkyvissä arkin yläreunassa' },
  { v: 203, teksti: 'Kuvat omissa mittasuhteissaan, ei panoraamana' },
  { v: 203, teksti: 'Aiheen vaihto ei enää hyppää näkymässä' },
  { v: 203, teksti: 'Väljemmät marginaalit Tutki-arkilla' },
  { v: 203, teksti: 'Afrikan aarre: Suuren Zimbabwen kivilintu' },
  { v: 202, teksti: 'Arkin reuna piirtyy kuin rantaviiva kartalla' },
  { v: 202, teksti: 'Tutki-kortti täyttää ruudun muistiinpanoarkkina' },
  { v: 202, teksti: 'Aiheliuskat kuvakkeina yhdelle riville' },
  { v: 201, teksti: 'Tutki-ikkunaan kirjanmerkkiliuskat aiheittain' },
  { v: 201, teksti: 'Lontooseen 53 kulttuurinostoa yhdeksään aiheeseen' },
  { v: 200, teksti: 'Työhuone ei enää syö pelin offline-muistia' },
  { v: 200, teksti: 'Turha päivityskehotus pois työhuoneesta' },
  { v: 199, teksti: 'Kaupungin oma ääni soi vihdoin isolla laudalla' },
  { v: 198, teksti: 'Radionapissa aseman nimi ja live-merkki' },
  { v: 198, teksti: 'Vain aidosti vanhat kuvat ovat mustavalkoisia' },
  { v: 198, teksti: 'Kuvat aukeavat isompina työpöytäselaimella' },
  { v: 198, teksti: 'Sisältötarkastus: 15 virhettä pois teksteistä' },
  { v: 198, teksti: 'Pariisin ja Lontoon tekstit vastaavat kertojaa' },
  { v: 197, teksti: 'Laajennussuunnat työhuoneen suunnitelmaan' },
  { v: 196, teksti: 'Työhuoneen karttakehys ei jää soimaan taustalle' },
  { v: 196, teksti: 'Työhuone näyttää peilin ja repojen koot' },
  { v: 196, teksti: 'Äänistudio työhuoneen sisään, oma sivu pois' },
  { v: 195, teksti: 'Äänistudio samaan tyyliin työhuoneen kanssa' },
  { v: 194, teksti: 'Työhuone uusiksi: selkeämpi ja oma sovellus' },
  { v: 193, teksti: 'Tunnusluvut 21 Aasian maalle' },
  { v: 192, teksti: 'Kuvakortit 40 Aasian kaupunkiin' },
  { v: 191, teksti: 'Päivitysloki versionumeron takana' },
  { v: 190, teksti: 'Lipputunnistus uutena kysymysmuotona' },
  { v: 190, teksti: 'Europeana mukaan kuvahakuun' },
  { v: 189, teksti: 'Maiden rajat Aasiaan: 84 maata minikartalla' },
  { v: 188, teksti: 'Omat artikkelit kaikkiin 143 kaupunkiin' },
  { v: 187, teksti: 'Suora radio kaikkiin 87 maahan' },
  { v: 186, teksti: '193 uutta kuvaa päiväkirjan näkymistä' },
  { v: 186, teksti: 'Korjattu: Lue lisää kaatui 69 paikassa' },
  { v: 185, teksti: 'Saapumistekstit kaikkiin 143 kaupunkiin' },
  { v: 185, teksti: 'Kuuntele kieltä soittaa suoraa radiota' },
  { v: 185, teksti: 'Korjattu: Darfurin kuva ei ollut vanha' },
  { v: 184, teksti: 'Kuvakortti keskelle ruutua' },
  { v: 183, teksti: 'Kuvapino kestää useamman kuin kaksi kuvaa' },
  { v: 182, teksti: 'Kuvakortti isommaksi isolla ruudulla' },
  { v: 181, teksti: 'Työhuoneeseen oma välilehti laseille' },
  { v: 180, teksti: 'Noppa takaisin yhdistetylle kartalle' },
  { v: 178, teksti: 'Wiki, ääni ja maa 66 uudelle kaupungille' },
  { v: 176, teksti: 'Kertojan ääni ei enää naksahda lopussa' },
  { v: 174, teksti: 'Korsika kartalle' },
  { v: 172, teksti: 'Tutki-ikkuna mahtuu puhelimen ruudulle' },
  { v: 169, teksti: 'Tiet näkyvät taas iPadilla' },
  { v: 167, teksti: 'Vinjetointi pois kaikilta laitteilta' },
  { v: 166, teksti: 'Kartta ei välky uutta osaa ladatessa' },
  { v: 165, teksti: 'Kartta bittikarttana: sujuva vieritys' },
  { v: 160, teksti: 'Lähizoomaus kaupunkiin saavuttaessa' },
  { v: 159, teksti: 'Meri näkyy taas iPadilla' },
  { v: 155, teksti: 'Yhdistetty vanha maailma yhdeksi kartaksi' },
];
