/*
 * Rakennustyön tilannetaulu työhuoneen etusivulle (omistajan toive
 * 8.8.2026: "yhteenveto, joka päivittyy, siitä missä tämänhetkinen
 * rakennustyö on menossa").
 *
 * TÄTÄ TIEDOSTOA PÄIVITTÄÄ FABLE aina, kun sessioilta saapuu
 * raportti tai työjono muuttuu — muut sessiot eivät kirjoita tähän.
 * Työhuone näyttää taulun etusivun kärjessä. Tilat: 'tyossa',
 * 'valmis', 'odottaa' (selväkielinen selite riville).
 */

export const TILANNE = {
  paivitetty: '15.8.2026 — v705–v751',
  tavoite: 'Kartat: 10 kaupungilla värikartta + piirrospisteet '
    + '(suurennos, kyltit, osuma-alue hiottu). Lippusivut 58/118. '
    + 'Kööpenhaminan lehtimalli valmis: avauskuvakaruselli, 2 palstan '
    + 'karttateksti, Matkailijalle kuvineen, opasartikkeli. '
    + 'Avauskuvat myös Berliini, Helsinki, Pariisi, Lontoo. Työhuoneen '
    + 'palkit (R2, repo, Eleven, pöllö, kulut). Paluunuoli '
    + 'henkilöjuttuihin. LEHTITAUKO: uusia lehtiä ei kirjoiteta ennen '
    + 'nykyisten parannusta.',
  rivit: [
    {
      tekija: 'Fable',
      rooli: 'päätoimittaja',
      tila: 'tyossa',
      tehtava: 'Lehtimallin pilotti, avauskuvaerät, lippusivut, '
        + 'kartan ja työhuoneen hionta omistajan palautteista.',
      seuraavaksi: 'Avauskuvaerä 2 (Rooma, Wien, Praha, Amsterdam, '
        + 'Tukholma); Matkailijalle-monistus Opukselle omistajan '
        + 'tsekin jälkeen; lippuerä 8.',
    },
  ],
  odottaaPaatosta: [
    'Kööpenhaminan lehtimallin hyväksyntä (monistuksen aloitus)',
    'Mac-Safari-äänikorjauksen testi Macilla (v741)',
    'Kehittäjätilan kytkentä täydellä koodilla (työhuoneen palkit)',
    'Pöllö-työtila Anthropic-konsoliin (kulujen rajaus)',
    'Karttaerien 2–5 kaupunkilistat',
    'Kazakstanin ja Syyrian lippusivut (erikseen)',
  ],
};

/**
 * Testattavaa juuri nyt. ÄÄRIMMÄISEN MINIMALISTINEN (omistajan
 * linjaus 15.8.2026: "tavuviiva ja muutama sana per kohta
 * korkeintaan — muistan itse kyllä suurimman osan"). Uusin ensin;
 * rivit siivotaan kun ne on katsottu.
 */
export const TESTATTAVAA = [
  'v851 — iPad: lippuikkunan tarkennustila (esim. Ranska, vaakuna suurennettuna): sumennettu sisältö leikkautuu nyt kortin pyöristyksen SISÄÄN eikä sen yli; testaa myös pitkän kortin (Saksa) vieritys sormella',
  'v850 — Raamatun Lukijoiden ehdotukset -osioon palkkiolinjaus: läpäissyt ehdotus palkitaan pelirahalla lunastuskoodilla, omistaja päättää summan',
  'v849 — Raamatussa uusi Lukijoiden ehdotukset -osio (kehittäjän liitteet): pelaajien kuva- ja juttuideakanavan linjaus',
  'v848 — iPad: lehden kansikarusellin napautus ei jätä enää vaaleaa harsoa kuvan laitaan (nuolinapin hover-tausta) — testaa Pariisin kansi: napauta oikeaa laitaa ja katso jääkö kuvan päälle vaalea kaista',
  'v847 — neljä uusittua miniatyyriä kartalla: Tampereen tuomiokirkko, Tripolin riemukaari ja Punainen linna, Tokion Shitamachi-museo — kaikilla kohteilla on nyt piirros',
  'v846 — Flickr-valokuvat Tampereen ja Firenzen lehtiin (19 kpl): avaa molemmat lehdet — avauskuvakaruselli, kansikuvien suurennos ja Matkailijan oppaan jaksot (Koski ja punatiili, Mustamakkara ja torit, Ilta / Perille ja jalkapatikkaan, Museot yhtenä päivänä, Torilla ja pöydässä, Ilta); tarkista että kuvat latautuvat ja tekijä + lisenssi näkyvät joka kuvatekstissä',
  'v845 — Raamatun Kuvat ja lähteet -osiossa uusi linjaus: kaikki sisältö ämpäristä (R2-peili), uusi lähde vasta kun peilausputki kattaa sen; kuvalähdelista päivitetty (Commons, Finna, LoC, Flickr)',
  'v844 — kohdekarttojen miniatyyripiirrokset kahdeksaan uuteen kaupunkiin: Tampere, Firenze, Bagdad, Teheran, Tripoli, Tokio, Soul ja Shanghai — tarkista että piirros näkyy kartalla numeroympyrän tilalla; neljä kohdetta jäi vielä ilman piirrosta (Tampereen tuomiokirkko, Marcus Aureliuksen riemukaari, Punainen linna, Shitamachi-museo)',
  'v843 — lippuikkuna (esim. Soul): iso lippu terävä myös iPadilla (haetaan nyt 1280 px:n kuvana), ja tunnus/versiolippu suurennettuna pysyy kortin sisällä selitteineen — ei enää katkeavaa kuvatekstiä alareunassa',
  'v842 — kuvakarusellien laitojen tummennus poistettu kaikkialta (lehden kansikuva, nostogalleria, nähtävyysjutut, opas) — tarkista että nuoli erottuu yhä vaalealla ja tummalla kuvalla; lisäksi lehden ja jutun alareunan sumea kaista kotipalkin yli iPadilla',
  'v841 — syvä lähikuva (maailmankartta) terävöityy heti zoomin jälkeen — kokeile nopeaa zoomailua syvällä zoomilla',
  'v840 — iPad: Firenzen Matkailijan opas — karussellikuvan yläpuolella ollut tumma palkki pois; tarkista myös alareunan kuvateksti ja lähderivi taustapaluun jälkeen',
  'v839 — zoomaile nopeasti sisään/ulos ja lopeta: kartta tarkentuu nyt parissa sekunnissa eikä jätä sumeita laikkuja',
  'v838 — kolme turhaa suoraa reittiä pois (Helsinki–Rovaniemi, Granada–Lissabon, Addis Abeba–Suakin) — ketjut uusien kaupunkien kautta',
  'v837 — iPad: kartta ei enää bugaa taustapaluussa (vaalea kaista, jäätynyt piirto) — testaa: raahaa karttaa, vaihda appia sormi pohjassa, palaa',
  'v836 — E00 2/2: Tokion, Soulin ja Shanghain kohdekartat ja kohteet — koko kuusikko valmis, tarkista pelissä',
  'v835 — E00 1/2: Bagdadin, Teheranin ja Tripolin kohdekartat ja kohteet (avaa lehdet ja kartat pelissä — omistaja tarkistaa suoraan pelistä)',
  'v834 — iPhone: lehti täyttää ruudun alas asti (sumennettu alakaista pois) — testaa myös taustapaluun jälkeen',
  'v833 — 11 uutta kaupunkia laudoilla ja maailmankartalla (Kioto, Varanasi, Mandalay, Kanton, Sevilla, Bergen, Fès, Lalibela, Sitka, Ouro Preto, Dunedin) — pisteet, reitit, visat ja kuvakortit; ei vielä lehtiä',
  'v832 — Firenze Euroopan laudalla lehtineen (avaa lehti: kansi, Kuvataide-sivu, opas, kohdekartta)',
  'v831 — Tampere Euroopan laudalla lehtineen (avaa lehti!); Lappi on nyt Rovaniemi (lehti vielä vanha Lappi-lehti)',
  'v830 — LAITETESTI iPad/iPhone: kartan eleet (raahaus, liuku, nipistys, rullazoom) toimivat kuten ennen',
  'v829 — kartta toimii kuten ennen (kamera omaksi moduulikseen): zoomi, panorointi, mannerzoom, lähikuvat',
  'v828 — taustapaperi ei näy enää millään ikkunamuodolla (kokeile kapea pysty- ja matala vaakaikkuna aloituskartalla ja mantereilla)',
  'v827 — Raamatun Karttalinssit-osiossa aikajana-ajo ja lavalinssi; Moduulit-osiossa M7+-hyväksyntä',
  'v826 — docs-siivous: Raamatussa Venäjä/Kabul- ja yksi otto -linjaukset; kaksi dokumenttia arkistoon',
  'v825 — Raamatun uusi Poistetut ideat -osio (kehittäjän liitteet): neljä riviä, pääosiot siistitty',
  'v824 — lehdet toimivat kuten ennen (tila koottu yhteen olioon); pöllön nähtävyyslinkki avaa taas jutun',
  'v823 — Islanti kartalla paikallaan; sääosion luonnehdinta joka kaupungissa (avaa muutama lehti); Bagdad+Teheran hintataso',
  'v822 — tuotantosuunnitelma (docs/tuotantosuunnitelma.md): lue ja päätä',
  'v821 — remontti valmis: luenta+visa moduuleiksi, ui.js -37 %',
  'v820 — remontti M5c: maalehti moduuliksi',
  'v819 — remontti M5b: kuvataitto+sää+uutiset lehteen',
  'v818 — remontti M5a: lehden sivukoneisto moduuliksi',
  'v817 — remontti M4: opas+nähtävyydet moduuleiksi',
  'v816 — Matkailijan Tokio, Soul, Shanghai ja Tripoli (O6 valmis)',
  'v815 — remontti M3: liput, karttazoom, vertailu moduuleiksi',
  'v814 — remontti M2: UI:n apurit omaan moduuliin',
  'v813 — remontti M1: sisältötaulut omaan moduuliin',
  'v812 — miniatyyrityökaluun hybridimalli (ei nakyvia muutoksia)',
  'v811 — Raamatussa: uusiin kohteisiin vain lehdet, ei kaarta',
  'v810 — opas: Matkakassa pois, hintatasorivit; 5 säänluonnehdintaa',
  'v809 — Raamatussa: oppaan avauskuva = karuselli jakson tekstistä',
  'v808 — remonttisuunnitelmat mainissa (docs/moduulirakenne + docs-remontti)',
  'v807 — Raamatussa: ei Matkakassaa; työlistassa paketti O5',
  'v806 — Raamatussa: maalehden nimiö, Matkailijalle-kuvan kaava',
  'v805 — Matkailijan Teheran: toinen kuudesta',
  'v804 — Matkailijan Bagdad: ensimmäinen kuudesta uudesta',
  'v803 — kaiuttimen kuvake otsikon kokoiseksi kohdekortissa',
  'v802 — lehden alanapit kotipalkin yläpuolelle iPadilla',
  'v801 — kohdekortti: kaiutin otsikon perään, 5/6 pois',
  'v800 — etusivun avausteksti pergamentille, ei tummalle',
  'v799 — arkin alalaidan napit takaisin ruudulle iPadilla',
  'v798 — pöllön kuvat aukeavat isoina myös isolla ruudulla',
  'v797 — oppaan otsikko esiin: iPhone ja iPad, yläreuna',
  'v796 — viiden oppaan avauskuva kolmen kuvan karuselliksi',
  'v795 — Helsingin etusivulle Uspenskin katedraali',
  'v794 — Wien, Rooma ja Kööpenhamina: pystykuva etusivulle',
  'v793 — Orsayn museo saa piirroksen Pariisin kartalle',
  'v792 — Pariisin kartalle piirrokset: ooppera ja Place des Vosges',
  'v791 — Berliini pystykuva; alanapit iPadilla; isompi pystykuva',
  'v790 — Lontoo: Big Ben etusivulle, 3 kuvan karuselli oppaaseen',
  'v789 — iPad-jumi: kartta ja alanapit palaavat app-vaihdosta',
  'v788 — Pariisissa 11 kohdetta; sää kaikissa 70 kaupungissa',
  'v787 — lippu maan otsikkoon, Eiffel etusivulle Pariisiin',
  'v786 — opas 5 kaupunkiin: tsekkaa ennen koko Euroopan ajoa',
  'v785 — sääennuste 32 lehteen, maasivun nimiö, oppaan graafi',
  'v784 — iPad: käy toisessa apissa ja palaa; alanapit paikallaan',
  'v783 — säägraafi elää, Seinen karuselli, paperi ehyt',
  'v782 — opas 2.2: kainalotaulu (napauta rivejä), säägraafi',
  'v781 — nauha koko osion yli, leveämpi, pehmeämmät värit',
  'v780 — opas 2.1: kainalot, uusi paletti, iso otsikko, lämmin kuva',
  'v779 — etusivulla yksi diagonaalinauha: Matkaopas',
  'v778 — Matkailijalle-kuvateksti napakaksi (7 kaupunkia)',
  'v777 — Matkailijalle: kyltti kuvan kulmassa, Lue lisää -linkki',
  'v776 — Pariisin opas 2.0: jaksot, sää, hinnat, linkit, lappu',
  'v775 — äänet poistettu repostä: luennat + taustat R2:sta',
  'v774 — äänet R2:sta; asennus kevenee 180 Mt (testaa äänet!)',
  'v773 — Maxin työlista huomiselle (moduulit + docs-remontti)',
  'v772 — Raamatussa: äänet R2, oppaan ilme, speksioppi, remontti',
  'v771 — Pariisin etusivukuvat: tsekkaa ja hyväksy monistus',
  'v770 — Raamatussa etusivukuvien kaava (Kuvat ja lähteet)',
  'v769 — karttatekstin loppu: piirroskarttojen oma ohje',
  'v768 — Matkailijalle 5 kaupunkiin (Berliini, Pariisi, Lontoo, Rooma, Wien)',
  'v767 — vaakunan ajoittainen tumma laatikko: pitäisi olla poissa',
  'v766 — opas: otsikko VIHDOIN näkyviin; kuvat tekstin lomaan',
  'v765 — Köpiksen uusilla kohteilla piirrokset kartalla',
  'v764 — Köpiksen kartalla 9 kohdetta (uudet: 7–9, ympyröinä)',
  'v763 — vaakuna isona ilman laatikkoa; liput paikallaan',
  'v762 — jutun otsikko: vahti pitää yläreunan paikallaan',
  'v761 — työhuoneessa vain palkit, tekstirivit pois',
  'v760 — tarkennettu vaakuna pergamenttilevyllä, ei tummaa',
  'v759 — jutun otsikko pysyy näkyvissä kuvan latautuessa',
  'v758 — työhuoneen palkit: pitäisi VIHDOIN näyttää luvut',
  'v757 — jutun napit kortissa kiinni; leveys kestää appivaihdon',
  'v756 — opas leveämpi iPadilla; ☰ pois oppaan yläkulmasta',
  'v755 — tyhjät palkit: sulje valikko ja avaa uudelleen',
  'v754 — kulurivi kertoo lähdevirheen; avaa valikko uudelleen',
  'v753 — Helsingin Matkailijalle: kappale, kuva, opas',
  'v751 — lippusivut: Kaakkois- ja Etelä-Aasia (10 maata)',
  'v750 — paluunuoli Engel-jutusta; kulurivin oikea syy',
  'v749 — karttateksti 2 palstaan; Matkailijalle- ja opaskuvat',
  'v748 — ison piirroksen klikki: vain kuvan keskiosa avaa',
  'v747 — lippusivut: Lähi-itä (8 maata)',
  'v746 — avauskuvat 4 kaupunkiin; R2 molemmat ämpärit; kulunimiö',
  'v745 — etusivun karuselli koko palstan levyinen',
  'v744 — R2-palkki megatavuina; Eleven-lukema tiiviiksi',
  'v743 — pöllön kuva: ei enää kaimakyliä; epävarmana ei kuvaa',
  'v742 — lukija seis joka pop-upista (kartta, maalehti, pöllö)',
  'v741 — Mac-Safari: striimiluennan ääni (testaa Macilla!)',
  'v740 — Työhuone: palkit, tyylinapit, Lukijaääni',
  'v739 — piirros juttuun; klikkausalue 80 %',
  'v738 — Kööpenhamina-lehti: karuselli + Matkailijalle',
  'v737 — 6 uutta karttaa; piirrokset terävinä; lippuanimaatio',
  'v736 — vain värikartta; numero kylttiin',
  'v735 — suurennos keskitetty, 75 %; kyltti kiinni',
  'v734 — kartta 70 %; kyltti tiiviimmin; lippu ilman laatikkoa',
  'v733 — lippusivut: Aasia (8 maata)',
  'v732 — suurennos 65 %; kyltti kiinni rakennukseen',
  'v731 — lippusivut: Slovenia–Azerbaidžan (6 maata)',
  'v730 — lippuikkunan tarkennus + sumennus; kartta 40 %',
  'v729 — lippusivut: Itä-Eurooppa + Balkan (9 maata)',
  'v728 — suurennos ¼ kartasta; kyltistä juttuun; vipunapin teksti',
  'v727 — lippusivut: Länsi-Eurooppa (8 maata)',
  'v726 — lippusivut: Pohjoismaat + Baltia (7 maata)',
  'v725 — lippuikkunan iso kuva reunasta reunaan',
  'v724 — piirrokset skaalautuvat zoomissa; peruskoko 40 px',
  'v723 — kultaneliön OIKEA syy: hover-korostus; koko 4×',
  'v722 — piirrokset PNG:inä: neliö varmasti pois',
  'v721 — iOS-neliö pois suurennoksesta; koko 3,5×',
  'v720 — piirroksen suurennos 3×',
  'v719 — piirroksen klikkaus vain suurentaa, ei ikkunaa',
  'v718 — piirrokset pienempinä, nuolet pois',
  'v717 — piirrokset yksivärisinä luonnoksina',
  'v716 — lippuikkuna: 2/3-korkeus, symboliikka, vaakunat',
  'v715 — piirrokset hajallaan + nuolet; klikkaus: kyltti → juttu',
  'v714 — kartan piirrokset leikattuina, numerot pois',
  'v713 — pöllön kuvalle paikanpitäjä + animaatio',
  'v712 — pöllön kuva löytyy myös hakusanalla',
  'v711 — lipusta lipun tarina (Saksa, Suomi)',
  'v710 — piirrokset pisteinä + kortit 4 kaupungissa',
  'v709 — värikartat: Helsinki, Pariisi, Lontoo',
  'v708 — Berliinin pisteet: piirroskortti + juttuun',
  'v707 — Berliinin värikartta (vipu kartalla)',
  'v706 — Raamatun taitto: kappaleet, ei palstoja',
  'v704 — radio hiljenee pöllön/lukijan puhuessa',
  'v703 — pöllön vastauskuva; klikkaus isoksi',
  'v702 — oletusprompti näkyvissä; vuosiluvut ei lueta',
  'v701 — Raamattu tiiviinä + valmis/kesken-tagit',
  'v699 — nähtävyysjutut: Panthéon, Luco, Kallio, Lintsi',
  'v697 — Kehittäjä-valikko: Raamattu- ja Tilannelehti',
  'v695/v696 — esipuskurit; reunuskartat 4 kaupunkia',
  'v694 — ElevenLabs-äänitteet takaisin merkintöihin',
  'v692 — taustaäänet tasattu; v691 Venäjän radio',
  'v683–v687 — lukijan automoodi, otsikkotauot, väistö',
];
