/*
 * Rakennustyön tilannetaulu työhuoneen etusivulle (omistajan toive
 * 8.8.2026: "yhteenveto, joka päivittyy, siitä missä tämänhetkinen
 * rakennustyö on menossa").
 *
 * TÄTÄ TIEDOSTOA PÄIVITTÄÄ FABLE aina, kun sessioilta saapuu
 * raportti tai työjono muuttuu — muut sessiot eivät kirjoita tähän.
 * Työhuone näyttää taulun etusivun kärjessä. Tilat: 'tyossa',
 * 'valmis', 'odottaa' (selväkielinen selite riville).
 */

export const TILANNE = {
  paivitetty: '15.8.2026 — v705–v751',
  tavoite: 'Kartat: 10 kaupungilla värikartta + piirrospisteet '
    + '(suurennos, kyltit, osuma-alue hiottu). Lippusivut 58/118. '
    + 'Kööpenhaminan lehtimalli valmis: avauskuvakaruselli, 2 palstan '
    + 'karttateksti, Matkailijalle kuvineen, opasartikkeli. '
    + 'Avauskuvat myös Berliini, Helsinki, Pariisi, Lontoo. Työhuoneen '
    + 'palkit (R2, repo, Eleven, pöllö, kulut). Paluunuoli '
    + 'henkilöjuttuihin. LEHTITAUKO: uusia lehtiä ei kirjoiteta ennen '
    + 'nykyisten parannusta.',
  rivit: [
    {
      tekija: 'Fable',
      rooli: 'päätoimittaja',
      tila: 'tyossa',
      tehtava: 'Lehtimallin pilotti, avauskuvaerät, lippusivut, '
        + 'kartan ja työhuoneen hionta omistajan palautteista.',
      seuraavaksi: 'Avauskuvaerä 2 (Rooma, Wien, Praha, Amsterdam, '
        + 'Tukholma); Matkailijalle-monistus Opukselle omistajan '
        + 'tsekin jälkeen; lippuerä 8.',
    },
  ],
  odottaaPaatosta: [
    'Kööpenhaminan lehtimallin hyväksyntä (monistuksen aloitus)',
    'Mac-Safari-äänikorjauksen testi Macilla (v741)',
    'Kehittäjätilan kytkentä täydellä koodilla (työhuoneen palkit)',
    'Pöllö-työtila Anthropic-konsoliin (kulujen rajaus)',
    'Karttaerien 2–5 kaupunkilistat',
    'Kazakstanin ja Syyrian lippusivut (erikseen)',
  ],
};

/**
 * Testattavaa juuri nyt. ÄÄRIMMÄISEN MINIMALISTINEN (omistajan
 * linjaus 15.8.2026: "tavuviiva ja muutama sana per kohta
 * korkeintaan — muistan itse kyllä suurimman osan"). Uusin ensin;
 * rivit siivotaan kun ne on katsottu.
 */
export const TESTATTAVAA = [
  'v883 — palautelappu: kortti keskitetty ruudulle (istui ennen dialogin vasemmassa reunassa) ja pro-rasti i-nappeineen on nyt ENNEN Lähetä ehdotus -nappia',
  'v882 — laukun tietäjärivi: vasemmalla avatar + tasonimike (esim. Maailmanmatkaaja) ja i heti sen perässä, oikeassa reunassa vain pisteet ("210 tp") — Tietäjä-sana pois',
  'v881 — pöllön valmiskysymykset ja ehdota-nappi: avaa pöllö Firenzessä (laatta tai lehti) — syöterivin yllä 2 valmista kysymystä + väkänen (väkänen/vieritys näyttää kaikki 5), napautus kysyy ja sen jälkeen palataan normaaleihin jatkokysymyksiin; pilottikaupungit Firenze, Tampere, Kairo, Tokio, Pariisi, Helsinki (muilla alue ei näy); paneelin oikeassa yläkulmassa pieni "Ehdota sisältöä" -nappi, joka avaa saman lomakkeen kuin hampurilainen — myös lehden päältä',
  'v880 — 30 uutta miniatyyriä: Kairon kaikki 10 kohdetta sekä Tampereen, Firenzen ja E00-kuusikon uudet kohteet piirroksina (numeroympyrät pois) — avaa esim. Kairon ja Tokion kartat; sävy istuu pohjaan (v877)',
  'v879 — ehdotuslomake: uusi saateteksti ("Näitkö matkallasi kuvan tai aiheen…"), ja pro-osio on nyt rasti "Haluan hakea pro-sisällöntuottajaksi" + pieni i, joka avaa selitteen minipopupissa; rasti paljastaa kirjautumisen',
  'v878 — kohdekartoille 15 uutta nähtävyyttä: Tokio 6→10 (Ueno Tōshō-gū, Uenon asema, Hanayashiki, Kyū-Iwasaki-tei), Soul 6→9 (Gwanghwamun, Insadong, Jogyesa), Shanghai 6→9 (Kaupunginjumalan temppeli, Fuyoun moskeija, Dajingin pavilonki), Bagdad 6→8 (Haydarkhanan ja al-Wazirin moskeijat), Teheran 6→8 (Toopkhanen aukio, Bagh-e Mellin portti), Tripoli 6→7 (Gurgin moskeija) — avaa kartat ja parit uudet jutut; uusilla kohteilla ei ole vielä miniatyyripiirrosta, joten ne näkyvät numeroympyröinä',
  'v877 — miniatyyrit sävytetty kartan pohjaväriin (kaikki 120): piirroksen paperi ei enää hohda vaaleampana kartan päällä — katso esim. Firenzen tai Helsingin kartta ja suurennos; uudet kuvat saavat sävyn automaattisesti leikkurista',
  'v876 — oppaan vuosisää samalle pohjalle kuin lehden: avaa Firenzen Matkailijan opas ja napauta Milloin matkaan -laatikon kuvaajaa — aukeaa sama sääkortti kuin lehden vuosiennusteesta (otsikko, luonnehdinta ja lähderivi graafin alla), napautus/Esc sulkee kortin muttei opasta; oppaan oma pelkistetty suurennos poistui',
  'v875 — E00-lehtien täydennys: Soulissa uusi aihesivu Arki ja ilta (telttakojut, kylpylä, PC bang), Shanghaissa Arki (avioliittotori, cifantuan-aamiainen, shanghainkieli), Tripolissa Kauppa ja karavaanit (Sahara, Ghadames, Philadelphia-fregatti) — jokaisessa minitehtävä sivun lopussa; Bagdadin, Teheranin ja Tripolin etusivuille avauskuvakaruselli (3 kuvaa/kaupunki, Commons) — avaa kaikki viisi lehteä',
  'v874 — laukun hionta: iPadilla laukku kapeampi (520 → 470 px) ja varusteet neljässä sarakkeessa (iPhonella kolme); iPhonella laukku matalampi (72 dvh) ja alanappirivi piiloutuu laukun ollessa auki, jotta linssin vaikutus karttaan näkyy; pöllöesittelyn lopusta poistui virke "Tasonnousu ei tuo etuja…" (i-napin galleria)',
  'v873 — Kairon lehti nykystandardiin: kartta 6 → 10 kohteeseen (uudet Abdeenin palatsi, Sulttaani Hassanin moskeija, Bab Zuweila, Al-Azhar-puisto nähtävyysjuttuineen), etusivulle kolmen yleisnäkymän avauskuvakaruselli ja Matkailijalle-osio Matkaopas-artikkeleineen (4 jaksoa) — avaa Kairon lehti: kansi, opas, kartta ja neljä uutta kohdepopuppia; miniatyyrit ovat vasta generointijonossa, uudet pisteet näkyvät numeroina',
  'v872 — lukija lukee kappaleen kerralla: ei enää uutta lähtöä (intonaatiohyppyä) kesken kappaleen — koko kappale on yksi generointi ja korostuu kerralla, korostusväri puolet aiempaa vaaleampi; aloitus ja kappalehyppy voivat viipyä hetken pidempään (koko kappale generoituu ennen soittoa, ensimmäinen kappale on esipuskuroitu)',
  'v871 — lehden alareuna + kartan taustapaluu (iPad): 1) avaa Firenzen lehti pystyasennossa — paperin alle jää vain kapea (~13 px + kotipalkki) sumea rako, alanapit näkyvät; 2) käy toisessa sovelluksessa ja palaa — alareunan pitää pysyä samana, ei leveää sumeaa kaistaa eikä nappeja piiloon; 3) kierrä vaakaan ja takaisin lehti auki — sama tulos; 4) sama koe lehti kiinni Afrikka-näkymässä: taustapaluun jälkeen kartassa ei vaaleaa pystykaistaa, kartta ei ole työntynyt sivuun eivätkä vasemman ylänurkan tekstit mene päällekkäin (jos tekstit menevät yhä päällekkäin, ota kuvakaappaus — se on eri juurisyy)',
  'v870 — laukun varusteet kerran: Tavaroissa ei enää linssirivejä; Varusteet on pyöreiden varustekuvien ruudukko (3 riviin, ei nimilappuja) + Ei linssiä -kiekko; napautus kytkee kuten ennen, valittu saa messinkirenkaan ja nimi+kuvaus näkyvät alla; pelkillä linsseillä Tavarat sanoo "Ei vielä matkalöytöjä."',
  'v869 — varustekuvat uusittu selkeämmiksi (laukun Tavarat/Varusteet): lasi täyttää ruudun ja sisältö kertoo toiminnan — vuoristo, jokiverkko, kolme värimaata + käyrät, kultainen maa + kirja, radio aaltoineen',
  'v868 — lukija lukee vain leipätekstit: avaa Firenzen Matkailijan opas ja paina kaiutinta — "Parasta täällä", "Hyvä tietää", kausitaulun lämpöhaarukat (Kevät 4–22 °C…), sääkuvaajan kuvateksti ja "Suunnittele matka" -linkit EIVÄT enää kuulu, mutta "Milloin matkaan?" luetaan otsikkoineen (vain aloituskappale) ja "Kupoli ja jonot" otsikkoineen ilman kuvatekstiä. Nähtävyysjuttu alkaa nyt suoraan leipätekstistä (rivi "Kohde 1 · 1296–1436" ja otsikko jäävät pois). Tarkista myös lehden etusivu ja maalehden Menovinkit (kohteen nimi luetaan selityksensä edellä). SAMALLA: luennan ajan oikeassa ylälaidassa on PYSYVÄ kaiutin — kartalla maapillerin alla, lehdessä sivun oman kaiuttimen alla — napautus avaa ja sulkee säätöpaneelin, kuvake hehkuu lukiessa ja himmenee tauolla',
  'v867 — pöllön ehdotuskutsu ("Haluatko osallistua…") ilmestyy nyt hampurilaisnapin ALLE kärki ylöspäin kohti nappia (näkyy vain kerran per laite; nollaus: localStorage-avain matkakirja-ehdotus-kupla pois)',
  'v865 — Tampereella 8 ja Firenzessä 9 kohdetta (oli kummassakin 6): uudet ovat Tallipiha ja Amurin työläismuseokortteli sekä Galleria dell\'Accademia, Santa Maria Novella ja Bargello — avaa molemmat kohdekartat ja uusien kohteiden jutut; uudet näkyvät vielä numeroympyröinä (miniatyyrit generoimatta), ja Firenzen oppaan nosto sanoo nyt "yhdeksän kohdetta"',
  'v864 — tilastolehti iPadilla: vieritä Mantereet-taulua vaakaan — kaikkien sarakkeiden otsikot (Lehti…Kieli, Maalehti…Radio) pysyvät näkyvissä (aiemmin osa katosi vierityksessä)',
  'v863 — tietäjäavatarit: avaa matkalaukku — tietäjärivin edessä on nykyisen tason PYÖREÄ MUOTOKUVA (pöllökuvake pois), rivin alla ohut kultainen edistymispalkki seuraavaan rajaan ja rivin perässä i-nappi, joka avaa Tietäjän tie -minipopupin (selitys + kaikki 10 tasoa kuvineen; saavuttamattomat himmeinä, nykyinen kehystettynä; sulkeutuu ruksista, taustasta ja Escistä). Tasonnousussa pöllön kupla on uusi: iso avatar, kalevalainen värssy kursiivilla kahdella rivillä ja onnittelu (40 tp tulee vastaan nopeasti). Ylin taso on nyt "Tietäjä iänikuinen" (ei Suurtietäjä)',
  'v862 — kohdekartat (esim. Firenze, Helsinki): karttatekstin lopusta poistui ohjevirke "Kohteet ovat kartalla…" kaikista 12 kaupungista, ja tilalle tuli kartan oikeaan yläkulmaan pieni opaste "Napauta nähtävyyttä, saat lisätietoja."; nimikyltin kirjasin isompi (0,74 → 0,95 rem) — katso tiheä kartta (Firenze, Pariisi) puhelimella',
  'v861 — palautedialogi pelkistyi: alkuteksti ja GitHub-linkki pois, Ehdota lehteen -kentät näkyvät suoraan ilman otsikkoa ja vipua — vain pro-osio on vivun takana',
  'v860 — työhuone kokonaan peliin: erillinen tyohuone.html on POISTETTU (poista myös sen vanha kotivalikkopikakuvake laitteelta). Hampurilaisen TYÖHUONE-osiossa uusi Tilastot-lehti: sivu 1 on manner → maa → kaupunki -vetolaatikkotaulu (napauta mannerta, sitten maata), yläreunassa järjestysvipu aakkosittain / valmiit ylimpänä (valinta muistuu laitteelle), leveä taulu vierittyy sormella omassa kotelossaan ja nimisarake jää paikalleen; sivu 2 Luvut. Raamattu-lehteen palasivat työhuoneen generoidut taulut "Aarteet taulukkona" ja "Pelit taulukkona". Lukijaääni-ikkunaan lisättiin Voimakkuus-liuku (oli vain työhuoneessa). Tarkista pariin tuttuun: Eurooppa/Suomi/Tampere',
  'v859 — aarteenpaljastus: vanha kääntyvä seepialaatta sädeviivoineen on poistettu kokonaan, kaikki paljastukset ovat nyt samaa uutta korttia (kuva nousee mustasta, tekstit ympärille). Testaa uusi peli → ensimmäinen laatta: aarre paljastuu generoidulla kuvalla ja PÖLLÖ heti perässä omalla muotokuvallaan (assets/tietaja/viisas-pollo.jpg — generoidaan avaimella viisas-pollo, tools/generoi-tietaja-avatarit.mjs; ilman tiedostoa kortti näyttää pelkän tekstin). Pöllön esittelyteksti on uusi (kalevalainen kehys). Kuvattomat laatat (tyhjä, rosvo, hevosenkenkä) ja aloitusnäytön lauta näyttävät kortin PELKKINÄ TEKSTEINÄ — niiltä puuttuu vielä generoitu kuva',
  'v858 — vuosisään ylin/alin-vaihteluvyöhyke kaikissa 75 kaupungissa — avaa esim. Rovaniemen (pakkaskaista) ja Firenzen sääkortit',
  'v857 — pro-sisällöntuottajat (vaihe 1): aja ensin Actions → "Lukijoiden ehdotukset: julkaise worker" uudelleen (uudet pro-reitit; ei uusia salaisuuksia). Sen jälkeen: työhuoneen Lukijoilta-lehden LOPUSSA on pro-osio — "Lisää pro-tuottaja" kysyy sähköpostin ja näyttää 8 merkin koodin (pysyvä, kopioi talteen); pelissä palautelomakkeen osio "Olen pro-sisällöntuottaja" ottaa saman sähköpostin ja koodin, avaa profiilinäkymän (oma kuva, esittely, 1–3 linkkiä) ja lähetyksen jälkeen sanoo "odottaa julkaisua"; työhuoneessa tuottajan sivulla näkyy profiili ja kuva sekä napit Julkaise / Hylkää. Lupapohja tuottajalle: docs/pro-lisenssilupa.md. Tekijäsivu pelissä avautuu vasta kun jonkin kuvan riville lisätään kentät tekija ja tekijaId — yhdelläkään kuvalla ei ole niitä vielä',
  'v856 — pöllö löytyy ensimmäisestä laatasta: aloita uusi peli — alapalkissa ei pöllöä, ensimmäinen käännetty laatta paljastaa pöllön omana aarteenaan (laatan oma sisältö säilyy), nappi ilmestyy ja jonoon kertyneet tietäjäonnittelut purkautuvat; vanha tallennus ei menetä pöllöä',
  'v855 — tietäjätasot ja matkalaukku: linssit VAIN laukussa (Varusteet-osasto, hampurilaisesta pois) — testaa kytkentä päälle ja pois; laukussa uusi tietäjärivi pöllökuvakkeineen ("Untuvikko · 60 tp") ja rivit avatut aarteet / käydyt kaupungit / käydyt maat; otsikko ja alkuteksti poistettu ja tavarat kolmessa sarakkeessa; hampurilaisessa vain äänet + leveät napit "uusi peli" ja "ehdota sisältöä"; pöllö onnittelee tason noususta (40 tp Utelias kulkija tulee vastaan nopeasti)',
  'v854 — ehdotuskanava AUKI: hampurilaisen alarivillä tekstinapit uusi ja ehdota (sääntönappi pois); ehdota-napista voi lähettää kuvia ja juttuideoita — testaa lähetys ja katso että se näkyy työhuoneen Lukijoilta-lehdellä (avain kysytään kerran)',
  'v853 — Lukijoiden ehdotukset (vaihe 1): kanava on vielä piilossa, koska EHDOTUS_OSOITE on tyhjä. Käyttöönotto: aseta salaisuudet CLOUDFLARE_API_TOKEN, EHDOTUS_AVAIN (+ valinnainen EHDOTUS_BUCKET), aja Actions → "Lukijoiden ehdotukset: julkaise worker", kerro workerin osoite Fablelle. Sen jälkeen testattavaa: palautelomakkeen "Ehdota lehteen" -osio, hampurilaisvalikon Lukijoilta-lehti (kysyy avaimen kerran) ja pöllön kupla 10 min pelaamisen jälkeen',
  'v852 — Flickr-valokuvat Tokion, Soulin ja Shanghain lehtiin (29 kpl): avaa kaikki kolme lehteä — etusivun avauskuvakaruselli on uusi (Shanghaissa yksi kuva, ei nuolia), kansikuvien pikkurivi näyttää nyt kaksi ja loput ovat suurennoksen sarjassa. Oppaan jaksot: Tokio (Perille ja liikkeelle, Torikuja radan alla, Katu jolla myydään muoviruokaa, Temppelin katu ja joki), Soul (Perille ja liikkeelle, Torilla syödään seisten, Viisi palatsia), Shanghai (Perille ja liikkeelle, Puutarha, Pieni kori höyryä, Vastaranta). Tarkista että kuvat latautuvat, tekijä + lisenssi näkyvät joka kuvatekstissä ja että Soulin avauskuvan (metsäinen kukkula) suurennos on SAMA rajaus kuin sivulla — se on rajattu jättipanoraamasta',
  'v851 — iPad: lippuikkunan tarkennustila (esim. Ranska, vaakuna suurennettuna): sumennettu sisältö leikkautuu nyt kortin pyöristyksen SISÄÄN eikä sen yli; testaa myös pitkän kortin (Saksa) vieritys sormella',
  'v850 — Raamatun Lukijoiden ehdotukset -osioon palkkiolinjaus: läpäissyt ehdotus palkitaan pelirahalla lunastuskoodilla, omistaja päättää summan',
  'v849 — Raamatussa uusi Lukijoiden ehdotukset -osio (kehittäjän liitteet): pelaajien kuva- ja juttuideakanavan linjaus',
  'v848 — iPad: lehden kansikarusellin napautus ei jätä enää vaaleaa harsoa kuvan laitaan (nuolinapin hover-tausta) — testaa Pariisin kansi: napauta oikeaa laitaa ja katso jääkö kuvan päälle vaalea kaista',
  'v847 — neljä uusittua miniatyyriä kartalla: Tampereen tuomiokirkko, Tripolin riemukaari ja Punainen linna, Tokion Shitamachi-museo — kaikilla kohteilla on nyt piirros',
  'v846 — Flickr-valokuvat Tampereen ja Firenzen lehtiin (19 kpl): avaa molemmat lehdet — avauskuvakaruselli, kansikuvien suurennos ja Matkailijan oppaan jaksot (Koski ja punatiili, Mustamakkara ja torit, Ilta / Perille ja jalkapatikkaan, Museot yhtenä päivänä, Torilla ja pöydässä, Ilta); tarkista että kuvat latautuvat ja tekijä + lisenssi näkyvät joka kuvatekstissä',
  'v845 — Raamatun Kuvat ja lähteet -osiossa uusi linjaus: kaikki sisältö ämpäristä (R2-peili), uusi lähde vasta kun peilausputki kattaa sen; kuvalähdelista päivitetty (Commons, Finna, LoC, Flickr)',
  'v844 — kohdekarttojen miniatyyripiirrokset kahdeksaan uuteen kaupunkiin: Tampere, Firenze, Bagdad, Teheran, Tripoli, Tokio, Soul ja Shanghai — tarkista että piirros näkyy kartalla numeroympyrän tilalla; neljä kohdetta jäi vielä ilman piirrosta (Tampereen tuomiokirkko, Marcus Aureliuksen riemukaari, Punainen linna, Shitamachi-museo)',
  'v843 — lippuikkuna (esim. Soul): iso lippu terävä myös iPadilla (haetaan nyt 1280 px:n kuvana), ja tunnus/versiolippu suurennettuna pysyy kortin sisällä selitteineen — ei enää katkeavaa kuvatekstiä alareunassa',
  'v842 — kuvakarusellien laitojen tummennus poistettu kaikkialta (lehden kansikuva, nostogalleria, nähtävyysjutut, opas) — tarkista että nuoli erottuu yhä vaalealla ja tummalla kuvalla; lisäksi lehden ja jutun alareunan sumea kaista kotipalkin yli iPadilla',
  'v841 — syvä lähikuva (maailmankartta) terävöityy heti zoomin jälkeen — kokeile nopeaa zoomailua syvällä zoomilla',
  'v840 — iPad: Firenzen Matkailijan opas — karussellikuvan yläpuolella ollut tumma palkki pois; tarkista myös alareunan kuvateksti ja lähderivi taustapaluun jälkeen',
  'v839 — zoomaile nopeasti sisään/ulos ja lopeta: kartta tarkentuu nyt parissa sekunnissa eikä jätä sumeita laikkuja',
  'v838 — kolme turhaa suoraa reittiä pois (Helsinki–Rovaniemi, Granada–Lissabon, Addis Abeba–Suakin) — ketjut uusien kaupunkien kautta',
  'v837 — iPad: kartta ei enää bugaa taustapaluussa (vaalea kaista, jäätynyt piirto) — testaa: raahaa karttaa, vaihda appia sormi pohjassa, palaa',
  'v836 — E00 2/2: Tokion, Soulin ja Shanghain kohdekartat ja kohteet — koko kuusikko valmis, tarkista pelissä',
  'v835 — E00 1/2: Bagdadin, Teheranin ja Tripolin kohdekartat ja kohteet (avaa lehdet ja kartat pelissä — omistaja tarkistaa suoraan pelistä)',
  'v834 — iPhone: lehti täyttää ruudun alas asti (sumennettu alakaista pois) — testaa myös taustapaluun jälkeen',
  'v833 — 11 uutta kaupunkia laudoilla ja maailmankartalla (Kioto, Varanasi, Mandalay, Kanton, Sevilla, Bergen, Fès, Lalibela, Sitka, Ouro Preto, Dunedin) — pisteet, reitit, visat ja kuvakortit; ei vielä lehtiä',
  'v832 — Firenze Euroopan laudalla lehtineen (avaa lehti: kansi, Kuvataide-sivu, opas, kohdekartta)',
  'v831 — Tampere Euroopan laudalla lehtineen (avaa lehti!); Lappi on nyt Rovaniemi (lehti vielä vanha Lappi-lehti)',
  'v830 — LAITETESTI iPad/iPhone: kartan eleet (raahaus, liuku, nipistys, rullazoom) toimivat kuten ennen',
  'v829 — kartta toimii kuten ennen (kamera omaksi moduulikseen): zoomi, panorointi, mannerzoom, lähikuvat',
  'v828 — taustapaperi ei näy enää millään ikkunamuodolla (kokeile kapea pysty- ja matala vaakaikkuna aloituskartalla ja mantereilla)',
  'v827 — Raamatun Karttalinssit-osiossa aikajana-ajo ja lavalinssi; Moduulit-osiossa M7+-hyväksyntä',
  'v826 — docs-siivous: Raamatussa Venäjä/Kabul- ja yksi otto -linjaukset; kaksi dokumenttia arkistoon',
  'v825 — Raamatun uusi Poistetut ideat -osio (kehittäjän liitteet): neljä riviä, pääosiot siistitty',
  'v824 — lehdet toimivat kuten ennen (tila koottu yhteen olioon); pöllön nähtävyyslinkki avaa taas jutun',
  'v823 — Islanti kartalla paikallaan; sääosion luonnehdinta joka kaupungissa (avaa muutama lehti); Bagdad+Teheran hintataso',
  'v822 — tuotantosuunnitelma (docs/tuotantosuunnitelma.md): lue ja päätä',
  'v821 — remontti valmis: luenta+visa moduuleiksi, ui.js -37 %',
  'v820 — remontti M5c: maalehti moduuliksi',
  'v819 — remontti M5b: kuvataitto+sää+uutiset lehteen',
  'v818 — remontti M5a: lehden sivukoneisto moduuliksi',
  'v817 — remontti M4: opas+nähtävyydet moduuleiksi',
  'v816 — Matkailijan Tokio, Soul, Shanghai ja Tripoli (O6 valmis)',
  'v815 — remontti M3: liput, karttazoom, vertailu moduuleiksi',
  'v814 — remontti M2: UI:n apurit omaan moduuliin',
  'v813 — remontti M1: sisältötaulut omaan moduuliin',
  'v812 — miniatyyrityökaluun hybridimalli (ei nakyvia muutoksia)',
  'v811 — Raamatussa: uusiin kohteisiin vain lehdet, ei kaarta',
  'v810 — opas: Matkakassa pois, hintatasorivit; 5 säänluonnehdintaa',
  'v809 — Raamatussa: oppaan avauskuva = karuselli jakson tekstistä',
  'v808 — remonttisuunnitelmat mainissa (docs/moduulirakenne + docs-remontti)',
  'v807 — Raamatussa: ei Matkakassaa; työlistassa paketti O5',
  'v806 — Raamatussa: maalehden nimiö, Matkailijalle-kuvan kaava',
  'v805 — Matkailijan Teheran: toinen kuudesta',
  'v804 — Matkailijan Bagdad: ensimmäinen kuudesta uudesta',
  'v803 — kaiuttimen kuvake otsikon kokoiseksi kohdekortissa',
  'v802 — lehden alanapit kotipalkin yläpuolelle iPadilla',
  'v801 — kohdekortti: kaiutin otsikon perään, 5/6 pois',
  'v800 — etusivun avausteksti pergamentille, ei tummalle',
  'v799 — arkin alalaidan napit takaisin ruudulle iPadilla',
  'v798 — pöllön kuvat aukeavat isoina myös isolla ruudulla',
  'v797 — oppaan otsikko esiin: iPhone ja iPad, yläreuna',
  'v796 — viiden oppaan avauskuva kolmen kuvan karuselliksi',
  'v795 — Helsingin etusivulle Uspenskin katedraali',
  'v794 — Wien, Rooma ja Kööpenhamina: pystykuva etusivulle',
  'v793 — Orsayn museo saa piirroksen Pariisin kartalle',
  'v792 — Pariisin kartalle piirrokset: ooppera ja Place des Vosges',
  'v791 — Berliini pystykuva; alanapit iPadilla; isompi pystykuva',
  'v790 — Lontoo: Big Ben etusivulle, 3 kuvan karuselli oppaaseen',
  'v789 — iPad-jumi: kartta ja alanapit palaavat app-vaihdosta',
  'v788 — Pariisissa 11 kohdetta; sää kaikissa 70 kaupungissa',
  'v787 — lippu maan otsikkoon, Eiffel etusivulle Pariisiin',
  'v786 — opas 5 kaupunkiin: tsekkaa ennen koko Euroopan ajoa',
  'v785 — sääennuste 32 lehteen, maasivun nimiö, oppaan graafi',
  'v784 — iPad: käy toisessa apissa ja palaa; alanapit paikallaan',
  'v783 — säägraafi elää, Seinen karuselli, paperi ehyt',
  'v782 — opas 2.2: kainalotaulu (napauta rivejä), säägraafi',
  'v781 — nauha koko osion yli, leveämpi, pehmeämmät värit',
  'v780 — opas 2.1: kainalot, uusi paletti, iso otsikko, lämmin kuva',
  'v779 — etusivulla yksi diagonaalinauha: Matkaopas',
  'v778 — Matkailijalle-kuvateksti napakaksi (7 kaupunkia)',
  'v777 — Matkailijalle: kyltti kuvan kulmassa, Lue lisää -linkki',
  'v776 — Pariisin opas 2.0: jaksot, sää, hinnat, linkit, lappu',
  'v775 — äänet poistettu repostä: luennat + taustat R2:sta',
  'v774 — äänet R2:sta; asennus kevenee 180 Mt (testaa äänet!)',
  'v773 — Maxin työlista huomiselle (moduulit + docs-remontti)',
  'v772 — Raamatussa: äänet R2, oppaan ilme, speksioppi, remontti',
  'v771 — Pariisin etusivukuvat: tsekkaa ja hyväksy monistus',
  'v770 — Raamatussa etusivukuvien kaava (Kuvat ja lähteet)',
  'v769 — karttatekstin loppu: piirroskarttojen oma ohje',
  'v768 — Matkailijalle 5 kaupunkiin (Berliini, Pariisi, Lontoo, Rooma, Wien)',
  'v767 — vaakunan ajoittainen tumma laatikko: pitäisi olla poissa',
  'v766 — opas: otsikko VIHDOIN näkyviin; kuvat tekstin lomaan',
  'v765 — Köpiksen uusilla kohteilla piirrokset kartalla',
  'v764 — Köpiksen kartalla 9 kohdetta (uudet: 7–9, ympyröinä)',
  'v763 — vaakuna isona ilman laatikkoa; liput paikallaan',
  'v762 — jutun otsikko: vahti pitää yläreunan paikallaan',
  'v761 — työhuoneessa vain palkit, tekstirivit pois',
  'v760 — tarkennettu vaakuna pergamenttilevyllä, ei tummaa',
  'v759 — jutun otsikko pysyy näkyvissä kuvan latautuessa',
  'v758 — työhuoneen palkit: pitäisi VIHDOIN näyttää luvut',
  'v757 — jutun napit kortissa kiinni; leveys kestää appivaihdon',
  'v756 — opas leveämpi iPadilla; ☰ pois oppaan yläkulmasta',
  'v755 — tyhjät palkit: sulje valikko ja avaa uudelleen',
  'v754 — kulurivi kertoo lähdevirheen; avaa valikko uudelleen',
  'v753 — Helsingin Matkailijalle: kappale, kuva, opas',
  'v751 — lippusivut: Kaakkois- ja Etelä-Aasia (10 maata)',
  'v750 — paluunuoli Engel-jutusta; kulurivin oikea syy',
  'v749 — karttateksti 2 palstaan; Matkailijalle- ja opaskuvat',
  'v748 — ison piirroksen klikki: vain kuvan keskiosa avaa',
  'v747 — lippusivut: Lähi-itä (8 maata)',
  'v746 — avauskuvat 4 kaupunkiin; R2 molemmat ämpärit; kulunimiö',
  'v745 — etusivun karuselli koko palstan levyinen',
  'v744 — R2-palkki megatavuina; Eleven-lukema tiiviiksi',
  'v743 — pöllön kuva: ei enää kaimakyliä; epävarmana ei kuvaa',
  'v742 — lukija seis joka pop-upista (kartta, maalehti, pöllö)',
  'v741 — Mac-Safari: striimiluennan ääni (testaa Macilla!)',
  'v740 — Työhuone: palkit, tyylinapit, Lukijaääni',
  'v739 — piirros juttuun; klikkausalue 80 %',
  'v738 — Kööpenhamina-lehti: karuselli + Matkailijalle',
  'v737 — 6 uutta karttaa; piirrokset terävinä; lippuanimaatio',
  'v736 — vain värikartta; numero kylttiin',
  'v735 — suurennos keskitetty, 75 %; kyltti kiinni',
  'v734 — kartta 70 %; kyltti tiiviimmin; lippu ilman laatikkoa',
  'v733 — lippusivut: Aasia (8 maata)',
  'v732 — suurennos 65 %; kyltti kiinni rakennukseen',
  'v731 — lippusivut: Slovenia–Azerbaidžan (6 maata)',
  'v730 — lippuikkunan tarkennus + sumennus; kartta 40 %',
  'v729 — lippusivut: Itä-Eurooppa + Balkan (9 maata)',
  'v728 — suurennos ¼ kartasta; kyltistä juttuun; vipunapin teksti',
  'v727 — lippusivut: Länsi-Eurooppa (8 maata)',
  'v726 — lippusivut: Pohjoismaat + Baltia (7 maata)',
  'v725 — lippuikkunan iso kuva reunasta reunaan',
  'v724 — piirrokset skaalautuvat zoomissa; peruskoko 40 px',
  'v723 — kultaneliön OIKEA syy: hover-korostus; koko 4×',
  'v722 — piirrokset PNG:inä: neliö varmasti pois',
  'v721 — iOS-neliö pois suurennoksesta; koko 3,5×',
  'v720 — piirroksen suurennos 3×',
  'v719 — piirroksen klikkaus vain suurentaa, ei ikkunaa',
  'v718 — piirrokset pienempinä, nuolet pois',
  'v717 — piirrokset yksivärisinä luonnoksina',
  'v716 — lippuikkuna: 2/3-korkeus, symboliikka, vaakunat',
  'v715 — piirrokset hajallaan + nuolet; klikkaus: kyltti → juttu',
  'v714 — kartan piirrokset leikattuina, numerot pois',
  'v713 — pöllön kuvalle paikanpitäjä + animaatio',
  'v712 — pöllön kuva löytyy myös hakusanalla',
  'v711 — lipusta lipun tarina (Saksa, Suomi)',
  'v710 — piirrokset pisteinä + kortit 4 kaupungissa',
  'v709 — värikartat: Helsinki, Pariisi, Lontoo',
  'v708 — Berliinin pisteet: piirroskortti + juttuun',
  'v707 — Berliinin värikartta (vipu kartalla)',
  'v706 — Raamatun taitto: kappaleet, ei palstoja',
  'v704 — radio hiljenee pöllön/lukijan puhuessa',
  'v703 — pöllön vastauskuva; klikkaus isoksi',
  'v702 — oletusprompti näkyvissä; vuosiluvut ei lueta',
  'v701 — Raamattu tiiviinä + valmis/kesken-tagit',
  'v699 — nähtävyysjutut: Panthéon, Luco, Kallio, Lintsi',
  'v697 — Kehittäjä-valikko: Raamattu- ja Tilannelehti',
  'v695/v696 — esipuskurit; reunuskartat 4 kaupunkia',
  'v694 — ElevenLabs-äänitteet takaisin merkintöihin',
  'v692 — taustaäänet tasattu; v691 Venäjän radio',
  'v683–v687 — lukijan automoodi, otsikkotauot, väistö',
];
