import { readFileSync, existsSync } from 'node:fs';
import http from 'node:http';
import { extname, join } from 'node:path';
import { Game } from '/home/user/Matkakirja/js/game.js';
import { packById } from '/home/user/Matkakirja/js/pack.js';
const paketti = await import('playwright').catch(() => import('/opt/node22/lib/node_modules/playwright/index.js'));
const chromium = paketti.chromium ?? paketti.default?.chromium;
const JUURI = '/home/user/Matkakirja/';
const TYYPIT = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml', '.png': 'image/png', '.webp': 'image/webp', '.jpg': 'image/jpeg', '.geojson': 'application/json' };
const palvelin = http.createServer((req, res) => { const polku = join(JUURI, req.url.split('?')[0] === '/' ? 'index.html' : req.url.split('?')[0]); if (!existsSync(polku)) { res.writeHead(404); res.end(); return; } res.writeHead(200, { 'content-type': TYYPIT[extname(polku)] ?? 'application/octet-stream' }); res.end(readFileSync(polku)); });
await new Promise((ok) => palvelin.listen(0, ok));
const osoite = `http://localhost:${palvelin.address().port}/`;
const valimuisti = new Map();
async function haku(url) { if (valimuisti.has(url)) return valimuisti.get(url); const l = fetch(url).then(async (v) => (v.ok ? { status: 200, body: Buffer.from(await v.arrayBuffer()), tyyppi: v.headers.get('content-type') } : { status: v.status, body: Buffer.alloc(0), tyyppi: 'text/plain' })).catch(() => null); valimuisti.set(url, l); return l; }
const peli = new Game({ players: [{ name: 'Fogg', color: '#c9a227', start: 'pariisi' }], pack: packById('maailmankartta'), seed: 5 });
peli.phase = 'action'; peli.tokens.delete('pariisi');
const selain = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await selain.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: 'block' });
await ctx.addInitScript((d) => { try { localStorage.setItem('matkakirja-save-v1', d); localStorage.removeItem('matkakirja-lauta'); localStorage.setItem('matkakirja-kehittaja', '1'); } catch {} }, JSON.stringify(peli.toJSON()));
const sivu = await ctx.newPage();
await sivu.route('**samireivinen.workers.dev/**', (r) => r.abort());
await sivu.route(/wikimedia\.org/, (r) => r.abort());
await sivu.route(/media\.matkakirja\.app|r2\.dev\//, async (route) => { const v = await haku(route.request().url()); if (!v || v.status !== 200) { route.abort(); return; } route.fulfill({ status: 200, contentType: v.tyyppi ?? 'application/octet-stream', body: v.body, headers: { 'access-control-allow-origin': '*' } }); });
await sivu.goto(`${osoite}?lauta=pallo`, { waitUntil: 'domcontentloaded', timeout: 60000 });
await sivu.waitForFunction(() => window.matkakirja?.ui?.svg, null, { timeout: 90000 });
await sivu.waitForFunction(() => Boolean(window.matkakirja?.ui?.pallolauta), null, { timeout: 60000 });
await sivu.waitForTimeout(3000);
const ulos = await sivu.evaluate(async () => {
  const { avaaNostonTunnuksella } = await import('/js/fokusnosto.js');
  avaaNostonTunnuksella(window.matkakirja.ui, 'pariisin-72-nimea');
  await new Promise((v) => setTimeout(v, 400));
  document.querySelector('.fokusnosto-kortti .nostokuva-lisaa')?.click();
  await new Promise((v) => setTimeout(v, 600));
  const k = document.querySelector('.fokusnosto-kortti');
  return [...k.querySelectorAll('.fokusnosto-teksti p')].map((p) => p.textContent);
});
for (const [i, p] of ulos.entries()) console.log(`--- p${i} (${p.length}) ---\n${p}\n`);
await selain.close(); palvelin.close();
