/*
 * PELIN MAAKOODI (ISO3) → ISO 3166-1 alpha-2 (Siirtoseppä 23.9.2026).
 *
 * Natiivi 3D-proto (Unity) tarvitsee kaupungin maan ISO2-koodina
 * (3D-selvittäjä 23.9.2026). Lähde: Wikidata, P298 (alpha-3) → P297
 * (alpha-2), haettu 23.9.2026 niille koodeille, joita maailmankartan
 * kaupungeissa esiintyy. Linssiseppä 23.9.2026: lisäksi kaikki laudan
 * maat (countryShapes), joilla ei ole kaupunkia (18 maata ALB…TKM) —
 * kokoelmat maat ja maarajat saavat iso2:n tästä, ja natiivin vertailu-
 * ja maatietolinssi tarvitsee sen jokaiselle napautettavalle maalle.
 *
 * Poikkeus: peli käyttää Etelä-Sudanille omaa koodia SDS (standardi on
 * SSD), joten se on kirjattu käsin → SS. Uusi maa laudalla = uusi rivi;
 * tests/sisaltopaketti.test.mjs vaatii, että jokaisella kaupungin maalla
 * on rivi, ja samoin jokaisella laudan maalla. Jerusalemin maa on laudalla tarkoituksella tyhjä, joten sen
 * ISO2 on myös null.
 */
export const ISO2 = {
  AFG: 'AF',
  AGO: 'AO',
  ALB: 'AL',
  AND: 'AD',
  ARE: 'AE',
  ARG: 'AR',
  ARM: 'AM',
  AUS: 'AU',
  AUT: 'AT',
  AZE: 'AZ',
  BDI: 'BI',
  BEL: 'BE',
  BEN: 'BJ',
  BFA: 'BF',
  BGD: 'BD',
  BGR: 'BG',
  BHR: 'BH',
  BIH: 'BA',
  BLR: 'BY',
  BOL: 'BO',
  BRA: 'BR',
  BRN: 'BN',
  BTN: 'BT',
  BWA: 'BW',
  CAF: 'CF',
  CAN: 'CA',
  CHE: 'CH',
  CHL: 'CL',
  CHN: 'CN',
  CIV: 'CI',
  CMR: 'CM',
  COD: 'CD',
  COG: 'CG',
  COL: 'CO',
  COM: 'KM',
  CPV: 'CV',
  CUB: 'CU',
  CYP: 'CY',
  CZE: 'CZ',
  DEU: 'DE',
  DJI: 'DJ',
  DNK: 'DK',
  DZA: 'DZ',
  ECU: 'EC',
  EGY: 'EG',
  ERI: 'ER',
  ESP: 'ES',
  EST: 'EE',
  ETH: 'ET',
  FIN: 'FI',
  FJI: 'FJ',
  FRA: 'FR',
  GAB: 'GA',
  GBR: 'GB',
  GEO: 'GE',
  GHA: 'GH',
  GIN: 'GN',
  GMB: 'GM',
  GNB: 'GW',
  GNQ: 'GQ',
  GRC: 'GR',
  GRL: 'GL',
  GTM: 'GT',
  HKG: 'HK',
  HRV: 'HR',
  HUN: 'HU',
  IDN: 'ID',
  IND: 'IN',
  IRL: 'IE',
  IRN: 'IR',
  IRQ: 'IQ',
  ISL: 'IS',
  ISR: 'IL',
  ITA: 'IT',
  JOR: 'JO',
  JPN: 'JP',
  KAZ: 'KZ',
  KEN: 'KE',
  KGZ: 'KG',
  KHM: 'KH',
  KOR: 'KR',
  KWT: 'KW',
  LAO: 'LA',
  LBN: 'LB',
  LBR: 'LR',
  LBY: 'LY',
  LIE: 'LI',
  LKA: 'LK',
  LSO: 'LS',
  LTU: 'LT',
  LUX: 'LU',
  LVA: 'LV',
  MAR: 'MA',
  MCO: 'MC',
  MDA: 'MD',
  MDG: 'MG',
  MDV: 'MV',
  MEX: 'MX',
  MKD: 'MK',
  MLI: 'ML',
  MLT: 'MT',
  MMR: 'MM',
  MNE: 'ME',
  MNG: 'MN',
  MOZ: 'MZ',
  MRT: 'MR',
  MUS: 'MU',
  MWI: 'MW',
  MYS: 'MY',
  NAM: 'NA',
  NER: 'NE',
  NGA: 'NG',
  NIC: 'NI',
  NLD: 'NL',
  NOR: 'NO',
  NPL: 'NP',
  NZL: 'NZ',
  OMN: 'OM',
  PAK: 'PK',
  PAN: 'PA',
  PER: 'PE',
  PHL: 'PH',
  PNG: 'PG',
  POL: 'PL',
  PRK: 'KP',
  PRT: 'PT',
  PRY: 'PY',
  PSE: 'PS',
  QAT: 'QA',
  ROU: 'RO',
  RUS: 'RU',
  RWA: 'RW',
  SAU: 'SA',
  SDN: 'SD',
  SDS: 'SS',
  SEN: 'SN',
  SGP: 'SG',
  SHN: 'SH',
  SLB: 'SB',
  SLE: 'SL',
  SMR: 'SM',
  SOM: 'SO',
  SRB: 'RS',
  STP: 'ST',
  SVK: 'SK',
  SVN: 'SI',
  SWE: 'SE',
  SWZ: 'SZ',
  SYC: 'SC',
  SYR: 'SY',
  TCD: 'TD',
  TGO: 'TG',
  THA: 'TH',
  TJK: 'TJ',
  TKM: 'TM',
  TLS: 'TL',
  TUN: 'TN',
  TUR: 'TR',
  TWN: 'TW',
  TZA: 'TZ',
  UGA: 'UG',
  UKR: 'UA',
  URY: 'UY',
  USA: 'US',
  UZB: 'UZ',
  VAT: 'VA',
  VEN: 'VE',
  VNM: 'VN',
  VUT: 'VU',
  YEM: 'YE',
  ZAF: 'ZA',
  ZMB: 'ZM',
  ZWE: 'ZW',
};
