/*
 * PELIN MAAKOODI (ISO3) → ISO 3166-1 alpha-2 (Siirtoseppä 23.9.2026).
 *
 * Natiivi 3D-proto (Unity) tarvitsee kaupungin maan ISO2-koodina
 * (3D-selvittäjä 23.9.2026). Lähde: Wikidata, P298 (alpha-3) → P297
 * (alpha-2), haettu 23.9.2026 niille koodeille, joita maailmankartan
 * kaupungeissa esiintyy.
 *
 * Poikkeus: peli käyttää Etelä-Sudanille omaa koodia SDS (standardi on
 * SSD), joten se on kirjattu käsin → SS. Uusi maa laudalla = uusi rivi;
 * tests/sisaltopaketti.test.mjs vaatii, että jokaisella kaupungin maalla
 * on rivi. Jerusalemin maa on laudalla tarkoituksella tyhjä, joten sen
 * ISO2 on myös null.
 */
export const ISO2 = {
  AFG: 'AF',
  AGO: 'AO',
  ARE: 'AE',
  ARG: 'AR',
  AUS: 'AU',
  AUT: 'AT',
  BEL: 'BE',
  BGR: 'BG',
  BIH: 'BA',
  BOL: 'BO',
  BRA: 'BR',
  CAN: 'CA',
  CHE: 'CH',
  CHL: 'CL',
  CHN: 'CN',
  CMR: 'CM',
  COD: 'CD',
  COL: 'CO',
  CUB: 'CU',
  CYP: 'CY',
  CZE: 'CZ',
  DEU: 'DE',
  DNK: 'DK',
  DZA: 'DZ',
  ECU: 'EC',
  EGY: 'EG',
  ESP: 'ES',
  EST: 'EE',
  ETH: 'ET',
  FIN: 'FI',
  FJI: 'FJ',
  FRA: 'FR',
  GBR: 'GB',
  GHA: 'GH',
  GRC: 'GR',
  GRL: 'GL',
  GTM: 'GT',
  HKG: 'HK',
  HRV: 'HR',
  HUN: 'HU',
  IDN: 'ID',
  IND: 'IN',
  IRL: 'IE',
  IRN: 'IR',
  IRQ: 'IQ',
  ISL: 'IS',
  ITA: 'IT',
  JOR: 'JO',
  JPN: 'JP',
  KAZ: 'KZ',
  KEN: 'KE',
  KOR: 'KR',
  KWT: 'KW',
  LBR: 'LR',
  LBY: 'LY',
  LKA: 'LK',
  LTU: 'LT',
  LUX: 'LU',
  LVA: 'LV',
  MAR: 'MA',
  MDG: 'MG',
  MEX: 'MX',
  MLI: 'ML',
  MLT: 'MT',
  MMR: 'MM',
  MNG: 'MN',
  MOZ: 'MZ',
  NAM: 'NA',
  NGA: 'NG',
  NIC: 'NI',
  NLD: 'NL',
  NOR: 'NO',
  NPL: 'NP',
  NZL: 'NZ',
  OMN: 'OM',
  PAK: 'PK',
  PAN: 'PA',
  PER: 'PE',
  PHL: 'PH',
  PNG: 'PG',
  POL: 'PL',
  PRT: 'PT',
  PRY: 'PY',
  QAT: 'QA',
  ROU: 'RO',
  RUS: 'RU',
  SAU: 'SA',
  SDN: 'SD',
  SDS: 'SS',
  SEN: 'SN',
  SGP: 'SG',
  SHN: 'SH',
  SLB: 'SB',
  SLE: 'SL',
  SOM: 'SO',
  SVK: 'SK',
  SVN: 'SI',
  SWE: 'SE',
  SYR: 'SY',
  TCD: 'TD',
  THA: 'TH',
  TLS: 'TL',
  TUN: 'TN',
  TUR: 'TR',
  TWN: 'TW',
  TZA: 'TZ',
  UGA: 'UG',
  UKR: 'UA',
  URY: 'UY',
  USA: 'US',
  UZB: 'UZ',
  VEN: 'VE',
  VNM: 'VN',
  VUT: 'VU',
  YEM: 'YE',
  ZAF: 'ZA',
  ZWE: 'ZW',
};
