/*
 * OMAT KOHTEET (omistaja 7.10.2026 08.4x: "tehdään Egypti kokeeksi loppuun omilla Blender-malleilla"; LS1/Päätoimittaja):
 * kohde, jolla on pelin omat 3D-mallit (Linnanrakentaja) eikä Googlen 3D:tä. Kohdelista, kierroksen järjestys ja
 * esigeneroitu kerronta (Opus-kirjoittaja + -tarkistaja, tools/opas/tarkista-esittely.mjs) ovat tässä koodissa; worker
 * tarjoaa ne kuten lukitun kaupungin listan ja valmiin esittelyn (valmis: true).
 *   kohde = { id (Q), nimi, lat, lon, koko_m, korkeus_m?, luokka, kuvaus, teksti, lyhyt, syventava, puhe_teksti?, puhe_lyhyt? }
 */
export const OPAS_OMAT = Object.freeze({
  giza: {
    nimi: 'Gizan pyramidit',
    kokeilu: true,   // vain otsakkeella x-matkakirja-kokeilu: giza (Päätoimittaja 7.10. 08.5x)
    // Pienin kameran kierto (omistaja 8.10., opas.js pieninKiertoReitti): Sfinksi → Kheops → Khefren → Mykerinos
    // (kierto 363° → 189°, matka 2,1 → 1,5 km; aiemmin LS1: Sfinksi → Khefren → Mykerinos → Kheops).
    kierros: ['Q130958', 'Q37200', 'Q208358', 'Q238623'],
    // Kerronta: Opus-kirjoittaja + -tarkistaja 7.10. (lähteet ja muutokset proto-3d/_tyo/opas-esittely/korjattu/giza*).
    kohteet: [
      {"id":"Q130958","nimi":"Gizan suuri sfinksi","lat":29.97528,"lon":31.13778,"koko_m":73,"korkeus_m":20,"luokka":"muu","kuvaus":"Kallioon veistetty ihmispäinen leijona","teksti":"Gizan suuri sfinksi makaa pyramidien edustalla kaivannossa, sillä se on veistetty suoraan tasangon kalkkikivikalliosta louhimalla kivi sen ympäriltä pois. Leijonanruumis on seitsemänkymmentäkolme metriä pitkä, ja ihmiskasvot katsovat itään kohti nousevaa aurinkoa ja Gizan kaupunkia, joka alkaa heti muinaisalueen laidalta. Kasvojen uskotaan esittävän faarao Khefreniä tai hänen isäänsä Kheopsia, mutta tutkijat eivät ole asiasta yksimielisiä. Nenää eivät tuhonneet Napoleonin sotilaat tykinkuulilla, kuten usein kerrotaan, sillä se oli vaurioitunut jo 900-luvulla. Kasvoissa näkyy yhä jälkiä pitkistä tangoista tai taltoista, joilla nenä väännettiin irti.","lyhyt":"Gizan suuren sfinksin etutassujen välissä on graniittinen unisteela. Sen mukaan nuori prinssi Thutmosis nukahti metsästysretkellä sfinksin varjoon, ja unessa sfinksi lupasi hänelle kuninkuuden, jos hän kaivaisi sen esiin hiekasta. Prinssistä tuli faarao Thutmosis neljäs, joka pystytti steelan ensimmäisenä hallitusvuotenaan.","syventava":"Kuka hakkasi sfinksin nenän irti?"},
      {"id":"Q208358","nimi":"Khefrenin pyramidi","lat":29.97611,"lon":31.13083,"koko_m":215,"korkeus_m":136,"luokka":"rakennus","kuvaus":"Gizan toiseksi suurin pyramidi","teksti":"Khefrenin pyramidin huippua peittää yhä osa alkuperäisestä kalkkikivipäällysteestä, joka erottuu ylhäältä porrastuneiden kylkien yllä sileänä lakkina. Maasta katsottuna pyramidi näyttää Kheopsin pyramidia korkeammalta, vaikka se on hieman matalampi, sillä se seisoo kymmenen metriä korkeammalla kalliolla ja sen kyljet nousevat jyrkemmin. Alkuperäisen sisäänkäynnin löysi vuonna 1818 italialainen Giovanni Belzoni, joka oli aiemmin esiintynyt voimamiehenä Lontoon markkinoilla. Hautakammiossa oli vain avoin sarkofagi ja sen rikkoutunut kansi, ja Belzoni kirjoitti kammion seinään nimensä ja päivämäärän, jotka näkyvät siellä yhä.","lyhyt":"Khefrenin pyramidilta laskeutuu lähes puolen kilometrin pituinen pengertie laaksotemppeliin, joka on aivan sfinksin vieressä. Auguste Mariette löysi temppelistä 1800-luvulla Khefrenin istuvan patsaan, joka on veistetty tummasta ja erittäin kovasta kivestä. Siinä haukaksi kuvattu Horus-jumala suojaa siivillään faaraon päätä takaapäin.","syventava":"Kuka oli Giovanni Belzoni?"},
      {"id":"Q238623","nimi":"Mykerinoksen pyramidi","lat":29.9725,"lon":31.12833,"koko_m":104,"korkeus_m":61,"luokka":"rakennus","kuvaus":"Gizan suurista pyramideista pienin","teksti":"Mykerinoksen pyramidi on Gizan kolmesta suuresta pyramidista pienin, alun perin noin kuusikymmentäviisi metriä korkea. Sen alimmat kerrokset päällystettiin Asuanista tuodulla punaisella graniitilla, ja sisäänkäynnin vierellä moni lohko on yhä viimeistelemätön, luultavasti koska työ keskeytyi faaraon kuoltua. Pohjoiskyljen suuri pystysuora lovi on jäänne vuodelta 1196, jolloin Egyptin sulttaani al-Aziz Uthman, Saladinin poika, yritti purkaa pyramidit ja aloitti tästä. Työmiehet saivat irti enintään kiven tai kaksi päivässä, ja kahdeksan kuukauden kuluttua urakasta luovuttiin.","lyhyt":"Mykerinoksen pyramidin kaakkoispuolelta on kaivettu esiin pyramidien rakentajien kaupunki, jossa oli makuusaleja, leipomoita, panimoita ja jopa sairaala. Löytöjen mukaan rakentajat eivät olleet orjia vaan vuoroissa työskennelleitä työmiehiä, jotka saivat hyvää ruokaa ja kunnollisen haudan pyramidien lähellä.","syventava":"Missä Mykerinoksen sarkofagi on nyt?","puhe_teksti":"Mykerinoksen pyramidi on Gizan kolmesta suuresta pyramidista pienin, alun perin noin kuusikymmentäviisi metriä korkea. Sen alimmat kerrokset päällystettiin Asuanista tuodulla punaisella graniitilla, ja sisäänkäynnin vierellä moni lohko on yhä viimeistelemätön, luultavasti koska työ keskeytyi faaraon kuoltua. Pohjoiskyljen suuri pystysuora lovi on jäänne vuodelta 1196, jolloin Egyptin sulttaani al-Aziz Usman, Saladinin poika, yritti purkaa pyramidit ja aloitti tästä. Työmiehet saivat irti enintään kiven tai kaksi päivässä, ja kahdeksan kuukauden kuluttua urakasta luovuttiin."},
      {"id":"Q37200","nimi":"Kheopsin pyramidi","lat":29.97917,"lon":31.13417,"koko_m":230,"korkeus_m":139,"luokka":"rakennus","kuvaus":"Ainoa säilynyt antiikin maailmanihme","teksti":"Kheopsin pyramidi on Gizan pyramideista suurin ja vanhin, ja sen kyljet on suunnattu lähes täsmälleen pääilmansuuntiin. Alun perin se kohosi lähes sataviisikymmentä metriä ja oli liki neljätuhatta vuotta maailman korkein ihmisen rakentama rakennelma. Antiikin seitsemästä maailmanihmeestä se on ainoa yhä pystyssä oleva. Vuonna 2013 Punaisenmeren rannalta löytyivät tarkastaja Mererin lokikirjat, vanhimmat tunnetut kirjoitetut papyrukset. Niihin Merer kirjasi, miten hänen noin neljänkymmenen miehen joukkonsa kuljetti veneillä valkoista kalkkikiveä Turan louhoksilta Gizaan, luultavasti juuri tämän pyramidin päällysteeksi.","lyhyt":"Kheopsin pyramidin juurelta löytyi vuonna 1954 kallioon hakatusta, suljetusta kuopasta osiin purettu puulaiva, joka koottiin yli tuhannesta kahdestasadasta kappaleesta neljäkymmentäkolme metriä pitkäksi. Vuonna 2021 laiva siirrettiin noin kahden kilometrin päähän Suureen egyptiläiseen museoon, joka avattiin kokonaan vuonna 2025.","syventava":"Kuka oli tarkastaja Merer?"},
    ],
  },
});
