/*
 * COMMONS-KUVIEN TEKIJÄT JA LISENSSIT, JOITA PAKETEISSA EI OLE.
 *
 * Tuotettu: node tools/hae-commons-tekijat.mjs --kirjoita (Commonsin
 * extmetadata). Älä muokkaa käsin. Muoto: tiedostonimi → [tekijä,
 * lisenssi, lisenssiUrl]; tyhjä tekijä = tekijä tuntematon (PD).
 * Käyttö: js/tekijakortti.js taytaLahderivi täydentää lähderivin,
 * tools/kuvatekijat.mjs ja tests/kuvatekijat.test.mjs vartioivat.
 */
export const COMMONS_TEKIJAT = {
  "1896 Olympic opening ceremony.jpg": ["","Public domain",""],
  "2018 Aurora Yellowknife Canada.jpg": ["raymond22112376","Public domain",""],
  "A thousand miles in a dug-out; being the narrative of a journey of investigation among the red-skin Indians of Central Brazil (1911) (14798735293).jpg": ["Internet Archive Book Images","No restrictions","https://www.flickr.com/commons/usage/"],
  "Abdelkader Ibn Muhieddine (1808-1883).jpg": ["CINEFRICAMAG","Public domain",""],
  "Alessandro Volta. Gaetano Bonatti inc.jpg": ["Gaetano Bonatti","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Alexander's Column, St. Petersburg, Russia-LCCN2001697508.jpg": ["Photochrom Print Collection","Public domain",""],
  "AlfredNobel adjusted.jpg": ["Gösta Florman (1831–1900) / The Royal Library","Public domain",""],
  "Ampelmännchen go.jpg": ["Gorkaazk","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Amphitheatre Drakensberg.jpg": ["Bothar","Public domain",""],
  "Amu darya delta.jpg": ["Science and Analysis Laboratory ym.","Public domain",""],
  "Anders Beer Wilse - Edvard Grieg - NMK.2006.5769 - National Museum of Art, Architecture and Design.jpg": ["Anders Beer Wilse","Public domain",""],
  "Apple cases being loaded onto ships, Hobart Wharves, Tasmania (c1900s) (31995606893).jpg": ["Tasmanian Archive and Heritage Office Commons","No restrictions","https://www.flickr.com/commons/usage/"],
  "Athènes. L' Acropole et le Temple de Thesée LCCN2017658103.jpg": ["Photoglob Co., publisher","Public domain",""],
  "Aurel Vlaicu 1912 Cotroceni.jpg": ["","Public domain",""],
  "Australia.A2002231.0145.250m NASA Nullarbor.jpg": ["","Public domain",""],
  "Baghdad, the riverfront, looking north to the Old City from the right bank, near the British Embassy LOC matpc.13270.jpg": ["Matson Collection","Public domain",""],
  "Banya Bashi 1900.jpg": ["","Public domain",""],
  "Barbary lion.jpg": ["Fernandus (formerly of Biskra ym.","Public domain",""],
  "Barcelona. Fachada de la Catedral LCCN2017660376.jpg": ["Photoglob Co., publisher","Public domain",""],
  "Bartók Béla 1927.jpg": ["","Public domain",""],
  "Battle of alcacer quibir.jpg": ["","Public domain",""],
  "Battle of Lake Erie - painted by W.H. Powell. LCCN2007683561.jpg": ["Johnson & Miles ym.","Public domain",""],
  "Battle on the River Oxus (right).jpg": ["فارسی: کمال‌الدین بهزاد English: Bihzād","Public domain",""],
  "Beeld in de Bobolituinen in Florence No. 2958 Firenze R. Giardino di Boboli. La Dovizia (Tacca e Salvini) (titel op object), RP-F-2010-169.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Beijing ast 2007220 lrg.jpg": ["NASA","Public domain",""],
  "Berber flag.svg": ["Mysid","Public domain",""],
  "Berlin - Potsdamer Platz - um 1900.jpg": ["","Public domain",""],
  "Bicycles piled up outside a picture theatre in Cairns, ca. 1937 (4461930292).jpg": ["State Library of Queensland, Australia","No restrictions","https://www.flickr.com/commons/usage/"],
  "Big Bend Santa Elena Canyon 2006.JPG": ["Leaflet","Public domain",""],
  "Binnen in het Behouden Huys, 1596-1597, NG-1979-564-22.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Binnenplaats van het Palazzo Vecchio te Florence No. 1951 (serietitel), RP-F-00-263.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Boekenkist van Hugo de Groot, NG-KOG-1208.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Book of Ballymote 008r.jpg": ["","Public domain",""],
  "Budapest, M1 metró (kisföldalatti), Andrássy út.png": ["","Public domain",""],
  "Bull leaping minoan fresco archmus Heraklion.jpg": ["Jebulon","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Cape Town tram, Adderley Street - ca. 1900.jpg": ["","Public domain",""],
  "Car ferry crossing the Kasai River in Bandundu Region.jpg": ["Meditz ym.","Public domain",""],
  "Carl Benz circa 1920.jpg": ["","Public domain",""],
  "Carl Nielsen c. 1908.jpg": ["Georg Lindstrøm 1866-1923","Public domain",""],
  "Castle Geyser, Yellowstone National Park-LCCN2008678250.jpg": ["","Public domain",""],
  "Chad AMO 2004323 lrg.jpg": ["NASA","Public domain",""],
  "Charles IV.jpg": ["","Public domain",""],
  "Chaudiere Falls Ottawa (NBY 440517).jpg": ["","Public domain",""],
  "Church of St. Basil, Red Square Moscow LCCN2017660946.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Clouds surround the Galapagos Islands (MODIS 2020-09-21).jpg": ["MODIS Land Rapid Response Team, NASA GSFC","Public domain",""],
  "Cobblestone street in Riga, Latvia LCCN2012648280.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Codex Argenteus.jpg": ["","Public domain",""],
  "Constructing the Metropolitan Railway.jpg": ["Percy William Justyne","Public domain",""],
  "Courante uyt Italien, Duytslandt, &c. 1618-11-23.jpg": ["","Public domain",""],
  "Court of the Lions, Alhambra by Juan Laurent.jpg": ["Juan Laurent","Public domain",""],
  "De haven van Aden in Zuid Jemen Aden (titel op object), RP-F-00-5018-14.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "De Nijûbashi-brug bij het Edo-kasteel van Tokyo Nijûbashi (titel op object), RP-F-F01177-AC.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Delhi Aerial View, Satellite Image, India September 2003.jpg": ["NASA","Public domain",""],
  "Derribo de casas para la apertura de la Gran Vía - 1912.jpg": ["","Public domain",""],
  "Diamantsorteerders bij een mijn van De Beers in Kimberley, Zuid-Afrika Sorting the rough Diamonds, De Beers Mines, Kimberley, South Africa, RP-F-F09044.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "DIMendeleevCab.jpg": ["","Public domain",""],
  "DneproGES 1947.JPG": ["","Public domain",""],
  "E. C. Frome - First view of the salt desert - called Lake Torrens - Google Art Project.jpg": ["E. C. FROME (1802 - 1890) (Australia) Born in Gibraltar ym.","Public domain",""],
  "Edinburgh from the castle, Scotland, 1890s.jpg": ["Detroit Publishing Co., under license","Public domain",""],
  "Edward Lear - Kangchenjunga from Darjeeling - Google Art Project.jpg": ["Edward Lear","Public domain",""],
  "Eiffel Tower, full-view looking toward the Trocadero, Exposition Universal, 1900, Paris, France.jpg": ["","Public domain",""],
  "Elevador-Sta-Justa 1902 fotoCarris.jpg": ["","Public domain",""],
  "Emi Koussi.jpg": ["NASA","Public domain",""],
  "Entrance to castle, Prague, Bohemia, Austro-Hungary-LCCN2002708487.jpg": ["Photochrom Print Collection","Public domain",""],
  "Erwin Schrodinger.jpg": ["American Institute of Physics (AIP)","Attribution",""],
  "Escolta, Manila, P. I. LCCN2013646443.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Etna eruption seen from the International Space Station.jpg": ["NASA","Public domain",""],
  "Ever Given in Suez Canal viewed from ISS.jpg": ["NASA JSC ISS image library","Public domain",""],
  "Ferdinand von Zeppelin.jpg": ["","Public domain",""],
  "Fireman shostakovich.jpg": ["","Public domain",""],
  "Fishermen at Celilo Falls on the Columbia River (3229038197).jpg": ["OSU Special Collections & Archives","No restrictions","https://www.flickr.com/commons/usage/"],
  "Flag of Afghanistan (2013–2021).svg": ["","Public domain",""],
  "Flag of Afghanistan.svg": ["Taliban; vektori: Lexicon","Public domain",""],
  "Flag of Albania.svg": ["Sadik Kaceli","Public domain",""],
  "Flag of Algeria.svg": ["National Liberation Front of Algeria; vektori: SKopp","Public domain",""],
  "Flag of Angola.svg": ["Henrique de Carvalho Santos; vektori: SKopp","Public domain",""],
  "Flag of Argentina.svg": ["Manuel Belgrano","Public domain",""],
  "Flag of Armenia.svg": ["Stepan Malkhasyants; vektori: SKopp","Public domain",""],
  "Flag of Assyria.svg": ["Assyrian Congress","Public domain",""],
  "Flag of Australia.svg": ["Ivor Evans ym.","Public domain",""],
  "Flag of Austria.svg": ["Bundesministerium für Landesverteidigung","Public domain",""],
  "Flag of Azerbaijan.svg": ["SKopp and others","Public domain",""],
  "Flag of Bahrain.svg": ["SKopp, rewritten by Zscout370","Public domain",""],
  "Flag of Bali.svg": ["AnonyLog ym.","Public domain",""],
  "Flag of Bangladesh.svg": ["","Public domain",""],
  "Flag of Bashkortostan.svg": ["multiple Автор: Conscious","Public domain",""],
  "Flag of Belarus.svg": ["","Public domain",""],
  "Flag of Belgium (civil).svg": ["Dbenbenn","Public domain",""],
  "Flag of Bermuda.svg": ["Caleb Moore","Public domain",""],
  "Flag of Bhutan.svg": ["","Public domain",""],
  "Flag of Bolivia.svg": ["","Public domain",""],
  "Flag of Bosnia and Herzegovina.svg": ["Mladen Kolobarić","Public domain",""],
  "Flag of Brazil.svg": ["Raimundo Teixeira Mendes","Public domain",""],
  "Flag of Bulgaria.svg": ["SKopp","Public domain",""],
  "Flag of Cambodia.svg": ["","Public domain",""],
  "Flag of Cameroon.svg": ["(of code) -xfi","Public domain",""],
  "Flag of Canada.svg": ["George F. G. Stanley / E Pluribus Anthony / Mzajac","Public domain",""],
  "Flag of Catalonia.svg": ["Motoroil","Public domain",""],
  "Flag of Cebu Province.svg": ["IllationGroup2000","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Flag of Chad.svg": ["SKopp & others","Public domain",""],
  "Flag of Chile.svg": ["","Public domain",""],
  "Flag of Colombia.svg": ["","Public domain",""],
  "Flag of Croatia.svg": ["Nightstallion ym.","Public domain",""],
  "Flag of Cuba.svg": ["Miguel Teurbe Tolón and Narciso López","Public domain",""],
  "Flag of Cyprus.svg": ["Vzb83","Public domain",""],
  "Flag of Denmark.svg": ["Madden and others","Public domain",""],
  "Flag of East Timor.svg": ["","Public domain",""],
  "Flag of Ecuador.svg": ["Husunqu, Zscout370","Public domain",""],
  "Flag of Egypt.svg": ["","Public domain",""],
  "Flag of Estonia.svg": ["SKopp ym.","Public domain",""],
  "Flag of et-Võru.svg": ["","Public domain",""],
  "Flag of Ethiopia.svg": ["SKopp","Public domain",""],
  "Flag of Fiji.svg": ["Tessa Mackenzie","Public domain",""],
  "Flag of Finland.svg": ["","Public domain",""],
  "Flag of France.svg": ["vektori: SKopp","Public domain",""],
  "Flag of Friesland.svg": ["P.H. Wagemakers and Joh","Public domain",""],
  "Flag of Galicia.svg": ["Pedro A. Gracia Fajardo","Public domain",""],
  "Flag of Georgia.svg": ["MapGrid SKopp","Public domain",""],
  "Flag of Germany.svg": ["SKopp ym.","Public domain",""],
  "Flag of Ghana.svg": ["Theodosia Okoh","Public domain",""],
  "Flag of Greece.svg": ["","Public domain",""],
  "Flag of Greenland.svg": ["Jeffrey Connell (IceKarma)","Public domain",""],
  "Flag of Guatemala.svg": ["K21edgo","Public domain",""],
  "Flag of Haiti.svg": ["(colours and size changes of the now deleted versions) Madden ym.","Public domain",""],
  "Flag of Hong Kong.svg": ["Designed by Tao Ho SVG code of 24 November 2005 version copied","Public domain",""],
  "Flag of Hungary.svg": ["SKopp","Public domain",""],
  "Flag of Iceland.svg": ["Matthías Þórðarson; vektori: Árni Dagur and Magasjukur2","Public domain",""],
  "Flag of India.svg": ["Government of India","Public domain",""],
  "Flag of Indonesia.svg": ["Jayakatwang","Public domain",""],
  "Flag of Iran.svg": ["SVG file: SiBr4 Designer: Hamid Nadimi Construction: ISIRI","Public domain",""],
  "Flag of Iraq.svg": ["","Public domain",""],
  "Flag of Ireland.svg": ["Éire","Public domain",""],
  "Flag of Italy.svg": ["","Public domain",""],
  "Flag of Japan.svg": ["Various","Public domain",""],
  "Flag of Jeju Province.svg": ["Jeju Province Government","Public domain",""],
  "Flag of Jordan.svg": ["","Public domain",""],
  "Flag of Karakalpakstan.svg": ["No machine-readable author provided","Public domain",""],
  "Flag of Kazakhstan.svg": ["Shaken Niyazbekop","Public domain",""],
  "Flag of Kenya.svg": ["Pumbaa80","Public domain",""],
  "Flag of Kurdistan.svg": ["","Public domain",""],
  "Flag of Kuwait.svg": ["","Public domain",""],
  "Flag of Kyrgyzstan.svg": ["Shakiev N.T., Primov U.B","Public domain",""],
  "Flag of Laos.svg": ["SKopp","Public domain",""],
  "Flag of Latgale.svg": ["President of Latvia; vektori: Great Brightstar","Public domain",""],
  "Flag of Latvia.svg": ["Ansis Cīrulis; vektori: SKopp","Public domain",""],
  "Flag of Liberia.svg": ["Government of Liberia","Public domain",""],
  "Flag of Libya.svg": ["Various The SVG code is valid","Public domain",""],
  "Flag of Lithuania.svg": ["Jonas Basanavičius ym.","Public domain",""],
  "Flag of Luxembourg.svg": ["SKopp","Public domain",""],
  "Flag of Madagascar.svg": ["","Public domain",""],
  "Flag of Malaysia.svg": ["MapGrid (old version SKopp ym.","Public domain",""],
  "Flag of Mali.svg": ["SKopp","Public domain",""],
  "Flag of Malta.svg": ["","Public domain",""],
  "Flag of Mexico.svg": ["Omar Alejandro Covarrubias Neri ym.","Public domain",""],
  "Flag of Moldova.svg": ["Gheorghe Vrabie","Public domain",""],
  "Flag of Mongolia.svg": ["","Public domain",""],
  "Flag of Montenegro.svg": ["B1mbo ym.","Public domain",""],
  "Flag of Morocco.svg": ["Denelson83, Zscout370","Public domain",""],
  "Flag of Mozambique.svg": ["FRELIMO","Public domain",""],
  "Flag of Myanmar.svg": ["","Public domain",""],
  "Flag of Namibia.svg": ["Vzb83~commonswiki et al","Public domain",""],
  "Flag of Nepal.svg": ["Pumbaa80, Achim1999","Public domain",""],
  "Flag of New Caledonia.svg": ["Superbenjamin and authors of indicated files","Public domain",""],
  "Flag of New Zealand.svg": ["Albert Hastings Markham; vektori: Zscout370 ym.","Public domain",""],
  "Flag of Nicaragua.svg": ["C records","Public domain",""],
  "Flag of Nigeria.svg": ["Jon Harald Søby","Public domain",""],
  "Flag of Norfolk Island.svg": ["","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Flag of North Korea.svg": ["Zscout370","Public domain",""],
  "Flag of North Macedonia.svg": ["Gabbe","Public domain",""],
  "Flag of Norway.svg": ["Fredrik Meltzer; vektori: Gutten på Hemsen","Public domain",""],
  "Flag of Nunavut.svg": ["Kooma (original)","Public domain",""],
  "Flag of Occitania.svg": ["Nimlar","Public domain",""],
  "Flag of Okinawa Prefecture.svg": ["Wrightbus","Public domain",""],
  "Flag of Oman.svg": ["","OGL-om 1.0","https://www.oman.om/en/home-footer-level/faq/open-government-licence-oman"],
  "Flag of Pakistan.svg": ["Zscout370","Public domain",""],
  "Flag of Panama.svg": ["Zscout370 et al","Public domain",""],
  "Flag of Papua New Guinea.svg": ["Nightstallion","Public domain",""],
  "Flag of Paraguay.svg": ["Republica del Paraguay","Public domain",""],
  "Flag of Peru.svg": ["David Benbennick","Public domain",""],
  "Flag of Poland.svg": ["","Public domain",""],
  "Flag of Portugal.svg": ["Columbano Bordalo Pinheiro (1910; generic design); vektori: Vítor Luís Rodrigues; António Martins-Tuválkin","Public domain",""],
  "Flag of Puerto Rico.svg": ["vektori: Cerejota","Public domain",""],
  "Flag of Qatar.svg": ["","Public domain",""],
  "Flag of Quebec.svg": ["René Chaloult; vektori: Krun","Public domain",""],
  "Flag of Romania.svg": ["AdiJapan","Public domain",""],
  "Flag of Russia.svg": ["Peter the Great","Public domain",""],
  "Flag of Saint Helena.svg": ["Patricia Fidi","Public domain",""],
  "Flag of Samoa.svg": ["Malietoa Tanumafili II and Tupua Tamasese Meaʻole","Public domain",""],
  "Flag of Saudi Arabia.svg": ["The Shura Council","Public domain",""],
  "Flag of Scotland.svg": ["none known","Public domain",""],
  "Flag of Senegal.svg": ["Nightstallion","Public domain",""],
  "Flag of Serbia.svg": ["","Public domain",""],
  "Flag of Sierra Leone.svg": ["Zscout370","Public domain",""],
  "Flag of Sindh.svg": ["Baba66","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Flag of Singapore.svg": ["Government of Singapore; vektori: Zscout370","Public domain",""],
  "Flag of Slovakia.svg": ["Ladislav Čisárik and Ladislav Vrtel; vektori: SKopp","Public domain",""],
  "Flag of Slovenia.svg": ["Marko Pogačnik; vektori: Achim1999","Public domain",""],
  "Flag of Somalia.svg": ["","Public domain",""],
  "Flag of Sorbs.svg": ["Mysid","Public domain",""],
  "Flag of South Africa.svg": ["Wikimedia Commons users","Public domain",""],
  "Flag of South Korea.svg": ["Government of the Republic of Korea; vektori: Great Brightstar and others","Public domain",""],
  "Flag of South Sudan.svg": ["Achim1999","Public domain",""],
  "Flag of Spain.svg": ["RelShot 263 ym.","Public domain",""],
  "Flag of Sri Lanka.svg": ["Sri Lanka; vektori: Zscout370 ym.","Public domain",""],
  "Flag of Sudan.svg": ["","Public domain",""],
  "Flag of Sweden.svg": ["Jon Harald Søby and others","Public domain",""],
  "Flag of Switzerland.svg": ["vektori: Marc Mongenet Credits: -xfi- Zscout370","Public domain",""],
  "Flag of Syria (1980–2024).svg": ["","Public domain",""],
  "Flag of Syria.svg": ["Coup de crayon 2011)","Public domain",""],
  "Flag of Tajikistan.svg": ["","Public domain",""],
  "Flag of Tanzania.svg": ["","Public domain",""],
  "Flag of Tatarstan.svg": ["Urmas","Public domain",""],
  "Flag of Thailand.svg": ["Zscout370","Public domain",""],
  "Flag of the Crimean Tatar people.svg": ["Riwnodennyk","Public domain",""],
  "Flag of the Czech Republic.svg": ["Jaroslav Kursa","Public domain",""],
  "Flag of the Democratic Republic of the Congo.svg": ["Nightstallion","Public domain",""],
  "Flag of the Falkland Islands.svg": ["Government of the United Kingdom; vektori: Nightstallion and Echando una mano","Public domain",""],
  "Flag of the Faroe Islands.svg": ["It was made by IceKarma (Jeffrey Connell) ym.","Public domain",""],
  "Flag of the Mapuches (1992).svg": ["Huhsunqu","Public domain",""],
  "Flag of the Netherlands.svg": ["Zscout370","Public domain",""],
  "Flag of the People's Republic of China.svg": ["Zeng Liansong","Public domain",""],
  "Flag of the Philippines.svg": ["","Public domain",""],
  "Flag of the Republic of China.svg": ["Sun Yat-sen","Public domain",""],
  "Flag of the Romani people.svg": ["AdiJapan","Public domain",""],
  "Flag of the Solomon Islands.svg": ["SKopp","Public domain",""],
  "Flag of the United Arab Emirates.svg": ["Abdulla Mohammed Al Maainah","Public domain",""],
  "Flag of the United Kingdom.svg": ["Acts of Union 1800; vektori: Yaddah","Public domain",""],
  "Flag of the United States.svg": ["Uploaded by Dbenbenn; edited by users such as Zscout370 ym.","Public domain",""],
  "Flag of Tunisia.svg": ["Various Wikimedia Commons' contributors","Public domain",""],
  "Flag of Turkey.svg": ["David Benbennick (original author)","Public domain",""],
  "Flag of Turkmenistan.svg": ["","Public domain",""],
  "Flag of Uganda.svg": ["tobias","Public domain",""],
  "Flag of Ukraine.svg": ["Government of Ukraine","Public domain",""],
  "Flag of Upper Silesia.svg": ["Andrew J.Kurbiko","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Flag of Uruguay.svg": ["","Public domain",""],
  "Flag of Uzbekistan.svg": ["Farhod Yoʻldoshev","Public domain",""],
  "Flag of Vanuatu.svg": ["Kalontas Mahlon","Public domain",""],
  "Flag of Venezuela.svg": ["","Public domain",""],
  "Flag of Vietnam.svg": ["","Public domain",""],
  "Flag of Wales.svg": ["Tobias Jakobs","Public domain",""],
  "Flag of West Java.svg": ["Indonesian Government","Public domain",""],
  "Flag of Zimbabwe.svg": ["","Public domain",""],
  "Flateyjarbok Olaf Tryggvason.jpg": ["Gilwellian","Public domain",""],
  "Fort Colombo te Ceylon, gezien vanaf bolwerk De Beer (..) Casteel Colombo van de Beer (titel op object), RP-T-1902-A-4662.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Frankincense 2005-12-31.jpg": ["snotch","Public domain",""],
  "Fratelli Lumiere.jpg": ["","Public domain",""],
  "Full cheese fondue set - in Switzerland.JPG": ["EquatorialSky","Public domain",""],
  "Gamliel.jpg": ["","Public domain",""],
  "Garesadihafun.jpg": ["Governor of Italian Somaliland ym.","Public domain",""],
  "Gebouwen aan de kust van Aden in Jemen Aden. French & English consulates (titel op object), RP-F-00-5018-15.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "George Stephenson.jpg": ["John Lucas","Public domain",""],
  "Gezicht op Darling Street te Kaapstad, RP-F-F01156-J.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op de Berg Kameroen (Mount Cameroon) vanuit Victoria (Kameroen), RP-F-F01175-AD.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op de botanische tuin te Kaapstad, RP-F-F01156-K.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op de bouw van een boot langs de Nijl te Luxor Louqsor (titel op object) Egypte (serietitel), RP-F-2001-7-1540-7.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op de Nieuwe Hollandse kerk van Batavia Het Gezigt van de Groote Hollandse Kerk tot Batavia Te Sien van de Overkant van de Groote Revier (titel op object), NG-400-T.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op de rivier de Daliki en bergen in Perzië Daliki rivier Shiraz-Buchire (titel op object), RP-F-F01048-T.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op Florence vanaf de Monte alle Croci FIRENZE Panorama preso dal Monte alle Croci. (titel op object), RP-F-F01093-AV.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op Galle Face in Colombo op Brits Ceylon, RP-F-AA3188-BR.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op Kyoto vanaf Maruyama Kioto Town from Maruyama (titel op object), RP-F-F01196-AE.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Gezicht op landhuis Weltevreden te Batavia Weldt Vried (titel op object), NG-400-Y.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "GKS 1005 fol., 0005v - 15 (cropped).jpg": ["Jón Þórðarson and Magnús Þórhallsson","Public domain",""],
  "Gondolas and Piazzetta di San Marco, Venice, Italy-LCCN2001701072.jpg": ["Photochrom Print Collection","Public domain",""],
  "Gospels1.jpg": ["","Public domain",""],
  "Gouvernement, kasteelkerk en dragonderwacht binnen het Kasteel te Batavia, NG-1985-7-3-145.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Grand Canyon)- Burro trains at Indian Gardens LCCN2002715958.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Grigoras Dinicu 02.jpg": ["Mecanicul","Public domain",""],
  "Guglielmo Marconi.jpg": ["Pach Brothers","Public domain",""],
  "Gustave Doré - Roland à Roncevaux.jpg": ["Gustave Doré","Public domain",""],
  "Hafun from space.jpg": ["NASA","Public domain",""],
  "Hall of columns, Karnac, RP-F-F25403-AG.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Harbor of Valparaiso, Chile LCCN2016821516.jpg": ["National Photo Company Collection","Public domain",""],
  "Harrat Khaybar Space.jpg": ["Expedition 16 Crew Member on the International Space Station ym.","Public domain",""],
  "Hayreddin Barbarossa 1530-60.jpg": ["","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Heinrich Rudolf Hertz.jpg": ["Robert Krewaldt","Public domain",""],
  "Henri Matisse, 1911-12, La Fenêtre à Tanger (Paysage vu d'une fenêtre Landscape viewed from a window, Tangiers), oil on canvas, 115 x 80 cm, Pushkin Museum.jpg": ["Henri Matisse","Public domain",""],
  "Henry Bessemer.jpg": ["","Public domain",""],
  "History of Tivoli Gardens (Copenhagen) around 1900.jpg": ["Peter Lars Elfelt (før Petersen)","Public domain",""],
  "Horse and camel team, Cloncurry, ca. 1904 (9725658555).jpg": ["State Library of Queensland, Australia","No restrictions","https://www.flickr.com/commons/usage/"],
  "Horse drawn carts portage goods around the impassable rapids on the Slave River -a.jpg": ["Jackson","Public domain",""],
  "Ilya Repin - Barge Haulers on the Volga - Google Art Project.jpg": ["Ilya Repin","Public domain",""],
  "Indians canoeing on Miami River - J.N. Chamberlain, photographer, Miami, Fla. LCCN00650881.jpg": ["Chamberlain ym.","Public domain",""],
  "ISS-29 Snowfall on the Selenga River Delta, Russia.jpg": ["NASA/Expedition 29 crew member","Public domain",""],
  "ISS-30 Lake Eyre - South Australia.jpg": ["NASA","Public domain",""],
  "ISS-33 Nighttime view of Qatar.jpg": ["NASA","Public domain",""],
  "ISS-37 Samarkand, Uzbekistan.jpg": ["NASA","Public domain",""],
  "ISS-47 Port of Aden, Yemen.jpg": ["NASA","Public domain",""],
  "ISS-50 Al-Jawf Oasis in Eastern Libya.jpg": ["NASA","Public domain",""],
  "ISS-57 Kenya and Somalia, Indian Ocean coastline.jpg": ["NASA","Public domain",""],
  "ISS-64 Sahara Desert, Murzuq District in central Libya.jpg": ["NASA","Public domain",""],
  "ISS022-E-5098 - View of China - Kunlun Mountains - Liushi Shan - Trungtse Glacier (cropped).jpg": ["Earth Science and Remote Sensing Unit ym.","Public domain",""],
  "ISS059-E-19273 - View of Manitoba.jpg": ["Earth Science and Remote Sensing Unit ym.","Public domain",""],
  "Jacques Cartier Square. Montreal LCCN2017659148.jpg": ["","Public domain",""],
  "Jean-Sibelius-at-the-piano.jpg": ["","Public domain",""],
  "John Logie Baird in 1917.jpg": ["","Public domain",""],
  "Joseph Marie Jacquard.jpg": ["Ephraïm Conquy / After Jean-Claude Bonnefond","Public domain",""],
  "Joseph-montgolfier.jpg": ["Unidentified painter","Public domain",""],
  "Kairiru & Muschu (Landsat).JPG": ["NASA","Public domain",""],
  "Kairo, marchands ambulants LCCN2017657437.jpg": ["Photoglob Co., publisher","Public domain",""],
  "Kaschau Theater 1900.jpg": ["","Public domain",""],
  "KellsFol034rChiRhoMonogram.jpg": ["","Public domain",""],
  "Kufra (aeroview).jpg": ["","Public domain",""],
  "Kufra Oasis.jpg": ["NASA","Public domain",""],
  "Kufra-space-radar.jpg": ["","Public domain",""],
  "Kultala Ivalojoki.jpg": ["","Public domain",""],
  "Kumasi 28-03-1900 sx.jpg": ["Darkone, Sioux","Public domain",""],
  "Kungstradgarden, Stockholm, Sweden-LCCN2001700741.jpg": ["Photochrom Print Collection","Public domain",""],
  "La Catedral, Habana LCCN90711052.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Lake Chad from Apollo 7.jpg": ["NASA","Public domain",""],
  "Lake Taymyr-txu-oclc-6654394-ns-46-48-2nd-ed.jpg": ["Army Map Service","Public domain",""],
  "Landsat.jpg": ["NASA","Public domain",""],
  "Lascaux painting.jpg": ["EU","Public domain",""],
  "Lascaux, Megaloceros.jpg": ["HTO","Public domain",""],
  "Le Griffon.jpg": ["Judge Campbell ym.","Public domain",""],
  "Leonid Utesov 1934.jpg": ["Mosfilm","Public domain",""],
  "Lions painting, Chauvet Cave (museum replica).jpg": ["HTO","Public domain",""],
  "Livingstone steamer, Congo, ca. 1902-1915 (IMP-CSCNWW33-OS10-73).jpg": ["","Public domain",""],
  "Louis Bleriot.jpg": ["","Public domain",""],
  "Louis Daguerre 2.jpg": ["Jean-Baptiste Sabatier-Blot","Public domain",""],
  "Louis entering Kallimarmaron at the 1896 Athens Olympics.jpg": ["","Public domain",""],
  "Lüderitzbucht, Deutsch-Südwestafrika. The newly finished pier with an Illing locomotive, February 1908, photograph by de Meillon.jpg": ["De Meillon","Public domain",""],
  "Macapá 1908.jpg": ["Amapá, minha terra amada!","Public domain",""],
  "Madrid. Plaza Mayor LCCN2017660767.jpg": ["Photoglob Co., publisher","Public domain",""],
  "Map Ubangi-Uelle 1888.png": ["van Gèle (recorded templates) ym.","Public domain",""],
  "Marie Curie c. 1898.jpg": ["","Public domain",""],
  "Marseille Filets sur le quai Saint-Jean.jpg": ["","Public domain",""],
  "Masks of Africa of Chokwe people freigestellt.jpg": ["The Photographer","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Metropolitan Railway, Baker Street Station.jpg": ["","Public domain",""],
  "Midnight sun in Tromsø.jpg": ["Kawon Kez Sel","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Mint tower, Amsterdam, Holland-LCCN2001697999.jpg": ["Photochrom Print Collection","Public domain",""],
  "Mission Marchand Haut-Oubangui Bahr-el-Ghazal Nil (...)Marchand Jean-Baptiste btv1b53198373d 4.jpg": ["Jean-Baptiste Marchand ym.","Public domain",""],
  "Modern market hall of Kejetia market.jpg": ["Afus199620","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Mykola Leontovych.jpg": ["","Public domain",""],
  "Naples Panorama prise de la Chartreuse S. Martin, RP-F-F16758.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Nikolaus August Otto.png": ["","Public domain",""],
  "Nikolaus Kopernikus.jpg": ["","Public domain",""],
  "NYC Mulberry Street 3g04637u.jpg": ["Detroit Publishing Co.(w), publisher","Public domain",""],
  "Obložené chlebíčky.jpg": ["Karelj","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Old French Market New Orleans Wagons W H Jackson.jpg": ["William Henry Jackson","Public domain",""],
  "Old Harbor (Vieux-Port), Marseille, France-LCCN2002715100.jpg": ["","Public domain",""],
  "Old part of town, Warsaw, Russia (i.e. Warsaw, Poland)-LCCN2001697518.jpg": ["Photochrom Print Collection","Public domain",""],
  "Opernring, Vienna, Austro-Hungary-LCCN2002708403.jpg": ["Photochrom Print Collection","Public domain",""],
  "Oranta-Kyiv.jpg": ["","Public domain",""],
  "Paleis Sponza te Dubrovnik Ragusa. Palazzo Sponza. (serietitel), RP-F-1919-182.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Panorama van de haven van Zanzibar Panorama of Zanzibar (titel op object) Zanzibar (titel op object), RP-F-F00999-DD.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Panorama van Istanbul, de Bosporus en de Gouden Hoorn Souvenir de Constantinople (titel op object), RP-F-F00968.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Panoramic view of Caracas, Venezuela 1900 restored version.jpg": ["Wilfredor","Public domain",""],
  "Peace River, Alberta (HS85-10-32013).jpg": ["","Public domain",""],
  "Peking - inside view of gateway leading toward the Emperor's Palace LCCN2004707954.jpg": ["William Henry Jackson","Public domain",""],
  "Pioneer, Pa., 186-. Oil barge in Oil Creek in foregrd. LCCN2002718639.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Planta da fortaleza da ilha de Moçambique, Leonardo de Ferrari, 1655.jpg": ["Leonardo de Ferrari","Public domain",""],
  "Plattegrond van Batavia, RP-P-OB-47.392.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Po River Delta- ISS020-E-9731.JPG": ["NASA ym.","Public domain",""],
  "Pocket Watch (Switzerland), 1850–53 (CH 18475631).jpg": ["","Public domain",""],
  "Pool on the River Shire at the Foot of the Murchison Cataracts, Africa, ca.1860-ca.1900 (imp-cswc-GB-237-CSWC47-LS16-040).jpg": ["","Public domain",""],
  "Poronkäristys.jpg": ["Htm","Public domain",""],
  "Port Radium in 1936.jpg": ["Matt Berry","Public domain",""],
  "Porte du non-retour au Benin.jpg": ["Borisghost","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Portrait of Edward Jenner M.D (4672926).jpg": ["William Ridley","Public domain",""],
  "Postcard from the Belle Époque with the Romanian Athenaeum and its garden.jpg": ["","Public domain",""],
  "Praha Hrad sníh 2010 22.jpg": ["Karelj","Public domain",""],
  "Puertas Cilícias.jpg": ["No machine-readable author provided","Public domain",""],
  "Quest dogs.JPG": ["No machine-readable author provided","Public domain",""],
  "Ragusa, general view, Dalmatia, Austro-Hungary-LCCN2002710782.jpg": ["Photochrom Print Collection","Public domain",""],
  "Rainandriamampandry ex gouverneur de Tamatave et sa famille.jpg": ["","Public domain",""],
  "Rapides de Lachine 1.JPG": ["Abxbay","Public domain",""],
  "Real Alcázar de Madrid, unknown.jpg": ["","Public domain",""],
  "Reval, general view, 1890 - 1900 crop.jpg": ["Detroit Publishing Co","Public domain",""],
  "Reykjavík. Fish drying and shark oil station. (4558216609).jpg": ["Cornell University Library","No restrictions","https://www.flickr.com/commons/usage/"],
  "Richelieu Stair, Odessa, Russia, (i.e., Ukraine)-LCCN2001697474.jpg": ["Photochrom Print Collection","Public domain",""],
  "Rio Negro Floodplain, Patagonia, Argentina 2010-01-04 lrg.jpg": ["NASA","Public domain",""],
  "Rivier met wadende buffels aan de rand van Luxor E 71. Het plaatsje Luxor (Arabisch kwartier). Opper-Egypte. (titel op object), RP-F-1997-28-6.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Roentgen2.jpg": ["","Public domain",""],
  "Royal Theatre, Copenhagen, Denmark-LCCN2001697986.jpg": ["Photochrom Print Collection","Public domain",""],
  "Rudolf Diesel.jpg": ["","Public domain",""],
  "Ruïnes op de Grote Markt te Brussel, 1695 Debris d'une partie du grand marché depuis le coing de la Heuvelstraet vers St. Nicolas (titel op object) Perspectives des ruines de la ville de Bruxelles (serietitel), RP-P-1903-A-23488.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "S. Maria Novella te Florence 371 (serietitel), RP-F-00-261.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "SA1899 pg136 A Pont . Vaal River.jpg": ["","Public domain",""],
  "Sackville Street and O'Connell Bridge, Dublin. County Dublin, Ireland-LCCN2002717398.jpg": ["","Public domain",""],
  "Sahara satellite hires.jpg": ["NASA","Public domain",""],
  "Sailing ship Alcestis being towed past Goat Island-Rakiriri, Otago Harbour, after running aground, probably 1880s (3056547339).jpg": ["National Library NZ on The Commons","No restrictions","https://www.flickr.com/commons/usage/"],
  "Salween River, The Rope Station (5710965271).jpg": ["Museum of Photographic Arts Collections","No restrictions","https://www.flickr.com/commons/usage/"],
  "Sami flag.svg": ["Jeltz","Public domain",""],
  "Sanddunes marzuq sandsea.jpg": ["NASA","Public domain",""],
  "Sanford Robinson Gifford - Longs Peak, Colorado - Google Art Project.jpg": ["Sanford Robinson Gifford","Public domain",""],
  "São João Baptista de Ajudá 1920s.jpg": ["","Public domain",""],
  "Sarajevo Sebilj and Bascarsija, ca. 1930.jpg": ["","Public domain",""],
  "Sicily Taormina Teatro Greco Etna.jpg": ["Grey48","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Singapore. Collyer Quai LCCN2017657654.jpg": ["Photoglob Co., publisher","Public domain",""],
  "Sir William Rowan Hamilton, head-and-shoulders portrait, facing slightly right LCCN90713420 (cropped).jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Spyridon Louis 1896.jpg": ["","Public domain",""],
  "Spyridon louis marathon winner.jpg": ["","Public domain",""],
  "St. Cristobal Fortress, San Juan, Puerto Rico LCCN96522666.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "St. Gall Gospels Cod.Sang.51 - p.6 - Carpet page.jpg": ["","Public domain",""],
  "Standard of the President of Ukraian People's Republic 1918.png": ["Evostoryarchive","Public domain",""],
  "Stanley Founding of Congo Free State 157 Scene from the Covelet near our Station at Stanley Falls The Seventh CAtaract in the distance.jpg": ["Henry Morton Stanley","Public domain",""],
  "State Street, north from Madison, Chicago-LCCN2008678298.jpg": ["","Public domain",""],
  "Statue of the goddess Sekhmet, granodiorite - Museo Egizio (Turin) C 255 p01.jpg": ["","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Storthings Bygningen (i.e., Stortingsbygningen) Christiania, Norway-LCCN2001699461.jpg": ["Photochrom Print Collection","Public domain",""],
  "Synthetic Production of Penicillin TR1468.jpg": ["Official photographer","Public domain",""],
  "Széchenyi Chain Bridge 2014.jpg": ["Perituss","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Tananarive-Temple d'Andohalo.jpg": ["","Public domain",""],
  "Tempels in Mandalay Birmah-Mandalay-Kyaning opposite the Incomparable Pagoda (titel op object), RP-F-F02363.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "The Colisuem and Meta Sudans, Rome, Italy-LCCN2001700939.jpg": ["Photochrom Print Collection","Public domain",""],
  "The Famous Quartet of Pireaus about 1934.jpg": ["","Public domain",""],
  "The Golden Horn, Constantinople, Turkey-LCCN2001699446.jpg": ["Photochrom Print Collection","Public domain",""],
  "The Lavra gate, Kiev, Russia, (i.e., Ukraine)-LCCN2001697423.jpg": ["Photochrom Print Collection","Public domain",""],
  "The new cathedral, Helsingfors, Russia, i.e., Helsinki, Finland-LCCN2001697412.jpg": ["Photochrom Print Collection","Public domain",""],
  "The Rhone Glacier, Glacier Hotel and Furka Road, Valais, Alps of, Switzerland-LCCN2001703310.jpg": ["Photochrom Print Collection","Public domain",""],
  "The Shrinking Aral Sea Recovers 2010.jpg": ["Jesse Allen","Public domain",""],
  "Theatre and promenade, Riga, Russia, (i.e., Latvia)-LCCN2001697477.jpg": ["Photochrom Print Collection","Public domain",""],
  "TheLandingPlaceAtSuakim(Suakin)1871.jpg": ["","Public domain",""],
  "Thomas Edward Gordon Lake Victoria, Great Pamir, May 2nd, 1874.png": ["Thomas Edward Gordon","Public domain",""],
  "Timbuktu-manuscripts-astronomy-mathematics.jpg": ["Elias Altmimi","Public domain",""],
  "Timbuktu, 1906.png": ["National Geographic","Public domain",""],
  "Tino Rangatiratanga Maori sovereignty movement flag.svg": ["of code: cs:-xfi-; of flag ym.","Public domain",""],
  "Toronto from the bay-LCCN2008678144.jpg": ["","Public domain",""],
  "Tôshôgû-schrijn in het Ueno-park in Tokyo Ueno Tôshôgû (titel op object), RP-F-F01177-G.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Travels in the central Caucasus and Bash P.380.jpg": ["Douglas William Freshfield","Public domain",""],
  "Tromsø, with Tromstind, Troms, Norway-LCCN2001700759.jpg": ["Photochrom Print Collection","Public domain",""],
  "Twee gezichten op boten in de haven van Kaapstad Cape Town - the docks (titel op object), RP-F-2001-7-425-2.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Twee gezichten op de mijn Die Groot Gat te Kimberley Diamond fields-Kimberley mine (titel op object) Diamond fields-Tramway, Kimberley mine (titel op object), RP-F-2001-7-425-25.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Umm Kulthum4.jpg": ["","Public domain",""],
  "United States Mint, New Orleans, La. LCCN93515339.jpg": ["Miscellaneous Items in High Demand ym.","Public domain",""],
  "Ural River Atyrau.JPG": ["Ds02006","Public domain",""],
  "UtsingiPoint-GreatSlaveLake.JPG": ["Paul Gierszewski","Public domain",""],
  "Vaticana, Vat. lat. 3868 (2r).jpg": ["","Public domain",""],
  "Via Appia Antica Rome 2006.jpg": ["Radosław Botev","Attribution",""],
  "Victoria Falls Bridge 1905.jpg": ["","Public domain",""],
  "Vilnia, Vostraja Brama. Вільня, Вострая Брама (S. Fleury, 1900).jpg": ["Stanisław Filibert Fleury","Public domain",""],
  "Waterbassins in het bergachtige landschap in Aden Aden waterworks. The tanks (titel op object), RP-F-00-5018-17.jpg": ["Rijksmuseum","CC0","http://creativecommons.org/publicdomain/zero/1.0/deed.en"],
  "Watt James von Breda.jpg": ["Carl Frederik von Breda","Public domain",""],
  "Western Galapagos Islands2000Nasa.jpg": ["NASA","Public domain",""],
  "Wheatstone Charles drawing 1868.jpg": ["Samuel Laurence","Public domain",""],
  "Windswept pine on Georgian Bay.jpg": ["Ezekiel","Public domain",""],
  "Wiphala.svg": ["Huhsunqu","Public domain",""],
  "Wvs 1885.jpg": ["Photograph","Public domain",""],
  "لوحة بسملة للقندوسي.jpg": ["","Public domain",""],
};
