/*
 * MAAKUNTIEN NIMISTÖ KAIKILLE PELIN MAILLE — GENEROITU, älä muokkaa käsin
 * (paitsi nimien suomennoksia; seuraava ajo kirjoittaa tiedoston uudelleen).
 *
 *   node tools/tee-maakuntavektorit.mjs --ne=<ne_10m_admin_1_states_provinces.geojson> \
 *     --versio=2026-09-25a --nykyalueet=docs/raportit/kaappaukset/maakuntavedos-20260921/vedos4 \
 *     --wikidata=<wikidata-admin1.json> --pelimaat=<pelimaat.json> --nimimoduuli=js/packs/maakunnat-nimet.js
 *
 * Avaimet: iso → { tunnus: nimi }, tunnus = maakuntavektorien alueen tunnus
 * (julisteet/pallo/maakunnat/2026-09-25a/<ISO>.json), joten "ISO:tunnus" on sama
 * avain kuin kartan värjäyksessä ja Maakunnat-välilehdellä. Nimi: kuratoitu
 * nykyalueet-nimi → seuturyhmän suomennos → Wikidatan suomenkielinen nimi →
 * Natural Earthin nimi (public domain). TYHJÄ OLIO = maalla ei ole maakuntia.
 */
export const MAAKUNNAT_VERSIO = '2026-09-25a';

export const MAAKUNNAT_KAIKKI = {
  AFG: {
    "Badakhshan": "Badahšan",
    "Badghis": "Badghis",
    "Baghlan": "Baghlan",
    "Balkh": "Balkh",
    "Bamyan": "Bamyan",
    "Farah": "Farah",
    "Faryab": "Faryab",
    "Ghazni": "Ghazni",
    "Ghor": "Ghor",
    "Hilmand": "Helmand",
    "Hirat": "Herat",
    "Jawzjan": "Jawzjan",
    "Kabul": "Kabul",
    "Kandahar": "Kandahar",
    "Kapisa": "Kapisa",
    "Khost": "Khost",
    "Kunar": "Konarha",
    "Laghman": "Laghman",
    "Logar": "Logar",
    "Nangarhar": "Nangarhar",
    "Nimroz": "Nimroz",
    "Nuristan": "Nuristan",
    "Paktika": "Paktika",
    "Paktya": "Paktya",
    "Parwan": "Parwan",
    "Kunduz": "Qunduz",
    "Samangan": "Samangan",
    "Sari Pul": "Sari Pul",
    "Takhar": "Takhar",
    "Uruzgan": "Uruzgan",
    "Wardak": "Wardak",
    "Zabul": "Zaboul",
  },
  NLD: {
    "Bonaire": "Bonaire",
    "Drenthe": "Drenthe",
    "Zuid-Holland": "Etelä-Holland",
    "Flevoland": "Flevoland",
    "Friesland": "Friisinmaa",
    "Gelderland": "Gelderland",
    "Groningen": "Groningen",
    "Limburg": "Limburg",
    "Overijssel": "Overijssel",
    "Noord-Brabant": "Pohjois-Brabant",
    "Noord-Holland": "Pohjois-Holland",
    "Saba": "Saba",
    "St. Eustatius": "Sint Eustatius",
    "Utrecht": "Utrecht",
    "Zeeland": "Zeeland",
  },
  ALB: {
    "Berat": "Berat",
    "Dibër": "Dibër",
    "Durrës": "Durrës",
    "Elbasan": "Elbasan",
    "Fier": "Fier",
    "Gjirokastër": "Gjirokastër",
    "Korçë": "Korçë",
    "Kukës": "Kukës",
    "Lezhë": "Lezhë",
    "Shkodër": "Shkodër",
    "Tiranë": "Tiranë",
    "Vlorë": "Vlorë",
  },
  DZA: {
    "Adrar": "Adrar",
    "Aïn Defla": "Aïn Defla",
    "Aïn Témouchent": "Aïn Témouchent",
    "Alger": "Alger",
    "Annaba": "Annaba",
    "Batna": "Batna",
    "Béchar": "Béchar",
    "Béjaïa": "Béjaïa",
    "Biskra": "Biskra",
    "Blida": "Blida",
    "Bordj Bou Arréridj": "Bordj Bou Arréridj",
    "Bouira": "Bouira",
    "Boumerdès": "Boumerdès",
    "Chlef": "Chlef",
    "Constantine": "Constantine",
    "Djelfa": "Djelfa",
    "El Bayadh": "El Bayadh",
    "El Oued": "El Oued Province",
    "El Tarf": "El Tarf",
    "Ghardaïa": "Ghardaïa",
    "Guelma": "Guelma",
    "Illizi": "Illizi",
    "Jijel": "Jijel",
    "Khenchela": "Khenchela",
    "Laghouat": "Laghouat",
    "M'Sila": "M'Sila",
    "Mascara": "Mascara",
    "Médéa": "Médéa",
    "Mila": "Mila",
    "Mostaganem": "Mostaganem",
    "Naâma": "Naama",
    "Oran": "Oran",
    "Ouargla": "Ouargla",
    "Oum el Bouaghi": "Oum el Bouaghi",
    "Relizane": "Relizane",
    "Saïda": "Saïda",
    "Sétif": "Sétif",
    "Sidi Bel Abbès": "Sidi Bel Abbès",
    "Skikda": "Skikda",
    "Souk Ahras": "Souk Ahras",
    "Tamanghasset": "Tamanrasset",
    "Tébessa": "Tébessa",
    "Tiaret": "Tiaret",
    "Tindouf": "Tindouf",
    "Tipaza": "Tipaza",
    "Tissemsilt": "Tissemsilt",
    "Tizi Ouzou": "Tizi Ouzou",
    "Tlemcen": "Tlemcen",
  },
  AGO: {
    "Bengo": "Bengo",
    "Benguela": "Benguela",
    "Bié": "Bié",
    "Cabinda": "Cabinda",
    "Cuando Cubango": "Cuando Cubango",
    "Cuanza Norte": "Cuanza Norte",
    "Cuanza Sul": "Cuanza Sul",
    "Cunene": "Cunene",
    "Huambo": "Huambo",
    "Huíla": "Huila",
    "Luanda": "Luanda",
    "Lunda Norte": "Lunda Norte",
    "Lunda Sul": "Lunda Sul",
    "Malanje": "Malanje",
    "Moxico": "Moxico",
    "Namibe": "Namibe",
    "Uíge": "Uige",
    "Zaire": "Zaire",
  },
  ARE: {
    "Abu Dhabi": "Abu Dhabi",
    "Ajman": "Ajman",
    "Dubay": "Dubay",
    "Fujayrah": "Fujayrah",
    "Neutral Zone": "Neutral Zone",
    "Ras Al Khaymah": "Ras Al Khaymah",
    "Sharjah": "Sharjah",
    "Umm Al Qaywayn": "Umm Al Qaywayn",
  },
  ARG: {
    "Buenos Aires": "Buenos Aires",
    "Ciudad de Buenos Aires": "Buenos Aires",
    "Catamarca": "Catamarca",
    "Chaco": "Chaco",
    "Chubut": "Chubut",
    "Córdoba": "Córdoba",
    "Corrientes": "Corrientes",
    "Entre Ríos": "Entre Ríos",
    "Formosa": "Formosa",
    "Jujuy": "Jujuy",
    "La Pampa": "La Pampa",
    "La Rioja": "La Rioja",
    "Mendoza": "Mendoza",
    "Misiones": "Misiones",
    "Neuquén": "Neuquén",
    "Río Negro": "Río Negro",
    "Salta": "Salta",
    "San Juan": "San Juan",
    "San Luis": "San Luis",
    "Santa Cruz": "Santa Cruz",
    "Santa Fe": "Santa Fe",
    "Santiago del Estero": "Santiago del Estero",
    "Tierra del Fuego": "Tierra del Fuego",
    "Tucumán": "Tucumán",
  },
  ARM: {
    "Aragatsotn": "Aragatsotn",
    "Ararat": "Ararat",
    "Armavir": "Armavir",
    "Gegharkunik": "Geghark'unik'",
    "Erevan": "Jerevan",
    "Kotayk": "Kotajk'",
    "Lori": "Lorri",
    "Shirak": "Širak",
    "Syunik": "Sjunik'",
    "Tavush": "Tavuš",
    "Vayots Dzor": "Vajots' Dzor",
  },
  AUS: {
    "Australian Capital Territory": "Australian pääkaupunkiterritorio",
    "South Australia": "Etelä-Australia",
    "Jervis Bay Territory": "Jervis Bay Territory",
    "Lord Howe Island": "Lord Howe Island",
    "Western Australia": "Länsi-Australia",
    "Macquarie Island": "Macquariensaari",
    "Northern Territory": "Pohjoisterritorio",
    "Queensland": "Queensland",
    "Tasmania": "Tasmania",
    "New South Wales": "Uusi Etelä-Wales",
    "Victoria": "Victoria",
  },
  AZE: {
    "Absheron Economic Region": "Absheron Economic Region",
    "Aran Economic Region": "Aran Economic Region",
    "Daghlig Shirvan Economic Region": "Daghlig Shirvan Economic Region",
    "Ganja-Gazakh Economic Region": "Ganja-Gazakh Economic Region",
    "Guba-Khachmaz Economic Region": "Guba-Khachmaz Economic Region",
    "Kalbajar-Lachin Economic Region": "Kalbajar-Lachin Economic Region",
    "Lankaran Economic Region": "Lankaran Economic Region",
    "Naxçıvan Autonomous Republic": "Naxçıvan Autonomous Republic",
    "Shaki-Zaqatala Economic Region": "Shaki-Zaqatala Economic Region",
    "Yukhari Garabakh Economic Region": "Yukhari Garabakh Economic Region",
  },
  BHR: {
    "Al Janūbīyah": "Al Janūbīyah",
    "Al Manāmah": "Al Manāmah",
    "Al Wusţá": "Al Wusţá",
    "Ash Shamālīyah": "Ash Shamālīyah",
    "Al Muḩarraq": "Muharraq",
  },
  BGD: {
    "Barisal": "Barisal",
    "Chittagong": "Chittagong",
    "Dhaka": "Dhaka",
    "Khulna": "Khulna",
    "Rajshahi": "Rajshahi",
    "Rangpur": "Rangpur District",
    "Sylhet": "Sylhet",
  },
  BEL: {
    "Antwerp": "Antwerp",
    "Brussels": "Brysselin pääkaupunkialue",
    "Flemish Brabant": "Flanderin Brabant",
    "Hainaut": "Hainaut",
    "East Flanders": "Itä-Flanderi",
    "Liege": "Liègen pronssi",
    "Limburg": "Limburg",
    "Luxembourg": "Luxembourg",
    "West Flanders": "Länsi-Flanderi",
    "Namur": "Namur",
    "Walloon Brabant": "Vallonian Brabant",
  },
  BMU: {
    "City of Hamilton": "Hamiltonin kaupunki",
    "City of Saint George": "St. George'sin kaupunki",
    "Devonshire": "Devonshire",
    "Hamilton": "Hamiltonin seurakunta",
    "Paget": "Paget",
    "Pembroke": "Pembroke",
    "Saint George's": "St. George'sin seurakunta",
    "Sandys": "Sandys",
    "Smith's": "Smith's",
    "Southampton": "Southampton",
    "Warwick": "Warwick",
  },
  BTN: {
    "Bumthang": "Bumthang",
    "Chhukha": "Chukha",
    "Daga": "Dagana",
    "Gasa": "Gasa",
    "Geylegphug": "Geylegphug",
    "Ha": "Haa",
    "Lhuntshi": "Lhuntse",
    "Mongar": "Mongar",
    "Paro": "Paro",
    "Pemagatsel": "Pemagatshel",
    "Punakha": "Punakha",
    "Samdrup Jongkhar": "Samdrup Jongkhar",
    "Samchi": "Samtse",
    "Thimphu": "Thimphu",
    "Tashigang": "Trashigang",
    "Tashi Yangtse": "Trashiyangste",
    "Tongsa": "Trongsa",
    "Chirang": "Tsirang",
    "Wangdi Phodrang": "Wangdue Phodrang",
    "Shemgang": "Zhemgang",
  },
  BOL: {
    "El Beni": "Beni",
    "Chuquisaca": "Chuquisaca",
    "Cochabamba": "Cochabamba",
    "La Paz": "La Paz",
    "Oruro": "Oruro",
    "Pando": "Pando",
    "Potosí": "Potosí",
    "Santa Cruz": "Santa Cruz",
    "Tarija": "Tarija",
  },
  BIH: {
    "Banja Luka": "Banja Luka",
    "Bijeljina": "Bijeljina",
    "Bosnian Podrinje": "Bosnian Podrinje",
    "Brčko Distrikt": "Brčkon piirikunta",
    "Central Bosnia": "Keski-Bosnia",
    "Doboj": "Doboj",
    "Foča": "Foča",
    "Herzegovina-Neretva": "Hertsegovina-Neretva",
    "Posavina": "Posavina",
    "Sarajevo": "Sarajevo",
    "Sarajevo-romanija": "Sarajevo-Romanija",
    "Trebinje": "Trebinje",
    "Tuzla": "Tuzla",
    "Una-Sana": "Una-Sana",
    "Vlasenica": "Vlasenica",
    "West Bosnia": "Länsi-Bosnia",
    "West Herzegovina": "Länsi-Hertsegovina",
    "Zenica-Doboj": "Zenica-Doboj",
  },
  BRA: {
    "Acre": "Acre",
    "Alagoas": "Alagoas",
    "Amapá": "Amapá",
    "Amazonas": "Amazonas",
    "Bahia": "Bahia",
    "Ceará": "Ceará",
    "Distrito Federal": "Distrito Federal",
    "Espírito Santo": "Espírito Santo",
    "Goiás": "Goiás",
    "Maranhão": "Maranhão",
    "Mato Grosso": "Mato Grosso",
    "Mato Grosso do Sul": "Mato Grosso do Sul",
    "Minas Gerais": "Minas Gerais",
    "Pará": "Pará",
    "Paraíba": "Paraíba",
    "Paraná": "Paraná",
    "Pernambuco": "Pernambuco",
    "Piauí": "Piauí",
    "Rio de Janeiro": "Rio de Janeiro",
    "Rio Grande do Norte": "Rio Grande do Norte",
    "Rio Grande do Sul": "Rio Grande do Sul",
    "Rondônia": "Rondônia",
    "Roraima": "Roraima",
    "Santa Catarina": "Santa Catarina",
    "São Paulo": "São Paulo",
    "Sergipe": "Sergipe",
    "Tocantins": "Tocantins",
  },
  BGR: {
    "Blagoevgrad": "Blagoevgrad",
    "Burgas": "Burgas",
    "Dobrich": "Dobrich",
    "Gabrovo": "Gabrovo",
    "Grad Sofiya": "Grad Sofiya",
    "Haskovo": "Haskovo",
    "Yambol": "Jambol",
    "Kardzhali": "Kardzhali",
    "Kyustendil": "Kjustendil",
    "Lovech": "Lovech",
    "Montana": "Montana",
    "Pazardzhik": "Pazardzhik",
    "Pernik": "Pernik",
    "Pleven": "Pleven",
    "Plovdiv": "Plovdiv",
    "Razgrad": "Razgrad",
    "Ruse": "Ruse",
    "Silistra": "Silistra",
    "Sliven": "Sliven",
    "Smolyan": "Smoljan",
    "Sofia": "Sofia",
    "Stara Zagora": "Stara Zagora",
    "Shumen": "Šumen",
    "Targovishte": "Targovishte",
    "Varna": "Varna",
    "Veliko Tarnovo": "Veliko Tarnovo",
    "Vidin": "Vidin",
    "Vratsa": "Vratsa",
  },
  CHL: {
    "Aisén del General Carlos Ibáñez del Campo": "Aisén",
    "Antofagasta": "Antofagasta",
    "La Araucanía": "Araucanía",
    "Arica y Parinacota": "Arica-Parinacota",
    "Atacama": "Atacama",
    "Bío-Bío": "Biobío",
    "Coquimbo": "Coquimbo",
    "Libertador General Bernardo O'Higgins": "O'Higgins",
    "Los Lagos": "Los Lagos",
    "Los Ríos": "Los Ríos",
    "Magallanes y Antártica Chilena": "Magallanes",
    "Maule": "Maule",
    "Ñuble": "Ñuble",
    "Región Metropolitana de Santiago": "Santiagon metropolialue",
    "Tarapacá": "Tarapacá",
    "Valparaíso": "Valparaíso",
  },
  ECU: {
    "Azuay": "Azuay",
    "Bolivar": "Bolívar",
    "Cañar": "Cañar",
    "Carchi": "Carchi",
    "Chimborazo": "Chimborazo",
    "Cotopaxi": "Cotopaxi",
    "El Oro": "El Oro",
    "Esmeraldas": "Esmeraldas",
    "Galápagos": "Galápagos",
    "Guayas": "Guayas",
    "Imbabura": "Imbabura",
    "Loja": "Loja",
    "Los Rios": "Los Ríos",
    "Manabi": "Manabí",
    "Morona Santiago": "Morona-Santiago",
    "Napo": "Napo",
    "Orellana": "Orellana",
    "Pastaza": "Pastaza",
    "Pichincha": "Pichincha",
    "Santa Elena": "Santa Elena",
    "Santo Domingo de los Tsáchilas": "Santo Domingo de los Tsáchilas",
    "Sucumbios": "Sucumbíos",
    "Tungurahua": "Tungurahua",
    "Zamora Chinchipe": "Zamora-Chinchipe",
  },
  EGY: {
    "Al Fayyum": "Faijum",
    "Al Gharbiyah": "Gharbia",
    "Al Iskandariyah": "Aleksandria",
    "Al Minya": "Minya",
    "Al Qahirah": "Kairo",
    "Al Bahr al Ahmar": "Punainenmeri",
    "Al Buhayrah": "Buhaira",
    "Ad Daqahliyah": "Dakahlia",
    "Al Minufiyah": "Minufia",
    "Al Qalyubiyah": "Qalyubia",
    "Ash Sharqiyah": "Sharqia",
    "Al Wadi at Jadid": "Uusi laakso",
    "Aswan": "Assuan",
    "Asyut": "Asyut",
    "Bani Suwayf": "Beni Suef",
    "Dumyat": "Damietta",
    "Al Jizah": "Giza",
    "Al Isma`iliyah": "Ismailia",
    "Janub Sina'": "Etelä-Siinai",
    "Kafr ash Shaykh": "Kafr el-Sheikh",
    "Luxor": "Luxor",
    "Matruh": "Matruh",
    "Bur Sa`id": "Port Said",
    "Qina": "Qena",
    "Shamal Sina'": "Pohjois-Siinai",
    "Suhaj": "Sohag",
    "As Suways": "Suez",
  },
  ESP: {
    "Andalucía": "Andalusia",
    "Aragón": "Aragonia",
    "Asturias": "Asturia",
    "Islas Baleares": "Baleaarit",
    "País Vasco": "Baskimaa",
    "Ceuta": "Ceuta",
    "Extremadura": "Extremadura",
    "Galicia": "Galicia",
    "Canary Is.": "Kanariansaaret",
    "Cantabria": "Kantabria",
    "Castilla y León": "Kastilia ja León",
    "Castilla-La Mancha": "Kastilia-La Mancha",
    "Cataluña": "Katalonia",
    "La Rioja": "La Rioja",
    "Madrid": "Madrid",
    "Melilla": "Melilla",
    "Murcia": "Murcia",
    "Foral de Navarra": "Navarra",
    "Valenciana": "Valencia",
  },
  ZAF: {
    "Eastern Cape": "Itä-Kap",
    "Free State": "Vapaavaltio",
    "Gauteng": "Gauteng",
    "KwaZulu-Natal": "KwaZulu-Natal",
    "Limpopo": "Limpopo",
    "Mpumalanga": "Mpumalanga",
    "North West": "Luoteinen provinssi",
    "Northern Cape": "Pohjois-Kap",
    "Western Cape": "Länsi-Kap",
  },
  KOR: {
    "Busan": "Busan",
    "Daegu": "Daegu",
    "Daejeon": "Daejeon",
    "South Chungcheong": "Etelä-Chungcheong",
    "South Gyeongsang": "Etelä-Gyeongsang",
    "South Jeolla": "Etelä-Jeolla",
    "Gangwon": "Gangwon",
    "Gwangju": "Gwangju",
    "Gyeonggi": "Gyeonggi",
    "Incheon": "Incheon",
    "Jeju": "Jeju",
    "North Chungcheong": "Pohjois-Chungcheong",
    "North Gyeongsang": "Pohjois-Gyeongsang",
    "North Jeolla": "Pohjois-Jeolla",
    "Sejong": "Sejong",
    "Seoul": "Soul",
    "Ulsan": "Ulsan",
  },
  SDS: {
    "Eastern Equatoria": "Itä-Ekvatoria",
    "Jonglei": "Jonglei",
    "Central Equatoria": "Keski-Ekvatoria",
    "Lakes": "Lakes",
    "Western Equatoria": "Länsi-Ekvatoria",
    "Western Bahr el Ghazal": "Läntinen Bahr el-Ghazal",
    "Northern Bahr el Ghazal": "Pohjoinen Bahr el-Ghazal",
    "Unity": "Unity",
    "Warrap": "Warrap",
    "Upper Nile": "Ylä-Niili",
  },
  ETH: {
    "Addis Ababa": "Addis Abeba",
    "Afar": "Afar",
    "Amhara": "Amhara",
    "Benshangul-Gumaz": "Benishangul-Gumuz",
    "Dire Dawa": "Dire Dawa",
    "Gambela Peoples": "Gambela",
    "Harari People": "Harari",
    "Oromiya": "Oromia",
    "Somali": "Somali",
    "Southern Nations, Nationalities and Peoples": "Southern Nations",
    "Tigray": "Tigré",
  },
  FLK: {},
  FJI: {
    "Central": "Keskinen divisioona",
    "Eastern": "Itäinen divisioona",
    "Northern": "Pohjoinen divisioona",
    "Rotuma": "Rotuma",
    "Western": "Läntinen divisioona",
  },
  PHL: {
    "Autonomous Region in Muslim Mindanao (ARMM)": "Bangsamoro",
    "Bicol (Region V)": "Bicol",
    "Cagayan Valley (Region II)": "Cagayanin laakso",
    "CALABARZON (Region IV-A)": "CALABARZON",
    "Central Luzon (Region III)": "Keski-Luzon",
    "Central Visayas (Region VII)": "Keski-Visayas",
    "Cordillera Administrative Region (CAR)": "Cordillera",
    "Davao (Region XI)": "Davao",
    "Dinagat Islands (Region XIII)": "Caraga",
    "Eastern Visayas (Region VIII)": "Itä-Visayas",
    "Ilocos (Region I)": "Ilocos",
    "MIMAROPA (Region IV-B)": "MIMAROPA",
    "National Capital Region": "Metro Manila",
    "Northern Mindanao (Region X)": "Pohjois-Mindanao",
    "SOCCSKSARGEN (Region XII)": "SOCCSKSARGEN",
    "Western Visayas (Region VI)": "Länsi-Visayas",
    "Zamboanga Peninsula (Region IX)": "Zamboangan niemimaa",
  },
  GEO: {
    "Abkhazia": "Abhasia",
    "Ajaria": "Adžaria",
    "Guria": "Guria",
    "Imereti": "Imereti",
    "Kakheti": "Kakheti",
    "Kvemo Kartli": "Kvemo Kartli",
    "Mtskheta-Mtianeti": "Mtskheta-Mtianeti",
    "Racha-Lechkhumi-Kvemo Svaneti": "Ratša-Letškhumi ja Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti": "Samegrelo ja Zemo Svaneti",
    "Samtskhe-Javakheti": "Samtskhe-Džavakheti",
    "Shida Kartli": "Šida Kartli",
    "Tbilisi": "Tbilisi",
  },
  GHA: {
    "Ashanti": "Ashanti",
    "Brong Ahafo": "Brong-Ahafo",
    "Central": "Central",
    "Eastern": "Eastern Ghana",
    "Greater Accra": "Greater Accra",
    "Northern": "Northern Ghana",
    "Upper East": "Upper East Ghana",
    "Upper West": "Upper West Ghana",
    "Volta": "Volta",
    "Western": "Western",
  },
  GRL: {
    "Nationalparken": "Koillis-Grönlannin kansallispuisto",
    "Kommune Kujalleq": "Kujalleq",
    "Pituffik": "Pituffik",
    "Qaasuitsup Kommunia": "Qaasuitsup",
    "Qeqqata Kommunia": "Qeqqata",
    "Kommuneqarfik Sermersooq": "Sermersooq",
  },
  GTM: {
    "Alta Verapaz": "Alta Verapaz",
    "Baja Verapaz": "Baja Verapaz",
    "Chimaltenango": "Chimaltenango",
    "Chiquimula": "Chiquimula",
    "El Progreso": "El Progreso",
    "Escuintla": "Escuintla",
    "Guatemala": "Guatemala",
    "Huehuetenango": "Huehuetenango",
    "Izabal": "Izabal",
    "Jalapa": "Jalapan Departementti",
    "Jutiapa": "Jutiapa",
    "Petén": "Petén",
    "Quezaltenango": "Quezaltenango",
    "Quiché": "Quiché",
    "Retalhuleu": "Retalhuleu",
    "Sacatepéquez": "Sacatepéquez",
    "San Marcos": "San Marcos",
    "Santa Rosa": "Santa Rosa",
    "Sololá": "Sololá",
    "Suchitepéquez": "Suchitepéquez",
    "Totonicapán": "Totonicapán",
    "Zacapa": "Zacapan depatermentti",
  },
  HKG: {
    "Central and Western": "Central and Western",
    "Eastern": "Eastern",
    "Islands": "Islands",
    "Kowloon City": "Kowloon City",
    "Kwai Tsing": "Kwai Tsing",
    "Kwun Tong": "Kwun Tong",
    "North": "North",
    "Sai Kung": "Sai Kung",
    "Sha Tin": "Sha Tin",
    "Sham Shui Po": "Sham Shui Po",
    "Southern": "Southern",
    "Tai Po": "Tai Po",
    "Tsuen Wan": "Tsuen Wan",
    "Tuen Mun": "Tuen Mun",
    "Wan Chai": "Wan Chai",
    "Wong Tai Sin": "Wong Tai Sin",
    "Yau Tsim Mong": "Yau Tsim Mong",
    "Yuen Long": "Yuen Long",
  },
  IDN: {
    "Aceh": "Aceh",
    "Bali": "Bali",
    "Bangka-Belitung": "Bangka-Belitung",
    "Banten": "Banten",
    "Bengkulu": "Bengkulu",
    "Yogyakarta": "Daérah Istiméwa Yogyakarta",
    "Kalimantan Selatan": "Etelä-Kalimantan",
    "Sulawesi Selatan": "Etelä-Sulawesi",
    "Sumatera Selatan": "Etelä-Sumatra",
    "Gorontalo": "Gorontalo",
    "Jawa Timur": "Itä-Jaava",
    "Kalimantan Timur": "Itä-Kalimantan",
    "Nusa Tenggara Timur": "Itäinen Nusa Tenggara",
    "Jakarta Raya": "Jakarta",
    "Jambi": "Jambi",
    "Sulawesi Tenggara": "Kaakkois-Sulawesi",
    "Jawa Tengah": "Keski-Jaava",
    "Kalimantan Tengah": "Keski-Kalimantan",
    "Sulawesi Tengah": "Keski-Sulawesi",
    "Lampung": "Lampung",
    "Jawa Barat": "Länsi-Jaava",
    "Kalimantan Barat": "Länsi-Kalimantan",
    "Papua Barat": "Länsi-Papua",
    "Sulawesi Barat": "Länsi-Sulawesi",
    "Sumatera Barat": "Länsi-Sumatra",
    "Nusa Tenggara Barat": "Läntinen Nusa Tenggara",
    "Maluku": "Molukit",
    "Papua": "Papua",
    "Maluku Utara": "Pohjois-Molukit",
    "Sulawesi Utara": "Pohjois-Sulawesi",
    "Sumatera Utara": "Pohjois-Sumatra",
    "Riau": "Riau",
    "Kepulauan Riau": "Riausaaret",
  },
  IND: {
    "Andaman and Nicobar": "Andamaanit ja Nikobaarit",
    "Andhra Pradesh": "Andhra Pradesh",
    "Arunachal Pradesh": "Arunachal Pradesh",
    "Assam": "Assam",
    "Bihar": "Bihar",
    "Chandigarh": "Chandigarh",
    "Chhattisgarh": "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu": "Dadra ja Nagar Haveli ja Daman ja Diu",
    "Delhi": "Delhi",
    "Goa": "Goa",
    "Gujarat": "Gujarat",
    "Haryana": "Haryana",
    "Himachal Pradesh": "Himachal Pradesh",
    "Jammu and Kashmir": "Jammu ja Kashmir",
    "Jharkhand": "Jharkhand",
    "Karnataka": "Karnataka",
    "Kerala": "Kerala",
    "Ladakh": "Ladakh",
    "Lakshadweep": "Lakshadweep",
    "West Bengal": "Länsi-Bengali",
    "Madhya Pradesh": "Madhya Pradesh",
    "Maharashtra": "Maharashtra",
    "Manipur": "Manipur",
    "Meghalaya": "Meghalaya",
    "Mizoram": "Mizoram",
    "Nagaland": "Nagaland",
    "Odisha": "Odisha",
    "Puducherry": "Puducherry",
    "Punjab": "Punjab",
    "Rajasthan": "Rajasthan",
    "Sikkim": "Sikkim",
    "Tamil Nadu": "Tamil Nadu",
    "Telangana": "Telangana",
    "Tripura": "Tripura",
    "Uttar Pradesh": "Uttar Pradesh",
    "Uttarakhand": "Uttarakhand",
  },
  IRQ: {
    "Al-Anbar": "Al-Anbar",
    "Al-Muthannia": "Al-Muthanna",
    "An-Najaf": "An-Najaf",
    "Babil": "Babil",
    "Baghdad": "Bagdad",
    "Al-Basrah": "Basra",
    "Dihok": "Dahuk",
    "Dhi-Qar": "Dhi Qar",
    "Diyala": "Diyala",
    "Arbil": "Erbil",
    "Karbala'": "Karbala'",
    "At-Ta'mim": "Kirkuk",
    "Maysan": "Maysan",
    "Ninawa": "Ninawa",
    "Al-Qādisiyyah": "Qadisiyya",
    "Sala ad-Din": "Salah al-Din",
    "As-Sulaymaniyah": "Sulaymaniyya",
    "Wasit": "Wasit",
  },
  IRN: {
    "Alborz": "Ālborz",
    "Ardebil": "Ardabīl",
    "West Azarbaijan": "Āzārbāyjān-e Gharbī",
    "East Azarbaijan": "Āzārbāyjān-e Sharqī",
    "Kohgiluyeh and Buyer Ahmad": "Boyer Ahmadī ja Kohkīlūyeh",
    "Bushehr": "Būšehr",
    "Chahar Mahall and Bakhtiari": "Chahār Mahāl ja Bakhtīārī",
    "Esfahan": "Esfahan",
    "Fars": "Fārs",
    "Gilan": "Gīlān",
    "Golestan": "Golestan",
    "Hamadan": "Hamadān",
    "Hormozgan": "Hormozgān",
    "Ilam": "Ilām",
    "Kerman": "Kermān",
    "Kermanshah": "Kermānšāh",
    "South Khorasan": "Khorāsān-e Junoubi",
    "Razavi Khorasan": "Khorāsān-e Razavi",
    "North Khorasan": "Khorāsān-e Shomali",
    "Khuzestan": "Khūzestān",
    "Kordestan": "Kordestān",
    "Lorestan": "Lorestān",
    "Markazi": "Markazī",
    "Mazandaran": "Māzandarān",
    "Qazvin": "Qazvin",
    "Qom": "Qom",
    "Semnan": "Semnān",
    "Sistan and Baluchestan": "Sīstān ja Balūchestān",
    "Tehran": "Tehrān",
    "Yazd": "Yazd",
    "Zanjan": "Zanjan",
  },
  IRL: {
    "Carlow": "Carlow",
    "Cavan": "Cavan",
    "Clare": "Clare",
    "Cork": "Cork",
    "Donegal": "Donegal",
    "Dublin": "Dublin",
    "Dún Laoghaire–Rathdown": "Dún Laoghaire–Rathdown",
    "Fingal": "Fingal",
    "Galway": "Galway",
    "Kerry": "Kerry",
    "Kildare": "Kildare",
    "Kilkenny": "Kilkenny",
    "Laoighis": "Laois",
    "Leitrim": "Leitrim",
    "Limerick": "Limerick",
    "Longford": "Longford",
    "Louth": "Louth",
    "Mayo": "Mayo",
    "Meath": "Meath",
    "Monaghan": "Monaghan",
    "Offaly": "Offaly",
    "Roscommon": "Roscommon",
    "Sligo": "Sligo",
    "South Dublin": "South Dublin",
    "North Tipperary": "Tipperary",
    "South Tipperary": "Tipperary",
    "Waterford": "Waterford",
    "Westmeath": "Westmeath",
    "Wexford": "Wexford",
    "Wicklow": "Wicklow",
  },
  ISL: {
    "Austurland": "Austurland",
    "Höfuðborgarsvæði": "Pääkaupunkiseutu",
    "Vestfirðir": "Länsivuonot",
    "Norðurland eystra": "Norðurland eystra",
    "Norðurland vestra": "Norðurland vestra",
    "Reykjavík": "Reykjavík",
    "Suðurland": "Suðurland",
    "Suðurnes": "Suðurnes",
    "Vesturland": "Vesturland",
  },
  GBR: {
    "England": "Englanti",
    "Northern Ireland": "Pohjois-Irlanti",
    "Scotland": "Skotlanti",
    "Wales": "Wales",
  },
  ITA: {
    "Abruzzo": "Abruzzo",
    "Valle d'Aosta": "Aostanlaakso",
    "Apulia": "Apulia",
    "Basilicata": "Basilicata",
    "Calabria": "Calabria",
    "Campania": "Campania",
    "Emilia-Romagna": "Emilia-Romagna",
    "Friuli-Venezia Giulia": "Friuli-Venezia Giulia",
    "Lazio": "Lazio",
    "Liguria": "Liguria",
    "Lombardia": "Lombardia",
    "Marche": "Marche",
    "Molise": "Molise",
    "Piemonte": "Piemonte",
    "Sardegna": "Sardinia",
    "Sicily": "Sisilia",
    "Toscana": "Toscana",
    "Trentino-Alto Adige": "Trentino-Alto Adige",
    "Umbria": "Umbria",
    "Veneto": "Veneto",
  },
  TLS: {
    "Aileu": "Aileu",
    "Ainaro": "Ainaro",
    "Baucau": "Baucau",
    "Bobonaro": "Bobonaro",
    "Cova Lima": "Cova Lima",
    "Dili": "Dili",
    "Ermera": "Ermera",
    "Lautém": "Lautem",
    "Liquica": "Liquica",
    "Manatuto": "Manatuto",
    "Manufahi": "Manufahi",
    "Ambeno": "Oecussi",
    "Viqueque": "Viqueque",
  },
  AUT: {
    "Niederösterreich": "Ala-Itävalta",
    "Burgenland": "Burgenland",
    "Kärnten": "Kärnten",
    "Salzburg": "Salzburg",
    "Steiermark": "Steiermark",
    "Tirol": "Tiroli",
    "Vorarlberg": "Vorarlberg",
    "Wien": "Wien",
    "Oberösterreich": "Ylä-Itävalta",
  },
  JPN: {
    "Aichi": "Aichi",
    "Akita": "Akita",
    "Aomori": "Aomori",
    "Chiba": "Chiba",
    "Ehime": "Ehime",
    "Fukui": "Fukui",
    "Fukuoka": "Fukuoka",
    "Fukushima": "Fukushima",
    "Gifu": "Gifu",
    "Gunma": "Gunma",
    "Hiroshima": "Hiroshima",
    "Hokkaidō": "Hokkaidō",
    "Hyōgo": "Hyōgo",
    "Ibaraki": "Ibaraki",
    "Ishikawa": "Ishikawa",
    "Iwate": "Iwate",
    "Kagawa": "Kagawa",
    "Kagoshima": "Kagoshima",
    "Kanagawa": "Kanagawa",
    "Kyōto": "Kioto",
    "Kōchi": "Kōchi",
    "Kumamoto": "Kumamoto",
    "Mie": "Mie",
    "Miyagi": "Miyagi",
    "Miyazaki": "Miyazaki",
    "Nagano": "Nagano",
    "Nagasaki": "Nagasaki",
    "Nara": "Nara",
    "Niigata": "Niigata",
    "Ōita": "Ōita",
    "Okayama": "Okayama",
    "Okinawa": "Okinawa",
    "Ōsaka": "Osaka",
    "Saga": "Saga",
    "Saitama": "Saitama",
    "Shiga": "Shiga",
    "Shimane": "Shimane",
    "Shizuoka": "Shizuoka",
    "Tochigi": "Tochigi",
    "Tokyo": "Tokio",
    "Tokushima": "Tokushima",
    "Tottori": "Tottori",
    "Toyama": "Toyama",
    "Wakayama": "Wakayama",
    "Yamagata": "Yamagata",
    "Yamaguchi": "Yamaguchi",
    "Yamanashi": "Yamanashi",
  },
  YEM: {
    "Abyan": "Abyan",
    "`Adan": "Aden",
    "Al Bayda'": "Al Bayda",
    "Al Dali'": "Al Dali",
    "Al Jawf": "Al Jawf",
    "Al Mahwit": "Al Mahwit",
    "Amran": "Amran",
    "Dhamar": "Dhamar",
    "Hadramawt": "Hadramaut",
    "Hajjah": "Hajjah",
    "Al Hudaydah": "Hodeida",
    "Ibb": "Ibb",
    "Lahij": "Lahij",
    "Al Mahrah": "Mahra",
    "Ma'rib": "Marib",
    "Raymah": "Raima",
    "Sa`dah": "Sa`dah",
    "Shabwah": "Šabwa",
    "Sana'a": "Sanaa",
    "Amanat Al Asimah": "Sanaa",
    "Ta`izz": "Taizz",
  },
  JOR: {
    "Ajlun": "Ajlun",
    "Aqaba": "Al 'Aqabah",
    "Balqa": "Al Balqa'",
    "Karak": "Al Karak",
    "Mafraq": "Al Mafraq",
    "Amman": "Amman",
    "Tafilah": "At Tafilah",
    "Zarqa": "Az Zarqa",
    "Irbid": "Irbid",
    "Jarash": "Jarash",
    "Ma`an": "Ma'an",
    "Madaba": "Madaba",
  },
  KHM: {
    "Bântéay Méanchey": "Bântéay Méancheăy",
    "Batdâmbâng": "Băt Dâmbâng",
    "Kâmpóng Cham": "Kâmpóng Cham",
    "Kâmpóng Chhnang": "Kâmpóng Chhnăng",
    "Kâmpóng Spœ": "Kâmpóng Spœ",
    "Kâmpóng Thum": "Kâmpóng Thum",
    "Kâmpôt": "Kâmpôt",
    "Kândal": "Kândal",
    "Kaôh Kong": "Kaôh Kông",
    "Kep": "Kêb",
    "Krâchéh": "Krâchéh",
    "Môndól Kiri": "Môndôl Kiri",
    "Otdar Mean Chey": "Ŏtâr Méancheăy",
    "Krong Pailin": "Pailĭn",
    "Phnom Penh": "Phnom Penh",
    "Pouthisat": "Poŭthĭsăt",
    "Preah Vihéar": "Preăh Vihéar",
    "Prey Vêng": "Prey Vêng",
    "Rôtânôkiri": "Rôtanak Kiri",
    "Siemréab": "Siĕm Réab",
    "Krong Preah Sihanouk": "Sihanoukville",
    "Stœng Trêng": "Stŏeng Trêng",
    "Svay Rieng": "Svay Riĕng",
    "Takêv": "Takêv",
  },
  CMR: {
    "Adamaoua": "Adamawa",
    "Centre": "Centre",
    "Est": "East",
    "Extrême-Nord": "Extrême-Nord",
    "Littoral": "Littoral",
    "Nord-Ouest": "Luoteisalue",
    "Nord": "North",
    "Sud": "South",
    "Sud-Ouest": "Southwest",
    "Ouest": "West",
  },
  CAN: {
    "Alberta": "Alberta",
    "British Columbia": "Brittiläinen Kolumbia",
    "Northwest Territories": "Luoteisterritoriot",
    "Manitoba": "Manitoba",
    "New Brunswick": "New Brunswick",
    "Newfoundland and Labrador": "Newfoundland ja Labrador",
    "Nova Scotia": "Nova Scotia",
    "Nunavut": "Nunavut",
    "Ontario": "Ontario",
    "Prince Edward Island": "Prinssi Edwardin saari",
    "Québec": "Quebec",
    "Saskatchewan": "Saskatchewan",
    "Yukon": "Yukon",
  },
  KAZ: {
    "Almaty": "Almaty",
    "Almaty City": "Almaty",
    "Aqmola": "Aqmola",
    "Aqtöbe": "Aqtöbe",
    "Astana": "Astana",
    "Atyrau": "Atyrau",
    "East Kazakhstan": "East Kazakhstan",
    "Qyzylorda": "Kyzyl-Orda",
    "Mangghystau": "Mangghystau",
    "North Kazakhstan": "North Kazakhstan",
    "Pavlodar": "Pavlodar",
    "Qaraghandy": "Qaraghandy",
    "Qostanay": "Qostanay",
    "South Kazakhstan": "South Kazakhstan",
    "West Kazakhstan": "West Kazakhstan",
    "Zhambyl": "Zhambyl",
  },
  KEN: {
    "Central": "Keskinen provinssi",
    "Coast": "Rannikkoprovinssi",
    "Eastern": "Itäinen provinssi",
    "North-Eastern": "Koillinen provinssi",
    "Nairobi": "Nairobi",
    "Nyanza": "Nyanza",
    "Rift Valley": "Rift Valley",
    "Western": "Läntinen provinssi",
  },
  CHN: {
    "Anhui": "Anhui",
    "Chongqing": "Chongqing",
    "Fujian": "Fujian",
    "Gansu": "Gansu",
    "Guangdong": "Guangdong",
    "Guangxi": "Guangxi",
    "Guizhou": "Guizhou",
    "Hainan": "Hainan",
    "Henan": "Henan",
    "Hebei": "Hebei",
    "Heilongjiang": "Heilongjiang",
    "Hubei": "Hubei",
    "Hunan": "Hunan",
    "Jiangsu": "Jiangsu",
    "Jiangxi": "Jiangxi",
    "Jilin": "Jilin",
    "Liaoning": "Liaoning",
    "Ningxia": "Ningxia",
    "Paracel Islands": "Paracelsaaret",
    "Beijing": "Peking",
    "Qinghai": "Qinghai",
    "Shaanxi": "Shaanxi",
    "Shandong": "Shandong",
    "Shanghai": "Shanghai",
    "Shanxi": "Shanxi",
    "Sichuan": "Sichuan",
    "Inner Mongol": "Sisä-Mongolia",
    "Tianjin": "Tianjin",
    "Xinjiang": "Xinjiang",
    "Xizang": "Tiibet",
    "Yunnan": "Yunnan",
    "Zhejiang": "Zhejiang",
  },
  KGZ: {
    "Batken": "Batken",
    "Bishkek": "Biškek",
    "Chuy": "Chuy",
    "Naryn": "Naryn",
    "Osh": "Oš",
    "Talas": "Talas",
    "Ysyk-Köl": "Ysyk-Köl",
    "Jalal-Abad": "Žalal-Abad",
  },
  COL: {
    "Amazonas": "Amazonas",
    "Antioquia": "Antioquia",
    "Arauca": "Arauca",
    "Atlántico": "Atlántico",
    "Bogota": "Bogotá",
    "Bolívar": "Bolívar",
    "Boyacá": "Boyacá",
    "Caldas": "Caldas",
    "Caquetá": "Caquetá",
    "Casanare": "Casanare",
    "Cauca": "Cauca",
    "Cesar": "Cesar",
    "Chocó": "Chocó",
    "COL+99?": "COL+99?",
    "Córdoba": "Córdoba",
    "Cundinamarca": "Cundinamarca",
    "Guainía": "Guainía",
    "La Guajira": "Guajira",
    "Guaviare": "Guaviare",
    "Huila": "Huila",
    "Magdalena": "Magdalena",
    "Meta": "Meta",
    "Nariño": "Nariño",
    "Norte de Santander": "Norte de Santander",
    "Putumayo": "Putumayo",
    "Quindío": "Quindío",
    "Risaralda": "Risaralda",
    "San Andrés y Providencia": "San Andrés, Providencia y Santa Catalina",
    "Santander": "Santander",
    "Sucre": "Sucre",
    "Tolima": "Tolima",
    "Valle del Cauca": "Valle del Cauca",
    "Vaupés": "Vaupés",
    "Vichada": "Vichada",
  },
  COD: {
    "Bandundu": "Bandundu",
    "Équateur": "Équateur",
    "Sud-Kivu": "Etelä-Kivu",
    "Kasaï-Occidental": "Kasaï-Occidental",
    "Kasaï-Oriental": "Kasaï-Oriental",
    "Katanga": "Katanga",
    "Bas-Congo": "Keski-Kongo",
    "Kinshasa City": "Kinshasa",
    "Maniema": "Maniema",
    "Orientale": "Orientale",
    "Nord-Kivu": "Pohjois-Kivu",
  },
  GRC: {
    "Ayion Oros": "Athos",
    "Attiki": "Attiki",
    "Ipeiros": "Epeiros",
    "Notio Aigaio": "Etelä-Egean saaret",
    "Anatoliki Makedonia kai Thraki": "Itä-Makedonia ja Traakia",
    "Ionioi Nisoi": "Jooniansaaret",
    "Stereá Elláda": "Keski-Kreikka",
    "Kentriki Makedonia": "Keski-Makedonia",
    "Kriti": "Kreeta",
    "Dytiki Ellada": "Länsi-Kreikka",
    "Dytiki Makedonia": "Länsi-Makedonia",
    "Peloponnisos": "Peloponnesos",
    "Voreio Aigaio": "Pohjois-Egean saaret",
    "Thessalia": "Thessalia",
  },
  HRV: {
    "Bjelovarsko-bilogorska": "Bjelovar-Bilogoran lääni",
    "Brodsko-Posavska": "Brod-Posavinan lääni",
    "Dubrovacko-Neretvanska": "Dubrovnik-Neretvan lääni",
    "Istarska": "Istrian lääni",
    "Karlovacka": "Karlovacin lääni",
    "Koprivničko-Križevačka": "Koprivnica-Križevcin lääni",
    "Krapinsko-Zagorska": "Krapina-Zagorjen lääni",
    "Licko-Senjska": "Lika-Senjin lääni",
    "Medimurska": "Međimurjen lääni",
    "Osjecko-Baranjska": "Osijek-Baranjan lääni",
    "Primorsko-Goranska": "Primorje-Gorski Kotarin lääni",
    "Šibensko-Kninska": "Šibenik-Kninin lääni",
    "Sisacko-Moslavacka": "Sisak-Moslavinan lääni",
    "Splitsko-Dalmatinska": "Split-Dalmatian lääni",
    "Varaždinska": "Varaždinin lääni",
    "Viroviticko-Podravska": "Virovitica-Podravinan lääni",
    "Vukovarsko-Srijemska": "Vukovar-Srijemin lääni",
    "Zadarska": "Zadarin lääni",
    "Zagrebacka": "Zagrebin lääni",
    "Grad Zagreb": "Zagrebin kaupunki",
  },
  CUB: {
    "Artemisa": "Artemisa",
    "Camagüey": "Camagüey",
    "Ciego de Ávila": "Ciego de Ávila",
    "Cienfuegos": "Cienfuegos",
    "Granma": "Granma",
    "Guantánamo": "Guantánamo",
    "Ciudad de la Habana": "Havanna",
    "Holguín": "Holguín",
    "Isla de la Juventud": "Isla de la Juventud",
    "Las Tunas": "Las Tunas",
    "Matanzas": "Matanzas",
    "Mayabeque": "Mayabeque",
    "Pinar del Río": "Pinar del Río",
    "Sancti Spíritus": "Sancti Spíritus",
    "Santiago de Cuba": "Santiago de Cuba",
    "Villa Clara": "Villa Clara",
  },
  KWT: {
    "Al Ahmadi": "Al Ahmadi",
    "Al Asimah": "Al Asimah",
    "Al Farwaniyah": "Al Farwaniyah",
    "Al Jahrah": "Al Jahrah",
    "Hawalli": "Hawalli",
    "Mubarak Al-Kabeer": "Mubarak Al-Kabeer",
  },
  CYP: {
    "Famagusta": "Famagusta",
    "Larnaca": "Larnaca",
    "Limassol": "Limassol",
    "Nicosia": "Nikosia",
    "Paphos": "Paphos",
  },
  LAO: {
    "Attapu": "Attapu",
    "Bokeo": "Bokeo",
    "Bolikhamxai": "Bolikhamxai",
    "Champasak": "Champasak",
    "Houaphan": "Houaphan",
    "Khammouan": "Khammouan",
    "Louang Namtha": "Loung Namtha",
    "Louangphrabang": "Lūang Phabāng",
    "Oudômxai": "Oudomxai",
    "Phôngsali": "Phongsali",
    "Saravan": "Salavan",
    "Savannakhét": "Savannakhet",
    "Vientiane": "Vientiane",
    "Vientiane [prefecture]": "Vientiane [prefecture]",
    "Xaignabouri": "Xaignabouli",
    "Xékong": "Xekong",
    "Xiangkhoang": "Xiangkhouang",
  },
  LVA: {
    "Kurzeme": "Kuramaa",
    "Latgale": "Latgale",
    "Riga": "Riika",
    "Vidzeme": "Vidzeme",
    "Zemgale": "Zemgale",
  },
  LBR: {
    "Bomi": "Bomi",
    "Bong": "Bong",
    "Gbapolu": "Gbarpolu",
    "Grand Bassa": "Grand Bassa",
    "Grand Cape Mount": "Grand Cape Mount",
    "Grand Gedeh": "Grand Gedeh",
    "Grand Kru": "Grand Kru",
    "Lofa": "Lofa",
    "Margibi": "Margibi",
    "Maryland": "Maryland",
    "Montserrado": "Montserrado",
    "Nimba": "Nimba",
    "River Gee": "River Gee",
    "River Cess": "Rivercess",
    "Sinoe": "Sinoe",
  },
  LBY: {
    "Ajdabiya": "Ajdabiya",
    "Al Butnan": "Al Butnan",
    "Al Jabal al Akhdar": "Al Jabal al Akhdar",
    "Al Jifarah": "Al Jifarah",
    "Al Kufrah": "Al Kufrah",
    "Al Marj": "Al Marj",
    "Al Marqab": "Al Marqab",
    "Al Qubbah": "Al Qubbah",
    "Ash Shati'": "Ash Shati'",
    "Benghazi": "Bengasi",
    "Ghadamis": "Ghadamis",
    "Ghat": "Ghat",
    "Al Jufrah": "Jufra",
    "Misratah": "Misratah",
    "Mizdah": "Mizdah",
    "Murzuq": "Murzuq District",
    "An Nuqat al Khams": "Nuqat al Khams",
    "Sabha": "Sabha",
    "Surt": "Surt",
    "Tajura' wa an Nawahi al Arba": "Tajura' wa an Nawahi al Arba",
    "Wadi al Hayaa": "Wadi al Hayaa",
    "Az Zawiyah": "Zawia",
  },
  LTU: {
    "Alytaus": "Alytusin kunnallispiiri",
    "Kauno": "Kaunas",
    "Klaipedos": "Klaipėda",
    "Marijampoles": "Marijampoles",
    "Panevezio": "Panevėžys",
    "Šiauliai": "Šiauliai",
    "Taurages": "Taurages",
    "Telšiai": "Telšiai",
    "Utenos": "Utenos",
    "Vilniaus": "Vilnius",
  },
  LUX: {
    "Diekirch": "Diekirch",
    "Grevenmacher": "Grevenmacher",
    "Luxembourg": "Luxembourg",
  },
  MDG: {
    "Amoron'i Mania": "Amoron'i Mania",
    "Androy": "Androy",
    "Anosy": "Anosy",
    "Analamanga": "Antananarivo",
    "Bongolava": "Antananarivo",
    "Vakinankaratra": "Antananarivo",
    "Itasy": "Antananarivo",
    "Atsimo-Andrefana": "Atsimo-Andrefana",
    "Atsimo-Atsinanana": "Atsimo-Atsinanana",
    "Betsiboka": "Betsiboka",
    "Boeny": "Boeny",
    "Diana": "Diana",
    "Haute Matsiatra": "Haute Matsiatra",
    "Ihorombe": "Ihorombe",
    "Melaky": "Melaky",
    "Menabe": "Menabe",
    "Sava": "Sava",
    "Sofia": "Sofia",
    "Analanjirofo": "Toamasina",
    "Atsinanana": "Toamasina",
    "Alaotra-Mangoro": "Toamasina",
    "Vatovavy-Fitovinany": "Vatovavy-Fitovinany",
  },
  MYS: {
    "Johor": "Johor",
    "Kedah": "Kedah",
    "Kelantan": "Kelantan",
    "Kuala Lumpur": "Kuala Lumpur",
    "Labuan": "Labuan",
    "Melaka": "Malakka",
    "Negeri Sembilan": "Negeri Sembilan",
    "Pahang": "Pahang",
    "Pulau Pinang": "Penang",
    "Perak": "Perak",
    "Perlis": "Perlis",
    "Putrajaya": "Putrajaya",
    "Sabah": "Sabah",
    "Sarawak": "Sarawak",
    "Selangor": "Selangor",
    "Terengganu": "Terengganu",
  },
  MLI: {
    "Bamako": "Bamako",
    "Gao": "Gao",
    "Kayes": "Kayes",
    "Kidal": "Kidal",
    "Koulikoro": "Koulikoro",
    "Mopti": "Mopti",
    "Ségou": "Ségou",
    "Sikasso": "Sikasso",
    "Timbuktu": "Timbuktu",
  },
  MLT: {
    "Southern Harbour": "Eteläinen satama-alue",
    "Gozo and Comino": "Gozo ja Comino",
    "South Eastern": "Kaakkoinen alue",
    "Western": "Läntinen alue",
    "Northern": "Pohjoinen alue",
    "Northern Harbour": "Pohjoinen satama-alue",
  },
  MAR: {
    "Chaouia - Ouardigha": "Chaouia-Ouardigha",
    "Doukkala - Abda": "Doukkala-Abda",
    "Fès - Boulemane": "Fès-Boulemane",
    "Gharb - Chrarda - Béni Hssen": "Gharb-Chrarda-Béni Hssen",
    "Grand Casablanca": "Grand Casablanca",
    "Guelmim - Es-Semara": "Guelmim-Es Semara",
    "Laâyoune - Boujdour - Sakia El Hamra": "Laâyoune-Boujdour-Sakia El Hamra",
    "Marrakech - Tensift - Al Haouz": "Marrakech-Tensift-Al Haouz",
    "Meknès - Tafilalet": "Meknès-Tafilalet",
    "Oriental": "Oriental",
    "Oued el Dahab": "Oued el Dahab",
    "Rabat - Salé - Zemmour - Zaer": "Rabat-Salé-Zemmour-Zaer",
    "Souss - Massa - Draâ": "Souss-Massa-Drâa",
    "Tadla - Azilal": "Tadla-Azilal",
    "Tanger - Tétouan": "Tangier-Tetouan",
    "Taza - Al Hoceima - Taounate": "Taza-Al Hoceima-Taounate",
  },
  MEX: {
    "Aguascalientes": "Aguascalientes",
    "Baja California": "Baja California",
    "Baja California Sur": "Baja California Sur",
    "Campeche": "Campeche",
    "Chiapas": "Chiapas",
    "Chihuahua": "Chihuahua",
    "Coahuila": "Coahuila",
    "Colima": "Colima",
    "Durango": "Durango",
    "Guanajuato": "Guanajuato",
    "Guerrero": "Guerrero",
    "Hidalgo": "Hidalgo",
    "Jalisco": "Jalisco",
    "MEX+99?": "Alacranesin riutta",
    "México": "Méxicon osavaltio",
    "Distrito Federal": "Méxicon kaupunki",
    "Michoacán": "Michoacán",
    "Morelos": "Morelos",
    "Nayarit": "Nayarit",
    "Nuevo León": "Nuevo León",
    "Oaxaca": "Oaxaca",
    "Puebla": "Puebla",
    "Querétaro": "Querétaro",
    "Quintana Roo": "Quintana Roo",
    "San Luis Potosí": "San Luis Potosí",
    "Sinaloa": "Sinaloa",
    "Sonora": "Sonora",
    "Tabasco": "Tabasco",
    "Tamaulipas": "Tamaulipas",
    "Tlaxcala": "Tlaxcala",
    "Veracruz": "Veracruz",
    "Yucatán": "Yucatán",
    "Zacatecas": "Zacatecas",
  },
  MDA: {
    "Anenii Noi": "Anenii Noi",
    "Bălţi": "Bălți",
    "Basarabeasca": "Basarabeasca",
    "Bender": "Bender",
    "Briceni": "Briceni",
    "Cahul": "Cahul",
    "Călărași": "Călărași",
    "Camenca": "Camenca",
    "Cantemir": "Cantemir",
    "Causeni": "Căușeni",
    "Chişinău": "Chișinău",
    "Cimişlia": "Cimișlia",
    "Comrat": "Comrat",
    "Criuleni": "Criuleni",
    "Donduseni": "Dondușeni",
    "Drochia": "Drochia",
    "Edineţ": "Edineț",
    "Făleşti": "Fălești",
    "Floreşti": "Florești",
    "Glodeni": "Glodeni",
    "Grigoriopol": "Grigoriopol",
    "Hîncesti": "Hîncești",
    "Ialoveni": "Ialoveni",
    "Leova": "Leova",
    "Nisporeni": "Nisporeni",
    "Ocniţa": "Ocnița",
    "Orhei": "Orhei",
    "Rezina": "Rezina",
    "Rîşcani": "Rîșcani",
    "Sîngerei": "Sîngerei",
    "Şoldăneşti": "Șoldănești",
    "Soroca": "Soroca",
    "Ștefan Vodă": "Ștefan Vodă",
    "Stîngă Nistrului": "Stînga Nistrului",
    "Străşeni": "Strășeni",
    "Taraclia": "Taraclia",
    "Teleneşti": "Telenești",
    "Transnistria": "Transnistria",
    "Ungheni": "Ungheni",
  },
  MNG: {
    "Arhangay": "Arkhangai",
    "Bayan-Ölgiy": "Bajan-Ölgii",
    "Bayanhongor": "Bajanhongor",
    "Bulgan": "Bulgan",
    "Darhan-Uul": "Darhan-Uul",
    "Dornod": "Dornod",
    "Dornogovi": "Dornogovi",
    "Dundgovi": "Dundgovi",
    "Govi-Altay": "Govi-Altai",
    "Govĭ-Sümber": "Govisumber",
    "Hentiy": "Hentii",
    "Hovd": "Hovd",
    "Hövsgöl": "Hövsgöl",
    "Orhon": "Orhon",
    "Selenge": "Selenge",
    "Sühbaatar": "Sühbaatar",
    "Töv": "Tuv",
    "Ulaanbaatar": "Ulan Bator",
    "Uvs": "Uvs",
    "Dzavhan": "Zavhan",
    "Ömnögovi": "Ömnögovi",
    "Övörhangay": "Övörhangai",
  },
  MNE: {
    "Andrijevica": "Andrijevica",
    "Bar": "Bar",
    "Berane": "Berane",
    "Bijelo Polje": "Bijelo Polje",
    "Budva": "Budva",
    "Cetinje": "Cetinje",
    "Danilovgrad": "Danilovgrad",
    "Herceg Novi": "Herceg Novi",
    "Kolašin": "Kolašin",
    "Kotor": "Kotor",
    "Mojkovac": "Mojkovac",
    "Nikšic": "Nikšić",
    "Plav": "Plav",
    "Pljevlja": "Pljevlja",
    "Plužine": "Plužine",
    "Podgorica": "Podgorica",
    "Rožaje": "Rožaje",
    "Šavnik": "Šavnik",
    "Tivat": "Tivat",
    "Ulcinj": "Ulcinj",
    "Žabljak": "Žabljak",
  },
  MOZ: {
    "Cabo Delgado": "Cabo Delgado",
    "Gaza": "Gaza",
    "Inhambane": "Inhambane",
    "Manica": "Manica",
    "Maputo": "Maputo",
    "Nampula": "Nampula",
    "Niassa": "Niassa",
    "Sofala": "Sofala",
    "Tete": "Tete",
    "Zambezia": "Zambezia",
  },
  MMR: {
    "Ayeyarwady": "Ayeyarwady",
    "Bago": "Bago",
    "Chin": "Chin",
    "Kachin": "Kachin",
    "Kayah": "Kayah",
    "Kayin": "Kayin",
    "Magway": "Magway",
    "Mandalay": "Mandalay",
    "Mon": "Mon",
    "Rakhine": "Rakhine",
    "Sagaing": "Sagaing",
    "Shan": "Shan",
    "Tanintharyi": "Tanintharyi",
    "Yangon": "Yangon",
  },
  NAM: {
    "Caprivi": "Caprivi",
    "Erongo": "Erongo",
    "Hardap": "Hardap",
    "Karas": "Karas",
    "Kavango": "Kavango",
    "Khomas": "Khomas",
    "Kunene": "Kunene",
    "Ohangwena": "Ohangwena",
    "Omaheke": "Omaheke",
    "Omusati": "Omusati",
    "Oshana": "Oshana",
    "Oshikoto": "Oshikoto",
    "Otjozondjupa": "Otjozondjupa",
  },
  NPL: {
    "Bagmati": "Bagmati",
    "Bheri": "Bheri",
    "Bhojpur": "Bhojpur",
    "Dhawalagiri": "Dhawalagiri",
    "Gandaki": "Gandaki",
    "Janakpur": "Janakpur",
    "Karnali": "Karnali",
    "Lumbini": "Lumbini",
    "Mahakali": "Mahakali",
    "Mechi": "Mechi",
    "Narayani": "Narayani",
    "Rapti": "Rapti",
    "Sagarmatha": "Sagarmatha",
    "Seti": "Seti",
  },
  NIC: {
    "Atlántico Norte": "Atlántico Norte",
    "Atlántico Sur": "Atlántico Sur",
    "Boaco": "Boaco",
    "Carazo": "Carazo",
    "Chinandega": "Chinandega",
    "Chontales": "Chontales",
    "Estelí": "Estelí",
    "Granada": "Granada",
    "Jinotega": "Jinotega",
    "León": "León",
    "Madriz": "Madrizin depatermentti",
    "Managua": "Managua",
    "Masaya": "Masaya",
    "Matagalpa": "Matagalpa",
    "Nueva Segovia": "Nueva Segovia",
    "Rio San Juan": "Rio San Juan",
    "Rivas": "Rivas",
  },
  NGA: {
    "Abia": "Abia",
    "Adamawa": "Adamawa",
    "Akwa Ibom": "Akwa Ibom",
    "Anambra": "Anambra",
    "Bauchi": "Bauchi",
    "Bayelsa": "Bayelsa",
    "Benue": "Benue",
    "Borno": "Borno",
    "Cross River": "Cross River",
    "Delta": "Delta",
    "Ebonyi": "Ebonyi",
    "Edo": "Edo",
    "Ekiti": "Ekiti",
    "Enugu": "Enugu",
    "Gombe": "Gombe",
    "Imo": "Imo",
    "Jigawa": "Jigawa",
    "Kaduna": "Kaduna",
    "Kano": "Kano",
    "Katsina": "Katsina",
    "Kebbi": "Kebbi",
    "Kogi": "Kogi",
    "Kwara": "Kwara",
    "Lagos": "Lagos",
    "Nassarawa": "Nasarawa",
    "Niger": "Niger",
    "Ogun": "Ogun",
    "Ondo": "Ondo",
    "Osun": "Osun",
    "Oyo": "Oyo",
    "Plateau": "Plateau",
    "Federal Capital Territory": "Pääkaupunkiterritorio",
    "Rivers": "Rivers",
    "Sokoto": "Sokoto",
    "Taraba": "Taraba",
    "Yobe": "Yobe",
    "Zamfara": "Zamfara",
  },
  NFK: {},
  NOR: {
    "Akershus": "Akershus",
    "Aust-Agder": "Aust-Agder",
    "Bouvet Island": "Bouvet Island",
    "Buskerud": "Buskerud",
    "Finnmark": "Finnmark",
    "Hedmark": "Hedmark",
    "Hordaland": "Hordaland",
    "Svalbard": "Huippuvuoret",
    "Møre og Romsdal": "Møre og Romsdal",
    "Nord-Trøndelag": "Nord-Trøndelag",
    "Nordland": "Nordland",
    "Oppland": "Oppland",
    "Oslo": "Oslo",
    "Rogaland": "Rogaland",
    "Sogn og Fjordane": "Sogn og Fjordane",
    "Sør-Trøndelag": "Sør-Trøndelag",
    "Telemark": "Telemark",
    "Troms": "Troms",
    "Vest-Agder": "Vest-Agder",
    "Vestfold": "Vestfold",
    "Østfold": "Østfold",
  },
  OMN: {
    "Al Batnah North": "Al Batnah North",
    "Al Batnah South": "Al Batnah South",
    "Al Buraymi": "Al-Buraimi",
    "Ad Dakhliyah": "Al-Dakhiliyya",
    "Al Wusta": "Al-Wusta",
    "Al Dhahira": "Al-Zahira",
    "Ash Sharqiyah North": "Ash Sharqiyah North",
    "Ash Sharqiyah South": "Ash Sharqiyah South",
    "Dhofar": "Dhofar",
    "Musandam": "Musandam",
    "Muscat": "Muscat",
  },
  PAK: {
    "Azad Kashmir": "Azad Kashmir",
    "Baluchistan": "Balochistan",
    "F.C.T.": "F.C.T.",
    "Northern Areas": "Gilgit-Baltistan",
    "K.P.": "Khyber Pakhtunkhwa",
    "F.A.T.A.": "Pakistanin heimoalueet",
    "Punjab": "Punjab",
    "Sind": "Sindh",
  },
  PAN: {
    "Bocas del Toro": "Bocas del Toro",
    "Chiriquí": "Chiriquí",
    "Coclé": "Coclé",
    "Colón": "Colón",
    "Darién": "Darién",
    "Emberá": "Emberá-Wounaan Comarca",
    "Kuna Yala": "Guna Yala",
    "Herrera": "Herrera",
    "Los Santos": "Los Santos",
    "Ngöbe Buglé": "Ngöbe-Buglé Comarca",
    "Panama": "Panama",
    "Veraguas": "Veraguas",
  },
  PNG: {
    "North Solomons": "Bougainville",
    "Chimbu": "Chimbu",
    "East Sepik": "Itä-Sepik",
    "Eastern Highlands": "Eastern Highlands",
    "Enga": "Enga",
    "Gulf": "Gulf",
    "East New Britain": "Itäinen Uusi-Britannia",
    "Central": "Keskinen provinssi",
    "West New Britain": "Läntinen Uusi-Britannia",
    "Madang": "Madang",
    "Manus": "Manus",
    "Milne Bay": "Milne Bay",
    "Morobe": "Morobe",
    "Northern": "Oro",
    "National Capital District": "Port Moresby",
    "Sandaun": "Sandaun",
    "Southern Highlands": "Southern Highlands",
    "New Ireland": "Uusi-Irlanti",
    "Western": "Läntinen provinssi",
    "Western Highlands": "Western Highlands",
  },
  PRY: {
    "Alto Paraguay": "Alto Paraguay",
    "Alto Paraná": "Alto Paraná",
    "Amambay": "Amambay",
    "Asunción": "Asunción",
    "Boquerón": "Boquerón",
    "Caaguazú": "Caaguazú",
    "Caazapá": "Caazapá",
    "Canindeyú": "Canindeyú",
    "Central": "Central",
    "Concepción": "Concepción",
    "Cordillera": "Cordillera",
    "Guairá": "Guairá",
    "Itapúa": "Itapúa",
    "Misiones": "Misiones",
    "Ñeembucú": "Ñeembucú",
    "Paraguarí": "Paraguarí",
    "Presidente Hayes": "Presidente Hayes",
    "San Pedro": "San Pedro",
  },
  PER: {
    "Amazonas": "Amazonas",
    "Áncash": "Ancash",
    "Apurímac": "Apurímac",
    "Arequipa": "Arequipa",
    "Ayacucho": "Ayacucho",
    "Cajamarca": "Cajamarca",
    "Callao": "Callao",
    "Cusco": "Cusco",
    "Huancavelica": "Huancavelica",
    "Huánuco": "Huánuco",
    "Ica": "Ica",
    "Junín": "Junín",
    "La Libertad": "La Libertad",
    "Lambayeque": "Lambayeque",
    "Lima": "Liman metropolialue",
    "Lima Province": "Liman metropolialue",
    "Loreto": "Loreto",
    "Madre de Dios": "Madre de Dios",
    "Moquegua": "Moquegua",
    "Pasco": "Pasco",
    "Piura": "Piura",
    "Puno": "Puno",
    "San Martín": "San Martín",
    "Tacna": "Tacna",
    "Tumbes": "Tumbes",
    "Ucayali": "Ucayali",
  },
  PRK: {
    "Chagang-do": "Chagang",
    "Hamgyŏng-namdo": "Etelä-Hamgyŏng",
    "Hwanghae-namdo": "Etelä-Hwanghae",
    "P'yŏngan-namdo": "Etelä-P'yŏngan",
    "Kangwŏn-do": "Kangwŏn",
    "P'yŏngyang": "Pjongjang",
    "Hamgyŏng-bukto": "Pohjois-Hamgyŏng",
    "Hwanghae-bukto": "Pohjois-Hwanghae",
    "P'yŏngan-bukto": "Pohjois-P'yŏngan",
    "Rasŏn": "Rasŏn",
    "Ryanggang": "Ryanggang",
  },
  MKD: {
    "Eastern": "Itäinen alue",
    "Southeastern": "Kaakkoinen alue",
    "Northeastern": "Koillinen alue",
    "Southwestern": "Lounainen alue",
    "Pelagonia": "Pelagonia",
    "Polog": "Polog",
    "Skopje": "Skopje",
    "Vardar": "Vardar",
  },
  PRT: {
    "Aveiro": "Aveiro",
    "Azores": "Azorit",
    "Beja": "Beja",
    "Braga": "Braga",
    "Bragança": "Bragança",
    "Castelo Branco": "Castelo Branco",
    "Coimbra": "Coimbra",
    "Évora": "Évora",
    "Faro": "Faro",
    "Guarda": "Guarda",
    "Leiria": "Leiria",
    "Lisboa": "Lissabon",
    "Madeira": "Madeira",
    "Portalegre": "Portalegre",
    "Porto": "Porto",
    "Santarém": "Santarém",
    "Setúbal": "Setúbal",
    "Viana do Castelo": "Viana do Castelo",
    "Vila Real": "Vila Real",
    "Viseu": "Viseu",
  },
  PRI: {},
  POL: {
    "Lower Silesian": "Ala-Sleesia",
    "Kuyavian-Pomeranian": "Kujavia-Pommeri",
    "Łódź": "Łódź",
    "Lublin": "Lublin",
    "Lubusz": "Lubuskie",
    "West Pomeranian": "Länsi-Pommeri",
    "Masovian": "Masovia",
    "Opole": "Opole",
    "Subcarpathian": "Podkarpackie",
    "Podlachian": "Podlasia",
    "Pomeranian": "Pommeri",
    "Silesian": "Sleesia",
    "Greater Poland": "Suur-Puola",
    "Świętokrzyskie": "Świętokrzyskie",
    "Warmian-Masurian": "Varmia-Masuria",
    "Lesser Poland": "Vähä-Puola",
  },
  QAT: {
    "Al Daayen": "Al-Dayyan",
    "Al Khawr": "Al-Khawr",
    "Ar Rayyān": "Al-Rayyan",
    "Madinat ach Shamal": "Al-Šamal",
    "Al Wakrah": "Al-Wakrah",
    "Ad Dawhah": "Doha",
    "Umm Salal": "Umm Salal",
  },
  FRA: {
    "Auvergne-Rhône-Alpes": "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté": "Bourgogne-Franche-Comté",
    "Bretagne": "Bretagne",
    "Centre-Val de Loire": "Centre-Val de Loire",
    "Corse": "Corse",
    "Grand Est": "Grand Est",
    "Guadeloupe": "Guadeloupe",
    "Guyane française": "Guyane française",
    "Hauts-de-France": "Hauts-de-France",
    "Île-de-France": "Île-de-France",
    "Martinique": "Martinique",
    "Mayotte": "Mayotte",
    "Normandie": "Normandie",
    "Nouvelle-Aquitaine": "Nouvelle-Aquitaine",
    "Occitanie": "Occitanie",
    "Pays de la Loire": "Pays de la Loire",
    "Provence-Alpes-Côte-d'Azur": "Provence-Alpes-Côte-d'Azur",
    "Réunion": "Réunion",
  },
  GUF: {},
  ROU: {
    "Alba": "Alba",
    "Arad": "Arad",
    "Arges": "Argeș",
    "Bacau": "Bacău",
    "Bihor": "Bihor",
    "Bistrita-Nasaud": "Bistrița-Năsăud",
    "Botosani": "Botoșani",
    "Braila": "Brăila",
    "Brasov": "Brașov",
    "Bucharest": "Bukarest",
    "Buzau": "Buzău",
    "Calarasi": "Călărași",
    "Caras-Severin": "Caraș-Severin",
    "Cluj": "Cluj",
    "Constanta": "Constanța",
    "Covasna": "Covasna",
    "Dâmbovita": "Dâmbovița",
    "Dolj": "Dolj",
    "Galati": "Galați",
    "Giurgiu": "Giurgiu",
    "Gorj": "Gorj",
    "Harghita": "Harghita",
    "Hunedoara": "Hunedoara",
    "Ialomita": "Ialomița",
    "Iasi": "Iași",
    "Ilfov": "Ilfov",
    "Maramures": "Maramureș",
    "Mehedinti": "Mehedinți",
    "Mures": "Mureș",
    "Neamt": "Neamț",
    "Olt": "Olt",
    "Prahova": "Prahova",
    "Salaj": "Sălaj",
    "Satu Mare": "Satu Mare",
    "Sibiu": "Sibiu",
    "Suceava": "Suceava",
    "Teleorman": "Teleorman",
    "Timis": "Timiș",
    "Tulcea": "Tulcea",
    "Vâlcea": "Vâlcea",
    "Vaslui": "Vaslui",
    "Vrancea": "Vrancea",
  },
  SWE: {
    "Blekinge": "Blekinge",
    "Dalarna": "Dalarna",
    "Gotland": "Gotland",
    "Gävleborg": "Gävleborg",
    "Halland": "Halland",
    "Jämtland": "Jämtland",
    "Jönköping": "Jönköping",
    "Kalmar": "Kalmar",
    "Kronoberg": "Kronoberg",
    "Norrbotten": "Norrbotten",
    "Skåne": "Skåne",
    "Stockholm": "Stockholm",
    "Södermanland": "Södermanland",
    "Uppsala": "Uppsala",
    "Värmland": "Värmland",
    "Västerbotten": "Västerbotten",
    "Västernorrland": "Västernorrland",
    "Västmanland": "Västmanland",
    "Västra Götaland": "Västra Götaland",
    "Orebro": "Örebro",
    "Östergötland": "Östergötland",
  },
  SHN: {
    "Ascension": "Ascension",
    "Saint Helena": "Saint Helena",
    "Tristan da Cunha": "Tristan da Cunha",
  },
  DEU: {
    "Niedersachsen": "Ala-Saksi",
    "Baden-Württemberg": "Baden-Württemberg",
    "Bayern": "Baijeri",
    "Berlin": "Berliini",
    "Brandenburg": "Brandenburg",
    "Bremen": "Bremen",
    "Hamburg": "Hampuri",
    "Hessen": "Hessen",
    "Mecklenburg-Vorpommern": "Mecklenburg-Etu-Pommeri",
    "Nordrhein-Westfalen": "Nordrhein-Westfalen",
    "Rheinland-Pfalz": "Rheinland-Pfalz",
    "Saarland": "Saarland",
    "Sachsen": "Saksi",
    "Sachsen-Anhalt": "Saksi-Anhalt",
    "Schleswig-Holstein": "Schleswig-Holstein",
    "Thüringen": "Thüringen",
  },
  SLB: {
    "Central": "Keskinen provinssi",
    "Choiseul": "Choiseul",
    "Guadalcanal": "Guadalcanal",
    "Capital Territory (Honiara)": "Honiara",
    "Isabel": "Isabel",
    "Makira": "Makira",
    "Malaita": "Malaita",
    "Rennell and Bellona": "Rennell ja Bellona",
    "Temotu": "Temotu",
    "Western": "Läntinen provinssi",
  },
  SAU: {
    "Al Bahah": "Al Bahah",
    "Al Hudud ash Shamaliyah": "Al Hudud ash Shamaliyah",
    "Al Jawf": "Al Jawf",
    "Al Madinah": "Al Madinah",
    "Al Quassim": "Al Qasim",
    "Ash Sharqiyah": "Al-Šarqiyya",
    "Ar Riyad": "Ar Riyad",
    "`Asir": "Asir",
    "Ha'il": "Ha'il",
    "Jizan": "Jizan",
    "Makkah": "Makkah",
    "Najran": "Najran",
    "Tabuk": "Tabuk",
  },
  SEN: {
    "Dakar": "Dakar",
    "Diourbel": "Diourbel",
    "Fatick": "Fatick",
    "Kaffrine": "Kaffrine",
    "Kaolack": "Kaolack",
    "Kédougou": "Kédougou",
    "Kolda": "Kolda",
    "Louga": "Louga",
    "Matam": "Matam",
    "Saint-Louis": "Saint-Louis",
    "Sédhiou": "Sédhiou",
    "Tambacounda": "Tambacounda",
    "Thiès": "Thiès",
    "Ziguinchor": "Ziguinchor",
  },
  SRB: {
    "Grad Beograd": "Belgrad",
    "Borski": "Bor",
    "Branicevski": "Braničevo",
    "Južno-Backi": "Etelä-Bačka",
    "Jablanicki": "Jablanica",
    "Srednje-Banatski": "Keski-Banat",
    "Kolubarski": "Kolubara",
    "Zapadno-Backi": "Länsi-Bačka",
    "Macvanski": "Mačva",
    "Moravicki": "Moravica",
    "Nišavski": "Nišava",
    "Severno-Banatski": "Pohjois-Banat",
    "Pcinjski": "Pčinja",
    "Pirotski": "Pirot",
    "Podunavski": "Podunavlje",
    "Severno-Backi": "Pohjois-Bačka",
    "Pomoravski": "Pomoravlje",
    "Raški": "Raška",
    "Južno-Banatski": "Etelä-Banat",
    "Sremski": "Srem",
    "Šumadijski": "Šumadija",
    "Toplicki": "Toplica",
    "Zajecarski": "Zaječar",
    "Zlatiborski": "Zlatibor",
  },
  SLE: {
    "Eastern": "Eastern",
    "Northern": "Northern",
    "Southern": "Southern",
    "Western": "Western",
  },
  SGP: {
    "Central Singapore": "Keski-Singapore",
    "North East": "Koillis-Singapore",
    "North West": "Luoteis-Singapore",
    "South East": "Kaakkois-Singapore",
    "South West": "Lounais-Singapore",
  },
  SVK: {
    "Banskobystrický": "Banská Bystrica",
    "Bratislavský": "Bratislavský",
    "Košický": "Košický",
    "Nitriansky": "Nitra",
    "Prešov": "Prešov",
    "Trenciansky": "Trenciansky",
    "Trnavský": "Trnavský",
    "Žilinský": "Žilinský",
  },
  SVN: {
    "Gorenjska": "Gorenjska",
    "Goriška": "Goriška",
    "Jugovzhodna Slovenija": "Jugovzhodna Slovenija",
    "Koroška": "Koroška",
    "Notranjsko-kraška": "Notranjsko-kraška",
    "Obalno-kraška": "Obalno-kraška",
    "Osrednjeslovenska": "Osrednjeslovenska",
    "Podravska": "Podravska",
    "Pomurska": "Pomurska",
    "Savinjska": "Savinjska",
    "Spodnjeposavska": "Spodnjeposavska",
    "Zasavska": "Zasavska",
  },
  SOM: {
    "Jubbada Hoose": "Ala-Juba",
    "Bakool": "Bakool",
    "Banaadir": "Banaadir",
    "Bari": "Bari",
    "Bay": "Bay",
    "Galguduud": "Galguduud",
    "Gedo": "Gedo",
    "Hiiraan": "Hiiraan",
    "Jubbada Dhexe": "Keski-Juba",
    "Mudug": "Mudug",
    "Nugaal": "Nugaal",
    "Shabeellaha Dhexe": "Shabeellaha Dhexe",
    "Shabeellaha Hoose": "Shabeellaha Hoose",
  },
  LKA: {
    "Ampāra": "Amparai",
    "Anurādhapura": "Anuradhapura",
    "Badulla": "Badulla",
    "Maḍakalapuva": "Batticaloa",
    "Kŏḷamba": "Colombo",
    "Gālla": "Galle",
    "Gampaha": "Gampaha",
    "Hambantŏṭa": "Hambantota",
    "Yāpanaya": "Jaffna",
    "Kaḷutara": "Kalutara",
    "Kægalla": "Kegalla",
    "Kilinŏchchi": "Kilinochchi",
    "Kuruṇægala": "Kurunegala",
    "Mahanuvara": "Mahanuvara",
    "Mannārama": "Mannar",
    "Mātale": "Matale",
    "Mātara": "Matara",
    "Mŏṇarāgala": "Moneragala",
    "Mulativ": "Mullaitivu",
    "Nuvara Ĕliya": "Nuwara Eliya",
    "Pŏḷŏnnaruva": "Polonnaruwa",
    "Puttalama": "Puttalama",
    "Ratnapura": "Ratnapura",
    "Trikuṇāmalaya": "Trincomalee",
    "Vavuniyāva": "Vavuniyāva",
  },
  SDN: {
    "Gezira": "Al Jazirah",
    "Gedarif": "Al Qadarif",
    "Red Sea": "Al-Bahr al-Ahmar",
    "White Nile": "An-Nil al-Abyad",
    "Blue Nile": "An-Nil al-Azraq",
    "Northern": "Aš-Šamaliya",
    "Southern Darfur": "Etelä-Darfur",
    "South Kordufan": "Etelä-Kordofan",
    "Eastern Darfur": "Itä-Darfur",
    "Kassala": "Kassala",
    "Central Darfur": "Keski-Darfur",
    "Khartoum": "Khartoum",
    "Western Darfur": "Länsi-Darfur",
    "River Nile": "Nahr an-Nil",
    "North Darfur": "Pohjois-Darfur",
    "North Kordufan": "Pohjois-Kordofan",
    "Sennar": "Sennar",
  },
  FIN: {
    "South Karelia": "Etelä-Karjala",
    "Southern Ostrobothnia": "Etelä-Pohjanmaa",
    "Southern Savonia": "Etelä-Savo",
    "Kainuu": "Kainuu",
    "Tavastia Proper": "Kanta-Häme",
    "Central Ostrobothnia": "Keski-Pohjanmaa",
    "Central Finland": "Keski-Suomi",
    "Kymenlaakso": "Kymenlaakso",
    "Lapland": "Lappi",
    "Pirkanmaa": "Pirkanmaa",
    "Ostrobothnia": "Pohjanmaa",
    "North Karelia": "Pohjois-Karjala",
    "Northern Ostrobothnia": "Pohjois-Pohjanmaa",
    "Northern Savonia": "Pohjois-Savo",
    "Päijät-Häme": "Päijät-Häme",
    "Satakunta": "Satakunta",
    "Uusimaa": "Uusimaa",
    "Finland Proper": "Varsinais-Suomi",
  },
  CHE: {
    "Aargau": "Aargau",
    "Appenzell Ausserrhoden": "Appenzell Ausserrhoden",
    "Appenzell Innerrhoden": "Appenzell Innerrhoden",
    "Basel-Landschaft": "Basel-Landschaft",
    "Basel-Stadt": "Basel-Stadt",
    "Bern": "Bern",
    "Fribourg": "Fribourg",
    "Genève": "Geneve",
    "Glarus": "Glarus",
    "Graubünden": "Graubünden",
    "Jura": "Jura",
    "Lucerne": "Luzern",
    "Neuchâtel": "Neuchâtel",
    "Nidwalden": "Nidwalden",
    "Obwalden": "Obwalden",
    "Schaffhausen": "Schaffhausen",
    "Schwyz": "Schwyz",
    "Solothurn": "Solothurn",
    "Sankt Gallen": "St. Gallen",
    "Thurgau": "Thurgau",
    "Ticino": "Ticino",
    "Uri": "Uri",
    "Valais": "Valais",
    "Vaud": "Vaud",
    "Zug": "Zug",
    "Zürich": "Zürich",
  },
  SYR: {
    "Aleppo": "Aleppo",
    "Ar Raqqah": "Ar Raqqah",
    "As Suwayda'": "As Suwayda'",
    "Damascus": "Damascus",
    "Dar`a": "Dar`a",
    "Dayr Az Zawr": "Dayr Az Zawr",
    "Hamah": "Hamah",
    "Hasaka (Al Haksa)": "Hasaka (Al Haksa)",
    "Homs (Hims)": "Homs",
    "Idlib": "Idlib",
    "Lattakia": "Latakia",
    "Quneitra": "Quneitra",
    "Rif Dimashq": "Rif Dimashq",
    "Tartus": "Tartus",
    "UNDOF": "UNDOF",
  },
  TJK: {
    "Dushanbe": "Dušanbe",
    "Gorno-Badakhshan": "Gorno-Badakhshan",
    "Tadzhikistan Territories": "Hallinnon alaiset piirit",
    "Khatlon": "Hatlon",
    "Leninabad": "Hudžand",
  },
  TWN: {
    "Changhua": "Changhua",
    "Chiayi": "Chiayi",
    "Chiayi City": "Chiayi City",
    "Hsinchu": "Hsinchu",
    "Hsinchu City": "Hsinchu",
    "Hualien": "Hualien",
    "Kaohsiung City": "Kaohsiung",
    "Keelung City": "Keelung",
    "Kinmen": "Kinmen",
    "Miaoli": "Miaoli",
    "Nantou": "Nantou",
    "Penghu": "Peskadorit",
    "Pingtung": "Pingtung",
    "Taichung City": "Taichung City",
    "Tainan City": "Tainan",
    "Taipei City": "Taipei",
    "Taitung": "Taitung",
    "Taoyuan": "Taoyuan City",
    "New Taipei City": "Uusi-Taipei",
    "Yilan": "Yilan",
    "Yunlin": "Yunlin",
  },
  TZA: {
    "Arusha": "Arusha",
    "Dar-Es-Salaam": "Dar es Salaam",
    "Dodoma": "Dodoma",
    "Geita": "Geita",
    "Iringa": "Iringa",
    "Kagera": "Kagera",
    "Kaskazini-Pemba": "Kaskazini-Pemba",
    "Katavi": "Katavi",
    "Kigoma": "Kigoma",
    "Kilimanjaro": "Kilimanjaro",
    "Kusini-Pemba": "Kusini-Pemba",
    "Lindi": "Lindi",
    "Manyara": "Manyara",
    "Mara": "Mara",
    "Mbeya": "Mbeya",
    "Morogoro": "Morogoro",
    "Mtwara": "Mtwara",
    "Mwanza": "Mwanza",
    "Njombe": "Njombe",
    "Pwani": "Pwani",
    "Rukwa": "Rukwa",
    "Ruvuma": "Ruvuma",
    "Shinyanga": "Shinyanga",
    "Simiyu": "Simiyu",
    "Singida": "Singida",
    "Tabora": "Tabora",
    "Tanga": "Tanga",
    "Kaskazini-Unguja": "Zanzibar North",
    "Zanzibar South and Central": "Zanzibar South and Central",
    "Zanzibar West": "Zanzibar Urban/West Region",
  },
  DNK: {
    "Midtjylland": "Midtjylland",
    "Nordjylland": "Nordjylland",
    "Hovedstaden": "Pääkaupunkialue",
    "Sjaælland": "Sjaælland",
    "Syddanmark": "Syddanmark",
  },
  THA: {
    "Amnat Charoen": "Amnat Charoen",
    "Ang Thong": "Ang Thong",
    "Bangkok Metropolis": "Bangkok",
    "Bueng Kan": "Bueng Kan",
    "Buri Ram": "Buri Ram",
    "Chachoengsao": "Chachoengsao",
    "Chai Nat": "Chai Nat",
    "Chaiyaphum": "Chaiyaphum",
    "Chanthaburi": "Chanthaburi",
    "Chiang Mai": "Chiang Mai",
    "Chiang Rai": "Chiang Rai",
    "Chon Buri": "Chon Buri",
    "Chumphon": "Chumphon",
    "Kalasin": "Kalasin",
    "Kamphaeng Phet": "Kamphaeng Phet",
    "Kanchanaburi": "Kanchanaburi",
    "Khon Kaen": "Khon Kaen",
    "Krabi": "Krabi",
    "Lampang": "Lampang",
    "Lamphun": "Lamphun",
    "Loei": "Loei",
    "Lop Buri": "Lop Buri",
    "Mae Hong Son": "Mae Hong Son",
    "Maha Sarakham": "Maha Sarakham",
    "Mukdahan": "Mukdahan",
    "Nakhon Pathom": "Nakhon Pathom",
    "Nakhon Phanom": "Nakhon Phanom",
    "Nakhon Ratchasima": "Nakhon Ratchasima",
    "Nakhon Sawan": "Nakhon Sawan",
    "Nakhon Si Thammarat": "Nakhon Si Thammarat",
    "Nakhon Nayok": "Nakhon Nayok",
    "Nan": "Nan",
    "Narathiwat": "Narathiwat",
    "Nong Bua Lam Phu": "Nong Bua Lam Phu",
    "Nong Khai": "Nong Khai",
    "Nonthaburi": "Nonthaburi",
    "Pathum Thani": "Pathum Thani",
    "Pattani": "Pattani",
    "Phangnga": "Phang Nga",
    "Phatthalung": "Phatthalung",
    "Phayao": "Phayao",
    "Phetchabun": "Phetchabun",
    "Phetchaburi": "Phetchaburi",
    "Phichit": "Phichit",
    "Phitsanulok": "Phitsanulok",
    "Phra Nakhon Si Ayutthaya": "Phra Nakhon Si Ayutthaya",
    "Phrae": "Phrae",
    "Phuket": "Phuket",
    "Prachin Buri": "Prachin Buri",
    "Prachuap Khiri Khan": "Prachuap Khiri Khan",
    "Ranong": "Ranong",
    "Ratchaburi": "Ratchaburi",
    "Rayong": "Rayong",
    "Roi Et": "Roi Et",
    "Sa Kaeo": "Sa Kaeo",
    "Sakon Nakhon": "Sakon Nakhon",
    "Samut Prakan": "Samut Prakan",
    "Samut Sakhon": "Samut Sakhon",
    "Samut Songkhram": "Samut Songkhram",
    "Saraburi": "Saraburi",
    "Satun": "Satun",
    "Si Sa Ket": "Si Sa Ket",
    "Sing Buri": "Sing Buri",
    "Songkhla": "Songkhla",
    "Sukhothai": "Sukhothai",
    "Suphan Buri": "Suphan Buri",
    "Surat Thani": "Surat Thani",
    "Surin": "Surin",
    "Tak": "Tak",
    "Trang": "Trang",
    "Trat": "Trat",
    "Ubon Ratchathani": "Ubon Ratchathani",
    "Udon Thani": "Udon Thani",
    "Uthai Thani": "Uthai Thani",
    "Uttaradit": "Uttaradit",
    "Yala": "Yala",
    "Yasothon": "Yasothon",
  },
  TCD: {
    "Barh El Gazel": "Barh el Gazel",
    "Batha": "Batha",
    "Borkou": "Borkou",
    "Chari-Baguirmi": "Chari-Baguirmi",
    "Ennedi": "Ennedi",
    "Guéra": "Guéra",
    "Hadjer-Lamis": "Hadjer-Lamis",
    "Kanem": "Kanem",
    "Lac": "Lac",
    "Logone Occidental": "Logone Occidental",
    "Logone Oriental": "Logone Oriental",
    "Mandoul": "Mandoul",
    "Mayo-Kebbi Est": "Mayo-Kebbi Est",
    "Mayo-Kebbi Ouest": "Mayo-Kebbi Ouest",
    "Moyen-Chari": "Moyen-Chari",
    "Ville de N'Djamena": "N’Djamena",
    "Ouaddaï": "Ouaddaï",
    "Salamat": "Salamat",
    "Sila": "Sila",
    "Tandjilé": "Tandjilé",
    "Tibesti": "Tibesti",
    "Wadi Fira": "Wadi Fira",
  },
  CZE: {
    "Jihočeský": "Jihočeský",
    "Jihomoravský": "Jihomoravský",
    "Karlovarský": "Karlovarský",
    "Královéhradecký": "Královéhradecký",
    "Liberecký": "Liberecký",
    "Moravskoslezský": "Moravskoslezský",
    "Olomoucký": "Olomoucký",
    "Pardubický": "Pardubický",
    "Plzeňský": "Plzeňský",
    "Prague": "Praha",
    "Středočeský": "Středočeský",
    "Ústecký": "Ústecký",
    "Vysočina": "Vysočina",
    "Zlínský": "Zlínský",
  },
  TUN: {
    "Béja": "Béja",
    "Ben Arous (Tunis Sud)": "Ben Arous",
    "Bizerte": "Bizerte",
    "Gabès": "Gabès",
    "Gafsa": "Gafsa",
    "Jendouba": "Jendouba",
    "Kairouan": "Kairouan",
    "Kassérine": "Kasserim",
    "Kebili": "Kebili",
    "Le Kef": "Kef",
    "Mahdia": "Mahdia",
    "Manubah": "Manubah",
    "Médenine": "Medenine",
    "Monastir": "Monastir",
    "Nabeul": "Nabeul",
    "Sfax": "Sfax",
    "Sidi Bou Zid": "Sidi Bou Said",
    "Siliana": "Siliana",
    "Sousse": "Sousse",
    "Tataouine": "Tataouine",
    "Tozeur": "Tozeur",
    "Tunis": "Tunis",
    "Zaghouan": "Zaghouan",
  },
  TUR: {
    "Adana": "Adana",
    "Adiyaman": "Adıyaman",
    "Afyonkarahisar": "Afyonkarahisar",
    "Agri": "Ağrı",
    "Aksaray": "Aksaray",
    "Amasya": "Amasya",
    "Ankara": "Ankara",
    "Antalya": "Antalya",
    "Ardahan": "Ardahan",
    "Artvin": "Artvin",
    "Aydin": "Aydın",
    "Balikesir": "Balıkesir",
    "Bartın": "Bartın",
    "Batman": "Batman",
    "Bayburt": "Bayburt",
    "Bilecik": "Bilecik",
    "Bingöl": "Bingöl",
    "Bitlis": "Bitlis",
    "Bolu": "Bolu",
    "Burdur": "Burdur",
    "Bursa": "Bursa",
    "Çanakkale": "Çanakkale",
    "Çankiri": "Çankırı",
    "Çorum": "Çorum",
    "Denizli": "Denizli",
    "Diyarbakir": "Diyarbakır",
    "Düzce": "Düzce",
    "Edirne": "Edirne",
    "Elazig": "Elazığ",
    "Erzincan": "Erzincan",
    "Erzurum": "Erzurum",
    "Eskisehir": "Eskişehir",
    "Gaziantep": "Gaziantep",
    "Giresun": "Giresun",
    "Gümüshane": "Gümüşhane",
    "Hakkari": "Hakkari",
    "Hatay": "Hatay",
    "Iğdir": "Iğdır",
    "Isparta": "Isparta",
    "Istanbul": "Istanbul",
    "Izmir": "Izmir",
    "K. Maras": "Kahramanmaraş",
    "Karabük": "Karabük",
    "Karaman": "Karaman",
    "Kars": "Kars",
    "Kastamonu": "Kastamonu",
    "Kayseri": "Kayseri",
    "Kilis": "Kilis",
    "Kinkkale": "Kırıkkale",
    "Kirklareli": "Kırklareli",
    "Kirsehir": "Kırşehir",
    "Kocaeli": "Kocaeli",
    "Konya": "Konya",
    "Kütahya": "Kütahya",
    "Malatya": "Malatya",
    "Manisa": "Manisa",
    "Mardin": "Mardin",
    "Mersin": "Mersin",
    "Mugla": "Muğla",
    "Mus": "Muş",
    "Nevsehir": "Nevşehir",
    "Nigde": "Niğde",
    "Ordu": "Ordu",
    "Osmaniye": "Osmaniye",
    "Rize": "Rize",
    "Sakarya": "Sakarya",
    "Samsun": "Samsun",
    "Sanliurfa": "Şanlıurfa",
    "Siirt": "Siirt",
    "Sinop": "Sinop",
    "Sivas": "Sivas",
    "Sirnak": "Şırnak",
    "Tekirdag": "Tekirdağ",
    "Tokat": "Tokat",
    "Trabzon": "Trabzon",
    "Tunceli": "Tunceli",
    "Usak": "Uşak",
    "Van": "Van",
    "Yalova": "Yalova",
    "Yozgat": "Yozgat",
    "Zinguldak": "Zonguldak",
  },
  TKM: {
    "Ahal": "Ahal",
    "Balkan": "Balkan",
    "Tashauz": "Daşoguz",
    "Chardzhou": "Lebap",
    "Mary": "Mary",
  },
  UGA: {
    "Eastern": "Itäinen alue",
    "Central": "Keskinen alue",
    "Western": "Läntinen alue",
    "Northern": "Pohjoinen alue",
  },
  UKR: {
    "Cherkasy": "Tšerkasyn alue",
    "Chernihiv": "Tšernihivin alue",
    "Chernivtsi": "Tšernivtsin alue",
    "Dnipropetrovs'k": "Dnipropetrovskin alue",
    "Donets'k": "Donetskin alue",
    "Ivano-Frankivs'k": "Ivano-Frankivskin alue",
    "Kharkiv": "Harkovan alue",
    "Kherson": "Hersonin alue",
    "Khmel'nyts'kyy": "Hmelnytskyin alue",
    "Kiev": "Kiovan alue",
    "Kiev City": "Kiova",
    "Kirovohrad": "Kirovohradin alue",
    "L'viv": "Lvivin alue",
    "Luhans'k": "Luhanskin alue",
    "Mykolayiv": "Mykolajivin alue",
    "Odessa": "Odessan alue",
    "Poltava": "Poltavan alue",
    "Rivne": "Rivnen alue",
    "Sumy": "Sumyn alue",
    "Ternopil'": "Ternopilin alue",
    "Transcarpathia": "Taka-Karpatian alue",
    "Vinnytsya": "Vinnytsian alue",
    "Volyn": "Volynin alue",
    "Zaporizhzhya": "Zaporižžjan alue",
    "Zhytomyr": "Žytomyrin alue",
  },
  HUN: {
    "Bács-Kiskun": "Bács-Kiskun",
    "Baranya": "Baranya",
    "Békés": "Békés",
    "Borsod-Abaúj-Zemplén": "Borsod-Abaúj-Zemplén",
    "Budapest": "Budapest",
    "Csongrád": "Csongrád",
    "Fejér": "Fejér",
    "Győr-Moson-Sopron": "Győr-Moson-Sopron",
    "Hajdú-Bihar": "Hajdú-Bihar",
    "Heves": "Heves",
    "Jász-Nagykun-Szolnok": "Jász-Nagykun-Szolnok",
    "Komárom-Esztergom": "Komárom-Esztergom",
    "Nógrád": "Nógrád",
    "Pest": "Pest",
    "Somogy": "Somogy",
    "Szabolcs-Szatmár-Bereg": "Szabolcs-Szatmár-Bereg",
    "Tolna": "Tolna",
    "Vas": "Vas",
    "Veszprém": "Veszprém",
    "Zala": "Zala",
  },
  URY: {
    "Artigas": "Artigas",
    "Canelones": "Canelones",
    "Cerro Largo": "Cerro Largo",
    "Colonia": "Colonia",
    "Durazno": "Durazno",
    "Flores": "Flores",
    "Florida": "Florida",
    "Lavalleja": "Lavalleja",
    "Maldonado": "Maldonado",
    "Montevideo": "Montevideo",
    "Paysandú": "Paysandú",
    "Río Negro": "Río Negro",
    "Rivera": "Rivera",
    "Rocha": "Rocha",
    "Salto": "Salto",
    "San José": "San José",
    "Soriano": "Soriano",
    "Tacuarembó": "Tacuarembó",
    "Treinta y Tres": "Treinta y Tres",
  },
  NCL: {
    "Sud": "Etelä-Provinssi",
    "Îles Loyauté": "Îles Loyauté",
    "Nord": "Nord",
  },
  NZL: {
    "Antipodes Islands": "Antipodisaaret",
    "Auckland": "Auckland",
    "Auckland Islands": "Aucklandinsaaret",
    "Bay of Plenty": "Bay of Plenty",
    "Campbell Islands": "Campbellinsaaret",
    "Canterbury": "Canterbury",
    "Chatham Islands Territory": "Chathamsaaret",
    "Gisborne District": "Gisborne",
    "Hawke's Bay": "Hawke's Bay",
    "Kermadec Islands": "Kermadecinsaaret",
    "Manawatu-Wanganui": "Manawatu-Whanganui",
    "Marlborough District": "Marlborough",
    "Nelson City": "Nelson",
    "Northland": "Northland",
    "Otago": "Otago",
    "Southland": "Southland",
    "Taranaki": "Taranaki",
    "Tasman District": "Tasman",
    "The Snares": "Snaresinsaaret",
    "Three Kings Islands": "Three Kings -saaret",
    "Tokelau": "Tokelau",
    "Waikato": "Waikato",
    "Wellington": "Wellington",
    "West Coast": "West Coast",
  },
  UZB: {
    "Andijon": "Andijon",
    "Bukhoro": "Bukhoro",
    "Ferghana": "Fergana",
    "Jizzakh": "Jizzakh",
    "Karakalpakstan": "Karakalpakia",
    "Namangan": "Namangan",
    "Navoi": "Navoi",
    "Kashkadarya": "Qashqadaryo",
    "Samarkand": "Samarkand",
    "Sirdaryo": "Sirdaryo",
    "Surkhandarya": "Surxondaryo",
    "Tashkent": "Tashkent",
    "Khorezm": "Xorazm",
  },
  BLR: {
    "Brest": "Brestin alue",
    "Gomel": "Gomelin alue",
    "Grodno": "Grodnon alue",
    "Mogilev": "Mogiljovin alue",
    "Minsk": "Minskin alue",
    "City of Minsk": "Minsk",
    "Vitebsk": "Vitebskin alue",
  },
  VUT: {
    "Malampa": "Malampa",
    "Penama": "Penama",
    "Sanma": "Sanma",
    "Shefa": "Shefa",
    "Tafea": "Tafea",
    "Torba": "Torba",
  },
  VEN: {
    "Amazonas": "Amazonas",
    "Anzoátegui": "Anzoátegui",
    "Apure": "Apure",
    "Aragua": "Aragua",
    "Barinas": "Barinas",
    "Bolívar": "Bolívar",
    "Carabobo": "Carabobo",
    "Cojedes": "Cojedes",
    "Delta Amacuro": "Delta Amacuro",
    "Dependencias Federales": "Dependencias Federales",
    "Falcón": "Falcón",
    "Guárico": "Guárico",
    "Vargas": "La Guaira",
    "Lara": "Lara",
    "Mérida": "Mérida",
    "Miranda": "Miranda",
    "Monagas": "Monagas",
    "Nueva Esparta": "Nueva Esparta",
    "Portuguesa": "Portuguesa",
    "Distrito Capital": "Pääkaupunkialue",
    "Sucre": "Sucre",
    "Táchira": "Táchira",
    "Trujillo": "Trujillo",
    "VEN+99?": "VEN+99?",
    "Yaracuy": "Yaracuy",
    "Zulia": "Zulia",
  },
  RUS: {
    "Adygey": "Adygea",
    "Altay": "Altain aluepiiri",
    "Amur": "Amurin alue",
    "Arkhangel'sk": "Arkangelin alue",
    "Astrakhan'": "Astrahanin alue",
    "Bashkortostan": "Baškortostan",
    "Belgorod": "Belgorodin alue",
    "Bryansk": "Brjanskin alue",
    "Buryat": "Burjatia",
    "Chelyabinsk": "Tšeljabinskin alue",
    "Chita": "Taka-Baikalin aluepiiri",
    "Crimea": "Krim",
    "Dagestan": "Dagestan",
    "Gorno-Altay": "Altain tasavalta",
    "Khakass": "Hakassia",
    "Khanty-Mansiy": "Hanti-Mansia",
    "Ingush": "Ingušia",
    "Irkutsk": "Irkutskin alue",
    "Ivanovo": "Ivanovon alue",
    "Kabardin-Balkar": "Kabardi-Balkaria",
    "Kaliningrad": "Kaliningradin alue",
    "Kalmyk": "Kalmukia",
    "Kaluga": "Kalugan alue",
    "Kamchatka": "Kamtšatkan aluepiiri",
    "Karachay-Cherkess": "Karatšai-Tšerkessia",
    "Karelia": "Karjalan tasavalta",
    "Kemerovo": "Kemerovon alue",
    "Khabarovsk": "Habarovskin aluepiiri",
    "Kirov": "Kirovin alue",
    "Komi": "Komin tasavalta",
    "Kostroma": "Kostroman alue",
    "Krasnodar": "Krasnodarin aluepiiri",
    "Krasnoyarsk": "Krasnojarskin aluepiiri",
    "Kurgan": "Kurganin alue",
    "Kursk": "Kurskin alue",
    "Leningrad": "Leningradin alue",
    "Lipetsk": "Lipetskin alue",
    "Maga Buryatdan": "Magadanin alue",
    "Mariy-El": "Marin tasavalta",
    "Mordovia": "Mordva",
    "Moskva": "Moskova",
    "Moskovskaya": "Moskovan alue",
    "Murmansk": "Murmanskin alue",
    "Nenets": "Nenetsia",
    "Nizhegorod": "Nižni Novgorodin alue",
    "Novgorod": "Novgorodin alue",
    "Novosibirsk": "Novosibirskin alue",
    "Omsk": "Omskin alue",
    "Orel": "Orjolin alue",
    "Orenburg": "Orenburgin alue",
    "Penza": "Penzan alue",
    "Perm'": "Permin aluepiiri",
    "City of St. Petersburg": "Pietari",
    "North Ossetia": "Pohjois-Ossetia-Alania",
    "Primor'ye": "Primorjen aluepiiri",
    "Pskov": "Pihkovan alue",
    "Rostov": "Rostovin alue",
    "RUS+99?": "Bajdaratskajanlahden saari",
    "Ryazan'": "Rjazanin alue",
    "Sakha (Yakutia)": "Jakutia",
    "Sakhalin": "Sahalinin alue",
    "Samara": "Samaran alue",
    "Saratov": "Saratovin alue",
    "Sevastopol": "Sevastopol",
    "Smolensk": "Smolenskin alue",
    "Stavropol'": "Stavropolin aluepiiri",
    "Sverdlovsk": "Sverdlovskin alue",
    "Tambov": "Tambovin alue",
    "Tatarstan": "Tatarstan",
    "Tomsk": "Tomskin alue",
    "Chechnya": "Tšetšenia",
    "Chukchi Autonomous Okrug": "Tšukotka",
    "Chuvash": "Tšuvassia",
    "Tula": "Tulan alue",
    "Tuva": "Tuva",
    "Tver'": "Tverin alue",
    "Tyumen'": "Tjumenin alue",
    "Udmurt": "Udmurtia",
    "Ul'yanovsk": "Uljanovskin alue",
    "Vladimir": "Vladimirin alue",
    "Volgograd": "Volgogradin alue",
    "Vologda": "Vologdan alue",
    "Voronezh": "Voronežin alue",
    "Yamal-Nenets": "Jamalin Nenetsia",
    "Yaroslavl'": "Jaroslavlin alue",
    "Yevrey": "Juutalainen autonominen alue",
  },
  VNM: {
    "An Giang": "An Giang",
    "Bà Rịa - Vũng Tàu": "Bà Rịa-Vũng Tàu",
    "Bắc Giang": "Bắc Giang",
    "Bạc Liêu": "Bạc Liêu",
    "Bắc Ninh": "Bắc Ninh",
    "Bến Tre": "Bến Tre",
    "Bình Định": "Bình Định",
    "Bình Dương": "Bình Dương",
    "Bình Phước": "Bình Phước",
    "Bình Thuận": "Bình Thuận",
    "Cà Mau": "Cà Mau",
    "Can Tho": "Cần Thơ",
    "Cao Bằng": "Cao Bằng",
    "Đà Nẵng": "Đà Nẵng",
    "Đắk Lắk": "Đắk Lắk",
    "Đắk Nông": "Đắk Nông",
    "Điện Biên": "Điện Biên",
    "Đông Bắc": "Bắc Kạn",
    "Đồng Bằng Sông Hồng": "Hưng Yên",
    "Đông Nam Bộ": "Đồng Nai",
    "Ðong Tháp": "Đồng Tháp",
    "Gia Lai": "Gia Lai",
    "Hà Giang": "Hà Giang",
    "Hà Nam": "Hà Nam",
    "Ha Tinh": "Hà Tĩnh",
    "Hải Dương": "Hải Dương",
    "Hải Phòng": "Hải Phòng",
    "Ha Noi": "Hanoi",
    "Hau Giang": "Hậu Giang",
    "Hồ Chí Minh city": "Hồ Chí Minhin kaupunki",
    "Hòa Bình": "Hòa Bình",
    "Thừa Thiên - Huế": "Huế",
    "Khánh Hòa": "Khánh Hòa",
    "Kiên Giang": "Kiên Giang",
    "Kon Tum": "Kon Tum",
    "Lai Chau": "Lai Châu",
    "Lâm Đồng": "Lâm Đồng",
    "Lạng Sơn": "Lạng Sơn",
    "Lào Cai": "Lào Cai",
    "Long An": "Long An",
    "Nam Định": "Nam Định",
    "Nghệ An": "Nghệ An",
    "Ninh Bình": "Ninh Bình",
    "Ninh Thuận": "Ninh Thuận",
    "Phú Thọ": "Phú Thọ",
    "Phú Yên": "Phú Yên",
    "Quảng Bình": "Quảng Bình",
    "Quàng Nam": "Quảng Nam",
    "Quảng Ngãi": "Quảng Ngãi",
    "Quảng Ninh": "Quảng Ninh",
    "Quảng Trị": "Quảng Trị",
    "Sóc Trăng": "Sóc Trăng",
    "Son La": "Sơn La",
    "Tây Ninh": "Tây Ninh",
    "Thái Bình": "Thái Bình",
    "Thái Nguyên": "Thái Nguyên",
    "Thanh Hóa": "Thanh Hóa",
    "Tiền Giang": "Tiền Giang",
    "Trà Vinh": "Trà Vinh",
    "Tuyên Quang": "Tuyên Quang",
    "Vĩnh Long": "Vĩnh Long",
    "Vĩnh Phúc": "Vĩnh Phúc",
    "Yên Bái": "Yên Bái",
  },
  EST: {
    "Harju": "Harjumaa",
    "Hiiu": "Hiidenmaa",
    "Ida-Viru": "Itä-Virumaa",
    "Jõgeva": "Jõgevamaa",
    "Järva": "Järvamaa",
    "Lääne-Viru": "Länsi-Virumaa",
    "Lääne": "Läänemaa",
    "Põlva": "Põlvamaa",
    "Pärnu": "Pärnumaa",
    "Rapla": "Raplamaa",
    "Saare": "Saarenmaa",
    "Tartu": "Tartumaa",
    "Valga": "Valgamaa",
    "Viljandi": "Viljandimaa",
    "Võru": "Võrumaa",
  },
  USA: {
    "Alabama": "Alabama",
    "Alaska": "Alaska",
    "Arizona": "Arizona",
    "Arkansas": "Arkansas",
    "Colorado": "Colorado",
    "Connecticut": "Connecticut",
    "Delaware": "Delaware",
    "South Carolina": "Etelä-Carolina",
    "South Dakota": "Etelä-Dakota",
    "Florida": "Florida",
    "Georgia": "Georgia",
    "Hawaii": "Havaiji",
    "Idaho": "Idaho",
    "Illinois": "Illinois",
    "Indiana": "Indiana",
    "Iowa": "Iowa",
    "California": "Kalifornia",
    "Kansas": "Kansas",
    "Kentucky": "Kentucky",
    "Louisiana": "Louisiana",
    "West Virginia": "Länsi-Virginia",
    "Maine": "Maine",
    "Maryland": "Maryland",
    "Massachusetts": "Massachusetts",
    "Michigan": "Michigan",
    "Minnesota": "Minnesota",
    "Mississippi": "Mississippi",
    "Missouri": "Missouri",
    "Montana": "Montana",
    "Nebraska": "Nebraska",
    "Nevada": "Nevada",
    "New Hampshire": "New Hampshire",
    "New Jersey": "New Jersey",
    "New Mexico": "New Mexico",
    "New York": "New York",
    "Ohio": "Ohio",
    "Oklahoma": "Oklahoma",
    "Oregon": "Oregon",
    "Pennsylvania": "Pennsylvania",
    "North Carolina": "Pohjois-Carolina",
    "North Dakota": "Pohjois-Dakota",
    "Rhode Island": "Rhode Island",
    "Tennessee": "Tennessee",
    "Texas": "Texas",
    "Utah": "Utah",
    "Vermont": "Vermont",
    "Virginia": "Virginia",
    "Washington": "Washington",
    "District of Columbia": "Washington D.C.",
    "Wisconsin": "Wisconsin",
    "Wyoming": "Wyoming",
  },
  ZWE: {
    "Bulawayo": "Bulawayo",
    "Harare": "Harare",
    "Manicaland": "Manicaland",
    "Mashonaland Central": "Mashonaland Central",
    "Mashonaland East": "Mashonaland East",
    "Mashonaland West": "Mashonaland West",
    "Masvingo": "Masvingo",
    "Matabeleland North": "Matabeleland North",
    "Matabeleland South": "Matabeleland South",
    "Midlands": "Midlands",
  },
};

/** Pelin maat suomalaisessa aakkosjärjestyksessä (paketin countryShapes-nimi). */
export const MAAKUNNAT_KAIKKI_MAAT = [
  { iso: 'AFG', nimi: "Afganistan" },
  { iso: 'NLD', nimi: "Alankomaat" },
  { iso: 'ALB', nimi: "Albania" },
  { iso: 'DZA', nimi: "Algeria" },
  { iso: 'AGO', nimi: "Angola" },
  { iso: 'ARE', nimi: "Arabiemiirikunnat" },
  { iso: 'ARG', nimi: "Argentiina" },
  { iso: 'ARM', nimi: "Armenia" },
  { iso: 'AUS', nimi: "Australia" },
  { iso: 'AZE', nimi: "Azerbaidžan" },
  { iso: 'BHR', nimi: "Bahrain" },
  { iso: 'BGD', nimi: "Bangladesh" },
  { iso: 'BEL', nimi: "Belgia" },
  { iso: 'BMU', nimi: "Bermuda" },
  { iso: 'BTN', nimi: "Bhutan" },
  { iso: 'BOL', nimi: "Bolivia" },
  { iso: 'BIH', nimi: "Bosnia ja Hertsegovina" },
  { iso: 'BRA', nimi: "Brasilia" },
  { iso: 'BGR', nimi: "Bulgaria" },
  { iso: 'CHL', nimi: "Chile" },
  { iso: 'ECU', nimi: "Ecuador" },
  { iso: 'EGY', nimi: "Egypti" },
  { iso: 'ESP', nimi: "Espanja" },
  { iso: 'ZAF', nimi: "Etelä-Afrikka" },
  { iso: 'KOR', nimi: "Etelä-Korea" },
  { iso: 'SDS', nimi: "Etelä-Sudan" },
  { iso: 'ETH', nimi: "Etiopia" },
  { iso: 'FLK', nimi: "Falklandinsaaret" },
  { iso: 'FJI', nimi: "Fidži" },
  { iso: 'PHL', nimi: "Filippiinit" },
  { iso: 'GEO', nimi: "Georgia" },
  { iso: 'GHA', nimi: "Ghana" },
  { iso: 'GRL', nimi: "Grönlanti" },
  { iso: 'GTM', nimi: "Guatemala" },
  { iso: 'HKG', nimi: "Hongkong" },
  { iso: 'IDN', nimi: "Indonesia" },
  { iso: 'IND', nimi: "Intia" },
  { iso: 'IRQ', nimi: "Irak" },
  { iso: 'IRN', nimi: "Iran" },
  { iso: 'IRL', nimi: "Irlanti" },
  { iso: 'ISL', nimi: "Islanti" },
  { iso: 'GBR', nimi: "Iso-Britannia" },
  { iso: 'ITA', nimi: "Italia" },
  { iso: 'TLS', nimi: "Itä-Timor" },
  { iso: 'AUT', nimi: "Itävalta" },
  { iso: 'JPN', nimi: "Japani" },
  { iso: 'YEM', nimi: "Jemen" },
  { iso: 'JOR', nimi: "Jordania" },
  { iso: 'KHM', nimi: "Kambodža" },
  { iso: 'CMR', nimi: "Kamerun" },
  { iso: 'CAN', nimi: "Kanada" },
  { iso: 'KAZ', nimi: "Kazakstan" },
  { iso: 'KEN', nimi: "Kenia" },
  { iso: 'CHN', nimi: "Kiina" },
  { iso: 'KGZ', nimi: "Kirgisia" },
  { iso: 'COL', nimi: "Kolumbia" },
  { iso: 'COD', nimi: "Kongo" },
  { iso: 'GRC', nimi: "Kreikka" },
  { iso: 'HRV', nimi: "Kroatia" },
  { iso: 'CUB', nimi: "Kuuba" },
  { iso: 'KWT', nimi: "Kuwait" },
  { iso: 'CYP', nimi: "Kypros" },
  { iso: 'LAO', nimi: "Laos" },
  { iso: 'LVA', nimi: "Latvia" },
  { iso: 'LBR', nimi: "Liberia" },
  { iso: 'LBY', nimi: "Libya" },
  { iso: 'LTU', nimi: "Liettua" },
  { iso: 'LUX', nimi: "Luxemburg" },
  { iso: 'MDG', nimi: "Madagaskar" },
  { iso: 'MYS', nimi: "Malesia" },
  { iso: 'MLI', nimi: "Mali" },
  { iso: 'MLT', nimi: "Malta" },
  { iso: 'MAR', nimi: "Marokko" },
  { iso: 'MEX', nimi: "Meksiko" },
  { iso: 'MDA', nimi: "Moldova" },
  { iso: 'MNG', nimi: "Mongolia" },
  { iso: 'MNE', nimi: "Montenegro" },
  { iso: 'MOZ', nimi: "Mosambik" },
  { iso: 'MMR', nimi: "Myanmar" },
  { iso: 'NAM', nimi: "Namibia" },
  { iso: 'NPL', nimi: "Nepal" },
  { iso: 'NIC', nimi: "Nicaragua" },
  { iso: 'NGA', nimi: "Nigeria" },
  { iso: 'NFK', nimi: "Norfolkinsaari" },
  { iso: 'NOR', nimi: "Norja" },
  { iso: 'OMN', nimi: "Oman" },
  { iso: 'PAK', nimi: "Pakistan" },
  { iso: 'PAN', nimi: "Panama" },
  { iso: 'PNG', nimi: "Papua-Uusi-Guinea" },
  { iso: 'PRY', nimi: "Paraguay" },
  { iso: 'PER', nimi: "Peru" },
  { iso: 'PRK', nimi: "Pohjois-Korea" },
  { iso: 'MKD', nimi: "Pohjois-Makedonia" },
  { iso: 'PRT', nimi: "Portugali" },
  { iso: 'PRI', nimi: "Puerto Rico" },
  { iso: 'POL', nimi: "Puola" },
  { iso: 'QAT', nimi: "Qatar" },
  { iso: 'FRA', nimi: "Ranska" },
  { iso: 'GUF', nimi: "Ranskan Guayana" },
  { iso: 'ROU', nimi: "Romania" },
  { iso: 'SWE', nimi: "Ruotsi" },
  { iso: 'SHN', nimi: "Saint Helena" },
  { iso: 'DEU', nimi: "Saksa" },
  { iso: 'SLB', nimi: "Salomonsaaret" },
  { iso: 'SAU', nimi: "Saudi-Arabia" },
  { iso: 'SEN', nimi: "Senegal" },
  { iso: 'SRB', nimi: "Serbia" },
  { iso: 'SLE', nimi: "Sierra Leone" },
  { iso: 'SGP', nimi: "Singapore" },
  { iso: 'SVK', nimi: "Slovakia" },
  { iso: 'SVN', nimi: "Slovenia" },
  { iso: 'SOM', nimi: "Somalia" },
  { iso: 'LKA', nimi: "Sri Lanka" },
  { iso: 'SDN', nimi: "Sudan" },
  { iso: 'FIN', nimi: "Suomi" },
  { iso: 'CHE', nimi: "Sveitsi" },
  { iso: 'SYR', nimi: "Syyria" },
  { iso: 'TJK', nimi: "Tadžikistan" },
  { iso: 'TWN', nimi: "Taiwan" },
  { iso: 'TZA', nimi: "Tansania" },
  { iso: 'DNK', nimi: "Tanska" },
  { iso: 'THA', nimi: "Thaimaa" },
  { iso: 'TCD', nimi: "Tšad" },
  { iso: 'CZE', nimi: "Tšekki" },
  { iso: 'TUN', nimi: "Tunisia" },
  { iso: 'TUR', nimi: "Turkki" },
  { iso: 'TKM', nimi: "Turkmenistan" },
  { iso: 'UGA', nimi: "Uganda" },
  { iso: 'UKR', nimi: "Ukraina" },
  { iso: 'HUN', nimi: "Unkari" },
  { iso: 'URY', nimi: "Uruguay" },
  { iso: 'NCL', nimi: "Uusi-Kaledonia" },
  { iso: 'NZL', nimi: "Uusi-Seelanti" },
  { iso: 'UZB', nimi: "Uzbekistan" },
  { iso: 'BLR', nimi: "Valko-Venäjä" },
  { iso: 'VUT', nimi: "Vanuatu" },
  { iso: 'VEN', nimi: "Venezuela" },
  { iso: 'RUS', nimi: "Venäjä" },
  { iso: 'VNM', nimi: "Vietnam" },
  { iso: 'EST', nimi: "Viro" },
  { iso: 'USA', nimi: "Yhdysvallat" },
  { iso: 'ZWE', nimi: "Zimbabwe" },
];
