/*
 * Suora radiolähetys maittain: "Kuuntele kieltä" -napin ensisijainen
 * ääni.
 *
 * Miksi radio eikä äänite: aporeen äänimaisemat on tallennettu
 * maisemaksi, ei puheeksi, ja torinäytteessä kuuluu enimmäkseen
 * askelia ja liikennettä (omistajan havainto). Suorassa puheradiossa
 * puhutaan koko ajan, eikä lähetys ole koskaan kahdesti samanlainen.
 *
 * Järjestys on omistajan antama: maan virallinen ykkösradio ensin,
 * sen puuttuessa mikä tahansa saman maan asema, ja vasta viimeisenä
 * vanha kolmen minuutin tallenne (js/packs/europe-kielet.js). Tallenne
 * jää varareitiksi: lähetysosoitteet lakkaavat toimimasta ilman
 * varoitusta, ja silloin nappi soittaa äänitteen sen sijaan että
 * vaikenisi.
 *
 * Kaikki osoitteet ovat https-muotoisia ja tarkistettu hakemalla —
 * salaamatonta virtaa selain ei soita lainkaan. Lista on tuotettu
 * komennoilla
 *   node tools/hae-radiot.mjs
 *   node tools/kirjoita-radiot.mjs
 * Radio Browserin aineistosta. Älä muokkaa käsin: aja haku uudelleen.
 *
 * 182 maata, joista 94 maan yleisradion kanava.
 *
 * Avaimena ISO-3-maatunnus, sama jota map.cityCountry käyttää.
 *
 * kaupunki/lat/lon (skeema, radioiden maailmanlaajennus 28.9.2026):
 * aseman kaupunki (yhtiön kotipaikka tai maan pääkaupunki), koordinaatit
 * Wikidatasta (P625), 2 desimaalia. Käytetään kartalla aseman paikkana
 * sen sijaan että näytettäisiin aluenimi (Sahara, Kamerun, Kongo…).
 */
export const RADIOT = {
  AFG: { url: 'https://s5.radio.co/se6264cb34/listen', asema: 'Radio Begum (Kabul)', kaupunki: 'Kabul', lat: 34.53, lon: 69.17 },
  AGO: { url: 'https://stream.zeno.fm/vyu630hfy4zuv', asema: 'Rádio Luanda (RNA)', virallinen: true, kaupunki: 'Luanda', lat: -8.84, lon: 13.23 },
  ALB: { url: 'https://cp1.sednastream.com/proxy/radioone94?mp=/stream', asema: 'RadioOne', kaupunki: 'Tirana', lat: 41.33, lon: 19.82 },
  AND: { url: 'https://streaming.giraweb.com/8020/stream', asema: 'Flaix FM Andorra', kaupunki: 'Andorra la Vella', lat: 42.51, lon: 1.52 },
  ARE: { url: 'https://l3.itworkscdn.net/smcradiolive/smcradiolive/icecast.audio', asema: 'Sharjah FM 94.4 (إذاعة الشارقة)', virallinen: true, kaupunki: 'Abu Dhabi', lat: 24.45, lon: 54.4 },
  ARG: { url: 'https://sa.mp3.icecast.magma.edge-access.net/sc_rad1', asema: 'LRA1 Radio Nacional Argentina', virallinen: true, kaupunki: 'Buenos Aires', lat: -34.6, lon: -58.38 },
  ARM: { url: 'https://streams.radio.co/sa0bf8ec29/listen?sid=1', asema: 'Armenian Christian Radio - Bashde Radio', kaupunki: 'Jerevan', lat: 40.18, lon: 44.51 },
  ATG: { url: 'https://testvibz-silcomwireless.radioca.st/stream.mp3', asema: 'Vibz FM', kaupunki: 'St. John’s', lat: 17.12, lon: -61.84 },
  AUS: { url: 'https://abc.streamguys1.com/live/rnnsw/icecast.audio', asema: 'ABC Radio National', virallinen: true, kaupunki: 'Canberra', lat: -35.29, lon: 149.13 },
  AUT: { url: 'https://orf-live.ors-shoutcast.at/oe1-q2a', asema: 'Ö1 | ORF | HQ', virallinen: true, kaupunki: 'Wien', lat: 48.21, lon: 16.37 },
  AZE: { url: 'https://icecast.livetv.az/yurdfm', asema: 'Yurd FM', kaupunki: 'Baku', lat: 40.37, lon: 49.84 },
  BDI: { url: 'https://stream.zeno.fm/eequgfw72hhvv', asema: 'Heaven FM Radio (Burundi)', kaupunki: 'Gitega', lat: -3.43, lon: 29.93 },
  BEL: { url: 'https://radios.rtbf.be/laprem1ere-64.aac', asema: 'RTBF La Première', virallinen: true, kaupunki: 'Bryssel', lat: 50.85, lon: 4.35 },
  BEN: { url: 'https://listen.radioking.com/radio/47608/stream/84430', asema: 'ORTB Radio Bénin', kaupunki: 'Porto-Novo', lat: 6.48, lon: 2.62 },
  BFA: { url: 'https://sonic.mediacp.eu/8040/;', asema: 'Radio Bizi Inter', kaupunki: 'Ouagadougou', lat: 12.37, lon: -1.53 },
  BGD: { url: 'https://stream-157.zeno.fm/eabgu655puquv', asema: 'Radio Shadhin', kaupunki: 'Dhaka', lat: 23.73, lon: 90.39 },
  BGR: { url: 'https://play.global.audio/testb.aac?dist=RADIOPLAY', asema: 'BNR Horizont', virallinen: true, kaupunki: 'Sofia', lat: 42.7, lon: 23.32 },
  BHR: { url: 'https://montecarlodoualiya128k.ice.infomaniak.ch/mc-doualiya.mp3', asema: 'Monte Carlo Doualiya', kaupunki: 'Manama', lat: 26.22, lon: 50.58 },
  BHS: { url: 'https://s2.reliastream.com/proxy/rumcayme?mp=/stream', asema: 'Bahamian or Nuttin', kaupunki: 'Nassau', lat: 25.08, lon: -77.34 },
  BIH: { url: 'https://s2.free-shoutcast.com/stream/18170', asema: 'Federalni radio (RTVFBiH)', virallinen: true, kaupunki: 'Sarajevo', lat: 43.86, lon: 18.41 },
  BLR: { url: 'https://myradio24.org/3355', asema: 'Love Is Radio Belarus', virallinen: true, kaupunki: 'Minsk', lat: 53.9, lon: 27.56 },
  BLZ: { url: 'https://stream.zeno.fm/nw7xmuzasyduv', asema: 'Riddim Radio', kaupunki: 'Belmopan', lat: 17.25, lon: -88.77 },
  BOL: { url: 'https://stream.zeno.fm/pnwpbyfambruv', asema: 'Radio Panamericana', virallinen: true, kaupunki: 'La Paz', lat: -16.5, lon: -68.13 },
  BRA: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/BANDNEWSFM_SPAAC_SC', asema: 'BandNews FM', virallinen: true, kaupunki: 'Brasília', lat: -15.79, lon: -47.88 },
  BRB: { url: 'https://ice66.securenetsystems.net:80/VOB929', asema: 'VOB 92.9 FM', kaupunki: 'Bridgetown', lat: 13.1, lon: -59.62 },
  BRN: { url: 'https://play.thestreamtech.com:7038/', asema: 'Kristal FM', kaupunki: 'Bandar Seri Begawan', lat: 4.92, lon: 114.92 },
  CAF: { url: 'https://stream.radiondekeluka.org/ndekeluka', asema: 'Radio Ndeke Luka', kaupunki: 'Bangui', lat: 4.37, lon: 18.56 },
  CAN: { url: 'https://26733.live.streamtheworld.com/CBLAFM_CBC_SC', asema: 'CBC Radio One - Toronto, ON (MP3 stream)', virallinen: true, kaupunki: 'Ottawa', lat: 45.42, lon: -75.69 },
  CHE: { url: 'https://stream.srg-ssr.ch/m/la-1ere/mp3_128', asema: 'RTS La Première', virallinen: true, kaupunki: 'Bern', lat: 46.95, lon: 7.45 },
  CHL: { url: 'https://unlimited3-cl.dps.live/biobiotemuco/aac/icecast.audio', asema: 'Radio Bio Bio Temuco', virallinen: true, kaupunki: 'Santiago de Chile', lat: -33.44, lon: -70.65 },
  CHN: { url: 'https://lhttp.qtfm.cn/live/15318317/64k.mp3', asema: 'CNR-1 中国之声', virallinen: true, kaupunki: 'Peking', lat: 39.9, lon: 116.41 },
  CIV: { url: 'https://dreamsiteradiocp6.com/proxy/rmcosta?mp=/stream', asema: 'Radio Maria Ivory Coast', kaupunki: 'Yamoussoukro', lat: 6.82, lon: -5.27 },
  CMR: { url: 'https://stream.zeno.fm/43q33pgvbphvv', asema: 'Radio Bafung', kaupunki: 'Yaoundé', lat: 3.86, lon: 11.52 },
  COD: { url: 'https://mpbradio.ice.infomaniak.ch/topcongo3-128.mp3', asema: 'Top Congo FM 88.4 (Kinshasa)', kaupunki: 'Kinshasa', lat: -4.32, lon: 15.31 },
  COG: { url: 'https://dreamsiteradiocp2.com/proxy/rmrepdemcongo?mp=/stream', asema: 'Radio Maria Democratic Rep. Congo', kaupunki: 'Brazzaville', lat: -4.27, lon: 15.27 },
  COL: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CARACOL_RADIOAAC.aac', asema: 'Caracol Radio - 100.9 FM / 810 AM - HJGL / HJCY -', virallinen: true, kaupunki: 'Bogotá', lat: 4.61, lon: -74.08 },
  CPV: { url: 'https://listen.radioking.com/radio/281506/stream/327253', asema: 'Caboradio', kaupunki: 'Praia', lat: 14.92, lon: -23.51 },
  CRI: { url: 'https://stream.zeno.fm/ftcx2988uwzuv', asema: 'Radio Revolución', kaupunki: 'San José', lat: 9.93, lon: -84.08 },
  CUB: { url: 'https://securestreams7.autopo.st/?uri=https://icecast.teveo.cu/kHKL7tWd', asema: 'Radio Rebelde 1180 AM', virallinen: true, kaupunki: 'Havanna', lat: 23.14, lon: -82.36 },
  CYP: { url: 'https://r1.cloudskep.com/cybcr/cybc1/icecast.audio', asema: 'ΡΙΚ Πρώτο Πρόγραμμα (CyBC)', virallinen: true, kaupunki: 'Nikosia', lat: 35.17, lon: 33.37 },
  CZE: { url: 'https://rozhlas.stream/radiozurnal_sport_high.aac', asema: 'ČRO Radiožurnál Sport', virallinen: true, kaupunki: 'Praha', lat: 50.09, lon: 14.42 },
  DEU: { url: 'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3?aggregator=web', asema: 'Deutschlandfunk | DLF | MP3 128k', virallinen: true, kaupunki: 'Berliini', lat: 52.52, lon: 13.38 },
  DMA: { url: 'https://stream.dbcradio.net:8005/live', asema: 'DBS Radio', virallinen: true, kaupunki: 'Roseau', lat: 15.3, lon: -61.38 },
  DNK: { url: 'https://live-icy.gss.dr.dk/A/A03H.mp3', asema: 'DR P1', virallinen: true, kaupunki: 'Kööpenhamina', lat: 55.68, lon: 12.57 },
  DOM: { url: 'https://node-08.zeno.fm/8wgv914262quv', asema: 'Radio Dial 670 AM (RD)', kaupunki: 'Santo Domingo', lat: 18.46, lon: -69.94 },
  DZA: { url: 'https://radiochaine1.ice.infomaniak.ch/chaine1.mp3', asema: 'Algérie Chaine 1', virallinen: true, kaupunki: 'Alger', lat: 36.78, lon: 3.06 },
  ECU: { url: 'https://icecast.radiopichincha.com/radiopichincha', asema: 'Radio Pichincha', kaupunki: 'Quito', lat: -0.22, lon: -78.51 },
  EGY: { url: 'https://9090streaming.mobtada.com/9090FMEGYPT', asema: 'Radio 9090 / 90.90 FM Radio Egypt (Kairo)', kaupunki: 'Kairo', lat: 30.04, lon: 31.24 },
  ERI: { url: 'https://linuxfreelancer.com:8443/test.mp3', asema: 'Eritrean/Ethiopian music', kaupunki: 'Asmara', lat: 15.33, lon: 38.92 },
  ESP: { url: 'https://d131.rndfnk.com/star/crtve/rne5/main/mp3/128/stream.mp3?aggregator=tunein&cid=01GEP4MW5CAHPYP1EXHVKWFJ8W&sid=2OeE42hivuba6dTGvjnMGjKByQe&token=cdczXcnimVx4AY4iamqYbTMdu3cK7oBxmS2UQN9cWc0&tvf=pdPcDBxuVxdkMTMxLnJuZGZuay5jb20', asema: 'Radio Nacional de España - Radio 5 Todo noticias', virallinen: true, kaupunki: 'Madrid', lat: 40.42, lon: -3.7 },
  EST: { url: 'https://icecast.err.ee/vikerraadio.mp3', asema: 'Vikerraadio', virallinen: true, kaupunki: 'Tallinna', lat: 59.44, lon: 24.75 },
  ETH: { url: 'https://stream-25.zeno.fm/2xguamap7yzuv', asema: 'EBC Radio 104.7 Addis Abeba', virallinen: true, kaupunki: 'Addis Abeba', lat: 9.04, lon: 38.75 },
  FIN: { url: 'https://icecast.live.yle.fi/radio/YleRadio1Hifi/icecast.audio', asema: 'Yle Radio 1 Hifi', virallinen: true, kaupunki: 'Helsinki', lat: 60.17, lon: 24.94 },
  FJI: { url: 'https://icecast1.sere.plus/RFOne', asema: 'Radio Fiji One (FBC, fidžin kieli)', virallinen: true, kaupunki: 'Suva', lat: -18.13, lon: 178.43 },
  FRA: { url: 'https://icecast.radiofrance.fr/franceinter-hifi.aac', asema: 'France Inter', virallinen: true, kaupunki: 'Pariisi', lat: 48.86, lon: 2.35 },
  GBR: { url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_east_asia', asema: 'BBC World Service', virallinen: true, kaupunki: 'Lontoo', lat: 51.51, lon: -0.13 },
  GEO: { url: 'https://listen.radioking.com/radio/282820/stream/328621', asema: 'Mutant Radio', kaupunki: 'Tbilisi', lat: 41.72, lon: 44.79 },
  GHA: { url: 'https://node-27.zeno.fm/ey34mac27vzuv?rj-ttl=5&rj-tok=AAABdyidjk4ACEJncwCTuO-dTg', asema: 'Info Radio Ghana', virallinen: true, kaupunki: 'Accra', lat: 5.56, lon: -0.2 },
  GIN: { url: 'https://stream.zeno.fm/xirmzwnnpintv', asema: 'LGF TALK GUINEE', kaupunki: 'Conakry', lat: 9.51, lon: -13.71 },
  GNB: { url: 'https://stream-179.surfernetwork.com/iwioelqe6qwtv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJpd2lvZWxxZTZxd3R2IiwiaG9zdCI6InN0cmVhbS0xNzkuc3VyZmVybmV0d29yay5jb20iLCJ0bSI6ZmFsc2UsInJ0dGwiOjUsImp0aSI6IlI3bmhuQURWVDV5RUFITVF5UC14ekEiLCJpYXQiOjE3OTA0MzEyNjcsImV4cCI6MTc5MDQzMTMyN30.kl8JlD55r3VyDon3KHBIxwW6U6zElfwyWE5xdBXPYj4', asema: 'Rádio Voz da Guiné', kaupunki: 'Bissau', lat: 11.86, lon: -15.58 },
  GNQ: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/XHPSFMAAC.aac', asema: 'Exa FM', kaupunki: 'Malabo', lat: 3.75, lon: 8.78 },
  GRC: { url: 'https://radiostreaming.ert.gr/ert-proto', asema: 'ΕΡΤ Πρώτο Πρόγραμμα', virallinen: true, kaupunki: 'Ateena', lat: 37.98, lon: 23.73 },
  GRD: { url: 'https://starchild.radioca.st/', asema: 'Star FM 101.9', kaupunki: 'St. George’s', lat: 12.05, lon: -61.75 },
  GRL: { url: 'https://getnanoq.retro-radio.dk/Nanoq-TX-1', asema: 'Nanoq FM (Nuuk)', kaupunki: 'Nuuk', lat: 64.18, lon: -51.73 },
  GTM: { url: 'https://stream.zenolive.com/z96sq8tndseuv', asema: 'Emisoras Unidas 89.7', virallinen: true, kaupunki: 'Guatemala', lat: 14.64, lon: -90.51 },
  GUY: { url: 'https://cast4.asurahosting.com/proxy/ncn1025/stream', asema: '102.5 FM Voice of Guyana', virallinen: true, kaupunki: 'Georgetown', lat: 6.81, lon: -58.15 },
  HKG: { url: 'https://stm1.rthk.hk/radio1', asema: 'RTHK Radio 1', virallinen: true, kaupunki: 'Hongkong', lat: 22.28, lon: 114.16 },
  HND: { url: 'https://securestreams7.autopo.st/?uri=http://216.152.154.134/HRN?=hrn670khz', asema: 'hrn 670 KHz', virallinen: true, kaupunki: 'Tegucigalpa', lat: 14.11, lon: -87.2 },
  HRV: { url: 'https://27863.live.streamtheworld.com/PROGRAM1AAC_SC', asema: 'HRT HR 1 - Prvi program', virallinen: true, kaupunki: 'Zagreb', lat: 45.81, lon: 15.98 },
  HTI: { url: 'https://rfimonde-96k.ice.infomaniak.ch/rfimonde-96k.mp3', asema: 'RFI', kaupunki: 'Port-au-Prince', lat: 18.55, lon: -72.34 },
  HUN: { url: 'https://icast.connectmedia.hu/4736/mr1.mp3', asema: 'Kossuth', virallinen: true, kaupunki: 'Budapest', lat: 47.5, lon: 19.04 },
  IDN: { url: 'https://stream-node0.rri.co.id/streaming/14/9014/kbrn.mp3', asema: 'RRI Pro 3 KBRN', virallinen: true, kaupunki: 'Jakarta', lat: -6.18, lon: 106.83 },
  IND: { url: 'https://audio-edge-fvq45.ams.d.radiomast.io/3ccc1156-fcf8-4ba7-9a0c-28e3a465e1ae?listening-from-radio-garden=1607152226837', asema: 'aakashvani', virallinen: true, kaupunki: 'New Delhi', lat: 28.61, lon: 77.21 },
  IRL: { url: 'https://icecast.rte.ie/radio1', asema: 'RTÉ Radio 1', virallinen: true, kaupunki: 'Dublin', lat: 53.35, lon: -6.26 },
  IRN: { url: 'https://radio.iraninternational.app/iintl_c', asema: 'Radio Iran International', virallinen: true, kaupunki: 'Teheran', lat: 35.69, lon: 51.39 },
  IRQ: { url: 'https://radio.shafaq.com/radio', asema: 'Radio Shafaq (Shafaq News)', kaupunki: 'Bagdad', lat: 33.32, lon: 44.37 },
  ISL: { url: 'https://stream.utvarpsaga.is/Hljodver', asema: 'Útvarp Saga', kaupunki: 'Reykjavík', lat: 64.15, lon: -21.93 },
  ISR: { url: 'https://28563.live.streamtheworld.com/KAN_BET.mp3', asema: 'Kan Bet', virallinen: true, kaupunki: 'Jerusalem', lat: 31.78, lon: 35.23 },
  ITA: { url: 'https://icestreaming.rai.it/1.mp3', asema: 'Rai Radio 1', virallinen: true, kaupunki: 'Rooma', lat: 41.89, lon: 12.48 },
  JAM: { url: 'https://stream.zeno.fm/cub84trbgy5tv', asema: 'Radio Jamaica 94FM', virallinen: true, kaupunki: 'Kingston', lat: 17.97, lon: -76.79 },
  JOR: { url: 'https://dc1.serverse.com/proxy/kjxwtpdt/stream', asema: 'Hayat FM (Amman)', kaupunki: 'Amman', lat: 31.93, lon: 35.93 },
  JPN: { url: 'https://fmsetagaya834.out.airtime.pro/fmsetagaya834_a', asema: 'エフエム世田谷 (FM Setagaya 83.4 MHz, Tokio)', kaupunki: 'Tokio', lat: 35.69, lon: 139.69 },
  KAZ: { url: 'https://radio-streams.kaztrk.kz/qazradio/qazradio/icecast.audio', asema: 'Qazaq radiosy', virallinen: true, kaupunki: 'Astana', lat: 51.13, lon: 71.43 },
  KEN: { url: 'https://stream.zeno.fm/ud2u96xst5quv', asema: 'KBC', virallinen: true, kaupunki: 'Nairobi', lat: -1.29, lon: 36.82 },
  KGZ: { url: 'https://liveradio.utrk.kg/1radio', asema: 'Birinchi Radio (UTRK)', virallinen: true, kaupunki: 'Biškek', lat: 42.87, lon: 74.57 },
  KHM: { url: 'https://streaming.radio.co/sd48fd711d/listen', asema: 'LDP Radio', kaupunki: 'Phnom Penh', lat: 11.57, lon: 104.92 },
  KIR: { url: 'https://streamer5.rightclickitservices.com:19790/stream', asema: 'Radio Kiribati 1440 kHz', virallinen: true, kaupunki: 'South Tarawa', lat: 1.33, lon: 172.97 },
  KNA: { url: 'https://media.slactech.com:8014/stream', asema: 'ZIZ Radio', virallinen: true, kaupunki: 'Basseterre', lat: 17.3, lon: -62.73 },
  KOR: { url: 'https://wbsradio.kr/wbs-seoul', asema: 'WBS 원음방송 서울', kaupunki: 'Soul', lat: 37.56, lon: 126.99 },
  KWT: { url: 'https://listen.radioking.com/radio/280804/stream/326527', asema: 'moja (مُوجَة), Kuwait City', kaupunki: 'Kuwait', lat: 29.38, lon: 47.98 },
  LAO: { url: 'https://radio.lnr.org.la/fm103', asema: 'Lao National Radio 103.7', virallinen: true, kaupunki: 'Vientiane', lat: 17.98, lon: 102.63 },
  LBN: { url: 'https://edge.mixlr.com/channel/qtqeb', asema: 'Radio Liban Libre', virallinen: true, kaupunki: 'Beirut', lat: 33.89, lon: 35.51 },
  LBR: { url: 'https://stream.zeno.fm/xxmnohwx4zyuv', asema: 'LBS Radio (Liberia Broadcasting System)', virallinen: true, kaupunki: 'Monrovia', lat: 6.31, lon: -10.8 },
  LBY: { url: 'https://stream.zeno.fm/z9wfrdpmgg0uv', asema: 'Radio Funun Tripoli (راديو فنون طرابلس)', kaupunki: 'Tripoli', lat: 32.89, lon: 13.19 },
  LCA: { url: 'https://streams.radio.co/s5f11a7ef9/listen', asema: 'BLAZIN 99.3FM', kaupunki: 'Castries', lat: 14.01, lon: -60.99 },
  LIE: { url: 'https://radiostream.radiobutler.com/7e9d5eb6-9249-4c7a-9f1c-6d4b9c7a48a8', asema: 'Radio Vaterland', kaupunki: 'Vaduz', lat: 47.14, lon: 9.52 },
  LKA: { url: 'https://stream-32.zeno.fm/xekhrn4zetzuv?zs=KXT1gTNYSemcxyslV6-vdA', asema: 'SLBC Tamil National Service', virallinen: true, kaupunki: 'Colombo', lat: 6.93, lon: 79.86 },
  LTU: { url: 'https://netradio.ziniur.lt/ziniur.mp3', asema: 'Žinių radijas', kaupunki: 'Vilna', lat: 54.69, lon: 25.28 },
  LUX: { url: 'https://stream.100komma7.lu/100komma7/live/mp3/128/stream.mp3', asema: 'Radio 100komma7', virallinen: true, kaupunki: 'Luxemburg', lat: 49.61, lon: 6.13 },
  LVA: { url: 'https://live.radioswh.lv/plusmp3', asema: 'Radio SWH+', kaupunki: 'Riika', lat: 56.95, lon: 24.11 },
  MAR: { url: 'https://stream.zeno.fm/une3a02mb', asema: 'MA:-Hit Radio Maroc', virallinen: true, kaupunki: 'Rabat', lat: 34.02, lon: -6.84 },
  MCO: { url: 'https://radiomonaco.ice.infomaniak.ch/radiomonaco-128.mp3', asema: 'Radio Monaco 98.2', virallinen: true, kaupunki: 'Monaco', lat: 43.73, lon: 7.42 },
  MDA: { url: 'https://stream.noroc.tv/radiovb_aac', asema: 'Vocea Basarabiei', kaupunki: 'Chișinău', lat: 47.02, lon: 28.84 },
  MDG: { url: 'https://direct.radiomadagasikara.com/listen/rnm/radio.mp3', asema: 'RNM', virallinen: true, kaupunki: 'Antananarivo', lat: -18.91, lon: 47.53 },
  MDV: { url: 'https://radio.psm.mv/draair', asema: 'Dhivehi Raajjeyge Adu', virallinen: true, kaupunki: 'Malé', lat: 4.18, lon: 73.51 },
  MEX: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/W_RADIOAAC.aac', asema: 'W Radio Ciudad de México - 96.9 FM / 900 AM -', virallinen: true, kaupunki: 'Mexico', lat: 19.35, lon: -99.14 },
  MKD: { url: 'https://liderfm.ipradio.mk/', asema: 'Lider FM 107,4', kaupunki: 'Skopje', lat: 42, lon: 21.43 },
  MLI: { url: 'https://stream-157.zeno.fm/yerp85sughwtv?zs=bzqHawb1Rha3gGg97iW8xg', asema: 'Radio Malijet', virallinen: true, kaupunki: 'Bamako', lat: 12.65, lon: -7.99 },
  MLT: { url: 'https://s4.radio.co/sf3aa4c25a/listen', asema: 'Calypso Radio', kaupunki: 'Valletta', lat: 35.9, lon: 14.51 },
  MMR: { url: 'https://listen.radioking.com/radio/681745/stream/746185', asema: 'Shwe FM (valtakunnallinen FM-verkko, Yangon)', kaupunki: 'Naypyidaw', lat: 19.75, lon: 96.12 },
  MNE: { url: 'https://stream.radios.rs:9008/;', asema: 'Radio S1 Crna Gora', kaupunki: 'Podgorica', lat: 42.44, lon: 19.26 },
  MNG: { url: 'https://c2.radioboss.fm/stream/394', asema: 'Гэр бүлийн радио 104.5 (Family Radio, Ulaanbaatar)', kaupunki: 'Ulan Bator', lat: 47.92, lon: 106.91 },
  MOZ: { url: 'https://stream.zeno.fm/tskpv4vscv8uv', asema: 'Rádio Moçambique', virallinen: true, kaupunki: 'Maputo', lat: -25.97, lon: 32.57 },
  MUS: { url: 'https://stream.radioplus.mu:8000/radio.mp3', asema: 'Radio Plus Mauritius', kaupunki: 'Port Louis', lat: -20.16, lon: 57.5 },
  MWI: { url: 'https://ice31.securenetsystems.net/0079', asema: 'ZBS Zodiak FM', kaupunki: 'Lilongwe', lat: -13.99, lon: 33.77 },
  MYS: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/NASIONAL_FM.mp3', asema: 'Nasional FM 88,5 MHz', virallinen: true, kaupunki: 'Kuala Lumpur', lat: 3.15, lon: 101.7 },
  NAM: { url: 'https://edge.iono.fm/xice/193_high.aac', asema: 'Omulunga Radio 100.9 (Windhoek)', kaupunki: 'Windhoek', lat: -22.57, lon: 17.08 },
  NER: { url: 'https://stream.zeno.fm/1y2c3qbgbchvv', asema: 'Wadata Radio 107.4 Niamey', kaupunki: 'Niamey', lat: 13.52, lon: 2.12 },
  NGA: { url: 'https://mega-public-relay.deathsmack-a51.workers.dev/', asema: 'ZamRock Radio Nigeria Relay', virallinen: true, kaupunki: 'Abuja', lat: 9.06, lon: 7.49 },
  NIC: { url: 'https://stream.zeno.fm/cbd1wweamzzuv', asema: 'La Voz del Norte', kaupunki: 'Managua', lat: 12.15, lon: -86.27 },
  NLD: { url: 'https://icecast.omroep.nl/radio1-bb-mp3', asema: 'NPO Radio 1', virallinen: true, kaupunki: 'Amsterdam', lat: 52.37, lon: 4.88 },
  NOR: { url: 'https://lyd.nrk.no/icecast/aac/high/s0w7hwn47m/p1_dk4', asema: 'NRK P1 Nordland', virallinen: true, kaupunki: 'Oslo', lat: 59.91, lon: 10.75 },
  NPL: { url: 'https://stream1.radionepal.gov.np/live/', asema: 'Radio Nepal', virallinen: true, kaupunki: 'Kathmandu', lat: 27.71, lon: 85.32 },
  NZL: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/NZME_41AAC.aac', asema: 'Newstalk ZB', kaupunki: 'Wellington', lat: -41.29, lon: 174.78 },
  OMN: { url: 'https://stream.zeno.fm/84652g7meg8uv', asema: 'Al Wisal (الوصال), Muscat', kaupunki: 'Masqat', lat: 23.61, lon: 58.59 },
  PAK: { url: 'https://samaakhi107-itelservices.radioca.st/stream', asema: 'MERA FM 107.4', kaupunki: 'Islamabad', lat: 33.7, lon: 73.04 },
  PAN: { url: 'https://stream.zeno.fm/nvpr0uec8e9uv', asema: 'La Exitosa Panamá', kaupunki: 'Panamá', lat: 8.97, lon: -79.53 },
  PER: { url: 'https://mdstrm.com/audio/5fab3416b5f9ef165cfab6e9/icecast.audio', asema: 'Radio RPP Noticias', virallinen: true, kaupunki: 'Lima', lat: -12.06, lon: -77.04 },
  PHL: { url: 'https://azura.dzrh.com.ph/listen/dzrh_manila/radio.mp3', asema: 'DZRH', virallinen: true, kaupunki: 'Manila', lat: 14.6, lon: 120.98 },
  PLW: { url: 'https://live.upbeat.pw/', asema: 'UpBeat.pw', kaupunki: 'Ngerulmud', lat: 7.5, lon: 134.62 },
  PNG: { url: 'https://stream.rcs.revma.com/n5vb288kmbpwv', asema: 'Yumi FM (tok pisin, Port Moresby)', kaupunki: 'Port Moresby', lat: -9.48, lon: 147.15 },
  POL: { url: 'https://radiostream.pl/tuba10-1.mp3', asema: 'TOK FM', kaupunki: 'Varsova', lat: 52.23, lon: 21.01 },
  PRK: { url: 'https://listen7.myradio24.com/69366', asema: 'Pyongyang Radio FM', virallinen: true, kaupunki: 'Pjongjang', lat: 39.02, lon: 125.75 },
  PRT: { url: 'https://radiocast.rtp.pt/rdpint80a.mp3', asema: 'RDP Internacional - Main', virallinen: true, kaupunki: 'Lissabon', lat: 38.71, lon: -9.14 },
  PRY: { url: 'https://1000noticias.live:8000/radio.mp3', asema: 'Radio 1000 AM', kaupunki: 'Asunción', lat: -25.28, lon: -57.63 },
  PSE: { url: 'https://cdna.streamgates.net/RadioNas/Live-Audio/icecast.audio', asema: 'راديو الناس', kaupunki: 'Ramallah', lat: 31.9, lon: 35.2 },
  QAT: { url: 'https://l3.itworkscdn.net/alarabyradiolive/alarabyradio_audio/icecast.audio', asema: 'Al Araby Radio (Doha/Lusail)', kaupunki: 'Doha', lat: 25.29, lon: 51.53 },
  ROU: { url: 'https://edge76.rcs-rds.ro/digifm/digi24fm.mp3', asema: 'Digi24 FM', kaupunki: 'Bukarest', lat: 44.41, lon: 26.1 },
  RUS: { url: 'https://icecast-vgtrk.cdnvideo.ru/vestifm_mp3_64kbps', asema: 'Вести ФМ', virallinen: true, kaupunki: 'Moskova', lat: 55.75, lon: 37.62 },
  RWA: { url: 'https://stream.zeno.fm/k5rq7qwkggauv', asema: 'MENYA FM', kaupunki: 'Kigali', lat: -1.95, lon: 30.12 },
  SAU: { url: 'https://stream-154.zeno.fm/pdeizhgrtrstv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJwZGVpemhncnRyc3R2IiwiaG9zdCI6InN0cmVhbS0xNTQuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Im9vbng2V1J3UXJ5Q0k5TVV0N01heEEiLCJpYXQiOjE3MjgyMjQ1MTYsImV4cCI6MTcyODIyNDU3Nn0.gpUIWkDBFNNFjqCg2R-xQN4LXT4z8_Ivs7d2UkeFE_8', asema: 'SBA Riyadh Radio 91.5 FM', virallinen: true, kaupunki: 'Riad', lat: 24.65, lon: 46.71 },
  SDN: { url: 'https://a13.asurahosting.com/listen/al_masaa_fm_101/radio.mp3', asema: 'Al Masaa FM 101 (Khartum)', kaupunki: 'Khartum', lat: 15.6, lon: 32.53 },
  SDS: { url: 'https://stream.zeno.fm/w3lic6qp9eouv', asema: 'Freedom FM', kaupunki: 'Juba', lat: 4.85, lon: 31.58 },
  SEN: { url: 'https://stream.zeno.fm/kxud8vhqt1duv', asema: 'RTS Matam 89.1', virallinen: true, kaupunki: 'Dakar', lat: 14.67, lon: -17.43 },
  SGP: { url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/CAPITAL958FM_PREM.aac', asema: 'CAPITAL 958', virallinen: true, kaupunki: 'Singapore', lat: 1.3, lon: 103.8 },
  SHN: { url: 'https://s2.radio.co/s418cc827e/listen', asema: 'SAMS Radio 1', kaupunki: 'Jamestown', lat: -15.93, lon: -5.72 },
  SLB: { url: 'https://listen.mixlr.com/e1e2be07dfce2a18e8ee3cdd0dd2d437', asema: 'SIBC Solomon Islands Broadcasting (Honiara)', virallinen: true, kaupunki: 'Honiara', lat: -9.43, lon: 159.95 },
  SLE: { url: 'https://stream.zeno.fm/jetj7igyezmtv', asema: 'Culture Radio FM 104.5 (Freetown)', kaupunki: 'Freetown', lat: 8.49, lon: -13.24 },
  SLV: { url: 'https://centova.playerfullhd.com/proxy/brfrtxcf/stream', asema: 'Radio Mercado Metapan', kaupunki: 'San Salvador', lat: 13.7, lon: -89.19 },
  SMR: { url: 'https://usmaradio.out.airtime.pro:8000/usmaradio_a', asema: 'USMARADIO', kaupunki: 'San Marino', lat: 43.93, lon: 12.45 },
  SOM: { url: 'https://stream.zeno.fm/m7p996vfec9uv', asema: 'Radio Shabelle 101.5 (Mogadishu)', kaupunki: 'Mogadishu', lat: 2.04, lon: 45.34 },
  SRB: { url: 'https://stream.redradio.rs/sid=1', asema: 'Red radio Beograd', virallinen: true, kaupunki: 'Belgrad', lat: 44.82, lon: 20.46 },
  SUR: { url: 'https://s5.radio.co/s85a633f73/listen', asema: 'Radio 10 Magic FM', kaupunki: 'Paramaribo', lat: 5.87, lon: -55.17 },
  SVK: { url: 'https://icecast.stv.livebox.sk/slovensko_128.mp3', asema: 'Rádio Slovensko', virallinen: true, kaupunki: 'Bratislava', lat: 48.15, lon: 17.11 },
  SVN: { url: 'https://mp3.rtvslo.si/val202', asema: 'Val 202', virallinen: true, kaupunki: 'Ljubljana', lat: 46.05, lon: 14.51 },
  SWE: { url: 'https://live1.sr.se/p1-aac-32', asema: 'Sveriges Radio P1', virallinen: true, kaupunki: 'Tukholma', lat: 59.33, lon: 18.07 },
  SYR: { url: 'https://asima.out.airtime.pro/asima_a', asema: 'Al Asemeh FM / العاصمة إف إم (Damaskos)', kaupunki: 'Damaskos', lat: 33.51, lon: 36.29 },
  TCD: { url: 'https://strhls.streamakaci.tv/str_tchad_radio/str_tchad_radio/icecast.audio', asema: 'Radiodiffusion Nationale Tchadienne', virallinen: true, kaupunki: 'N’Djamena', lat: 12.11, lon: 15.05 },
  TGO: { url: 'https://stream.zeno.fm/vkhv6gl43g5tv', asema: 'Radio Victoire 96.3 Lomé', kaupunki: 'Lomé', lat: 6.13, lon: 1.22 },
  THA: { url: 'https://radio12.plathong.net/7234/;stream.mp3', asema: 'วิทยุเสียงอิสลาม', virallinen: true, kaupunki: 'Bangkok', lat: 13.75, lon: 100.52 },
  TLS: { url: 'https://streaming.kalohan.net/proxy/raliber?mp=/stream', asema: 'Rádio Liberdade Dili', kaupunki: 'Dili', lat: -8.55, lon: 125.58 },
  TON: { url: 'https://stream.zeno.fm/wnd22q3485quv', asema: 'Letio Tonga', kaupunki: 'Nukuʻalofa', lat: -21.13, lon: -175.2 },
  TTO: { url: 'https://media.streambrothers.com:8450/stream', asema: 'Talk City 91.1 FM', kaupunki: 'Port of Spain', lat: 10.67, lon: -61.52 },
  TUN: { url: 'https://radio.radiotunisienne.tn/nationale', asema: 'Radio Nationale', virallinen: true, kaupunki: 'Tunis', lat: 36.8, lon: 10.18 },
  TUR: { url: 'https://trt.radyotvonline.net/trt1', asema: 'TRT Radyo 1', virallinen: true, kaupunki: 'Ankara', lat: 39.94, lon: 32.84 },
  TWN: { url: 'https://n03.rcs.revma.com/78fm9wyy2tzuv', asema: '中廣新聞網', virallinen: true, kaupunki: 'Taipei', lat: 25.04, lon: 121.56 },
  TZA: { url: 'https://a7.asurahosting.com/listen/tbc_taifa/radio.mp3', asema: 'TBC Taifa', virallinen: true, kaupunki: 'Dodoma', lat: -6.18, lon: 35.75 },
  UGA: { url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service_west_africa', asema: '107.3 BBC Radio Uganda', virallinen: true, kaupunki: 'Kampala', lat: 0.31, lon: 32.58 },
  UKR: { url: 'https://online-news.radioplayer.ua/RadioNews', asema: 'Єдині новини (Radio News)', kaupunki: 'Kiova', lat: 50.45, lon: 30.52 },
  URY: { url: 'https://stream.rcast.net/73479', asema: 'CX 30 Radio Nacional (La Treinta)', virallinen: true, kaupunki: 'Montevideo', lat: -34.91, lon: -56.19 },
  USA: { url: 'https://fm939.wnyc.org/wnycfm', asema: 'WNYC-FM 93.9 New York Public Radio', virallinen: true, kaupunki: 'Washington', lat: 38.9, lon: -77.04 },
  UZB: { url: 'https://live.qalbimnavosi.uz/qalbimnavosi', asema: 'Qalbim navosi', kaupunki: 'Taškent', lat: 41.31, lon: 69.28 },
  VAT: { url: 'https://radio.vaticannews.va/stream-en', asema: 'Radio Vaticana English', virallinen: true, kaupunki: 'Vatikaani', lat: 41.9, lon: 12.45 },
  VCT: { url: 'https://video1.getstreamhosting.com:2000/stream/8260', asema: 'WE FM 99.9 SVG', kaupunki: 'Kingstown', lat: 13.16, lon: -61.23 },
  VEN: { url: 'https://guri.tepuyserver.net/8048/stream', asema: 'Radio Nacional de Venezuela - Informativa', virallinen: true, kaupunki: 'Caracas', lat: 10.51, lon: -66.91 },
  VNM: { url: 'https://rfienvietnamien64k.ice.infomaniak.ch/rfienvietnamien-64.mp3', asema: 'RFI Tiếng Việt', kaupunki: 'Hanoi', lat: 21.02, lon: 105.84 },
  VUT: { url: 'https://radio.vbtc.vu/paradisefm', asema: 'Paradise 98FM (VBTC, Port Vila)', virallinen: true, kaupunki: 'Port Vila', lat: -17.73, lon: 168.32 },
  XKX: { url: 'https://stream.glamradio.fm:8443/glamradio', asema: 'GlamRADIO', kaupunki: 'Pristina', lat: 42.67, lon: 21.17 },
  YEM: { url: 'https://dc5.serverse.com/proxy/pbmhbvxs/stream', asema: 'Sana\'a Radio (إذاعة صنعاء)', virallinen: true, kaupunki: 'Sanaa', lat: 15.35, lon: 44.2 },
  ZAF: { url: 'https://25643.live.streamtheworld.com/UKHOZIFMAAC_SC', asema: 'Ukhozi FM (SABC)', virallinen: true, kaupunki: 'Kapkaupunki', lat: -33.93, lon: 18.42 },
  ZMB: { url: 'https://edge.iono.fm/xice/57_medium.aac?ref=https%3A%2F%2Fhot1027.co.za%2F&adToken=', asema: 'Hot 102.7FM', kaupunki: 'Lusaka', lat: -15.42, lon: 28.28 },
  ZWE: { url: 'https://edge.iono.fm/xice/159_high.aac', asema: 'Star FM 89.7 (Harare)', kaupunki: 'Harare', lat: -17.83, lon: 31.05 },
};

/** Maan suora lähetys, tai null. */
export function radioMaalle(maa) {
  return (maa && RADIOT[maa]) || null;
}
