// VALTIOT 1873 — Isoisän linssin valtioiden nimet (Karttaseppä 21.9.2026, Sisältökirjuri tarkistaa).
//
// Lähde: historical-basemaps world_1878 (GPL-3.0) NAME-kenttä, 1878 → 1873:
// Bulgaria ja Bosnia-Hertsegovina pois (Osmanien), Romania/Serbia/Montenegro
// vasalleiksi (luokka 2), Ranskan Kongo ja Wassoulou pois (syntyivät 1878).
// Nimiöpaikka (lon/lat) on suurimman alueen saavuttamattomuusnapa; suurille
// valtakunnille käsin siirretty (tools/tee-valtiot-1873.mjs SIIRROT).
// Nimet suomalaisittain vakiintuneina 1873-muodossa (Abessinia, Persia, Siam,
// Kotšinkiina, Osmanien valtakunta); kaanon docs/isoisan-raamattu.md voittaa.
//
// luokka: 1 = itsenäinen valtio, 2 = vasalli/autonominen, 3 = siirtomaa/alusmaa
// koko: 'suuri' (> 100°²) ja 'keski' (> 3,5°²) näkyvät laudan uloimmalla zoomilla, 'pieni' lähempänä.

export const VALTIOT_1873 = [
  { teksti: 'ABESSINIA', lon: 36.81, lat: 11.56, luokka: 1, koko: 'keski', lahde: 'Ethiopia' },
  { teksti: 'AFGANISTAN', lon: 65.07, lat: 33.41, luokka: 1, koko: 'keski', lahde: 'Afghanistan' },
  { teksti: 'ALANKOMAAT', lon: 6.3, lat: 52.79, luokka: 1, koko: 'keski', lahde: 'Netherlands' },
  { teksti: 'ALANKOMAIDEN GUAYANA', lon: -55.81, lat: 3.97, luokka: 3, koko: 'keski', lahde: 'Dutch Guiana' },
  { teksti: 'ALANKOMAIDEN INTIA', lon: 114.04, lat: -1.1, luokka: 3, koko: 'keski', lahde: 'Netherlands Indies' },
  { teksti: 'ALGERIA', lon: 2.5, lat: 34, luokka: 3, koko: 'keski', huom: 'Ranska', lahde: 'Algeria (FR)' },
  { teksti: 'ANGOLA', lon: 13.79, lat: -9.46, luokka: 3, koko: 'keski', huom: 'Portugali', lahde: 'Angola (Portugal)' },
  { teksti: 'ANNAM', lon: 105.27, lat: 21.68, luokka: 1, koko: 'keski', lahde: 'Annam' },
  { teksti: 'ARABIA', lon: 49.64, lat: 19.54, luokka: 1, koko: 'suuri', lahde: 'Arabia' },
  { teksti: 'ARGENTIINA', lon: -62.91, lat: -28.62, luokka: 1, koko: 'suuri', lahde: 'Argentina' },
  { teksti: 'ASANTE', lon: -1.72, lat: 6.62, luokka: 1, koko: 'keski', lahde: 'Asante' },
  { teksti: 'BASUTOMAA', lon: 28.07, lat: -29.43, luokka: 3, koko: 'pieni', huom: 'Britannia', lahde: 'Basutoland' },
  { teksti: 'BELGIA', lon: 4.69, lat: 50.73, luokka: 1, koko: 'keski', lahde: 'Belgium' },
  { teksti: 'BHUTAN', lon: 89.82, lat: 27.4, luokka: 1, koko: 'pieni', lahde: 'Bhutan' },
  { teksti: 'BOLIVIA', lon: -64.58, lat: -17.11, luokka: 1, koko: 'suuri', lahde: 'Bolivia' },
  { teksti: 'BRASILIAN KEISARIKUNTA', lon: -50, lat: -12, luokka: 1, koko: 'suuri', lahde: 'Kingdom of Brazil' },
  { teksti: 'BRITANNIA', lon: -1.8, lat: 53.2, luokka: 1, koko: 'keski', huom: 'Ison-Britannian ja Irlannin yhdistynyt kuningaskunta', lahde: 'United Kingdom of Great Britain and Ireland' },
  { teksti: 'BRITTILÄINEN GUAYANA', lon: -58.65, lat: 5.53, luokka: 3, koko: 'keski', lahde: 'British Guiana' },
  { teksti: 'BRITTILÄINEN HONDURAS', lon: -88.74, lat: 16.94, luokka: 3, koko: 'pieni', lahde: 'Belize' },
  { teksti: 'BRITTILÄINEN INTIA', lon: 78, lat: 22, luokka: 3, koko: 'suuri', lahde: 'British Raj' },
  { teksti: 'BRUNEI', lon: 114.75, lat: 4.48, luokka: 1, koko: 'pieni', lahde: 'Brunei' },
  { teksti: 'BUGANDA', lon: 32.25, lat: 0.08, luokka: 1, koko: 'keski', lahde: 'Buganda' },
  { teksti: 'BUHARAN EMIRAATTI', lon: 62.54, lat: 37.4, luokka: 2, koko: 'keski', lahde: 'Bokhara Khanate' },
  { teksti: 'CEYLON', lon: 80.83, lat: 7.06, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'Ceylon' },
  { teksti: 'CHILE', lon: -69.67, lat: -26.69, luokka: 1, koko: 'keski', lahde: 'Chile' },
  { teksti: 'COSTA RICA', lon: -83.96, lat: 10.1, luokka: 1, koko: 'keski', lahde: 'Costa Rica' },
  { teksti: 'DAHOMEY', lon: 1.71, lat: 7.42, luokka: 1, koko: 'pieni', lahde: 'Dahomey' },
  { teksti: 'DOMINIKAANINEN TASAVALTA', lon: -71.01, lat: 19.15, luokka: 1, koko: 'keski', lahde: 'Dominican Republic' },
  { teksti: 'ECUADOR', lon: -76.6, lat: -2.16, luokka: 1, koko: 'keski', lahde: 'Ecuador' },
  { teksti: 'EGYPTI', lon: 30.5, lat: 26.5, luokka: 2, koko: 'suuri', huom: 'Osmanien khedivaatti', lahde: 'Egypt' },
  { teksti: 'EL SALVADOR', lon: -89.26, lat: 13.88, luokka: 1, koko: 'pieni', lahde: 'El Salvador' },
  { teksti: 'ESPANJA', lon: -3.7, lat: 40, luokka: 1, koko: 'keski', lahde: 'Spain' },
  { teksti: 'ETELÄ-AUSTRALIA', lon: 136.12, lat: -29.3, luokka: 3, koko: 'suuri', huom: 'Britannia', lahde: 'South Australia (UK)' },
  { teksti: 'FIDŽI', lon: 177.97, lat: -17.83, luokka: 1, koko: 'pieni', lahde: 'Fiji' },
  { teksti: 'FILIPPIINIT', lon: 121.23, lat: 17, luokka: 3, koko: 'keski', huom: 'Espanja', lahde: 'Philippines' },
  { teksti: 'GAMBIA', lon: -16, lat: 13.53, luokka: 3, koko: 'pieni', huom: 'Britannia', lahde: 'Gambia' },
  { teksti: 'GRÖNLANTI', lon: -42, lat: 72, luokka: 3, koko: 'suuri', huom: 'Tanska', lahde: 'Greenland' },
  { teksti: 'GUATEMALA', lon: -91.05, lat: 15.06, luokka: 1, koko: 'keski', lahde: 'Guatemala' },
  { teksti: 'HAITI', lon: -72.23, lat: 19.22, luokka: 1, koko: 'pieni', lahde: 'Haiti' },
  { teksti: 'HAVAIJI', lon: -155.63, lat: 19.65, luokka: 1, koko: 'pieni', huom: 'kuningaskunta', lahde: 'Kingdom of Hawaii' },
  { teksti: 'HONDURAS', lon: -87.14, lat: 14.73, luokka: 1, koko: 'keski', lahde: 'Honduras' },
  { teksti: 'ISLANTI', lon: -18.6, lat: 64.58, luokka: 3, koko: 'keski', huom: 'Tanska', lahde: 'Iceland' },
  { teksti: 'ITALIA', lon: 12.4, lat: 43, luokka: 1, koko: 'keski', huom: 'kuningaskunta', lahde: 'Italy' },
  { teksti: 'ITÄVALTA-UNKARI', lon: 18.5, lat: 47.6, luokka: 1, koko: 'keski', lahde: 'Austria Hungary' },
  { teksti: 'JAPANI', lon: 139.47, lat: 36.58, luokka: 1, koko: 'keski', huom: 'keisarikunta', lahde: 'Imperial Japan' },
  { teksti: 'KANADA', lon: -100, lat: 57, luokka: 3, koko: 'suuri', huom: 'Britannian dominio 1867', lahde: 'Canada' },
  { teksti: 'KANEM-BORNU', lon: 15.12, lat: 14.12, luokka: 1, koko: 'keski', lahde: 'Kanem-Bornu' },
  { teksti: 'KAPMAA', lon: 20.77, lat: -31.53, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'Cape Colony' },
  { teksti: 'KIINAN KEISARIKUNTA', lon: 104, lat: 35, luokka: 1, koko: 'suuri', huom: 'Qing-dynastia', lahde: 'Manchu Empire' },
  { teksti: 'KOKAND', lon: 72.88, lat: 39.32, luokka: 1, koko: 'keski', huom: 'kaanikunta', lahde: 'central Asian khanates' },
  { teksti: 'KOLUMBIA', lon: -71.96, lat: 2.76, luokka: 1, koko: 'suuri', lahde: 'Colombia' },
  { teksti: 'KOREA', lon: 128.23, lat: 36.68, luokka: 1, koko: 'keski', huom: 'Joseon', lahde: 'Korea' },
  { teksti: 'KOTŠINKIINA', lon: 104.42, lat: 12.58, luokka: 3, koko: 'keski', huom: 'Ranska', lahde: 'French Indochina' },
  { teksti: 'KREIKKA', lon: 21.9, lat: 39.53, luokka: 1, koko: 'keski', lahde: 'Greece' },
  { teksti: 'KULTARANNIKKO', lon: -1.61, lat: 5.47, luokka: 3, koko: 'pieni', huom: 'Britannia', lahde: 'Gold Coast (GB)' },
  { teksti: 'LIBERIA', lon: -10.51, lat: 6.98, luokka: 1, koko: 'keski', lahde: 'Liberia' },
  { teksti: 'LUXEMBURG', lon: 6.11, lat: 49.71, luokka: 1, koko: 'pieni', lahde: 'Luxembourg' },
  { teksti: 'LÄNSI-AUSTRALIA', lon: 121.8, lat: -26.66, luokka: 3, koko: 'suuri', huom: 'Britannia', lahde: 'Western Australia (UK)' },
  { teksti: 'MADAGASKAR', lon: 45.17, lat: -23.99, luokka: 1, koko: 'keski', huom: 'Merinan kuningaskunta', lahde: 'Madagascar' },
  { teksti: 'MAROKKO', lon: -5, lat: 33.16, luokka: 1, koko: 'keski', lahde: 'Morocco' },
  { teksti: 'MATABELE', lon: 26.95, lat: -19.38, luokka: 1, koko: 'keski', lahde: 'Ndebele' },
  { teksti: 'MEKSIKO', lon: -102.79, lat: 24.95, luokka: 1, koko: 'suuri', lahde: 'Mexico' },
  { teksti: 'MONTENEGRO', lon: 19.19, lat: 42.83, luokka: 2, koko: 'pieni', huom: 'de facto itsenäinen 1873', lahde: 'Montenegro' },
  { teksti: 'MOSAMBIK', lon: 35.34, lat: -18.01, luokka: 3, koko: 'keski', huom: 'Portugali', lahde: 'Mozambique' },
  { teksti: 'MOSSI', lon: -1.05, lat: 12.53, luokka: 1, koko: 'keski', lahde: 'Mossi States' },
  { teksti: 'NATAL', lon: 30.01, lat: -29.54, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'Natal' },
  { teksti: 'NEPAL', lon: 82.13, lat: 29.03, luokka: 1, koko: 'keski', lahde: 'Nepal' },
  { teksti: 'NICARAGUA', lon: -85.27, lat: 12.56, luokka: 1, koko: 'keski', lahde: 'Nicaragua' },
  { teksti: 'OMAN', lon: 58.96, lat: 22.08, luokka: 1, koko: 'keski', lahde: 'Oman' },
  { teksti: 'ORANJEN VAPAAVALTIO', lon: 26.13, lat: -28.53, luokka: 1, koko: 'keski', lahde: 'Orange Free State' },
  { teksti: 'OSMANIEN VALTAKUNTA', lon: 33, lat: 39.5, luokka: 1, koko: 'suuri', lahde: 'Ottoman Empire' },
  { teksti: 'PARAGUAY', lon: -57.16, lat: -23.87, luokka: 1, koko: 'keski', lahde: 'Paraguay' },
  { teksti: 'PERSIA', lon: 55.62, lat: 32.09, luokka: 1, koko: 'suuri', lahde: 'Persia' },
  { teksti: 'PERU', lon: -72.95, lat: -13.36, luokka: 1, koko: 'keski', lahde: 'Peru' },
  { teksti: 'POHJOISTERRITORIO', lon: 133.45, lat: -20.16, luokka: 3, koko: 'suuri', huom: 'Britannia', lahde: 'Northern Territory (UK)' },
  { teksti: 'PORTUGALI', lon: -7.83, lat: 40.43, luokka: 1, koko: 'keski', lahde: 'Portugal' },
  { teksti: 'PORTUGALIN GUINEA', lon: -16.21, lat: 12.8, luokka: 3, koko: 'pieni', lahde: 'Portuguese Guinea' },
  { teksti: 'QUEENSLAND', lon: 145.25, lat: -24.04, luokka: 3, koko: 'suuri', huom: 'Britannia', lahde: 'Queensland (UK)' },
  { teksti: 'RANSKA', lon: 2.3, lat: 47, luokka: 1, koko: 'keski', huom: 'tasavalta', lahde: 'France' },
  { teksti: 'RANSKAN GUAYANA', lon: -53, lat: 4.03, luokka: 3, koko: 'keski', lahde: 'French Guiana' },
  { teksti: 'ROMANIA', lon: 27.8, lat: 46.17, luokka: 2, koko: 'keski', huom: 'Osmanien vasalli 1873', lahde: 'Romania' },
  { teksti: 'RUOTSI-NORJA', lon: 15, lat: 62, luokka: 1, koko: 'suuri', huom: 'unioni', lahde: 'Sweden–Norway' },
  { teksti: 'SAKSAN KEISARIKUNTA', lon: 11, lat: 51.5, luokka: 1, koko: 'keski', lahde: 'Germany' },
  { teksti: 'SAMOA', lon: -172.38, lat: -13.63, luokka: 1, koko: 'pieni', lahde: 'Samoa' },
  { teksti: 'SANSIBAR', lon: 39.14, lat: -2.83, luokka: 1, koko: 'keski', huom: 'sulttaanikunta', lahde: 'Sultinate of Zanzibar' },
  { teksti: 'SENEGAL', lon: -13.16, lat: 15.15, luokka: 3, koko: 'keski', huom: 'Ranska', lahde: 'Senegal (FR)' },
  { teksti: 'SERBIA', lon: 21.29, lat: 43.76, luokka: 2, koko: 'keski', huom: 'Osmanien vasalli 1873', lahde: 'Serbia' },
  { teksti: 'SIAM', lon: 101.86, lat: 17.17, luokka: 1, koko: 'keski', lahde: 'Rattanakosin Kingdom' },
  { teksti: 'SIERRA LEONE', lon: -12.25, lat: 8.8, luokka: 3, koko: 'pieni', huom: 'Britannia', lahde: 'Sierra Leone' },
  { teksti: 'SOKOTON KALIFAATTI', lon: 7.63, lat: 13.56, luokka: 1, koko: 'keski', lahde: 'Sokoto Caliphate' },
  { teksti: 'SVEITSI', lon: 7.5, lat: 46.78, luokka: 1, koko: 'keski', lahde: 'Switzerland' },
  { teksti: 'SWAZIMAA', lon: 31.14, lat: -26.56, luokka: 1, koko: 'pieni', lahde: 'Swaziland' },
  { teksti: 'TANSKA', lon: 9.03, lat: 55.81, luokka: 1, koko: 'keski', lahde: 'Denmark' },
  { teksti: 'TONGA', lon: -175.15, lat: -21.22, luokka: 1, koko: 'pieni', lahde: 'Tonga' },
  { teksti: 'TRANSVAAL', lon: 29.19, lat: -24.39, luokka: 1, koko: 'keski', huom: 'buuritasavalta', lahde: 'Transvaal' },
  { teksti: 'TUKULORIEN VALTAKUNTA', lon: -8.35, lat: 13.94, luokka: 1, koko: 'keski', lahde: 'Tukular Caliphate' },
  { teksti: 'URUGUAY', lon: -56.07, lat: -32.99, luokka: 1, koko: 'keski', lahde: 'Uruguay' },
  { teksti: 'UUSI ETELÄ-WALES', lon: 145.98, lat: -32.33, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'New South Wales (UK)' },
  { teksti: 'UUSI-GUINEA', lon: 142.95, lat: -5.77, luokka: 1, koko: 'keski', lahde: 'Papua New Guinea' },
  { teksti: 'UUSI-SEELANTI', lon: 168.98, lat: -45.37, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'M?ori' },
  { teksti: 'VENEZUELA', lon: -64.06, lat: 5.52, luokka: 1, koko: 'keski', lahde: 'Venezuela' },
  { teksti: 'VENÄJÄN KEISARIKUNTA', lon: 45, lat: 57, luokka: 1, koko: 'suuri', lahde: 'Russian Empire' },
  { teksti: 'VICTORIA', lon: 142.95, lat: -36.85, luokka: 3, koko: 'keski', huom: 'Britannia', lahde: 'Victoria (UK)' },
  { teksti: 'WADAI', lon: 22.79, lat: 15.54, luokka: 1, koko: 'keski', lahde: 'Wadai Empire' },
  { teksti: 'YHDYSVALLAT', lon: -99, lat: 39.5, luokka: 1, koko: 'suuri', lahde: 'United States of America' },
  { teksti: 'ZULUMAA', lon: 31.58, lat: -28.48, luokka: 1, koko: 'pieni', lahde: 'Zululand' },
];
