// Dioraaman äänipankki (erä 2, speksi docs/raportit/dioraama-rajapinnat-era2-
// 20260929.md kohta 2 "AANET"). Nimet ja arvot ovat sitovia sellaisenaan —
// rakennuskone (tools/dioraama/rakenna.mjs) ja rakennukset (mm. olavinlinna.js)
// viittaavat näihin id:llä (repliikit[].aani, reaktio.aani, taulu.kohdat[].aani,
// tilan aanet[].aani ja tehosteet[].aanet[]).
//
// Lähde: Pelikoodarin äänitoimitus 29.9.2026 (linna-keittio-aanet: ElevenLabs
// Sound Effects + Text-to-Speech). kesto_s toimituksen kestot.json:sta (id →
// kesto_s, 31 kpl); silmukka = toimituksen aanet.json:n laji === 'silmukka'
// (kerta/puhe eivät silmukoi). voimakkuus = 1 kaikilla (huonekohtainen
// vaimennus tulee tilan aanet[].voimakkuus/tehosteet[].voimakkuus-kentistä).
// lisenssi kopioitu aanet.json:sta silmukka-/kerta-äänille sellaisenaan; puhe-
// riveillä aanet.json:ssa ei ole lisenssi-kenttää, joten se on johdettu sen
// ylätason `lahde`-kentästä (Text-to-Speech eikä Sound Effects) — tarkista.
// versio: 1 kaikilla (uusi kenttä, ei speksissä): natiivi välimuistittaa äänet
// levylle URL:n mukaan, ja rakennus.json:n tiedosto-polku sisältää tämän
// (aanet/v<versio>/<id>.mp3) — uusintaotto tästä äänestä kasvattaa VAIN sen
// omaa versiota, jolloin natiivi lataa uuden tiedoston eikä vanhaa välimuistia.
export const AANET = {
  // --- Silmukat (ambienssit, päällekkäin taustana) ---
  'keittio-ambienssi': { silmukka: true, voimakkuus: 1, kesto_s: 28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'tulisija-ratina': { silmukka: true, voimakkuus: 1, kesto_s: 9, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'pata-poreilu': { silmukka: true, voimakkuus: 1, kesto_s: 9, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  vaivaaminen: { silmukka: true, voimakkuus: 1, kesto_s: 7, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'linna-tuuli': { silmukka: true, voimakkuus: 1, kesto_s: 9, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'jarvi-laineet': { silmukka: true, voimakkuus: 1, kesto_s: 9, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },

  // --- Kerta-tehosteet (satunnaiset, ks. tilan tehosteet-kenttä) ---
  'pilkkominen-1': { silmukka: false, voimakkuus: 1, kesto_s: 2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'pilkkominen-2': { silmukka: false, voimakkuus: 1, kesto_s: 1.76, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'pilkkominen-3': { silmukka: false, voimakkuus: 1, kesto_s: 2.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'pilkkominen-4': { silmukka: false, voimakkuus: 1, kesto_s: 1.6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'askel-puu': { silmukka: false, voimakkuus: 1, kesto_s: 2.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'askel-kivi': { silmukka: false, voimakkuus: 1, kesto_s: 2.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  vesisanko: { silmukka: false, voimakkuus: 1, kesto_s: 2.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'ovi-puu': { silmukka: false, voimakkuus: 1, kesto_s: 3, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  lokit: { silmukka: false, voimakkuus: 1, kesto_s: 4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },
  'kellot-kaukaa': { silmukka: false, voimakkuus: 1, kesto_s: 4.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Sound Effects)', versio: 1 },

  // --- Puhe: kokki, apulainen, vesipoika (repliikit) ---
  'kokki-1': { silmukka: false, voimakkuus: 1, kesto_s: 4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kokki-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'apulainen-1': { silmukka: false, voimakkuus: 1, kesto_s: 4.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'apulainen-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'vesipoika-1': { silmukka: false, voimakkuus: 1, kesto_s: 4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'vesipoika-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },

  // --- Puhe: Pulun reaktiot (yksi per hahmo) ---
  'pulu-kokki-r1': { silmukka: false, voimakkuus: 1, kesto_s: 4.16, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'pulu-apulainen-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.44, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'pulu-vesipoika-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },

  // --- Puhe: taulujen kohdat (Pulun kertoma, linnan taulu + keittiön taulu) ---
  'linna-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 7.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'linna-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.16, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'linna-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 6.32, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 2 },
  'keittio-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.76, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 2 },
  'keittio-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 2 },

  // --- Puhe: linnan huoneet (Pelikoodari 1.10.2026; omistajan lupa 30.9. klo 23.4x): kuunnelmat, repliikit, reaktiot,
  // taulujen kohdat ja Pulun kertomukset; äänet aanikartan mukaan, eleven_v4, −17,2 LUFS ---
  'laituri-k1': { silmukka: false, voimakkuus: 1, kesto_s: 9.12, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-k2': { silmukka: false, voimakkuus: 1, kesto_s: 7.44, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-k3': { silmukka: false, voimakkuus: 1, kesto_s: 8.72, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-k4': { silmukka: false, voimakkuus: 1, kesto_s: 12.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-soutaja-1': { silmukka: false, voimakkuus: 1, kesto_s: 6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-soutaja-2': { silmukka: false, voimakkuus: 1, kesto_s: 6.72, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-pulu-soutaja-r1': { silmukka: false, voimakkuus: 1, kesto_s: 6.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-renki-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-renki-2': { silmukka: false, voimakkuus: 1, kesto_s: 7.28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-pulu-renki-r1': { silmukka: false, voimakkuus: 1, kesto_s: 6.24, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 7.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.32, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 6.56, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'laituri-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 22.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-k1': { silmukka: false, voimakkuus: 1, kesto_s: 6.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-k2': { silmukka: false, voimakkuus: 1, kesto_s: 5.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-k3': { silmukka: false, voimakkuus: 1, kesto_s: 8.32, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-k4': { silmukka: false, voimakkuus: 1, kesto_s: 9.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-hoitaja-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-hoitaja-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.8, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-pulu-hoitaja-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.36, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-renki-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-renki-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-pulu-renki-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.44, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 7.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 6.24, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'fatabuuri-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 17.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-k1': { silmukka: false, voimakkuus: 1, kesto_s: 10.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-k2': { silmukka: false, voimakkuus: 1, kesto_s: 9.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-k3': { silmukka: false, voimakkuus: 1, kesto_s: 8.72, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-k4': { silmukka: false, voimakkuus: 1, kesto_s: 7.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-kirjuri-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-kirjuri-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-pulu-kirjuri-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-renki-1': { silmukka: false, voimakkuus: 1, kesto_s: 4.16, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-renki-2': { silmukka: false, voimakkuus: 1, kesto_s: 6.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-pulu-renki-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 6.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.12, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.8, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kierreportaat-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 16.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-k1': { silmukka: false, voimakkuus: 1, kesto_s: 6.64, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-k2': { silmukka: false, voimakkuus: 1, kesto_s: 9.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-k3': { silmukka: false, voimakkuus: 1, kesto_s: 10, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-k4': { silmukka: false, voimakkuus: 1, kesto_s: 8.16, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-vartija-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-vartija-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.92, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-pulu-vartija-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.28, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-talonpoika-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-talonpoika-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.56, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-pulu-talonpoika-r1': { silmukka: false, voimakkuus: 1, kesto_s: 6.4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 4.88, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 4.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 9.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'muurinharja-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 20.4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-k1': { silmukka: false, voimakkuus: 1, kesto_s: 9.12, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-k2': { silmukka: false, voimakkuus: 1, kesto_s: 6.64, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-k3': { silmukka: false, voimakkuus: 1, kesto_s: 8.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-k4': { silmukka: false, voimakkuus: 1, kesto_s: 3.76, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-k5': { silmukka: false, voimakkuus: 1, kesto_s: 8.72, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-kappalainen-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-kappalainen-2': { silmukka: false, voimakkuus: 1, kesto_s: 6.16, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-pulu-kappalainen-r1': { silmukka: false, voimakkuus: 1, kesto_s: 6.4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-vouti-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-vouti-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.36, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-pulu-vouti-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 6.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 6.4, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'kappeli-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 21.44, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-k1': { silmukka: false, voimakkuus: 1, kesto_s: 7.36, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-k2': { silmukka: false, voimakkuus: 1, kesto_s: 3.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-k3': { silmukka: false, voimakkuus: 1, kesto_s: 7.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-k4': { silmukka: false, voimakkuus: 1, kesto_s: 5.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-k5': { silmukka: false, voimakkuus: 1, kesto_s: 8.32, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-tarjoilija-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.04, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-tarjoilija-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-pulu-tarjoilija-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.92, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-vartija-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-vartija-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-pulu-vartija-r1': { silmukka: false, voimakkuus: 1, kesto_s: 7.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-vartija2-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-vartija2-2': { silmukka: false, voimakkuus: 1, kesto_s: 5.12, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-pulu-vartija2-r1': { silmukka: false, voimakkuus: 1, kesto_s: 5.68, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-talonpoika-1': { silmukka: false, voimakkuus: 1, kesto_s: 5.52, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-talonpoika-2': { silmukka: false, voimakkuus: 1, kesto_s: 4.64, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-pulu-talonpoika-r1': { silmukka: false, voimakkuus: 1, kesto_s: 4.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-kohta-0': { silmukka: false, voimakkuus: 1, kesto_s: 6.72, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-kohta-1': { silmukka: false, voimakkuus: 1, kesto_s: 4.56, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-kohta-2': { silmukka: false, voimakkuus: 1, kesto_s: 10.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keskushalli-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 20.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-k1': { silmukka: false, voimakkuus: 1, kesto_s: 9.2, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-k2': { silmukka: false, voimakkuus: 1, kesto_s: 6.08, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-k3': { silmukka: false, voimakkuus: 1, kesto_s: 6.8, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-k4': { silmukka: false, voimakkuus: 1, kesto_s: 6.96, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-k5': { silmukka: false, voimakkuus: 1, kesto_s: 6.48, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-pulu': { silmukka: false, voimakkuus: 1, kesto_s: 19.84, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'keittio-etsinta-0': { silmukka: false, voimakkuus: 1, kesto_s: 4.64, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  // Rakennuksen kertoja (isoisä, Viisas Kertoja, eleven_v3; omistaja 30.9. klo 23.5x).
  'linna-kertoja-jarvelta': { silmukka: false, voimakkuus: 1, kesto_s: 11.92, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'linna-kertoja-tornit': { silmukka: false, voimakkuus: 1, kesto_s: 12.32, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'linna-kertoja-piha': { silmukka: false, voimakkuus: 1, kesto_s: 11.6, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
  'linna-kertoja-laituri': { silmukka: false, voimakkuus: 1, kesto_s: 20, lisenssi: 'CC0 (oma tuotanto, ElevenLabs Text-to-Speech)', versio: 1 },
};
